### ISSUE TITLE
Playback history on YouTube web stopped being updated

### ISSUE THREAD

**Issue by Razzamatazz777** [anxdpanic/plugin.video.youtube#1008]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.3
* Kodi Version:  20.5
* Kodi GUI Language: English
* Operating System: Windows 7 SP1
* Operating System Language: English

------

### Expected Behavior

After enabling "Update playback history on Youtube" in Advanced Settings, the YouTube webpage "Watch history" is updated to include all videos streamed from the Kodi YouTube add-on. 

------

### Current Behavior

YouTube webpage "Watch history" is no longer being updated from Kodi after updating to 7.1.1.3. 

------

### Steps to Reproduce

1. Install YouTube add-on 7.1.1.3.
2. Run the setup wizard (including selecting the recommended quality settings.)
3. Enable Advanced Settings "Update playback history on YouTube".
4. Playback any YouTube video.
5. Check the "Watch history" YouTube webpage.

------

### Log

https://paste.kodi.tv/nowiwiteso.kodi

------

### Additional Information

Tried deleting settings.xml and re-running the setup wizard. Also tried a fresh installation of Kodi 20.5 and 7.1.1.3 on a different (Windows 11) system. 

However, Local Playback History is still working and the custom "Kodi History" playlist on YouTube web is still being updated.

This was previously working on 7.0.3.2 using the default player (until playback stopped working when YouTube changes caused the "video is not available" issue two weeks ago.)

Thank you for all your hard work and support of this amazing add-on.

------

**Comment by krisztianloki** [comment]
I also encountered this error and git bisect pointed to ['Only use OAuth tokens if necessary'](https://github.com/anxdpanic/plugin.video.youtube/commit/46c389bd814779dda40a54307aa2358868a4d921) as the culprit

**Comment by MoojMidge** [comment]
Yes this is expected. Unfortunately nothing can be done about this at this stage.

**Comment by MoojMidge** [comment]
> Unfortunately nothing can be done about this at this stage.

Or maybe not. See if it works using this test version: 
https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.2.0%2Bbeta.1/plugin.video.youtube-7.2.0+beta.1.zip

**Comment by Razzamatazz777** [comment]
Sorry to report that the problem still remains. (I deleted settings.xml and ran the setup wizard, as well.)

https://paste.kodi.tv/emayeboqib.kodi

**Comment by MoojMidge** [comment]
Try again:
https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.2.0%2Bbeta.1/plugin.video.youtube-7.2.0+beta.1.zip

I have no way of testing it, so if it doesn't work this time, then will just have to consider this feature broken.

**Comment by Razzamatazz777** [comment]
Unfortunately, the remote watch history is still not updating. 
Should you post any future test versions here, I will test and post the result. Thanks again for your efforts.

https://paste.kodi.tv/qitomofulo.kodi

**Comment by krisztianloki** [comment]
With the latest change the `Playback reported` lines disappeared from the log... Is it because of this condition:
`if use_remote_history and self._auth_client:` ?

**Comment by MoojMidge** [comment]
It was due to an incomplete commit.

Lets try again: https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Razzamatazz777** [comment]
It works now! Also, the "playback reported" lines are back in the debug log.
Thank you so much!

https://paste.kodi.tv/tawexemonu.kodi

**Comment by MoojMidge** [comment]
Glad it is working for the moment, but please note that this feature is likely to break again in the near future, assuming that YouTube continue restricting authentication methods, and it won't be able to fixed again.

**Comment by MoojMidge** [comment]
Can someone please test and confirm the watch history is being updated using this version as well?
https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.1.1.4/plugin.video.youtube-7.1.1.4.zip

**Comment by jmh2002** [comment]
Tested and confirmed that v7.1.1.4 does now update the watch history on YouTube. THANK YOU! :)

**Comment by jmh2002** [comment]
EDIT: Test v7.1.1.4 seems to have broken My Subscriptions - rolling back to 7.1.1.3

**Comment by Razzamatazz777** [comment]
Confirmed with 7.1.1.4 that the watch history is being updated. 

However, I'm now unable to enter the "My Subscriptions" folder (gives a "YouTube error. Check the log" ... at the 14:41 timestamp.)

https://paste.kodi.tv/tiwumokizo.kodi

**Comment by MoojMidge** [comment]
Thanks for the quick response and log. Error with cherry picking commit from newer branch.

Updated: https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.1.1.4/plugin.video.youtube-7.1.1.4.zip

**Comment by Razzamatazz777** [comment]
Confirmed that both the remote watch history and "My Subscriptions" are working. Great work!

**Comment by MoojMidge** [comment]
Thanks for confirming
