### ISSUE TITLE
Not a bug but important: v7.2.0+beta.1

### ISSUE THREAD

**Issue by C-O-D** [anxdpanic/plugin.video.youtube#1009]
I just downloaded version v7.2.0+beta.1 from your MoojMidge repository. Then you released the same version on the regular repository a few minutes later. When I compare the two versions, I see differences. Which version is the right one?

**Comment by MoojMidge** [comment]
> Then you released the same version on the regular repository a few minutes later.

Didn't do this. While you are free to access the code on my personal repository, it is strictly for testing and there will never be any releases from there.

There may be release workflows run from there to help users with installation, but they will never be published.
Edit: Ah, I see the last draft release did actually get published, but it was not published here, and will be deleted shortly

Any release will only be published here, and whatever happens elsewhere is just staging for the release here.


> Which version is the right one?

Neither. The versioning, changes, history, etc. are all uncontrolled in my personal repository, but you can just use whatever is latest for testing.

**Comment by C-O-D** [comment]
okay all right, thanks 👍
