### ISSUE TITLE
New version 7.1.1.4 causing me issues

### ISSUE THREAD

**Issue by OldManJax** [anxdpanic/plugin.video.youtube#1013]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.4
* Kodi Version: 21.1
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English

For some reason after getting this update, the add-on doesn't read my api keys. It keeps asking for them when they are clearly installed into the settings.
I tried a fresh install of Kodi, then installed 7.1.1.4, then entered my keys but still get the same issue.
If I go back to 7.1.1.3 it works perfectly. If I try updating that again to 7.1.1.4, it breaks and constantly tells me I need api keys. The keys are displayed correctly in the settings.xml file and in the api_keys.json file, but the add-on doesn't see them.
The log simply shows: warning <general>: [plugin.video.youtube] API request: aborted
I tested 7.1.1.4 on an Android box, and my keys worked perfectly which really confused me as I wouldn't expect an OS to make a difference for something like this.
Sorry I don't have time to help troubleshoot, I just wanted to leave a report in case others have this issue.

**Comment by lindagues** [comment]
Same here, differences:

OS: LibreElec (x86 Generic Build)
Languages: German

**Comment by Liquidrag** [comment]
Same issues on macOS Big Sur v 11.7.10

**Comment by MoojMidge** [comment]
Can someone provide a log?

**Comment by MoojMidge** [comment]
Never mind, I can see where the problem is. You just need to sign-in for the moment, rather than only using the API key.

**Comment by MoojMidge** [comment]
Fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.5
