### ISSUE TITLE
Suddenly unable to play videos on all recent versions.

### ISSUE THREAD

**Issue by jwmay2012** [anxdpanic/plugin.video.youtube#1018]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.5, 7.1.1.4, 7.1.1.3
* Kodi Version: 21.1.0 21.1-Omega 2024-08-18
* Kodi GUI Language: English
* Operating System: LibreELEC (official) 12.0.1 (kernel: Linux 6.6.46)
* Operating System Language: English

------

### Expected Behavior

After sending video link, video starts playing.

------

### Current Behavior

Dropped into the youtube app menu page (Watch Later, Settings, Log in, etc) and no video plays. To leave with the back button often takes 5+ "backs" to leave youtube app, as if it's been nested inside itself. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install youtube addon
2. Send video link with Play on Kodi via Kore app OR via Yatse app
3. Video does not play and drops into youtube app menu.

------

### Log
~~I'll see if I can take the time to get logs.~~
https://paste.kodi.tv/ijisuqiqol.kodi

------

### Additional Information

From this comment https://forum.kodi.tv/showthread.php?tid=356934&pid=3218203#pid3218203
and can confirm, v7.1.0.1 still works. 

------

**Comment by MoojMidge** [comment]
Nothing can be done without a debug log.

**Comment by jwmay2012** [comment]
@MoojMidge Debug logs--
https://paste.kodi.tv/ijisuqiqol.kodi

**Comment by MoojMidge** [comment]
Thanks, looks like the same issue reported in #991 and appears related to API requests not working because an API key has not been provided. Having a look into it.

**Comment by MoojMidge** [comment]
The issue is related to recently added handling of deleted or otherwise unavailable videos.

Sometimes API requests for listings are for videos that can't be accessed via the API, in which case the addon identifies that the video is unplayable in the listing.

However if you are not using an API key in the first place then you can't make any API requests and can't open any listings either, but it was not correct to also assume that the video being attempted to play was actually unplayable.

Can you try this test version and confirm playback now works again?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

**Comment by 43qcc2cn** [comment]
> The issue is related to recently added handling of deleted or otherwise unavailable videos.
> 
> Sometimes API requests for listings are for videos that can't be accessed via the API, in which case the addon identifies that the video is unplayable in the listing.
> 
> However if you are not using an API key in the first place then you can't make any API requests and can't open any listings either, but it was not correct to also assume that the video being attempted to play was actually unplayable.
> 
> Can you try this test version and confirm playback now works again? https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

For info. I've never supplied an API key and have recently been getting:
```
2024-12-07 13:00:32.187 T:2048     info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.5
                                                   	Kodi:   v21.1 (Kodi Omega)
                                                   	Python: v3.11.9
                                                   	Path:   |/play/|
                                                   	Params: |{'video_id': 'QErMnvy2j_A'}|
2024-12-07 13:00:32.668 T:2048    error <general>: [plugin.video.youtube] API error - forbidden
                                                   	Exception: YouTubeException('"error" in response JSON data')
                                                   	Message:   Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
                                                   	Response:   {'error': {'code': 403, 'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'errors': [{'message': "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.", 'domain': 'global', 'reason': 'forbidden'}], 'status': 'PERMISSION_DENIED'}}
```
I can confirm that this no longer happens with the test version:
```
2024-12-07 13:21:57.600 T:2096     info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.6
                                                   	Kodi:   v21.1 (Kodi Omega)
                                                   	Python: v3.11.9
                                                   	Path:   |/play/|
                                                   	Params: |{'video_id': 'QErMnvy2j_A'}|
2024-12-07 13:21:58.000 T:2096  warning <general>: [plugin.video.youtube] API request: aborted
2024-12-07 13:21:58.018 T:1962     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=QErMnvy2j_A
```

**Comment by MoojMidge** [comment]
Thanks for confirming
