### ISSUE TITLE
Playlist item count not updating

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#1024]
it is a personal playlist that I have used since the beginning of using
this app, which goes back a couple of years now. Reason was that
the standard
"play later" playlist was not supported by the app so I created my own
playlist.
What I normally do now is go to "my subscriptions" and add the
newest videos (that I want to see) to that local playlist which I then
browse
to in the app and go from there. I noticed that the version 7.1.1.1. now
shows the number of items in a playlist, but that number is not
dynamically
updated. Not sure why as the number shown is now completely useless. Once
I've watched a video I remove it from my local playlist so I keep the list
clear of any watched videos. Apparently, this is a different usage of
playlists that is assumed by the developer(s). Luckily, this 'bug' does not
prevent me from using the app.

_Originally posted by @Rialtho-the-Magnificent in https://github.com/anxdpanic/plugin.video.youtube/issues/1021#issuecomment-2531712385_

**Comment by Rialtho-the-Magnificent** [comment]
I did find that once you clear the datacache, the numbers shown behind the playlist names is correct again. 

Also, I noticed that the first time you 'open' the playlists, it takes some extra time as it has to determine the number of items in all the playlists it needs to show. Probably, this is why the numbers are not updated 'dynamically'.

But, maybe the number can be updated when you select the option 'refresh' while in the playlist? It has to collect the list of entries anyway so it could easily keep track of the amount of the items.

**Comment by MoojMidge** [comment]
> But, maybe the number can be updated when you select the option 'refresh' while in the playlist? It has to collect the list of entries anyway so it could easily keep track of the amount of the items.

This wont work because the contents of a playlist are queried using a different API endpoint to the details of a playlist.

Anyway you can try this test version https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

The playlist item count should update more regularly.

Still don't understand what any of this has to do with no videos playing, which was your original complaint. If you are having an issue with this then first run the Setup Wizard and post a debug log from when the videos fail to play.

**Comment by Rialtho-the-Magnificent** [comment]
videos are now playing again, since I reverted back to the version 7.1.1.1. I'm reluctant to upgrade to the latest version as that was when the problems began with no longer being able to play videos. Rebooting did help with version 7.1.1.3 but no longer with version 7.1.1.6 (which is the most recent version at writing this (Dec. 13, 2024). As for the number of items count, I just ignore those.

**Comment by MoojMidge** [comment]
Lol... ok then
