### ISSUE TITLE
No Video Available 

### ISSUE THREAD

**Issue by A11st0r** [anxdpanic/plugin.video.youtube#1025]
### Context
I have opened an issue before about this. Since then I have kept up and tested with all the new releases (7.1.1.6) but I can't play any video.
My IP is for AWS Frankfurt. I have changed multiple IPs via its Elastic IP service.
Even I used Oracle cloud UK with no avail. 

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.6
* Kodi Version: 20.2.0
* Kodi GUI Language: English
* Operating System: English
* Operating System Language: English

------

### Expected Behavior

Playing Videos.

------

### Current Behavior

What is the current behavior?

Video not Available.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/ebokerumif.kodi

------

### Additional Information

I remember the developer stating about something related to IP being banned. I think you can check that with using DuckDuckGo video search feature. It let's you watch the video without going to Youtube. On some networks it show "signin to confrim you're not a bot"

------

**Comment by michaelminuse** [comment]
Experiencing the same issue in the US.

**Comment by MoojMidge** [comment]
There is nothing that can be done about this unfortunately.

YouTube has blocked your IP and also removed the methods previously available to authenticate the player requests that are used by this addon.

You can try switching IP addresses if possible, but if you are not using an IP address that is from a range considered to be used for residential/personal purposes, then the block is inevitable.

**Comment by A11st0r** [comment]
I really don't like using Google products but Youtube grip on video is inevitable. I heard buying a  subscription may lift the restriction even in cloud provider IP ranges. 

I need to find someway to play videos on Kodi even it means automating something like downloading a video URL and playing it. I found out before that downloading is not so easy now.

**Comment by MoojMidge** [comment]
> I heard buying a subscription may lift the restriction even in cloud provider IP ranges.

No it won't, don't waste your money if that is the only reason you are considering it.

> automating something like downloading a video URL and playing it. I found out before that downloading is not so easy now.

Downloading or streaming doesn't matter. The IP addresses you are using are blocked. The only reliable option you have at the moment is to login using an official client, use a proxy that is not blocked, or proxy through something like Invidious.

**Comment by A11st0r** [comment]
thank you for letting me know about Invidious. Is there a way to make kodi plugin work with a Invidious instance instead of Youtube?

**Comment by MoojMidge** [comment]
> Is there a way to make kodi plugin work with a Invidious instance instead of Youtube?

No.

You can use the Invidious plugin, search for it on Github.

Note that you will need to find a server instance that fully proxies YouTube otherwise you will still be blocked.

Can't really advise you any further as I have no experience with using it myself.
