### ISSUE TITLE
[401] Deleted Client

### ISSUE THREAD

**Issue by ShadoUrufu** [anxdpanic/plugin.video.youtube#103]
https://i.gyazo.com/8fd91985c3805c3e034a80864fb0a7f1.png

this is the message i get after following all of the steps and attempting ot log in. I think this app is dead on Kodi, and i've downloaded the 'latest' version of it i could find just today. Win7 Desktop PC

**Comment by fedprod** [comment]
It's not dead at all, just use your own API credentials like the message says...

**Comment by asm0dey** [comment]
Looks like you have to add yourself as user of application in setting [here](https://console.developers.google.com/apis/credentials/consent) via "Add Users" button.

@anxdpanic looks like it should be added to instruction.
