### ISSUE TITLE
Play original version (not dubbed)

### ISSUE THREAD

**Issue by regseb** [anxdpanic/plugin.video.youtube#1036]
### Context

* Add-on Version: 7.1.1.6
* Kodi Version: 21.1
* Kodi GUI Language: French
* Operating System: OSMC 2024.10-1
* Operating System Language: fr_FR

------

### Expected Behavior

YouTube has added an [automatic dubbing](https://support.google.com/youtube/answer/15569972) feature ([_Break down language barriers with auto dubbing on YouTube_](https://blog.youtube/news-and-events/auto-dubbing-on-youtube/)). When you play a video with dubbing, I expect to play the original version.

For example with video [_À quoi ressemblerait JINX dans la vraie vie ? (Je crée un accessoire pour Arcane)_](https://youtu.be/CqbfN4CIP2k) whose original is in French and which has an English dub. When I play it, I want it to be in French.

------

### Current Behavior

The English version is played.

Here are some other videos:

| Video | Original / dubbings | Language played |
| --- | --- | --- |
| [_À quoi ressemblerait JINX_...](https://youtu.be/CqbfN4CIP2k) | French / English | English |
| [_OpenAI atteint l’AGI avec o3_...](https://youtu.be/vHRyMNGkCic) | French / English | English |
| [_Doblaje automático en videos_...](https://youtu.be/VOv8n2A0z78) | Spanish / English | English |
| [_I Documented My Life_...](https://youtu.be/TzJqJQwhZh0) | English / Spanish, Italian, Portuguese, German, French | English |
| [_2,000 People Fight_...](https://youtu.be/gs8qfL9PNac) | English / 22 languages (manually dubbed) | English

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. In YouTube plugin, search: _À quoi ressemblerait JINX dans la vraie vie_
2. Select _À quoi ressemblerait JINX dans la vraie vie ? (Je crée un accessoire pour Arcane)_
3. The video is in English.

------

### Log

```
2024-12-23 18:57:10.128 T:11141    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.6
                                                   	Kodi:   v21.1 (Kodi Omega)
                                                   	Python: v3.9.2
                                                   	Path:   |/play/|
                                                   	Params: |{'video_id': 'CqbfN4CIP2k'}|
2024-12-23 18:57:10.566 T:3414     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=CqbfN4CIP2k
2024-12-23 18:57:10.568 T:13882    info <general>: Creating InputStream
2024-12-23 18:57:10.572 T:13882    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 1
2024-12-23 18:57:10.579 T:13882    info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 9, Type: VOD)
2024-12-23 18:57:10.579 T:13882    info <general>: Creating Demuxer
2024-12-23 18:57:10.582 T:13882    info <general>: Opening stream: 1001 source: 256
2024-12-23 18:57:11.038 T:13882    info <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 25.000, 3D: false
2024-12-23 18:57:11.042 T:13882    info <general>: Display resolution ADJUST : 1920x1080 @ 50.000000 Hz (31) (weight: 0.000)
2024-12-23 18:57:11.074 T:3414     info <general>: VideoPlayer: OnLostDisplay received
2024-12-23 18:57:11.075 T:3414  warning <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2024-12-23 18:57:11.075 T:3414  warning <general>: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2024-12-23 18:57:11.076 T:3414     info <general>: GLES: Maximum texture width: 4096
2024-12-23 18:57:11.078 T:13882    info <general>: Creating video codec with codec id: 27
2024-12-23 18:57:11.079 T:13882    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem H.264 decoder wrapper
2024-12-23 18:57:11.099 T:13882    info <general>: Creating video thread
2024-12-23 18:57:11.099 T:13887    info <general>: running thread: video_thread
2024-12-23 18:57:11.100 T:13882    info <general>: Opening stream: 1008 source: 256
2024-12-23 18:57:11.133 T:3414     info <general>: VideoPlayer: OnResetDisplay received
2024-12-23 18:57:11.134 T:3414  warning <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2024-12-23 18:57:11.732 T:13882    info <general>: Skipped 1 duplicate messages..
2024-12-23 18:57:11.732 T:13882    info <general>: Finding audio codec for: 86018
2024-12-23 18:57:11.734 T:13882    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-12-23 18:57:11.735 T:13882    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 50 ms
2024-12-23 18:57:11.735 T:13882    info <general>: Creating audio thread
2024-12-23 18:57:11.735 T:13890    info <general>: running thread: CVideoPlayerAudio::Process()
2024-12-23 18:57:12.302 T:13890    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2024-12-23 18:57:12.324 T:3429     info <general>: CActiveAESink::OpenSink - initialize sink
2024-12-23 18:57:12.524 T:3429     info <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2024-12-23 18:57:12.528 T:3429     info <general>: CAESinkALSA::Initialize - Opened device "sysdefault"
2024-12-23 18:57:12.529 T:3429     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-12-23 18:57:12.529 T:3429     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2024-12-23 18:57:12.576 T:3414     info <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 25.000, 3D: false
2024-12-23 18:57:12.578 T:3414     info <general>: Display resolution ADJUST : 1920x1080 @ 50.000000 Hz (31) (weight: 0.000)
```

------

### Additional Information

Both audio streams are available in Kodi, but it's not the original version that's used by default.

- _English (US) - English (US) [Original (130 kbps)] - AAC-LC - 2 channels [**default**, original] (1/2)_
- _French - French [Original (130 kbps)] - AAC-LC - 2 channels [original] (2/2)_

**Comment by MoojMidge** [comment]
Give this a try: https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.2.0%2Bbeta.2/plugin.video.youtube-7.2.0+beta.2.zip

Language settings configured in the addon now work in conjunction with the Kodi language selection settings (`Kodi > Settings > Player > Language > Preferred audio language`)

1. Media default will use the language configured in the addon if available, falling back to original language
  1.a) Due to technical limitations the default language will always be English, rather than the language configured in the addon
  1.b) To ensure that the default English is not used in preference to the configured language, the following setting needs to be disabled `Kodi > Settings > Player > Language > Preferred default audio streams`.
  1.c) `Preferred default audio streams` is enabled by default in Kodi, but may not result in a preferred outcome in this specific scenario. Open to feedback whether this addon should ignore this setting and always prefer the language configured in the addon.
3. Original will use the original language in the video
4. User interface will use the Kodi interface language if available, falling back to original language
5. Any other language selected will be used if selected and available, falling back to original language

Edit: Thanks for the comprehensive report with example videos

**Comment by regseb** [comment]
I've tested version _7.2.0+beta.2_ and the videos are in the right language. Thanks for the fix.

**Comment by MoojMidge** [comment]
>    1.b) To ensure that the default English is not used in preference to the configured language, the following setting needs to be disabled `Kodi > Settings > Player > Language > Preferred default audio streams`.
>    1.c) `Preferred default audio streams` is enabled by default in Kodi, but may not result in a preferred outcome in this specific scenario. Open to feedback whether this addon should ignore this setting and always prefer the language configured in the addon.

Do you have the `Preferred default audio streams` setting enabled or disabled?

**Comment by regseb** [comment]
Here are the results with Kodi and addon in French:

- With _Preferred audio language_: _Media default_ ; and _Prefer default audio streams_: **enabled**.

  | Original / dubbings | Language played |
  | --- | --- |
  | [`fr` / auto `en`](https://youtu.be/CqbfN4CIP2k) | original `fr` |
  | [`es` / auto `en`](https://youtu.be/VOv8n2A0z78) | original `es` |
  | [`en` / many auto](https://youtu.be/TzJqJQwhZh0) | auto dubbed `fr` |
  | [`en` / many manual](https://youtu.be/gs8qfL9PNac) | **manual dubbed `fr`** |

- With _Preferred audio language_: _Media default_ ; and _Prefer default audio streams_: **disabled**.

  | Original / dubbings | Language played |
  | --- | --- |
  | `fr` / auto `en` | original `fr` |
  | `es` / auto `en` | original `es` |
  | `en` / many auto | auto dubbed `fr` |
  | `en` / many manual | **original `en`** |

**Comment by MoojMidge** [comment]
Thanks for testing and reporting your results.

Looks like there are some edge cases that need to be looked at a bit more.

Next beta release will fix this:

- With _Preferred audio language_: _Media default_ ; and _Prefer default audio streams_: **enabled**.
| Original / dubbings | Language played |
  | --- | --- |
  | [`en` / many auto](https://youtu.be/TzJqJQwhZh0) | auto dubbed `fr` |

- With _Preferred audio language_: _Media default_ ; and _Prefer default audio streams_: **disabled**.

  | Original / dubbings | Language played |
  | --- | --- |
  | [`en` / many auto](https://youtu.be/TzJqJQwhZh0) | ~auto dubbed `fr`~ (incorrect)
  | [`en` / many auto](https://youtu.be/TzJqJQwhZh0) |   **original `en`** (correct) |

**Comment by MoojMidge** [comment]
@regseb and others who have reacted to this issue - can you please test https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.3.zip

It contains changes to how the various audio streams are handled compared to how it was originally implemented in response to this original issue, as a further response to a number of duplicate issues that want conflicting outcomes, and comments indicating that the Kodi settings are not good enough.

The main user-facing change is that it decouples selection of dubbed and auto-dubbed audio streams from the `Prefer default audio streams` Kodi setting, instead using separate stream features selections:

- `YouTube addon > Settings > General > Stream features > Prefer dubbed audio over original audio` 
  - For manually dubbed audio provided by the uploader
- `YouTube addon > Settings > General > Stream features > Prefer automatically translated dubbed audio over original audio`
  -  For automatically machine translated audio provided by YouTube

These new stream feature selections are technically enabled by default, but as they are changes to the existing stream feature selections you will need manually enable them or alternatively run the Setup Wizard.

It should no longer matter what `Prefer default audio streams` is set to for YouTube dubbed audio streams. Have tested based on the examples that were previously provided and all seems ok, can you confirm that this still works for you?

**Comment by regseb** [comment]
With Kodi in French, the texts in French are not good in _Stream features_ list:

- _Prefer dubbed audio over original audio_: [_Ajouté à "À regarder plus tard"_](https://github.com/anxdpanic/plugin.video.youtube/blob/d6eebf76a1206a0064084c4423bd8101e27e81fd/resources/language/resource.language.fr_fr/strings.po#L1156)
- _Prefer automatically translated dubbed audio over original audio_: [_Ajouté à la liste de lecture_](https://github.com/anxdpanic/plugin.video.youtube/blob/d6eebf76a1206a0064084c4423bd8101e27e81fd/resources/language/resource.language.fr_fr/strings.po#L1160)

---

Here are the results with Kodi and addon in French:

- **Without** feature;
- With _Prefer **dubbed** audio over original audio_;
- With _Prefer **automatically** translated dubbed audio over original audio_;
- With _Prefer **dubbed** audio over original audio_ and _Prefer **automatically** translated dubbed audio over original audio_.

| Original / dubbings | without | dubbed | automatically | dubbed & automatically |
| --- | --- | --- | --- | --- |
| [`fr` / auto `en`](https://youtu.be/CqbfN4CIP2k) | original `fr` | original `fr` | original `fr` | original `fr` |
| [`es` / auto `en`](https://youtu.be/VOv8n2A0z78) | original `es` | original `es` | original `es` | original `es` |
| [`en` / many auto](https://youtu.be/TzJqJQwhZh0) | original `en` | original `en` | auto dubbed `fr` | auto dubbed `fr` |
| [`en` / many manual](https://youtu.be/gs8qfL9PNac) | original `en` | manual dubbed `fr` | original `en` | manual dubbed `fr` |

It works: the selected language is correct based on the activated features.

**Comment by MoojMidge** [comment]
> It works: the selected language is correct based on the activated features.

Thanks for taking the time to test and confirm. 

> With Kodi in French, the texts in French are not good in _Stream features_ list:

The changes have not been merged into the master branch yet, so the translatable strings have not been synced to the various translation files. Will happen for the next beta release.

**Comment by sedric** [comment]
Sorry I'm late to the party.
I'm on LibreElec 12.2.0 with addon v7.3.0+beta.2 and french UI and I disagree with regseb observations.
With both dubbed audio over original audio and Prefer automatically translated dubbed audio over original audio deactivated (grey) and Preferred default audio streams in either mode, I still have dubbed `fr` tracks by default on the videos they linked.

Is there something else that might conflict ? I join a log when playing the first english original video :

[kodi-play-TzJqJQwhZh0.log](https://github.com/user-attachments/files/21935138/kodi-play-TzJqJQwhZh0.log)

**Comment by MoojMidge** [comment]
Can't determine anything without a full log as the settings that are used are not continuously fetched and therefore not logged everytime they are used.

If you have the full log I can have a look otherwise as of v7.3.0+beta.1 it works in the following manner.

---

Language settings configured in the addon now work in conjunction with the Kodi language selection settings
- `Kodi > Settings > Player > Language > Preferred audio language`
- `Kodi > Settings > Player > Language > Prefer default audio streams`


The following combination of settings for __Preferred audio language__ allows for various options in choosing the preferred audio stream:
1. __Media default__ (enabled by default in Kodi) will use the language configured in the addon if available, falling back to original language. The preferred default audio stream is selected based on the following criteria:
    - If `YouTube addon > Settings > General > Stream features > Prefer dubbed audio over original audio` is enabled (enabled by default in the addon if the Setup Wizard has been run) then manually dubbed audio provided by the uploader, that matches the language configured in the addon, will be preferred if available.
    - Otherwise if `YouTube addon > Settings > General > Stream features > Prefer automatically translated dubbed audio over original audio` is enabled (enabled by default in the addon if the Setup Wizard has been run) then automatically machine translated audio provided by YouTube, that matches the language configured in the addon, will be preferred if available.
    - Otherwise if __Prefer default audio streams__ is enabled (enabled by default in Kodi), then whatever audio stream YouTube thinks should be the default will be preferred.
3. __Original__ will use the original language in the video
4. __User interface__ will use the Kodi interface language if available, falling back to original language
5. Any other language selected will be used if selected and available, falling back to original language

**Comment by sedric** [comment]
Ah, yes, my media default was set to Match UI, sorry.
