### ISSUE TITLE
Missing message argument to 'raise InvalidGrant' caused the plugin to crash after upgrade to 7.1.1.6 (from 7.0.9.2)

### ISSUE THREAD

**Issue by kendrak24** [anxdpanic/plugin.video.youtube#1038]
In [provider.py](https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/provider.py) the line
`raise InvalidGrant` is causing an exception since it is missing the required message argument. 

https://github.com/anxdpanic/plugin.video.youtube/blob/95632c3b79b3abbcfac2c0b45ddae9ca2c86bc16/resources/lib/youtube_plugin/youtube/provider.py#L276-L284

This caused (for me) the upgrade to 7.1.1.6 from 7.0.9.2 to make the plugin to crash at start, since after the upgrade the refresh token apparently needed to be reset. (When I added a message: `raise InvalidGrant("InvalidGrant")` I got the correct  error and after that it worked next retry.

<details>
<summary>Log excerpt for the initial error causing the crash</summary>

> 2024-12-25 18:08:23.529 T:2182    error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
> 2024-12-25 18:08:23.537 T:2056    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
> 2024-12-25 18:08:28.770 T:2193     info <general>: [plugin.video.youtube] Plugin: Running v7.1.1.6
>                                                    	Kodi:   v21.1 (Kodi Omega)
>                                                    	Python: v3.11.2
>                                                    	Path:   |/|
>                                                    	Params: |{}|
> 2024-12-25 18:08:28.772 T:2193    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: KodionException.__init__() missing 1 required positional argument: 'message'
>                                                    Traceback (most recent call last):
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
>                                                        plugin_runner.run()
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 67, in run
>                                                        plugin.run(provider, context, focused=(current_uri == new_uri))
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 185, in run
>                                                        result, options = provider.navigate(context)
>                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 169, in navigate
>                                                        result = handler(provider=self, context=context, re_match=re_match)
>                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1212, in on_root
>                                                        _ = provider.get_client(context)  # required for self.is_logged_in()
>                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                                                      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 282, in get_client
>                                                        raise InvalidGrant
>                                                    TypeError: KodionException.__init__() missing 1 required positional argument: 'message'
>                                                    -->End of Python script error report<--
>  

</details>

**Comment by MoojMidge** [comment]
> since after the upgrade the refresh token apparently needed to be reset.

Thanks for the report. This is obviously an error, but I'm trying to figure out what may have caused the access tokens not to have been refreshed in the first place.

Can you provide more details:

1. Can you confirm you had been signed in using v7.0.9.2?
2. Is your internet/network connection generally stable? Have you had any other issues with accessing parts of the addon previously? 
3. When was the last time you accessed the addon using v7.0.9.2 prior to updating and getting the error? 
4. No big deal if you don't want to, but would you be willing to roll back to v7.0.9.2 then upgrade to v7.1.1.6 and provide a debug log? I tried to replicate this issue but couldn't. It is an odd occurrence, but could just have been a passing glitch with the OAuth process (which is what the InvalidGrant exception was meant to signify).

**Comment by kendrak24** [comment]
> 1. Can you confirm you had been signed in using v7.0.9.2?

No, I was **not** signed in (I never sign in, actually)

> 2. Is your internet/network connection generally stable? Have you had any other issues with accessing parts of the addon previously?

I'd consider my internet and network connection being "rock solid". I've never noticed any issues with that. 

> 3. When was the last time you accessed the addon using v7.0.9.2 prior to updating and getting the error?

I use the plugin basically every day, so in this case it worked on Dec 23, and I got the crash on Dec 24. I've got the plugin on automatic update from the official Kodi Repo, so I cannot be 100% sure exactly when it updated, but I actually just assumed it had updated between Dec 23 and 24 since it worked Dec 23. And when I rolled back to 7.0.9.2 it worked again.

> 4. No big deal if you don't want to, but would you be willing to roll back to v7.0.9.2 then upgrade to v7.1.1.6 and provide a debug log? I tried to replicate this issue but couldn't. It is an odd occurrence, but could just have been a passing glitch with the OAuth process (which is what the InvalidGrant exception was meant to signify).

I actually did go back and forth between 7.0.9.2 and 7.1.1.6 several times before creating this issue, trying different things to "make it work", e.g. clearing the caches, running the setup wizard again, rebooting between changes, etc. But none of these actions helped. Every time I rolled forward to 7.1.1.6 I got the crash when starting the plugin. And every time I rolled back to 7.0.9.2 it worked again. After rolling forward to 7.1.1.6 and checked the log and fixed the error locally in the code, 7.1.1.6 "got past" the error and then 7.1.1.6 worked. And **now I can no longer reproduce the error**. I can go back and forth between 7.0.9.2 and 7.1.1.6 and both versions work without errors.

**Comment by MoojMidge** [comment]
> No, I was **not** signed in (I never sign in, actually)

Ah ok, I think I see what the problem was now. Had you ever tried to sign-in in the past by any chance?

> 7.1.1.6 "got past" the error and then 7.1.1.6 worked. And **now I can no longer reproduce the error**. I can go back and forth between 7.0.9.2 and 7.1.1.6 and both versions work without errors.

Yeah, once the information stored in access_manager.json was updated then the issue would no longer be reproducible.

Thanks for the additional info.

**Comment by kendrak24** [comment]
> Ah ok, I think I see what the problem was now. Had you ever tried to sign-in in the past by any chance?
> 

Not that I can recall. If I have, it would have been several years ago, right after personal API keys became more or less mandatory to use the plugin.
