### ISSUE TITLE
MPEG DASH errors out with quota exceeded

### ISSUE THREAD

**Issue by tiagogaspar8** [anxdpanic/plugin.video.youtube#1039]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.6
* Kodi Version: latest master
* Kodi GUI Language: English
* Operating System: Android 11
* Operating System Language: English

------

### Expected Behavior

I expect the video to play without issue.

------

### Current Behavior

The video doesn't play, and spits out an error saying the quota is exceeded in the logs.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add API keys
2. Follow the wizard and select 4k hdr
3. Try to play a video, it doesn't work.

------

### Log

https://paste.kodi.tv/yiboyemeke

------

### Additional Information

Please provide any additional information that may be helpful.

This issue only happens If I enable MPEG-DASH for videos, when disabled it works perfectly.

------

**Comment by MoojMidge** [comment]
Playback isn't working because the http server that this addon runs is listening on `192.0.0.4`, which is blocked by default as it is not technically an IP address that is within a range designated for private usage.

Try changing the IP address to `127.0.0.1` in the addon settings: `YouTube > Settings > Advanced > HTTP Server > Select listen IP`

Regarding the quota is exceeded message, see here https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1748629019

You may need to recreate the API key.

**Comment by tiagogaspar8** [comment]
> Playback isn't working because the http server that this addon runs is listening on 192.0.0.4, which is blocked by default as it is not technically an IP address that is within a range designated for private usage.
> 
> Try changing the IP address to 127.0.0.1 in the addon settings: YouTube > Settings > Advanced > HTTP Server > Select listen IP

I see, this fixed the issue.
The reason the IP is 192.0.0.4 is because this device is in a IPv6-Only network. Would it be possible to add the option of the server also listening on IPv6 addresses? this will fix the issue on single stack devices.

**Comment by MoojMidge** [comment]
> Would it be possible to add the option of the server also listening on IPv6 addresses? this will fix the issue on single stack devices.

I don't have a IPv6 network so this is completely untested, but you can see if it works using this test version:
https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.2.0%2Bbeta.2/plugin.video.youtube-7.2.0+beta.2.zip

**Comment by tiagogaspar8** [comment]
Heyy @MoojMidge,
I'm testing this version, and when I select :: I get an error, and when I select ::1 it works flawlessly, even on ipv4-only networks.
What is the default?
Is :: supposed to be working? I do have Ipv6 addresses.
Thanks!

**Comment by MoojMidge** [comment]
> I'm testing this version, and when I select :: I get an error

I can't do anything with this. If you have a problem a log is the only means to provide the necessary information to understand what the problem may be. 

> What is the default?

`127.0.0.1`, but it this may not work for all setups, just like `0.0.0.0` didn't work for you. The Setup Wizard will check for any local IP address. 

> Is :: supposed to be working? I do have Ipv6 addresses.
>> The reason the IP is 192.0.0.4 is because this device is in a IPv6-Only network.

There are a bunch of things in your log that indicates that this is not actually the case. 

Not sure why you have chosen to use that particular IP address, but when you select `::` it will try to use any available IP address, in much the same way that using `0.0.0.0` also tries to do. When using `::` it may or may not end up using an IPv6 address.

Whether the available IP address is actually designated for private usage is something you control. You are likely running into the same problem you had when using `0.0.0.0`.

If you really want to use such an IP address then you can add it to the whitelist to force the http server to allow the request.

Or maybe there is a bug with the implementation? A log will clear things up. As I mentioned, I don't have the means to test this, so I am reliant on people who may use this functionality to provide feedback.
