### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Enzoinventor** [anxdpanic/plugin.video.youtube#1044]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.6
* Kodi Version: 21.1
* Kodi GUI Language: it
* Operating System: android 14.0.0
* Operating System Language: it

------

### Expected Behavior

Please describe the behavior you are expecting.

when connected to the WiFi network it works but when I use the phone's data connection it doesn't work

------

### Current Behavior

What is the current behavior?

Always

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Disconnect to wify
2. start the data connection from your phone
3. no video playback will work

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

Not accesible

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> Not accesible

🤷 

If you want help provide a debug log.

**Comment by Enzoinventor** [comment]
> > Non accessibile
> 
> 🤷
> 
> Se desideri aiuto, fornisci un log di debug.

I'm aware of this, but on my Samsung S24 the Kodi folder is not accessible. Can you kindly show me a method to extract it?
Thank you

**Comment by MoojMidge** [comment]
The steps to do so are documented in the Kodi Wiki. A link to this is provided in the section of the issue template that requests a log.

https://kodi.wiki/view/Log_file/Easy

**Comment by Enzoinventor** [comment]
this is the log when I use my phone's data connection and it doesn't work:https://paste.kodi.tv/doxuvusaye

**Comment by Enzoinventor** [comment]
this is the log when I am connected to WiFi and it works: https://paste.kodi.tv/ewamebovil

**Comment by Enzoinventor** [comment]
I attach a new log using the data connection, where I tried 3 times to play the same video and it always gives me an error: https://paste.kodi.tv/ewolapifiq

**Comment by Enzoinventor** [comment]
the error is right here when I use the data connection this link does not open:
error <general>: AddOnLog:
inputstream.adaptive: Download
failed, HTTP error 403
http://100.106.142.157:50152
◦ /youtube/manifest/dash?file=
LjwY4mBEOII.mpd

**Comment by MoojMidge** [comment]
```
info <general>: Disabled debug logging due to GUI setting. Level 0.
```

You haven't followed the first step in the instructions for producing a debug log...

Anyway, the problem will probably be fixed if you change the IP address for the http server to 127.0.0.1 in the addon settings: `YouTube > Settings > Advanced > HTTP Server > Select listen IP`

**Comment by Enzoinventor** [comment]
thank you very much, setting the server to 127.0.0.1 solved the problem. will you release an update about it or will the user always have to intervene manually?

**Comment by MoojMidge** [comment]
> will you release an update about it or will the user always have to intervene manually?

There is no one correct setting for this. `127.0.0.1` doesn't work in all cases, and `0.0.0.0` won't work in all cases either.

Anyway the last couple of beta versions have already changed the default value to `127.0.0.1` again, with the Setup Wizard changed to also check all local addresses, and then fallback to `0.0.0.0` if nothing else works.
