### ISSUE TITLE
Cannot sign in to Youtube addon

### ISSUE THREAD

**Issue by berkhornet** [anxdpanic/plugin.video.youtube#1045]
Until recently I've had no issues with the Youtube addon. Recently it asked me to sign-in again. I got the prompt about having to go to google.com/device page twice, but then received a Login Exception error.

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.6
* Kodi Version: 21.2
* Kodi GUI Language: English UK
* Operating System: Windows 10 and 11
* Operating System Language: English UK

------

### Expected Behavior

Able to log on without error

------

### Current Behavior

Login Exception Error 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. try to sign in from main menu
[kodi.log](https://github.com/user-attachments/files/18268066/kodi.log)

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
The 401 invalid client type error is quite common.

You will need to recreate your OAuth client details.

See the pinned issue for instructions and pay particular attention to Step 10:
https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1509319017

**Comment by berkhornet** [comment]
Many thanks. Up and running again. The process has changed a bit since those notes were put together but it’s possible if you are careful to work through it all.

Mick Rollitt
________________________________

**Comment by MoojMidge** [comment]
Glad you got it working
