### ISSUE TITLE
PO token

### ISSUE THREAD

**Issue by RNavega** [anxdpanic/plugin.video.youtube#1046]
Hi Mooj. According to the ["addendum" in this section here](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#manually-acquiring-a-po-token-from-a-browser-for-use-when-logged-out) from the YT-DLP guys, the PO token is visible in the "videoplayback" type requests done by the browser while watching on the YouTube site.
I use a personal MV2 browser extension to watch stuff in Kodi, it's in my alt account: https://github.com/doko-desuka/StreamCatcher
The flow is basically: Python add-on on Kodi starts a server listening on specific IP/port, then on my phone I browse to some site and wait for it to detect a video playback attempt where it blocks that request but reads all the juicy details (URL, headers, cookies etc), then I click on a button from the extension and it sends a request to my Kodi device (using the beacon API, it's a POST request w/o response) and then the add-on from Kodi grabs the resolved URL + headers and makes Kodi play it.

I think something based on this could be used to retrieve the PO token. The user would have to own an Android phone, and then use either Kiwi or Yandex which are Android web browsers, and both allow loading persistent extensions from a ZIP file by activating developer mode, which is needed as the extension wouldn't be on any official extensions catalog. So the extension could be distributed from a Github page for example.

Also from YT-DLP, the PO token should last for about 12 hours, so hopefully this would only have to be done twice a day. But even if it had to be done per video, the process takes about 30 seconds per video. I've been using that extension for quite a while.  
Before any effort is expended though, IMO the first thing to try is to see if the technique actually works: doing all these steps manually, going to the YT site and manually grabbing the "pot" parameter value etc and trying to play it with Kodi with like the "WEB" or "MWEB" clients and seeing if it bypasses these HTTP 403 responses.

**Comment by MoojMidge** [comment]
> going to the YT site and manually grabbing the "pot" parameter value etc and trying to play it with Kodi with like the "WEB" or "MWEB" clients and seeing if it bypasses these HTTP 403 responses.

There are two problem with doing this.

The first is that the HTML clients require the  `n` and/or `signatureCipher` parameters to be decoded i.e. it needs a JavaScript interpreter.

Could try and get these decoded values from the HTML client as well, but from when I last looked at this they were not common per video, but unique per stream. Could be wrong about that though.

Either way it would likely mean that the stream selection capabilities of the addon will be effectively neutered.

I do have an older version of the addon that can decode these parameters using the minimal JS interpreter that yt-dlp use. Will need to dust that off and update it.

The second problem is that just using the PO token is not sufficient to avoid the 403 errors and I suspect the fingerprinting that is inherent to the generation of these tokens, and other means of generating authenticated requests, could in fact lead to further IP blocks. Will need to see how this pans out.

The more general issue is that having to rely on a second device/app/client to enable is not a great outcome, although I agree that doing this has advantages over generating the PO tokens separately. Had a look and there currently only appears to be two implementations for doing so, both require a JS runtime, and both already appear to have reports that the tokens don't work all the time. I think both are reliant on executing the same token generating code, so it seems like this will end up as just another endless cycle akin to what the web player JS updates (i.e. `n` cipher changes ) currently are.

**Comment by RNavega** [comment]
You're right that while these IP ban changes are not completely committed, it's difficult if not impossible to debug and find a solution.

Unless I read it wrong, in YT-DLP it mentions that the PO token is paired with the session cookies (either incognito cookies, or logged in cookies), but it's not clear if it's for a specific client/platform or if that pair could be used with any other clients to get the full stream list as usual and also when playing specific streams.  
If it's possible to get the token+cookies pair from an easy place like the desktop website (for which the browser extension could be used) and then use it again with like the iOS or Android clients, then that would be the most convenient case IMO -- there'd be no need to worry about web player JS updates, the browser is serving as the JS engine.

Cheers!
