### ISSUE TITLE
Login not working (quota exceeded)

### ISSUE THREAD

**Issue by MisterT87** [anxdpanic/plugin.video.youtube#1047]
### Context
After Installing and configuring youtube Addon Settings I put my Youtube API Data in the settings and also Disabled the option "Allow Developer Keys".
Then tried to login to my youtube account and put the 9 Letters displayed from kodi to google.com/device (with success).

Then Youtube Addon shows something with quota exceeded...

Already tried: disabled MPEG-DASH -> same issue
deleting / Recreating API Credentials -> same issue (with new Youtube API Login)
Logged out and re login in youtube addon -> same issue

Checked also the quota limits for youtube api data: everything is on 0% on my account.

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.6
* Kodi Version: 21.1
* Kodi GUI Language: Germany
* Operating System: LibreElec 12.0.1 (Linux)
* Operating System Language: Germany

------

### Expected Behavior
I can Login to my youtube account and test if my subscriptions all available

------

### Current Behavior

Nothing is working

------

**Comment by MoojMidge** [comment]
> Then Youtube Addon shows something with quota exceeded...

If you want help from here you will need to provide a debug log.

Otherwise seek help from Google as that error message is coming directly from them.
