### ISSUE TITLE
quotaExceeded

### ISSUE THREAD

**Issue by marcogaio** [anxdpanic/plugin.video.youtube#109]
Suddenly the plugin refuse even to query youtube video, popping up the 'quotaExceeded' error.

Looking in google API page, the only strange thing i note is the 'YouTube Data API v3' that have a quota for 'Query per day' at 0, not modifiable.

Log attached.
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/6193185/kodi.log)

**Comment by marcogaio** [comment]
Still waiting some feedback.

Today i've deleted my API keys and OAuth client ID, cleared the kodi plugin config and redone all by scratch.

Same result.

Attached two screensot of my google account, where you can see that there's 100% error for all API calls; also, i've a limit, not modifiable, of '0 query per day'.

![Schermata da 2021-04-11 21-50-22](https://user-images.githubusercontent.com/7048664/114319215-ce6d8c80-9b10-11eb-825a-97be2b8fb238.png)
![Schermata da 2021-04-11 21-49-37](https://user-images.githubusercontent.com/7048664/114319216-d0375000-9b10-11eb-9eb8-046110cd6f0a.png)

Please, say me something. Thanks.

**Comment by l1krust** [comment]
Hi, I had the same issue. It was because I enable youtube API in Google console but scope was missing. 
The following steps solved the problem:
- Go to OAuth consent screen, then edit your app
- Go to screen 2: Scopes / add & remove scope
- Check all "YouTube Data API v3" APIs (I don't thing that all these API are mandatory to make it work. It can probably fine tuned)
- Click on update, then save
- You should now have a similar screen:
![image](https://user-images.githubusercontent.com/83354564/116419856-bcdcf200-a83d-11eb-9764-7337b1020e31.png)

Hope it will help you.

**Comment by marcogaio** [comment]
I've simply uninstalled and reinstalled the youtube plugin, without trying to link the plugin to my Google account.
And now i can send with Kore youtube video to the media player.

Currently i cannot test your suggestion, but because practically i've never used the youtube plugin directly but ony senting videos from my phones, seems a sufficient solution for me.

Only a note: in my screen __sensitive scopes__ are marked with an attention sign, pending Big G approval.

Thanks.

**Comment by keywan2020** [comment]
Can you please pin this comment? 
https://github.com/anxdpanic/plugin.video.youtube/issues/50#issuecomment-741829603

Resolved for me.

**Comment by rpgdev** [comment]
> Hi, I had the same issue. It was because I enable youtube API in Google console but scope was missing. The following steps solved the problem:
> 
>     * Go to OAuth consent screen, then edit your app
> 
>     * Go to screen 2: Scopes / add & remove scope
> 
>     * Check all "YouTube Data API v3" APIs (I don't thing that all these API are mandatory to make it work. It can probably fine tuned)
> 
>     * Click on update, then save
> 
>     * You should now have a similar screen:
>       ![image](https://user-images.githubusercontent.com/83354564/116419856-bcdcf200-a83d-11eb-9764-7337b1020e31.png)

Did not work for me.

**Comment by devhl-labs** [comment]
I just saw this. The scopes solution did not work for me. The post keywan2020 links worked for me. I had to create a new project, api key, and oauth credential with my email as an authorized test user.
