### ISSUE TITLE
Crash on playback while video loading

### ISSUE THREAD

**Issue by teodoryantcheff** [anxdpanic/plugin.video.youtube#113]
### Context

Crashlogs attached [kodi_crashlog.zip](https://github.com/anxdpanic/plugin.video.youtube/files/6259652/kodi_crashlog.zip)

-----

### Steps to Reproduce

1. Send a youtube video to be played. Either via yatse or [play to Kodi ](https://github.com/khloke/play-to-xbmc-chrome)chrome extension
2. While the progress spinner is on screen (several seconds) but before the video has actually started playing -  play or queue another video.
3. Crash happens.

This has been the case for at least 18 months now.
I like to queue up a "playlist" to watch on my TV, but recently videos take too long to start playing and it happens consistently and before the first video even starts playing.

**Comment by funkyfunked** [comment]
Experienced this bug a lot of times, complete Kodi crash if this happened.... An update to Kodi 19 Matrix stable fixed this for me, maybe worth a try.

**Comment by upbox-org** [comment]
I have the same problem as described for a long time. Even on Matrix. 
Kodi crashes when you try to start or add another web video (tried it with ZDFmediathek, Spiegel TV, Tele 5 and the YT plug-in of course). 

**So it is NOT a specific problem with the YouTube addon, it is a problem within Kodi - at least in my case.**
I think @anxdpanic could confirm that. 

**Specs:** 
Kodi v19.0 32-bit
OS: Linux 32-bit (CoreELEC 19.1-RC2)
YT Plugin: v6.8.10+matrix.1 (official unofficial version 🙃)
Tried it with and without the Yatse Matrix helper script addon (v92.4.3). Makes no difference.
Device: Odroid N2 4GB (Amlogic S922X)

**Logs:**
[kodi_crashlog_20210425152437.log](https://github.com/anxdpanic/plugin.video.youtube/files/6372103/kodi_crashlog_20210425152437.log)
[kodi.old.log](https://github.com/anxdpanic/plugin.video.youtube/files/6372104/kodi.old.log)

**Comment by upbox-org** [comment]
https://github.com/xbmc/xbmc/issues/15688
https://github.com/xbmc/xbmc/issues/16756

**Comment by teodoryantcheff** [comment]
@Retardium thanks for linking this to the underlying issues! Would have never found them.

**Comment by MMan1982** [comment]
Me too,crash kodi fully,buffering issue or something,but symptons are the same what's described here.
[kodi_crashlog-20210912_153040.log](https://github.com/anxdpanic/plugin.video.youtube/files/7149691/kodi_crashlog-20210912_153040.log)
