### ISSUE TITLE
Sharing playlist URIs for playback no longer works

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#115]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.10+matrix.1
* Kodi Version: 19.0
* Kodi GUI Language: EN
* Operating System: LibreELEC 9.95.1
* Operating System Language: EN

As far as the logs are concerned, I'm using this playlist as a specific example:

https://youtube.com/playlist?list=PLWP9RYfQbKCLOHuNqPrXwlY58HnXDKd1k

------

### Expected Behavior

I'm sharing a YouTube playlist URI (for example via Yatse from an Android phone) and I expect that playlist to start playing / maybe be asked whether I want to play it in regular / reverse / shuffled order.

------

### Current Behavior

After sharing the URI, Kodi dims the screen and shows a 'processing' spinner in the center. After a second or so, there is no further activity in the log.
Then, I can press the Back button and a dialog appears saying some items could not be played, refer to log.
There's nothing in the log that looks like an immediate clue to me.

------

### Steps to Reproduce

For example:

0. Have an Android phone with YouTube and Yatse installed and configured 
1. Find any (regular, not YouTube mix or such) playlist in the Android app
  I chose the "Transistor - No Commentary" playlist that comes up when searching for "Supergiant Transistor" playlists
2. Open the three dots context menu, choose 'Share'
3. Choose Yatse's 'Play on Media Center'
4. (Kodi hangs on a spinner screen)
5. Press 'Back' (in Yatse remote or keyboard or any other way)
6. Error dialog comes up

------

### Log

https://paste.kodi.tv/popikopuji.kodi

------

### Additional Information

Some time back, sharing playlists like this used to work. If I remember correctly, I believe it broke around the time of some overhaul that was taking place because of YouTube APIs changing / being deprecated.
Since the addon can handle playlists resulting from its own searching and browsing functions, I believe this to be well fixable and not limited in principle.

Having the Yatse Kodi Helper Script installed/activated on Kodi makes no difference to this use case.
Either way, the following internal URI is invoked and things go wrong from there:
`plugin://plugin.video.youtube/uri2addon/?uri=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist%3DPLWP9RYfQbKCLOHuNqPrXwlY58HnXDKd1k`

I've dug around in the code a bit. In provider.py, _on_uri2addon returns a result object containing a 
`plugin://plugin.video.youtube/special/description_links/?playlist_ids=PLWP9RYfQbKCLOHuNqPrXwlY58HnXDKd1k` URI. With that, processing apparently stops.
If, as an experiment, I change to `url_converter = UrlToItemConverter(flatten=False)` in provider.py, I get a result object with an
 `plugin://plugin.video.youtube/playlist/PLWP9RYfQbKCLOHuNqPrXwlY58HnXDKd1k/`URI, but nothing seems to get done with that, either:
 
https://paste.kodi.tv/ovesecaqah.kodi

I'm happy to look into this further, but I don't understand how the uri2addon mechanism is supposed to work. When I share a single regular video, I get a result object with an URI like `plugin://plugin.video.youtube/play/?video_id=MTR52CBdWUg` and the next line says `DEBUG <general>: [plugin.video.youtube] Converting PlayItem |plugin://plugin.video.youtube/play/?video_id=MTR52CBdWUg|`. No such line is printed in the playlist case; and execution does not reach to_playback_item in xbmc_items.py. Instead, the immediate next thing is '[plugin.video.youtube] Shutdown of Kodion after ...' (some very small amount of time).
Where does processing go with the return value from uri2addon?

------

**Comment by jmbreuer** [comment]
Looking at on_play in provider.py, I thought an URI format like this `plugin://plugin.video.youtube/play/?playlist_id=PLWP9RYfQbKCLOHuNqPrXwlY58HnXDKd1k` returned from uri2addon might help, but no change.

Hmm... It seems that the playlist is turned into a DirectoryItem, in a URI namespace 'within' the YouTube plugin. Where does/should "playing a DirectoryItem" happen?

**Comment by AlexNk** [comment]
Not sure if it's a bug or not, but play_playlist in yt_play.py doesn't receive "play" parm in the context. If I replace the last line with return videos[playlist_position], it starts playing. I guess, it's not a proper fix, but may be helpful.

So until the proper fix is available, I made the following change in on_play method in provider.py:

```
        elif 'playlist_id' in params:
            params['play'] = '1' # added this line
            return yt_play.play_playlist(self, context)
```
