### ISSUE TITLE
Enhance handling of subtitles in multiple languages

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#121]
### What Problem Does This Solve? 

I'm watching content in a mix of languages (English, German, Japanese, sometimes others).

When things get hard to understand, I'd like to have subtitles readily accessible at my current playback location, using Kodi's support for switching between multiple subtitles. To allow me to switch between same-language subtitles and translated subtitles.

------

### Suggest a Solution (optional)

The settings dialog should allow a list of languages to be freely configured (independent of add-on UI language) which subtitles to pre-load and populate whenever a video is started.

Normal and auto-generated subtitles are handled separately, one can then switch between those during playback and configure their relative priority in the settings. My suggestion would be to handle 'en' and 'en [auto]' just as two separate languages for a dialog where the user can add/remove/reorder a language preference list.

Any subtitles available for a video that match entries in that preference list are downloaded on playback, made available to Kodi's 'switch subtitle' functionality, and labeled appropriately there (i.e. to be able to discern which are the auto generated ones.)

------

**Comment by Skirmisher** [comment]
I would really appreciate this sort of sophisticated subtitle handling. In particular, if a video lacks standard English subtitles but has auto-generated ones, I usually don't want the auto-generated ones to be displayed by default, *but* I would like them to be available for selection so I can enable them if I need to. In general, there is no way to change subtitle language without navigating all the way to the add-on settings and restarting the video; being able to pick from all available subtitles on the fly would be a huge UX win.

(BTW, YouTube's own (vintage) [video on captions and subtitles](https://www.youtube.com/watch?v=QRS8MkLhQmM) is a perfect test case as a video with many different caption languages available.)

**Comment by w64** [comment]
I would greatly appreciate it if someone actually works on this improvement. For years I have been missing just such an option, to specify several possible languages and in what order the automatically translated and human translated subtitles should be.
