### ISSUE TITLE
Auto remove files 

### ISSUE THREAD

**Issue by jamos316** [anxdpanic/plugin.video.youtube#122]
Is it possible to add the function to automatically remove videos from 'my subscriptions' once they have reached the play count minimum percentage? This will also be a useful feature if you can use it with 'popular right now'

### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

------

**Comment by MoojMidge** [comment]
Closing as this is one of the purposes of the unofficial version. It allows displaying all/only watched/only unwatched videos in any listing using the Kodi inbuilt view options.
