### ISSUE TITLE
6.8.11: My Subscriptions - Can't change selection of `All Videos | Unwatched | Watched`

### ISSUE THREAD

**Issue by kuraikaze** [anxdpanic/plugin.video.youtube#124]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.11
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LibreELEC (Linux)
* Operating System Language: English

------

### Expected Behavior

Ability to change listing selector for [**All Videos | Unwatched | Watched**] to **Unwatched** so that already viewed videos are hidden and I don't have to scroll the selector up and down to skip past already viewed videos every time I return to the listing page.

------

### Current Behavior

Selector is set to **All Videos** and cannot be changed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open **My Subscriptions** folder
2. Try to change **All Videos | Unwatched | Watched** filter to  **Unwatched**

------

### Log

https://paste.kodi.tv/emupuhovuv.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by jodsclass** [comment]
I can second this. Unofficial repo version on 6.8.10 allowed hiding of watched/unwatched videos. The 6.8.11 update seems to have stopped this functionality working, even using the unofficial repo & test builds.

**Comment by dtteufel** [comment]
6.8.14 seems to have resolved this issue.

**Comment by kuraikaze** [comment]
6.8.14 still shows the issue for me.

I had downgraded to 6.8.10 to retain the ability, but the recent change at Youtube's end causing the "No videos found" error forced me to update.

**Comment by dtteufel** [comment]
@kuraikaze
Just for the record:
Hiding of watched/unwatched videos now works for me.
I'm running an OSMC Vero 4k with Kodi 18.9 
plugin.video.youtube-unofficial-6.8.14.zip

Possibly your setup is different.

**Comment by kuraikaze** [comment]
Resolved with 6.8.15

Thank you :)
