### ISSUE TITLE
Some videos play in low resolution in Kodi 19

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#125]
Some videos play in low resolution. For example this one: 
https://youtu.be/BpjHCTmKN2M

_RPi4, LibrELEC 9.95.2, Kodi 19, YouTube 6.8.11+matrix.1_

**Comment by toupeira** [comment]
Just noticed the same, all videos were suddenly playing at SD resolution. Interestingly a Kodi restart fixed it.

I'm using MPEG-DASH and had video quality set to "Adaptive (WEBM/VP9)", which IIRC worked fine for several months. Switched to a static "1080p (HD)" now and will see if the bug happens again.

(Debian sid, Kodi 19.1, YouTube 6.8.15+matrix.1, InputStream Adaptive 2.6.14)

**Comment by ebym** [comment]
RPi4 8GB, LE10, Kodi 19.1, Youtube 6.8.18.alpha3+matrix.1

Adaptive (MP4/H264) or Adaptive (WEBM/VP9) - play 144p(default) videos when selecting resolution higher than 720p. If video quality is set to 1080p or higher(upto 8k), it plays the selected resolution.

I'm not sure if this is YT add-on bug or InputStream related.

Other option is to select desired resolution and 'set as default for all media" or hit pause then change video resolution from settings.
