### ISSUE TITLE
Videos in My Subscriptions show much later or not at all

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#128]
_Translator:_
Some videos in My Subscriptions show much later than the smartphone or not at all. 

_RPi4, LibrELEC 9.95.3, Kodi 19.1, YouTube 6.8.11+matrix.1_

**Comment by Cnuut** [comment]
I have the same problem I think, with no videos showing up at all somtimes.
_Vero 4k+, OSMC (latest dev), YouTube 6.8.11+matrix.1 unofficial_

**Comment by crwolff** [comment]
I've seen the same issue, the only workaround I've found is to unsubscribe/subscribe the failing channels using a browser. It might work from within Kodi, but the UI is easier to navigate in a browser.
