### ISSUE TITLE
No Streams found

### ISSUE THREAD

**Issue by isleepinabucket** [anxdpanic/plugin.video.youtube#139]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.11
* Kodi Version: Leia
* Kodi GUI Language: english
* Operating System: windows 10
* Operating System Language: english

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/129
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.8.14

Check for updates, the latest update 6.8.14 should be available from the official repository as well.

**Comment by pattonwebz** [comment]
Just updated to latest 6.8.14 and I still have this issue too. If it doesn't resolve by tomorrow I will open a fresh issue thread with logs

**Comment by quijotez** [comment]
Still have this issue on 6.8.14 too

**Comment by Dendraspis** [comment]
Me, too, sadly.

Everything worked well with 6.8.11 (I guess) on Kodi v18.9 till yesterday. Today:  **No streams found**.
I updated Kodi to v19.1 and also this to v6.8.14-matrix1 from the official repository. I can see all streams and the search also seem to work correctly, but when I want to play a video:  **No streams found**.


```
2021-06-18 10:47:47.276 T:9100     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.14+matrix.1) on Matrix (Kodi-19.1) with Python 3.8.5
                                                   	Path: /play/
                                                   	Params: {'video_id': 'glQXCAORkDU'}
2021-06-18 10:47:49.775 T:9100    ERROR <general>: Traceback (most recent call last):
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 104, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 515, in load_stream_infos
                                                       return self._method_get_video_info(video_id)
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 1040, in _method_get_video_info
                                                       raise YouTubeException('No streams found')
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: No streams found
                                                   
2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
2021-06-18 10:47:49.775 T:9100    ERROR <general>: [plugin.video.youtube] None
2021-06-18 10:47:49.776 T:9100     INFO <general>: CPythonInvoker(22, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py): script successfully run
2021-06-18 10:47:49.789 T:7556    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=glQXCAORkDU]
```

**Comment by rafhtl** [comment]
Same Problem here with 6.8.14

**Comment by azaim** [comment]
> Me, too, sadly.
> 
> Everything worked well with 6.8.11 (I guess) on Kodi v18.9 till yesterday. Today: **No streams found**.
> I updated Kodi to v19.1 and also this to v6.8.14-matrix1 from the official repository. I can see all streams and the search also seem to work correctly, but when I want to play a video: **No streams found**.
> 
> ```
> 2021-06-18 10:47:47.276 T:9100     INFO <general>: [plugin.video.youtube] Running: YouTube (6.8.14+matrix.1) on Matrix (Kodi-19.1) with Python 3.8.5
>                                                    	Path: /play/
>                                                    	Params: {'video_id': 'glQXCAORkDU'}
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: Traceback (most recent call last):
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_play.py", line 50, in play_video
>                                                        video_streams = client.get_video_streams(context, video_id)
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 104, in get_video_streams
>                                                        video_streams = video_info.load_stream_infos(video_id)
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 515, in load_stream_infos
>                                                        return self._method_get_video_info(video_id)
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 1040, in _method_get_video_info
>                                                        raise YouTubeException('No streams found')
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: No streams found
>                                                    
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: 
> 2021-06-18 10:47:49.775 T:9100    ERROR <general>: [plugin.video.youtube] None
> 2021-06-18 10:47:49.776 T:9100     INFO <general>: CPythonInvoker(22, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py): script successfully run
> 2021-06-18 10:47:49.789 T:7556    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=glQXCAORkDU]
> ```

I am still having same problem with kodi 8.19 not working with both 6.8.11 and 6.8.14.

**Comment by ghost** [comment]
I am having the same problem with Kodi 18.9 and plugin version 6.8.14
Any new ideas?
