### ISSUE TITLE
YouTube Through VPN

### ISSUE THREAD

**Issue by nimaghz** [anxdpanic/plugin.video.youtube#14]
Hi,
I live in Iran and have to use VPN Manager for OpenVPN ([Link](https://github.com/Zomboided/service.vpn.manager)) to watch YouTube on my Kodi. I've got the private API, I've set it up and I don't think there an issue there. But after the update on my LibreELEC, it just doesn't work anymore. I've uploaded my log here:

https://pastebin.com/bJ1FCN3h

I believe now the addon, doesn't connect to YouTube server through my VPN.

Thank you.

**Comment by mohammadnassiri** [comment]
Hi @nimaghz,
If you still have this error, it's because of the DNS. You should set DNS in settings of your connection to something like 1.1.1.1 and 1.0.0.1
The openvpn configs usually couldn't set DNS and it still resolves domains from Iran ISPs.

**Comment by nimaghz** [comment]
Hi @mohammadnassiri 
Thank you for your response. Actually tried it in DNS Servers, but no changes unfortunately.
