### ISSUE TITLE
Video frame gets stuck on seeking video

### ISSUE THREAD

**Issue by XxAcielxX** [anxdpanic/plugin.video.youtube#140]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.14
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LibreELEC 9.2.6
* Operating System Language: English
------

### Expected Behavior

When seeking the video forward or backwards, the video should not get stuck on a certain frame. Audio keeps playing. 
------

### Current Behavior

Video gets stuck on certain frames when seeking forward or backwards, but audio keeps playing.
------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play any video
2. Seek forward or backwards
3. Video gets stuck on certain frame
------

### Additional Information

When the video is stuck, seeking the video again will fix the stuck frame. It keeps happening on very random seeking. This issue started after the 6.8.11 update, between 6.8.13 & 6.8.14

**Comment by kuraikaze** [comment]
I'm seeing this too - skipping forward or back frequently results in, most often, video frame freezing for a few seconds while audio continues then video catches up or, less often, long pause in both video and audio.

Looking at the extra stats overlay I can see that when seeking the "**aq**" (Audio Queue) almost instantly fill to 99% and plays audio but the "**vq**" (Video Queue) is at 0% and takes a while to start filling (variable dependent on bandwidth/bitrate/resolution of content).

Past behaviour (6.8.11 and earlier) it was very rare for there to be a long pause before new video/audio queue would start to fill, and when there was a hitch in fetching new section, audio would pause along with video frame.

Addon 6.8.14
Kodi 18.9
MPEG-Dash/Inputstream Adaptive @1440p

**Comment by XxAcielxX** [comment]
It seems the issue is fixed in 6.8.15, as I haven't seen it happen after this update. I'll mark this as fixed now.
