### ISSUE TITLE
Only low quality stream(s) available with certain videos

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#142]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.14+matrix.1
* Kodi Version: 19.1.0
* Kodi GUI Language: EN
* Operating System: LibreELEC 9.95.4
* Operating System Language: EN

------

My current example is https://youtu.be/gArxf7l4WZg

### Expected Behavior

On normal playback (just clicking on the video), Kodi/plugin.video.youtube should choose the highest quality stream combination that makes sense for the playback device (i.e. bandwidth limits configured for DASH, available codecs, ...).

When using 'Play (Ask for quality)', all video and audio streams served by YouTube should be presented as a choice.

------

### Current Behavior

The video mentioned above is played back in 360p using this plugin.

Using 'Play (Ask for quality)', there are some audio-only options, and 360p is the only video option shown.

------

### Steps to Reproduce

1. Browse to Kina Grannis' channel
2. Select the latest video, currently: 'Future Memories (Official Music Video)'
3. Video is played back in 360p

------

### Log

https://paste.kodi.tv/wimesomuhe.kodi

------

### Additional Information

Playing back in a desktop browser shows that the video does, in fact, have streams all the way up to 1080p.

youtube-dl 2021.05.16 recognizes the following formats:
```
> youtube-dl --list-formats 'https://youtu.be/gArxf7l4WZg'
[youtube] gArxf7l4WZg: Downloading webpage
[info] Available formats for gArxf7l4WZg:
format code  extension  resolution note
249          webm       audio only tiny   53k , webm_dash container, opus @ 53k (48000Hz), 1.59MiB
250          webm       audio only tiny   70k , webm_dash container, opus @ 70k (48000Hz), 2.08MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 3.84MiB
251          webm       audio only tiny  134k , webm_dash container, opus @134k (48000Hz), 3.99MiB
278          webm       256x144    144p   85k , webm_dash container, vp9@  85k, 24fps, video only, 2.52MiB
160          mp4        256x144    144p  100k , mp4_dash container, avc1.4d400c@ 100k, 24fps, video only, 2.97MiB
394          mp4        256x144    144p  109k , mp4_dash container, av01.0.00M.08@ 109k, 24fps, video only, 3.25MiB
242          webm       426x240    240p  183k , webm_dash container, vp9@ 183k, 24fps, video only, 5.42MiB
133          mp4        426x240    240p  222k , mp4_dash container, avc1.4d4015@ 222k, 24fps, video only, 6.60MiB
395          mp4        426x240    240p  242k , mp4_dash container, av01.0.00M.08@ 242k, 24fps, video only, 7.18MiB
243          webm       640x360    360p  390k , webm_dash container, vp9@ 390k, 24fps, video only, 11.56MiB
396          mp4        640x360    360p  403k , mp4_dash container, av01.0.01M.08@ 403k, 24fps, video only, 11.96MiB
134          mp4        640x360    360p  466k , mp4_dash container, avc1.4d401e@ 466k, 24fps, video only, 13.82MiB
244          webm       854x480    480p  718k , webm_dash container, vp9@ 718k, 24fps, video only, 21.26MiB
135          mp4        854x480    480p  723k , mp4_dash container, avc1.4d401e@ 723k, 24fps, video only, 21.42MiB
397          mp4        854x480    480p  725k , mp4_dash container, av01.0.04M.08@ 725k, 24fps, video only, 21.47MiB
136          mp4        1280x720   720p 1080k , mp4_dash container, avc1.4d401f@1080k, 24fps, video only, 31.99MiB
247          webm       1280x720   720p 1410k , webm_dash container, vp9@1410k, 24fps, video only, 41.75MiB
398          mp4        1280x720   720p 1518k , mp4_dash container, av01.0.05M.08@1518k, 24fps, video only, 44.96MiB
399          mp4        1920x1080  1080p 2111k , mp4_dash container, av01.0.08M.08@2111k, 24fps, video only, 62.51MiB
248          webm       1920x1080  1080p 2464k , webm_dash container, vp9@2464k, 24fps, video only, 72.96MiB
137          mp4        1920x1080  1080p 3416k , mp4_dash container, avc1.640028@3416k, 24fps, video only, 101.16MiB
18           mp4        640x360    360p  727k , avc1.42001E, 24fps, mp4a.40.2 (44100Hz), 21.54MiB (best)
```

youtube-dl's default download uses formats 137+251.
I don't know where/why youtube-dl marks format 18 as 'best' - this is the (only, video) format that plugin.video.youtube chooses according to the log above.

I'll see whether I can path the plugin to provide more log output around stream selection.

Might be related to issue #38.

------

**Comment by anxdpanic** [comment]
https://snipboard.io/PCI438.jpg

Enable MPEG-DASH for videos.
`Settings -> MPEG-DASH -> Use MPEG-DASH`
`Settings -> MPEG-DASH -> Use for videos`
`Settings -> MPEG-DASH -> Video quality`

**Comment by jmbreuer** [comment]
> https://snipboard.io/PCI438.jpg
> 
> Enable MPEG-DASH for videos.
> `Settings -> MPEG-DASH -> Use MPEG-DASH`
> `Settings -> MPEG-DASH -> Use for videos`
> `Settings -> MPEG-DASH -> Video quality`

Ah, thanks! I was convinced it's (supposed to be) turned on - is it possible that the recent update turned it off somehow?
