### ISSUE TITLE
unknown - Stereo (1/2) / unknown - Stereo(2/2)  _ Sound issue in MPEG-DASH

### ISSUE THREAD

**Issue by Caballingus** [anxdpanic/plugin.video.youtube#144]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.14
* Kodi Version: 17.6 Krypton
* Kodi GUI Language: English
* Operating System: Android
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

Audio was working fine in previous versions. 
Since version 6.8.14 MPEG-DASH audio streams in most videos won't get decoded properly.
By default there is no sound at all. 
In most cases 2 Unknown Stereo streams (1/2) and (2/2) are showing up, 
even though stream selection in MPEG-DASH-InputStream Adaptive is set to Auto.
Manually selecting Unknown Stereo Stream (2/2) will work but can't be set as default.
Hence in the next video the audio stream will have to be selected manually again.    

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by fedprod** [comment]
Kodi Version: 17.6 Krypton < I would say there lies your problem...

**Comment by anxdpanic** [comment]
Can you try with https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.8.15

**Comment by Dikowda** [comment]
Had same issue on Kodi 17.6.
6.8.15 release has fixed it for me.  Thanks @anxdpanic
