### ISSUE TITLE
Currently playing video title contains Unicode codes for non-Latin.

### ISSUE THREAD

**Issue by oleg-komaristov** [anxdpanic/plugin.video.youtube#154]
### Context

Please provide any relevant information about your setup.

* Add-on Version: 6.8.14
* Kodi Version: 18.9
* Kodi GUI Language: Ukrainian
* Operating System: LibreELEC 9.2.7
* Operating System Language: -

------

### Expected Behavior

In the system player title of the youtube video is displayed the same way as in the list of videos inside the youtube plugin.

------

### Current Behavior

In the player, titles are displayed as escape codes like "\u0412\u0417\u0413..."

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open any youtube video with a Russian title.
2. Show video information in Kodi player

------

### Log

Not sure the log file will be helpful in this case - it doesn't contain any errors
------

### Additional Information

It was work correctly before the last updates (in v. 6.8.12, I think).

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.8.15

**Comment by oleg-komaristov** [comment]
Thank you! It is working as expected now.
