### ISSUE TITLE
Broken non-English characters in notifications 

### ISSUE THREAD

**Issue by mikromcz** [anxdpanic/plugin.video.youtube#160]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.15-matrix.1
* Kodi Version: 19.1
* Kodi GUI Language: Czech 
* Operating System: Ubuntu 20.10
* Operating System Language: Czech 

------

### Expected Behavior

Please describe the behavior you are expecting.

When I add/remove video to/from WL, notification in the top right corner have broken text. It just screw up Czech characters. 

I have checked all related files in addon and all seems to be correct and in utf8. 

I don't have this issue with other addons. 

------

### Current Behavior

What is the current behavior?

See pictures 
![screenshot00021](https://user-images.githubusercontent.com/25269950/122995041-5c83b000-d3a9-11eb-8635-de3c503b7984.png)
![screenshot00022](https://user-images.githubusercontent.com/25269950/122995043-5d1c4680-d3a9-11eb-8cb6-f5435e77671e.png)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add video to watch later 
2. Remove video from watch later 
3. Probably anything else with notification 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

Definitely not critical issue, but it might be the same in other languages too. 

------

**Comment by nixxo** [comment]
Italian language has the same problem has OP.

it's a problem added by https://github.com/anxdpanic/plugin.video.youtube/commit/fe1825d6c9356852dcbf1bff6a09ef39361bcd07

if I comment out those two lines of code the notification msg gets shown properly

**Comment by mikromcz** [comment]
> Italian language has the same problem has OP.
> 
> it's a problem added by [fe1825d](https://github.com/anxdpanic/plugin.video.youtube/commit/fe1825d6c9356852dcbf1bff6a09ef39361bcd07)
> 
> if I comment out those two lines of code the notification msg gets shown properly

I can confirm! after commenting

```
#if PY3 and isinstance(message, str):
#    message = message.encode('utf-8')
```

in

`xbmc_context_ui.py`

problem went away and notifications are correct
