### ISSUE TITLE
Error Contents: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /youtube/v3/search... (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xdc5a8070>: Failed to establish a new connection: [Errno -2] Name or service not known',))

### ISSUE THREAD

**Issue by clement-analogue** [anxdpanic/plugin.video.youtube#166]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.4.7.1
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LibreELEC 9.2.6
* Operating System Language: English

* Device: Pine64 ROCKPro64 (RK3399)

------

### Expected Behavior

Please describe the behavior you are expecting.

After installing the addon, I want to be able to search for video.

------

### Current Behavior

What is the current behavior?

After installing the addon, I tried to search, but I have an error message.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the addon
2. Search for something, like "v"

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/rizecoluma.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

It's a fresh install. I tried to reinstall the addon a second time with wiping out the data from the addon, but same result.

------

**Comment by neo-neo1** [comment]
Searching works fine here, not an Addon issue. Try new YouTube api credentials perhaps.
