### ISSUE TITLE
Sort as... context menu for search results

### ISSUE THREAD

**Issue by probonopd** [anxdpanic/plugin.video.youtube#172]
Please make it possible to define for each saved search what the search should be ordererd/sorted by, e.g., "by date" with the most recent search results first. It should be possible to choose the order for each saved search term separately through its context menu.

### What Problem Does This Solve? 

Use case:
I have set up some searches for terms for which I always want the latest, not just the top-ranked, search results.

------

### Suggest a Solution (optional)

Here is an implementation of this exact feature from [plugin.video.invidious](https://github.com/lekma/plugin.video.invidious/):
https://github.com/lekma/plugin.video.invidious/commit/b1f48d30fcc67b44abba8d877267d07cf97b3780

Reference:
* https://github.com/lekma/plugin.video.invidious/issues/48 (implemented)

**Comment by MoojMidge** [comment]
This is now availabe in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.4
