### ISSUE TITLE
Installation feedback / Documentation wiki

### ISSUE THREAD

**Issue by Plumf** [anxdpanic/plugin.video.youtube#19]
## Context

* With [OSMC](https://osmc.tv/) on Raspberry Pi 3B+.
* OSMC's fresh installation.
* Just one extension : ARTE+7

## What ?

During the configuration of the Youtube extension, when use `youtube.com/activate` it doesn't work. I do use `google.com/device` for a good installation.

I don't know if it specific problems or it's more général.

Thank for your good extension to kodi.

**Comment by elvey** [comment]
The UI has changed since the video was made.
I followed the instructions as best I could but to no avail. It needs to be re-shot

**Comment by e474** [comment]
The video is blurry, and apparently wrong anyway, which just shows that uploading video howtos is a stupid practice. There's a step by step (in text) at: https://kodibeginner.com/setup-personal-api-key-youtube-kodi/ - or just Google for better howtos.
