### ISSUE TITLE
README.md should explain the variants

### ISSUE THREAD

**Issue by probonopd** [anxdpanic/plugin.video.youtube#196]
There are four downloads. The differences should be explained in [README.md](https://github.com/anxdpanic/plugin.video.youtube/blob/master/README.md).

* plugin.video.youtube-$VERSION+matrix.1.zip
* plugin.video.youtube-$VERSION.zip
* plugin.video.youtube-unofficial-$VERSION+matrix.1.zip
* plugin.video.youtube-unofficial-$VERSION.zip

**Comment by anxdpanic** [comment]
Added to the Wiki: https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation#zip-file-variants

**Comment by probonopd** [comment]
Thank you @anxdpanic that helps a lot. :+1:
