### ISSUE TITLE
The API key and the authentication credential are from different...

### ISSUE THREAD

**Issue by nickrout** [anxdpanic/plugin.video.youtube#20]
I have just installed this addon in coreelec 9.2.4.2. The resulting version of the addon is 6.8.4.

I have added the API keys, exactly the same ones I use on another kodi box.

I logged in (twice) using the same google account that the API keys were generated in. I have rebooted.

When I enter the addon, it shows me the list of directories like I expect if I am logged in.

If I click on My Subscriptions, all is well. There are numerous videos there that are ones from my subscription list, sorted by date.

If I click on Subscriptions on the other hand (the link further down that usually gives you the individual subscribed channels) then I get a notification "The API key and the authentication credential are from different...". The rest is cut off. The resulting directory listing is blank, except for the ... go up a level.

History works (kinda, it only shows videos I watched elsewhere, like my laptop, not from kodi).

Recommendations shows the error. 

What have I done wrong?

**Comment by anxdpanic** [comment]
Do you happen to have a debug log? This is working here, and doesn't sound like you did anything wrong in particular.
