### ISSUE TITLE
Official (HOW-TO: Install) link is broken.

### ISSUE THREAD

**Issue by BeastOfBodmin** [anxdpanic/plugin.video.youtube#203]
On
https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation

This lnk is broken
Official (HOW-TO: Install) -> https://kodi.wiki/view/HOW-TO:Install_add-ons

**Comment by logological** [comment]
The same problem exists with the "Repository zip files (HOW-TO: Install)" link at the bottom of the page.  This link points to https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files but there is no such page on the Kodi wiki.

**Comment by logological** [comment]
Probably the first installation link should point to https://kodi.wiki/view/Add-on_manager and the second should point to https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

**Comment by anxdpanic** [comment]
Both should be fixed now, thanks for the heads up
