### ISSUE TITLE
Error 403 when trying to sign after adding my keys to the youtube addon

### ISSUE THREAD

**Issue by briantho** [anxdpanic/plugin.video.youtube#204]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.17+matrix.1
* Kodi Version: 19.1
* Kodi GUI Language: English
* Operating System: Fire TV
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

I expect to be able to log into the google.com/devices page, and have everything work.

------

### Current Behavior

What is the current behavior?
So, I have created my keys enabled Youtube APIv3 and sucessfully pasted them into the Kodi Youtube Client. Now, I go to sign in on the youtube app and it says to go to google.com/device and enter the code. I do that. I get asked to sign into my google account. Done. Next page is a authorization error, 403. Access denied. Take a look at the screenshot. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create API Keys, enter them into Kodi Youtube Addon. 
2. CLick sign in, go to google.com/device and enter the code
3. Sign into my google account
4. Get a 403 Access Denied Error

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/mebewuzino

------

### Additional Information

Please provide any additional information that may be helpful.

I've tried this several times, and have gotten the same error every time. I've deleted the keys, recreated them, and even tried to create another project with new keys, on google cloud. Nothing gets me past this error. Please help. Thanks

------

**Comment by briantho** [comment]
Here is the screensh
![134795369-7ad20585-2314-4ea2-a46a-7eb1c9f5ee5f](https://user-images.githubusercontent.com/3977205/135208207-211948d4-030e-4307-9eac-9f96de9a3f8e.jpg)
ot

**Comment by infoscav** [comment]
I think you've configured OAuth consent incorrectly (Internal instead if External) when creating your application.

**Comment by briantho** [comment]
sure enough, it's set to external. Any idea how to change it to internal? When i go to my OAuth consent screen page. I can't appear to change the type to internal? Should I just create a new google cloud project, and start over, this time i will be sure to select internal, Or is there some way to change to internal on my current project. See the screenshot below.
![Untitled](https://user-images.githubusercontent.com/3977205/135322545-d348d3e5-3a45-4f96-a2cb-cefcf01cbbe4.png)

**Comment by briantho** [comment]
Ok, I just checked again, and the only option I have is external. After checking a few guides from my understanding it needs to be external. Or is this wrong, and it really needs to be internal? If that's the case how do i set up internal?

**Comment by briantho** [comment]
Does anyone have any idea why this is happening? am I the only one that's affected by this? did google change something, or is this something I am doing wrong? Please help

**Comment by 7FM** [comment]
@briantho 
I just had the same issue. After adding myself to the list of test users (under the OAuth consent screen), signing in succeeds. Hope this works for you too!

**Comment by briantho** [comment]
Derp, that fixed it. Thanks. This should be included in the instructions. Thanks again

**Comment by 43Rageon** [comment]
> @briantho I just had the same issue. After adding myself to the list of test users (under the OAuth consent screen), signing in succeeds. Hope this works for you too!

hi, i have the same problem, i couldn't add myself as test user because it wants Google Workspace account, or Cloud Identity account. Is there any other way?
