### ISSUE TITLE
Repository expired certificate

### ISSUE THREAD

**Issue by matejdro** [anxdpanic/plugin.video.youtube#221]
This is not completely related to the addon, but your repository appears to have SSL issues, preventing Kodi from connecting:

```
GetDirectory - Error getting addons://repository.anxdpanic/
CGUIMediaWindow::GetDirectory(addons://repository.anxdpanic/) failed
CCurlFile::FillBuffer - Failed: SSL peer certificate or SSH remote key was not OK(60)
```

* Kodi Version: `Kodi (19.2 (19.2.0) Git:20211006-52c19a0728). Platform: Android ARM 32-bit`

**Comment by anxdpanic** [comment]
Thanks for the heads up, the certs have been updated and verified working.
