### ISSUE TITLE
subtitles not working on 6.8.18.alpha3+matrix.1

### ISSUE THREAD

**Issue by ebym** [anxdpanic/plugin.video.youtube#222]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18.alpha3+matrix.1
* Kodi Version: 19.1
* Kodi GUI Language: English
* Operating System: LibreELEC 10
* Operating System Language: EN

------

### Expected Behavior

Subtitles should be working.

------

### Current Behavior

Subtitles not working, It show dialogue box to select subtitles, but won't display anything.

------

### Steps to Reproduce

Enable subtitle in setting.

------

### Log

------

### Additional Information

Subtitles were working with official add-on version, esp for the following channels and videos.

Rick Steves' Europe.
Free Documentary.
Eugenio Monesma - Spanish Audio (English subtitles).
Mark Weins.
and other subtitles enabled videos.....

------

**Comment by anxdpanic** [comment]
alpha4 is in the usual place and repositories updated. this includes @RNavega 's fixup for subtitles.

**Comment by ebym** [comment]
@RNavega & @anxdpanic  - subtitles not working on -  RPi4, LE10, Matrix 19.1, alpha4, both builds. The video won't play when 'Download subtitles before playback" is selected. This issue is not there with alpha3.

```
plugin.video.youtube-6.8.18.alpha4+matrix.1.zip
plugin.video.youtube-unofficial-6.8.18.alpha4+matrix.1.zip
```
Have rebooted, sign-in & out few times, even uninstalled alpha3 and did fresh alpha4 install.

logs.
https://pastebin.com/kuRPMiew

**Comment by anxdpanic** [comment]
I've just pushed a fix for subtitles, alpha5 is available from the usual places

**Comment by jmh2002** [comment]
Thanks, I can confirm that Alpha 5 fixes the Subtitles not working for me with Alpha 3 & 4.

**Comment by ebym** [comment]
Many thanks, subtitle issue is fixed on alpha5.

**Comment by kedarz** [comment]
It is working like a charm. Many thanks

**Comment by anxdpanic** [comment]
6.8.18 should be available from the official repository now.
