### ISSUE TITLE
some youtube videos always freeze - others never freeze!

### ISSUE THREAD

**Issue by kiai72** [anxdpanic/plugin.video.youtube#231]
since a while youtube playback freezes quite often. I checked network etc. - but it's only in youtube!
Then i noticed: it seems to be only with SOME videos. Most likely: newer videos!
For example: 
this ALWAYS freezes: https://www.youtube.com/watch?v=a-fpLmJHLvw
this NEVER freezes: https://www.youtube.com/watch?v=nY7GnAq6Znw

i tried:
RPI4 with Kodi 18
RPI4 with Kodi 19
RPI3 with Kodi 18
Libreelec X86_64 with Kodi 18
-> all the same.

Choosing lower resolution hardly makes a difference.

Any idea why - and how to fix this ?

**Comment by stefan-walluhn** [comment]
I can reproduce the behavior and diged into it. It seems, youtube added some kind off throttling. After some conversation with the youtube-dl folks (https://github.com/ytdl-org/youtube-dl/issues/30132), that are also affected, I came across this explanation https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/163
https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
