### ISSUE TITLE
No audio MPEG-DASH@1080p 6.8.18.alpha6+matrix1 libreelec10/kodi19/rpi4/InputStream19.0.0.1

### ISSUE THREAD

**Issue by Morgyn** [anxdpanic/plugin.video.youtube#232]
### Context

Please provide any relevant information about your setup
```
* Add-on Version: 6.8.18.alpha6+matrix.1
* Kodi Version: 19
* Kodi GUI Language: English
* Operating System: Libreelec 10
* Operating System Language: English
```

### Expected Behavior

Sound when playing 1080p streams via MPEG-DASH

### Current Behavior

Sound when playing 1080p streams via MPEG-DASH

720p works with audio

Audio Only works.

Weirdly when I ask to pick resolution, the 1080p has an audio rate of 128.

```
1080p (mpd h264 / aac@128) = no audio
720p (mp4 h264 / aac@192) = audio
360p (mp4 h264 / aac@96) = audio 
```

### Steps to Reproduce

1. Pick video to play
2. Ask for resolution
3. Select 1080p (1080p (mpd h264 / aac@128))

### Log

https://gist.github.com/Morgyn/05114ec1db761a663a7cee057a01f6c6

In this log I first play a 1080p video with no sound, then a 720p video with sound.

### Additional Information

libreelec 10
kodi 19
rpi4
InputStream19.0.0.1

------

**Comment by geonerozero** [comment]
I have the same issue, but with 2160p streams in 6.8.18. I see that you faced it with 6.8.18.alpha. Has 6.8.18 solved it for you?

**Comment by Morgyn** [comment]
No this occurs still with 6.8.18 release.

**Comment by malick-2892** [comment]
Do You happen to have 
Apps -> Addon Browser -> My Addons -> VideoPlayer Input Stream -> Inputstream Adaptive -> Settings -> General -> Media
set to anything else than "All" (e.g. "Video")?
If that's the case You need the "All" setting applied. Hope that'd be as trivial for You.

**Comment by geonerozero** [comment]
For me, this setting is already set to "all".

**Comment by Morgyn** [comment]
> Apps -> Addon Browser -> My Addons -> VideoPlayer Input Stream -> Inputstream Adaptive -> Settings -> General -> Media
> set to anything else than "All" (e.g. "Video")?
> If that's the case You need the "All" setting applied. Hope that'd be as trivial for You.

This fixed it for me! Thanks
