### ISSUE TITLE
Improve accessibility to Unsubscribe context menu option

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#240]
Context menu only has `Subscribe` option. There's no option to unsubscribe from within this plugin at all. 

Similarly to your [Twitch Kodi Plugin](https://github.com/anxdpanic/plugin.video.twitch) there's a `Toggle Follow` option which allows both follows and unfollows. On this YouTube plugin please implement`Toggle Subscribe` instead of the current `Unsubscribe` only. If `Toggle` isn't possible to implement then add an additional `Unsubscribe` option at least.

Past 4 years of using this YouTube Plugin on Kodi I've always had to open YouTube app on my phone just to unsubscribe.

**Comment by netty0** [comment]
Glad someone else noticed. Would like to see this get implemented.

**Comment by anxdpanic** [comment]
Go to `Subscriptions` on the main menu, open the context menu on the subscription you want to unsubscribe from.

**Comment by neo-neo1** [comment]
> Go to `Subscriptions` on the main menu, open the context menu on the subscription you want to unsubscribe from.

Thanks but is it not possible to have a toggle on the context menu?

**Comment by anxdpanic** [comment]
It will cost more quota, which is limited. Where Twitch doesn't have the quota limitation with the v5 api.

**Comment by neo-neo1** [comment]
> It will cost more quota, which is limited. Where Twitch doesn't have the quota limitation with the v5 api.

2 thoughts:

Having `Subscribe` context option in `Subscription` menu  is the true problem. Why not change default to `Unsubscribe`? More Logical. 

Or add `Subscribe` context option underneath existing `Unsubscribe` option. This would eliminate the need for `My Subscriptions` menu and streamline usability greatly.  Or even add `Unsubscribe` to current `More` expandable context option



Thanks for your time.

**Comment by netty0** [comment]
> It will cost more quota, which is limited. Where Twitch doesn't have the quota limitation with the v5 api.

As @neo-neo1 said, at the very least adding "Unsubscribe" under existing "More" is a legitimate usability improvement. This feature suggestion was closed prematurely.

**Comment by anxdpanic** [comment]
it was closed under the premise this was opened because you couldn't do it from the add-on, and a toggle isn't the option as stated.

That said, I'll re-open under a different title

**Comment by jonisb** [comment]
It would be really nice not having to go to the "Subscriptions" to unsubscribe, I have subscribed to a lot of channels and takes forever to get to the right channel.

**Comment by FaBjE** [comment]
I didn't know unsubscribing was possible from the add-on. Many times I accidentally subscribed (wanting to go to the channel) I opened YouTube in a browser to unsubscribe.
I think It would be a welcome improvement if the unsubscribe option was given next to the subscribe option.

Maybe both can be moved to the "More..." menu options? to "simplify" the standard context menu a bit. as subscribing to a channel is not something you do every day.
