### ISSUE TITLE
Integration with SponsorBlock API

### ISSUE THREAD

**Issue by bshamanov** [anxdpanic/plugin.video.youtube#246]
### What Problem Does This Solve? 

Now the plugin is very valuable with its YouTube advert blocking, but in addition, some channels will have very long and very annoying sponsor blocks. I can mention RAID: SHADOW LEGENDS and I think I need no more.

------

### Suggest a Solution (optional)

Automatically skipping certain sponsored or self promotion blocks would make very many people happy. The only solution that I am aware right now is integration with SponsorBlock API: https://sponsor.ajay.app/
It works very well with Youtube Vanced (https://vancedapp.com/).

It would be a nice extra to be able to exclude certain channels from this block.

------

**Comment by anxdpanic** [comment]
https://github.com/siku2/script.service.sponsorblock
