### ISSUE TITLE
Allow opening videos in browser

### ISSUE THREAD

**Issue by toupeira** [anxdpanic/plugin.video.youtube#249]
### What Problem Does This Solve? 

I sometimes want to read the comments after watching a video, which currently involves opening a browser and manually finding the video I just watched.

------

### Suggest a Solution (optional)

Add a context menu item "Open in browser", which opens the video's URL with the default OS handler.

It looks like in Python this can be done very easily with `webbrowser.open()`: https://docs.python.org/3/library/webbrowser.html.

------

**Comment by jonisb** [comment]
You can read comments via the plugin (Even though reading longer texts can be annoying with the auto scroll )

**Comment by toupeira** [comment]
Ooh neat, didn't realize! But yeah that's not very usable, I'd rather read them in a browser where I can also open links or searches.
