### ISSUE TITLE
Playlists without API Key

### ISSUE THREAD

**Issue by Mynacol** [anxdpanic/plugin.video.youtube#254]
### What Problem Does This Solve? 

Using Kore on your Android device or similar software allows you to easily cast a video to your Kodi box. But playing back playlists is impossible without an API key. Some, like I, don't want to log into YouTube or create and "log in" using API Keys for privacy reasons.

This would aid in using YouTube Music without logging in, which heavily uses playlists in the background.

Additionally, this would lower the usage of API keys, making it less likely to hit a limit.

------

### Suggest a Solution

The relevant information should be obtainable by scraping the website, similar to [youtube-dl/yt-dlp](https://github.com/yt-dlp/yt-dlp/) and [NewPipe](https://github.com/TeamNewPipe/NewPipeExtractor/). Another light-weight scraper in JavaScript is [ytpl](https://github.com/TimeForANinja/node-ytpl).

------

Other features of this add-on could be migrated as well, almost completely eliminating the need for API keys (think NewPipe)

**Comment by anxdpanic** [comment]
The suggested alternatives aren't an option for this add-on. 
Some one can gladly create a NewPipe add-on (if it's possible), and there have been issues related to this suggestion many times.
