### ISSUE TITLE
Plugin incompatible with python 3.10.1

### ISSUE THREAD

**Issue by graysky2** [anxdpanic/plugin.video.youtube#255]
### Context

* Add-on Version: 6.8.18 matrix.1
* Kodi Version: 19.3
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

Plugin should work with python 3.10.1

------

### Current Behavior

Plugin crashes Kodi with python 3.10.1

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install python 3.10.1 on the system
2. Load Kodi
3. Install this plugin and attempt to use it

------

### Log

[debug log](https://gist.github.com/graysky2/8a1e5b3130f31db227089251b1a2d352).

**Comment by asavah** [comment]
@graysky2 it's not this plugin's fault.
I've stumbled into this too.
It's cpython's fault as evidenced by your debug log the issue happens when importing sqlite, it happens only with subinterpreters.
They (core python devs) somehow broke subinterpreters with this change in 3.10.1 https://github.com/python/cpython/commit/d0d29655ffc43d426ad68542d8de8304f7f1346a  the problematic change is in import.c file. Reverting this change and rebuilding python fixes the issue.
Sadly I have absolutely no free time to properly report bugs right now.

**Comment by graysky2** [comment]
Thanks @asavah - this is over my head.  I did not see anything on their [bug tracker](https://bugs.python.org/).  Is that where you would file a report?

**Comment by asavah** [comment]
Yep, they probably will ask for a minimal c code snippet reproducing the issue which is above my paygrade )
From my limited testing It seems to happen only when importing sqlite in a script running under subinterpreter.
A plain script run with python itself works fine.

Another very very dirty workaround would be to edit /usr/lib/python3.10/sqlite3/dbapi2.py
and comment out this line
```
    register_converter("timestamp", convert_timestamp)
```
But I'm totally not sure what would this break in your system.

**Comment by graysky2** [comment]
Thank you :+1: I am happy to revert https://github.com/python/cpython/commit/d0d29655ffc43d426ad68542d8de8304f7f1346a while compiling 3.10.1 if that is safer.  Testing now.

**Comment by graysky2** [comment]
Closed since not the fault of the plugin.  Used your verbiage in these bug reports, @asavah, thanks for the time :+1: 

https://bugs.python.org/issue46070
https://bugs.archlinux.org/task/73002

**Comment by NikitaKarnauhov** [comment]
Hi! So, does it actually work with python-3.10.1 with bpo-44050 reverted? I have a similar crash with python-3.10.0 (on Fedora 35) that isn't supposed to have that commit.

**Comment by graysky2** [comment]
It did for me.  I have since gone back to the official 3.10.1 release and just disabled the youtube plugin until I get some feedback on whether or not running python with that commit disabled is safe.

**Comment by ghen2** [comment]
3.10.0 was ok for me, so your issue must be a different one (bpo-44050 is in [the changelog between 3.10.0 and 3.10.1](https://github.com/python/cpython/compare/v3.10.0...v3.10.1)).

**Comment by graysky2** [comment]
You are right, @ghen2 .  I just pulled down [python-3.10.0-1](https://archive.archlinux.org/packages/p/python/python-3.10.0-1-x86_64.pkg.tar.zst) and found that the bug is not present.

**Comment by NikitaKarnauhov** [comment]
Yeah my issue must be something different then. Upgrading to 3.10.1 (sans bpo-44050) didn't help. I get crashes in various places, mostly this one:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f207a914228 in _PyErr_SetObject (tstate=0x7f1f6c22d4e0, exception=0x7f1ffdbb0aa0, value=0x7f200835f2f0) at /usr/src/debug/python3.10-3.10.0-1.fc35.
x86_64/Python/errors.c:119
119         if (exception != NULL &&
[Current thread is 1 (Thread 0x7f1fc2ffd640 (LWP 53560))]
...
Thread 1 (Thread 0x7f1fc2ffd640 (LWP 53560)):
#0  0x00007f207a914228 in _PyErr_SetObject (tstate=0x7f1f6c22d4e0, exception=0x7f1ffdbb0aa0, value=0x7f200835f2f0) at /usr/src/debug/python3.10-3.10.0-1.fc35.
x86_64/Python/errors.c:119
#1  0x00007f207a91245c in _PyErr_FormatV (vargs=0x7f1fc2ff9f90, format=0x7f201c02f240 "Error binding parameter %d - probably unsupported type.", exception=0x7
f1ffdbb0aa0, tstate=0x7f1f6c22d4e0) at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_64/Python/errors.c:1060
#2  PyErr_Format (exception=0x7f1ffdbb0aa0, format=format@entry=0x7f201c02f240 "Error binding parameter %d - probably unsupported type.") at /usr/src/debug/py
thon3.10-3.10.0-1.fc35.x86_64/Python/errors.c:1100
#3  0x00007f201c02a18c in pysqlite_statement_bind_parameters (parameters=0x7f1f9b82ee40, self=0x7f1fe85bca40) at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_6
4/Modules/_sqlite/statement.c:290
#4  _pysqlite_query_execute (self=0x7f1f9b84cc40, multiple=0, operation=<optimized out>, second_argument=<optimized out>) at /usr/src/debug/python3.10-3.10.0-
1.fc35.x86_64/Modules/_sqlite/cursor.c:539
...
```

that is somehow triggered by [this line](https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/utils/storage.py#L79).

Also, I tried disabling plugin.video.youtube and the crashes stopped.

Thanks for confirming that 3.10.0 should work fine! Maybe I'll try downgrading python to 3.9.

**Comment by asm0dey** [comment]
@graysky2, may I please ask you to keep this open until the upstream bug is fixed? At least it will be easier to search for it.

**Comment by die2gether** [comment]
With python 3.10.2-1 it seems to be working for me.

**Comment by graysky2** [comment]
Agreed, 3.10.2-1 fixes the issue.
