### ISSUE TITLE
Sign in to acount  broken

### ISSUE THREAD

**Issue by sflix** [anxdpanic/plugin.video.youtube#256]
### Context

Please provide any relevant information about your setup

* Add-on Version:  6.8.18 matrix.1
* Kodi Version: 19.3
* Kodi GUI Language: English
* Operating System: Android
* Operating System Language: English

------

### Expected Behavior

Sing in  - Shows "google.com/device" and a code to enter on that site. Once enter the code, you log on to your acount. 

------

### Current Behavior

Google has chande it sing in method, so the page "google.com/device" isn't working anymore for singnin in. 
Where it used to show a box to enter the code and authenticate your davice, now shows a page with your logged in devices.

**Comment by crwolff** [comment]
Working for me. 
https://www.google.com/device  automatically redirects to:
https://accounts.google.com/o/oauth2/device/usercode?flowName=DeviceOAuth
You might try that link instead. Tested with chrome (signed in to google) and firefox (logged out), and both present the device code page.

Edit: https://www.google.com/devices (with an 's' at the end) gives a list of signed in devices.

**Comment by david-morris** [comment]
I had a similar bug, #272 .  Could you check if the solution for that (using an API key for TV/Limited Input Device) fixes your problem?  The timing is different but Google might have done an incremental rollout on the new security.

**Comment by calvin4242** [comment]
**SOLVED:** 
I had the same error " ERROR : [plugin.video.youtube] LoginException: [401] invalid_client: Only clients of type 'TVs and Limited Input devices' can use the OAuth 2.0 flow for TV and Limited-Input Device Applications. Please create and use an appropriate client."

_NO NEED TO ERASE YOUR_ youtube API on Google developper  ^^
You just have to create another "ID client OAuth" for "TV and Limited-Input Device Applications" on https://developers.google.com/

**_HOW TO:_**
1.Go to the https://console.developers.google.com/apis/credentials.
2.Click on top "Create credentials" >OAuth Client ID .
3.Choose application type : TVs and Limited Input devices .
4.Enter a name for this and click on "Create". 
5. Erase the old "OAuth Client ID" for desktop computer on OAuth 2.0 Client IDs credentials' section . 
6. Copy the ID key generated for TVs and Limited Input devices. Paste it on the youtube addon. Note: maybe the secret ID has changed (dont remember).
7. Go to you kodi tube addon, click connect. Copy the validation code that will appear. 
8. Go to https://www.google.com/device and paste this code, choose your youtube account, and authorize, and accept.
9. Another code will appear on youtube addon. Repeat this process once. 
 Youtube addon will automatically connect and display your account on kodi. That's done. Enjoy!

Jerome (FR)

**Comment by david-morris** [comment]
Hmm, @sflix appears to be inactive.  Can anyone else still reproduce this bug or should a maintainer close this as cannot reproduce?

**Comment by DjDiabolik** [comment]
> 



> **SOLVED:** I had the same error " ERROR : [plugin.video.youtube] LoginException: [401] invalid_client: Only clients of type 'TVs and Limited Input devices' can use the OAuth 2.0 flow for TV and Limited-Input Device Applications. Please create and use an appropriate client."
> 
> _NO NEED TO ERASE YOUR_ youtube API on Google developper ^^ You just have to create another "ID client OAuth" for "TV and Limited-Input Device Applications" on https://developers.google.com/
> 
> **_HOW TO:_** 1.Go to the https://console.developers.google.com/apis/credentials. 2.Click on top "Create credentials" >OAuth Client ID . 3.Choose application type : TVs and Limited Input devices . 4.Enter a name for this and click on "Create". 5. Erase the old "OAuth Client ID" for desktop computer on OAuth 2.0 Client IDs credentials' section . 6. Copy the ID key generated for TVs and Limited Input devices. Paste it on the youtube addon. Note: maybe the secret ID has changed (dont remember). 7. Go to you kodi tube addon, click connect. Copy the validation code that will appear. 8. Go to https://www.google.com/device and paste this code, choose your youtube account, and authorize, and accept. 9. Another code will appear on youtube addon. Repeat this process once. Youtube addon will automatically connect and display your account on kodi. That's done. Enjoy!
> 
> Jerome (FR)


Oh My good.......... really strange on my KODI Setup i have ever use my very old ID and Secret created about in 2017.

From today apparently it's not works anymore and when i open youtube addons i see i'm logged out (no "My subscript" section etc etc).

I have to logged in and create a totally new ID OAuth whit "TV and limited entry"...... paste this now keys on setting.xml of youtube addons and relogin my kodi setup.

Now need to test if i can watch all video :)
