### ISSUE TITLE
A way to use YT witout API

### ISSUE THREAD

**Issue by dudumaroja** [anxdpanic/plugin.video.youtube#263]
### What Problem Does This Solve? 

Api is a mess for most users.. even if tutorials its a pain in the ass to creat the api and set up correctly. even more when english is not you main langague and many tutorials do not reflet the google api site in other languages.. 

------

### Suggest a Solution (optional)

there is a opensource app for android that can acess youtube without API and logins.. i dont know how feaseble to use the same methods in this addon when you dont want to mess with API stuff, what trailers.. cast links to kodi and basic subscrition acess ( using google takeout xml ) without using google API and not even need to login. 

https://github.com/TeamNewPipe/NewPipe or https://github.com/polymorphicshade/NewPipe

------

**Comment by M-Reimer** [comment]
Problem with not using the API is that, after doing "unexpected" request patterns for some time, YouTube may display a Captcha to solve. The Apps pass this through to the user for solving. But this may be pretty difficult for Kodi. Kodi has no builtin method of rendering a website and even if something is hacked together, not everyone has a mouse connected to his HTPC to solve the Captcha.
