### ISSUE TITLE
Intermittent audio cutouts during playback

### ISSUE THREAD

**Issue by Azelphur** [anxdpanic/plugin.video.youtube#265]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: 19.3 (19.3.0) Git:41d819a51cafb7228ca10108a64cb1b7e06b43b3 Media Center Kodi
* Kodi GUI Language: English
* Operating System: CoreELEC
* Operating System Language: English

------

### Expected Behavior

The audio should not cut out during playback

------

### Current Behavior

When playing a video from youtube, audio intermittently cuts out during playback. The drop outs have seemingly random positions and lengths which change every time I replay the same video.

I have uploaded a video [here](https://www.youtube.com/watch?v=O9-GzTVRIXc) to demonstrate (see description for cutout times)

it only seems to happen on some videos. [This](https://www.youtube.com/watch?v=-nsGtO2c4pw) is the video I was playing in my demo, which experiences dropouts, however [This video](https://www.youtube.com/watch?v=hmm6O25BOSg) plays fine and does not experience any dropouts.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play a youtube video (I use send to kodi firefox addon)

------

### Log
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/7920055/kodi.log)
Log contains Kodi starting, starting the video, and the video playing all the way through, with multiple dropouts during playback.

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by hjri** [comment]
i have same issue, thought it was a kodi problem but it ONLY happens on youtube plugin, not on twitch plugin nor on local videos
