### ISSUE TITLE
Codec: add opus support

### ISSUE THREAD

**Issue by tiagogaspar8** [anxdpanic/plugin.video.youtube#267]
Hi!

I wanted to ask for support for the opus audio codec instead of the current aac.
It's open source so it's a better alternative to fit with the current VP9 coded.

I've read also that it might have better audio quality (?).

Thanks!

**Comment by anxdpanic** [comment]
This isn't currently possible, as inputstream.adaptive doesn't support opus currently. It will be added to the add-on when possible though.

**Comment by tiagogaspar8** [comment]
Ok, should I keen this open?

On another side not, I'm confused about the differences between YouTube and tubed, is there any literature on it?

Thanks for the quick response!

**Comment by dev77-07** [comment]
As a test, I edited the resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_context.py file and changed 'opus': None in capability_map to 'opus': '2.3.14' and it played with opus audio with no issue

`2022-01-25 16:03:43.030 T:11504   DEBUG <general>: [plugin.video.youtube] Generated MPD highest supported quality found: |{'video': {'height': '2160', 'fps': '30000/1001', 'codec': 'vp9', 'mime': 'video/webm', 'quality_label': '2160p', 'bandwidth': 11800658}, 'audio': {'bitrate': 160, 'codec': 'opus', 'mime': 'audio/webm', 'bandwidth': 133899}}|
`
`
2022-01-25 16:03:43.871 T:11800    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
`

**Comment by anxdpanic** [comment]
I must have missed when this changed, thanks for the heads up. Will look at adding it.

**Comment by bkuhls** [comment]
fixed by https://github.com/anxdpanic/plugin.video.youtube/pull/379
