### ISSUE TITLE
Issue with some HDR videos

### ISSUE THREAD

**Issue by dev77-07** [anxdpanic/plugin.video.youtube#268]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: 20.0-ALPHA1 (19.90.101) Git:20220115-c69943bdcf (also tested with 19.3 and have same issue)
* Kodi GUI Language: English
* Operating System: Windows 11
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Play video with HDR

------

### Current Behavior

What is the current behavior?

Video doesn't play, after a bit the audio will start and the GUI glitches but no video

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play https://www.youtube.com/watch?v=oPDC9ZxowVo with HDR
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/vejudekowu.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

If I disable HDR in the addon settings, video plays fine. I've tried 4k HDR, 1440p HDR, 1080p HDR and they all fail.

https://i.imgur.com/j8RIbs5.jpg is what the GUI looks like, multiple mouse pointers, duplicate playbar, time is wrong (1 hour 53 minutes on a 59 second video)

------

I have played other HDR videos through youtube and never had a problem, but all the videos on this channel https://www.youtube.com/channel/UCoe7QOGeGGrWTvU2ADlkvrg have the same problem.

**Comment by david-morris** [comment]
I have an issue where if I enable HDR and play a video, my screen goes black or freezes but I can hear the sound of the video.  I assumed it was a problem with my HDR view.

Are there any ways you can successfully play HDR through kodi?  Apart from anything else, I'd like to get HDR working and I don't have any HDR videos.

I had this issue on the following video, do you also have issues with this video? https://www.youtube.com/watch?v=njX2bu-_Vw4

**Comment by dev77-07** [comment]
The video you linked works fine for me.

**Comment by tiagogaspar8** [comment]
I'm having the same issue!

I have done some investigation and it seems that video loading is ratelimited at 60mbps while SDR isn't capped, reaching 400+Mbps

Could this be related to the issue we had a while back where the videos were buffering?

**Comment by tiagogaspar8** [comment]
Some non HDR videos are in the "block" too. Here's an example:
https://www.youtube.com/watch?v=x543uWA3mTk

Also, this only seems to be true when videos are in 4k, other smaller resolutions aren't affected.
