### ISSUE TITLE
LoginException when signing in

### ISSUE THREAD

**Issue by david-morris** [anxdpanic/plugin.video.youtube#272]
### Context
2022-02-04 21:05:10.480 T:9942    ERROR <general>: [plugin.video.youtube] LoginException: [401] invalid_client: Only clients of type &#39;TVs and Limited Input devices&#39; can use the OAuth 2.0 flow for TV and Limited-Input Device Applications. Please create and use an appropriate client.
Please provide any relevant information about your setup

* Add-on Version: git from yesterday
* Kodi Version: 19.3-2
* Kodi GUI Language: English
* Operating System: Arch (kodi-x11 standalone)
* Operating System Language:  English

I remember hearing that recently some tools which query youtube videos will pretend to be androids.

------

### Expected Behavior

Sign in button should quickly open the google.com/device prompt and filling out the webform should promptly advance the auth.

------

### Current Behavior

What is the current behavior?

Doesn't sign in successfully.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Initiate sign in dialog
2. Sometimes, it will happen.

------

### Log
Unfortunately, not debug.  Intermittent bug.  Will keep trying to get a full log with this error.
https://termbin.com/01xa
------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by dagfinnr1** [comment]
Phew! Thought I was the only one with this issue for the last couple weeks. Installed 19.0 a couple months ago login worked fine then. Clean install 19.3 and  this time no bueno.

**Comment by dagfinnr1** [comment]
Also seems to login as "youtube on tv" on google device login page where as I think it used to login as kodi? I could be wrong tho.

**Comment by anxdpanic** [comment]
https://forum.kodi.tv/showthread.php?tid=356934&pid=3078580#pid3078580

**Comment by pro2type1** [comment]
> https://forum.kodi.tv/showthread.php?tid=356934&pid=3078580#pid3078580

I have tried this a few times and it didn't worked. I created 3 new OAuth 2.0 Client ID and i still can't sign in.

Any other sugestions?

**Comment by dagfinnr1** [comment]
> > https://forum.kodi.tv/showthread.php?tid=356934&pid=3078580#pid3078580
> 
> I have tried this a few times and it didn't worked. I created 3 new OAuth 2.0 Client ID and i still can't sign in.
> 
> Any other sugestions?


I just did it following these instructions with one caveat. At #11 of the api section do not select "desktop app". Select "Tv limited input device" instead.

https://www.kodivpn.co/how-to-install-youtube-kodi-addon/

**Comment by pro2type1** [comment]
I have that selected. Print screen added: 

I can watch youtube but i cant sign in.

![0Zajeta slika](https://user-images.githubusercontent.com/99179289/153143271-ff3261fa-7ec9-4914-a455-4be65ad7abd4.JPG)

**Comment by dagfinnr1** [comment]
Sorry, I can't be of more help. I followed those instructions and it worked for me. All I can say is make sure to go and double check that the secret, key and ID are fully entered in correctly in the api section of the addon even if you copied and pasted them using Kore or some other remote app. I believe I have also read somewhere that if you go to the youtube add-on configuration and delete the various caches in there that, that might help. Alternatively maybe try uninstalling and reinstalling the add-on for a fresh start and then try adding the api stuff and then try logging in again. Hope you get it figured.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by pro2type1** [comment]
Thank you for your answer. I will uninstall youtube app again today and i will make new api keys and try that if it helps.
I hope it will.

I will report back when i try.

**Comment by david-morris** [comment]
I can confirm, this is an issue caused by Youtube changing policies.  An API key for TV/limited input device is now required, if yours is for desktop, you need to make a new one.

As a heads up, the double login runs quickly and smoothly once you've got the API key set up correctly.  So you don't need to dread getting this done.
