### ISSUE TITLE
Sharing Link from Yatse not working with MPEG Dash enabled

### ISSUE THREAD

**Issue by RyuuTDF** [anxdpanic/plugin.video.youtube#274]
### Context

Please provide any relevant information about your setup

See: https://community.yatse.tv/t/yatse-add-on-and-youtube-lins/3867

Issue was also reproduced on:
* Add-on Version: 6.8.18+matrix.1
* Kodi Version: 19.3
* Kodi GUI Language: English
* Operating System: OSMC 2021.12-1 (Vero 4k+)
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Selecting 'Play on Media Player' through Yatse sending a Youtube video to the player and the player proceeds to play it.

------

### Current Behavior

What is the current behavior?
Link gets resolved, but video does not get started by Kodi. Either does nothing or states it is unplayable.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Send any video from the Youtube app to a Kodi instance using Yatse's 'Play On Media Player'

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
See https://community.yatse.tv/t/yatse-add-on-and-youtube-lins/3867

------

### Additional Information

Please provide any additional information that may be helpful.

Turning MPEG-Dash off in the settings does make the links resolve again and the video gets played.
However turning it off limits resolution.

------

**Comment by Tolriq** [comment]
To avoid future discussion, in this case Yatse is not really involved it just call the Youtube plugin

b'Playing url: plugin://plugin.video.youtube/uri2addon/?uri=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsoNiEk_fMCE'

**Comment by Doktor-X** [comment]
I for now use kore until this problem is resolved, i like yatse better

**Comment by Tolriq** [comment]
You can have the same result as Kore by just disabling the Yatse plugin ;)

**Comment by Doktor-X** [comment]
Just try it it works, thanks Tolriq, what helper script plugin do if kodi can play without it?

**Comment by Tolriq** [comment]
This is not a discussion for here, but many things for better metadata/ playlist and tons of other sites. For this case it call the plugin with the direct video id and not the uri2addon so it's the uri2addon part of the youtube plugin that is broken and needs to be fixed.

**Comment by anxdpanic** [comment]
Will take a look when I get a chance next 👍

**Comment by anxdpanic** [comment]
Should be resolved in the next release, w/ dc9163046b25f34a2a1cbd0dc69053adf75c7fca

**Comment by Doktor-X** [comment]
Again sharing link using yatse is not working. I have try latest master version of kodi addon

**Comment by Michelle1493** [comment]
Seems to be relevant again in 2025, had to disable the Yatse Helper Script for sharing Youtube links again

**Comment by Doktor-X** [comment]
> Seems to be relevant again in 2025, had to disable the Yatse Helper Script for sharing Youtube links again

I, for example after initial problem in 2022, never used yatse helper plugin
