### ISSUE TITLE
Videos that are shared from Smartphone as kodi playlist play normal but do not play after about 12 hours or so.

### ISSUE THREAD

**Issue by T0mS4wy3r** [anxdpanic/plugin.video.youtube#279]

**Comment by neo-neo1** [comment]
You couldn’t be bothered to edit your post to fix mistake or is it intentional?

**Comment by T0mS4wy3r** [comment]
> You couldn’t be bothered to edit your post to fix mistake or is it intentional?

No it wasn't intentional. It was my first issues try. I'm no able to edit the description. I just have a smartphone. I just could edit the title and close the bug
