### ISSUE TITLE
This video may be inappropirate for some users.

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#294]
Example:
https://youtu.be/BEY39Ekth30

**Comment by PrBart** [comment]
Experiencing the same issue.

Example: https://youtu.be/NOuIXUmFc3g

**Comment by ayarovy** [comment]
The same:
https://youtu.be/yuOOhy6M81c

**Comment by daufinsyd** [comment]
It's likely related to this issue #278
