### ISSUE TITLE
YouTube videos have no sound, stop playing after a few seconds

### ISSUE THREAD

**Issue by kcowolf** [anxdpanic/plugin.video.youtube#300]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: Kodi (19.4 (19.4.0) Git:19.4-Matrix). Platform: Linux ARM 32-bit
* Kodi GUI Language: English
* Operating System: LibreELEC (official): 10.0.2, kernel: Linux ARM 64-bit version 5.10.95, running on Raspberry Pi 400
* Operating System Language: English

------

### Expected Behavior

YouTube video opens, plays with sound.

------

### Current Behavior

After upgrading to LibreELEC from 10.0.1 to 10.0.2, I noticed that when I tried to play videos they would often start playing with no sound.  After a few seconds, the video would slow down and stop.  This behavior consistently happens after I leave the Pi idle for a couple of hours; rebooting it solves the issue temporarily.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run LibreELEC 10.0.2 on Raspberry Pi 400.
2. Leave the Pi idle for a few hours.
3. Attempt to open any YouTube video.  I use the Kore Android app and open the video from the YouTube app using the "Queue on Kodi" option in the Share menu.
4. Observe that the video has no sound and stops playing after a few seconds.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/esageciwuw.kodi

Video exhibiting the problem is: https://www.youtube.com/watch?v=_5vad_uwWdA
Previously attempted video, failed to load: https://www.youtube.com/watch?v=19h5Z7DJUbc

------

### Additional Information

Please provide any additional information that may be helpful.

The problem started after I upgraded LibreELEC from 10.0.1 to 10.0.2.  I also have an RPi 4 running LibreELEC which I haven't upgraded from 10.0.1, and this issue does not occur on it.

------

**Comment by gctypo** [comment]
I can confirm the occurrence of this on OSMC 2022.03-1.

Paste: http://paste.osmc.tv/koravotufe
Video: https://www.youtube.com/watch?v=c66mDHckyoM
