### ISSUE TITLE
We Can't Choose (auto generated) Subtitles!

### ISSUE THREAD

**Issue by 03stevensmi** [anxdpanic/plugin.video.youtube#305]
### Context

Tested on All setups (android both latest matrix & last version of lea, Linux both omsc 18.4+19 & librelec 18.4+19)

* Add-on Version: Latest + master
* Kodi Version: 18 last version + 19 latest fersion
* Kodi GUI Language: English
* Operating System: Tried on Android, Linux (raspberry pi 2b+ & 4 4gb) omsc last 18 + latest 19 & librelec both last & latest 18 + 19
* Operating System Language: English

------

### Expected Behavior

we should be able to choose auto generated subtitle languages like we use to back before version 6.8.18 alpha2!

------

### Current Behavior

Ever since version 6.8.18 alpha 3, none of us can select or translate auto generated subtitles.
The video's "original" launguse is working but we can not choose languages like we used to!
Its been reported many times but has been completely ignored.
I saw a new comment that looked like it had fixed this issue but whatever fixed... The main problem
Still exists with absolutely no way what so ever of translating subtitles from say 
(German, Portuguese, French etc) to english! 

Could you please take a look into this.
It would be very much appreciated.
Cheers.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Find a non-english video
2. Choose play with subtitles (with the option to choose)
3. Only the original (auto generated) language is available and NOT any others like there used to be (e.g. Portuguese to English etc.)

(NOTE: SETTING IT TO AUTO DOWNLOAD / LOAD TO ENGLISH "eng auto generated fallback eng" IN THE SETTINGS DOES NOTHING! 
DOENT LOAD ANY SUBTITLES WHAT SO EVER AND REFUSES TO EVEN AUTO DOWNLOAD)

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

This was working (and still does) in version 6.8.18 APLHA 2

------

**Comment by tr1p0p** [comment]
Yeah have this problem too. Kind of amazed how little it's done on kodi addon project and all when it's... the only media center available at here.

No easy sign-in, subtitles not working, not features like sponsorblock and all. It's a really basic plugin that don't update often and don't work with google API when Andorid have like a TONS of youtube client and all, so, weird to me.

Also, dead ? No response ?

**Comment by 03stevensmi** [comment]
> 

Yeah, Hasn't Updated (OR SPOKE) since may. I think This Is officially DEAD! 
It still works for me, but ofc, broken subtitles and no "recommended VIDEOS" page like you get on the yt android app makes this addon only inches away from being perfect. No adds etc makes this #1 for an alternitive for most, but you find me a media centre like this for somthing like a raspberry pi with yt support and you will only find kodi. so its sad that its getting neglected. i don't mind at all devs going quet, i get it! life happends... i'm cool with things getting abbandoned. BUT... what pisses me off is when somthing is as big, and popular like this and all it takes is a simple, quick "ON HIHATUS, DONT KNOW WHEN ILL BE BACK", "NO LONGER WORKING ON THIS", "ETC", "ETC", and when people are wating long periodes for a reply or help... NOTHING??? there is no excuse! Just say its gone, i'm gong for x amoumt of time, or somthing instead of leaving eeryone in the blank! no one is going to take on this project if no one OFFICIALLY states the project is no longer being developed!

**Comment by anxdpanic** [comment]
I have actually stated, that I wasn't able to work on any of my projects for a while. And was trying to get another issue working, failed at doing so and took a lot of that time.

Recommended, for the millionth time in issues/forum posts isn't by choice, and by API limitation. I am looking at migrating this completely so it's more like the other apps, (A LOT of work). That work may end up in Tubed, and this add-on replaced completely by Tubed. But I don't know what will happen or I would be very forward with that. I will look into this issue but it also ties into that other issue which wasted a lot of time already.

Work WILL be done to improve the add-on experience, I can't promise what or when though.

I'm sorry my lack of volunteer time on this project upsets you, but there is nothing more than I can offer is that apology.
Cheers.

**Comment by 03stevensmi** [comment]
> 

Thank you for letting us know! Means a lot. :)
Just curious, where did you mention that you weren't able to work on this project for while?
