### ISSUE TITLE
403:Access denied error on last step of personal API walkthrough

### ISSUE THREAD

**Issue by ferfey** [anxdpanic/plugin.video.youtube#312]
I followed the walk through and on the second device ID screen I received the following error
![ECB86475-7E37-47AC-837D-05670CB7AEBC](https://user-images.githubusercontent.com/24929840/172069135-28cfdd0a-f75b-4f13-b7bb-c7a1f255206a.jpeg)

I tried to use the “less secure apps” option but that feature has been disabled by google.
Is there some other setting in Oauth or credentials that needs to be tweaked to give my Kodi add on access?

**Comment by ferfey** [comment]
Not sure why the link didn’t work. Here’s an attacged version of the error I received
![B3091B6D-F366-489D-B35A-6071F21AE2E8](https://user-images.githubusercontent.com/24929840/172069115-3ee7b769-8d6c-48c0-ad7f-a7faf6f1fdc8.jpeg)

**Comment by Duke999R** [comment]
G'day, 

I was getting this error on the second code as well. I went back into the oauth consent section and clicked "publish". https://i.imgur.com/KBudxAO.png Then the second code worked and I signed in... should work for you.
![Screenshot_94](https://user-images.githubusercontent.com/65851971/172390662-ba4c2e93-6b19-4353-a485-4cc7fd6ab8f6.png)
.

**Comment by Niquarl** [comment]
Thank you, the fix worked for me too. Perhaps one should consider updating it on the wiki.

**Comment by volkanpaksoy** [comment]
This worked for me too. 

Is there a security risk involved? Google warns that "Your app will be available to any user with a Google Account". Does it pose a risk without them having the API key and OAuth credentials?

**Comment by Duke999R** [comment]
That's only because "the app" (kodi youtube plugin) has not been reviewed by Google. They are warning you about connecting to the app. It's fine because you are controlling the access the "app" has to your own machine.

**Comment by Duke999R** [comment]
I'm pretty sure that it only causes an issue if someone else gets access to the keys and such. Keep them safe and you should be fine. I've had no issues so far.

**Comment by SpeckiJ** [comment]
As an alternative to publishing you can add your Account as a `Test User`, thereby allowing access. By default nobody (not even the account owning the project) has access.

![oauth](https://user-images.githubusercontent.com/13851077/198346405-9c4328a9-7b35-450e-87cd-eb5a09eeefa9.png)

**Comment by KnightOfCups** [comment]
For what it worth, I'd like to emphasise that before facing the issue I had to complete the sign-in process under the private mode of the browser. For unknown reason, it failed in normal mode with this cryptic message "_Sorry, something went wrong there. Try again._"
