### ISSUE TITLE
Handling Multiple Live From  Same Channel

### ISSUE THREAD

**Issue by Sphinxroot** [anxdpanic/plugin.video.youtube#314]
### Context

Please provide any relevant information about your setup

* Add-on Version:  6.8.18
* Kodi Version: leia 18.9 or Matrix 19.4
* Kodi GUI Language: ENG
* Operating System: Win 10 
* Operating System Language: ENG

------

### Expected Behavior

Using in  Playlist m3u

plugin://plugin.video.youtube/play/?channel_id=IDHERE&live=1

if a channel have more than 10 to 12 lives  adding more  live=xxx wont play 

they are channel up to 30+ lives 

is there any way  possible to handle this pass 10 to 12 lives per channel ?

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> they are channel up to 30+ lives

Can you provide an example of a channel with a large number of live streams, where you see this problem? Do you have a log showing the actual problem?
