### ISSUE TITLE
"video may be inappropriate for some users" 

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#316]
The following video does not play for me:

https://www.youtube.com/watch?v=UBS4Gi1y_nc

(Neither via the URL from Yatse, nor by searching in the addon. The search term should be obvious from following the URL, I'm not repeating it here in case there are political correctness filters in place.)

Instead of playing the video, a brief toast "This video may be inappropriate for some users" is displayed.

I am correctly logged into my account.

Toggling the Age Gate option makes no difference.

I remember that a little while back I had to jump through some hoops to get my YT account age verified, and whatever was the issue back then got resolved by this.

The above video plays back correctly for me both in the official YouTube app and Chrome mobile (both logged into the very same account as the Kodi addon).

**Comment by jmbreuer** [comment]
... Apparently related to #278

(weird, didn't see that issue when searching for duplicates before my report 🙄)

Since I have a "known broken for me" candidate currently, I'll have a look what I can figure out.

**Comment by FunctionalHacker** [comment]
This issue tracker is filled with duplicates, can you please close this one, let's use #278 for tracking this.

Just trying to help out the author a bit
