### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by zsoltszasz** [anxdpanic/plugin.video.youtube#319]
### Context

Please provide any relevant information about your setup

* Add-on Version: Repo: 2.0.2; Youtube: 6.8.19~ALPHA1
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: Librlelec (Official) 9.2.8 
* Operating System Language: English

------

### Expected Behavior

I expect to be able to watch youtube content.

------

### Current Behavior

It looks like it's not possible to watch certain videos anymore. I get an error: The following contents is not available on this app. Watch this content on the latest version of Youtube.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. https://www.youtube.com/watch?v=RbOtJ4fzdu8
2. https://youtu.be/3-pr1aZcziM
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by cpu123** [comment]
I'm getting the same error, started about a week ago.

I reinstalled and generated new API keys yesterday and it seemed to fix it, but today I'm getting the error again.

**Comment by deosrc** [comment]
I encountered this with a live stream but restarting the stream seems to have resolved it.

**Comment by Doktor-X** [comment]
I can play your videos but i still cant play age gate videos and its problem
