### ISSUE TITLE
"START FROM BEGINNING" on CONTEXT MENU for livestream........

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#320]
### What Problem Does This Solve? 

I thinks it's usefull........ sometime also where it's a livestream and you want to start to watch this livestream from beginning.

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

I thinks it's a very easy to add....... i thinks it's only need to open the same video but whit s=0 how 0 it's seconds you want to start...

------

@anxdpanic you thinks is feasible?

**Comment by MoojMidge** [comment]
Added in #864
