### ISSUE TITLE
unauthorized_client error with any video

### ISSUE THREAD

**Issue by doomdogus** [anxdpanic/plugin.video.youtube#327]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: Kodi-19.1
* Kodi GUI Language:
* Operating System: OSMC
* Operating System Language:

------

### Expected Behavior

Play without error.

------

### Current Behavior

All videos play. 
But all videos generate the error unauthorized_client.
This is with both old(ish) and new API keys, including new "TV and limited input" OATH credentials.
Attached is the complete log captured from starting a video to end.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

[kodi-yt.txt](https://github.com/anxdpanic/plugin.video.youtube/files/9583128/kodi-yt.txt)

**Comment by anxdpanic** [comment]
theres an issue with your keys
