### ISSUE TITLE
All videos show "The following content is not available on this ap.."

### ISSUE THREAD

**Issue by Kellett** [anxdpanic/plugin.video.youtube#333]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.20
* Kodi Version: 19.4 (flatpak)
* Kodi GUI Language: EN
* Operating System: Flatpak on Manjaro Linux 5.15 
* Operating System Language: EN

------

### Expected Behavior

Please describe the behavior you are expecting.

Video should play

------

### Current Behavior

What is the current behavior?

Video "plays" but only shows the black screen and error text

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try play video
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/iyefucatoq.kodi

------

### Additional Information

Please provide any additional information that may be helpful.
![image](https://user-images.githubusercontent.com/1553850/194699626-f3d049f5-2046-4984-abf4-44e08a1103e8.png)

------

**Comment by CategoryQ** [comment]
I had an identical issue several months ago, which I managed to get around by signing it, and signing back in using a different identity in the same account.

Whilst it let me watch videos again, I lost all my playlists and subscriptions in the move... Exact same issue happened to me on YouTube Vanced for Android at the same time, which makes me think it is happening on the Google side of things.

Just checked, and my second account identity is doing the same as yours, but I haven't tried my workaround again yet

**Comment by tomjshore** [comment]
I had this issue as well.  I signed out for a couple of days.  And have just signed in again and it's now working fine.

**Comment by CategoryQ** [comment]
It happens to me on and off - I stay signed in all the time, and for a few days I'll get the black "content not accessible" warning, then for a few days it will work fine, it's really 50/50.

**Comment by doomdogus** [comment]
It's more "off" than "on". It worked for 2 days and now it's been off again for a week.
Makes kodi useless except for local storage/NAS.
It would be interesting if someone with Youtube Premium could chime in and tell us if it works for them.
I've now migrated to a TV stick with official Youtube app. I have ads but at least it works fine.

**Comment by mike-gh** [comment]
I have this issue with 6.8.23 and 6.8.24 on LibreElec 9.2.6.  It's intermittent tough.  The video fails with "The following content is not available on this app." maybe 10% of the time.  I have a debug log of it which I can provide.

**Comment by Zlopez** [comment]
I'm now having the same issue. It worked for me without signing for some time, but now I'm getting this error for each video I want to watch. I will try to sign in and see if that helps.

**Comment by Zlopez** [comment]
Updating to latest version from testing repository solved the issue for me.

**Comment by MoojMidge** [comment]
FYI the testing repository may not yet have the latest release available. The previous development releases are missing a few of the later fixes.

The latest release can be found at https://github.com/anxdpanic/plugin.video.youtube/releases/latest

It will also eventually be updated in the official Kodi addon repository.
