### ISSUE TITLE
Plugin hangs on Fedora 32 [ solved on Fedora 33 alpha 3 ]

### ISSUE THREAD

**Issue by enigma131** [anxdpanic/plugin.video.youtube#34]
### Context

Please provide any relevant information about your setup

* Add-on Version:6.8.5
* Kodi Version: 18.8
* Kodi GUI Language: French
* Operating System: Fedora32
* Operating System Language: French

------
### Expected Behavior
Load Plugin via interface
------
### Current Behavior
Got error message, see log below
------

### Steps to Reproduce

Activate Youtube account ( is activated and works on Windows and Linux Mint )
Install Fedora32 on fresh Disk partition and update it
Install Kodi 18.8 from Fedora RPM fusion
Try to install the plugin on Kodi via GUI by normal way
------
### Log
https://paste.kodi.tv/aboxakayog.kodi
------

### Additional Information
Kodi is working for Video playing and works with pvr.hts plugin.
------

**Comment by anxdpanic** [comment]
This is an issue upstream with either Fedora or the Python installation, it's failing in the `io` module which is a standard library included with Python. Kodi uses system python when used on linux, hopefully that gives you somewhere to start.

**Comment by enigma131** [comment]
Upgraded to Fedora 33 . After update of Kodi 19 alpha3 this morning, plugin is working ! (it wasn't for Alpha2). Solved
