### ISSUE TITLE
Viewtype option is not persisted between pages

### ISSUE THREAD

**Issue by lockie** [anxdpanic/plugin.video.youtube#350]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.20
* Kodi Version: 19.4
* Kodi GUI Language: English
* Operating System: Raspberry Pi OS 64-bit (bullseye based)
* Operating System Language: English

------

### Expected Behavior

After I set a viewtype on a folder (say, "My subscriptions"), it is persisted when I flip pages in that folder.

------

### Current Behavior

When I set e.g. InfoWall viewtype on "My subscriptions" and click on "Next Page (2)", the second page is displayed, but its viewtype is default WideList again, which I don't like much.
Am I supposed to manually set viewtype on each of 432 pages of my WatchLater playlist?..

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to "My subscriptions".
2. Click Options on the left, then set Viewtype to InfoWall.
3. Click "Next Page (2)" on a list.
4. Observe the problem: videos from page 2 are displayed with default WideList viewtype.

------

### Log

https://paste.kodi.tv/wedejajuvu

------

### Additional Information

None. Just wanted to thank developers of this amazing addon for their tireless work :)

-----

**Comment by DjDiabolik** [comment]
Yes i confirm also on 6.8.21..... but if i remember this little trouble it's present from a lot of time.

**Comment by lockie** [comment]
After some time using Kodi it looks to me that this might be not plugin's fault, but rather bug in Kodi. Just a guess though :)

**Comment by DjDiabolik** [comment]
> After some time using Kodi it looks to me that this might be not plugin's fault, but rather bug in Kodi. Just a guess though :)

I thought it could be a problem with the skin used....... currently i use the "Estuary MOD V2 KodiNerds Edition" and this skin has a setting to made a force view by default but apparently it's not works for all addons. lol.

**Comment by anxdpanic** [comment]
this is a kodi side thing, use the unofficial version for forced viewtypes (not allowed in official repository)

**Comment by DjDiabolik** [comment]
@anxdpanic i already use the unofficial version...... and this "bug" it's infact also present.
