### ISSUE TITLE
Does it display ads? Can I connect my phone?

### ISSUE THREAD

**Issue by agluszak** [anxdpanic/plugin.video.youtube#352]
I'm thinking about getting a Raspberry PI and setting up Kodi on it to replace my LG Smart TV functionality. I use it mostly to watch YouTube. It's nice that anyone at home can connect their the YouTube app on their phone and enqueue videos. However ads recently have gotten so bad that I'm looking for alternatives.

Is it possible to connect a phone to Kodi with this plugin?

What's the situation with ads?

**Comment by rjousse18** [comment]
Nope, no ads on this app

Yep you can "connect" your phone but you need Yatse app.

Yatse is a controller for kodi and allows you to share a video from youtube to kodi.

How ?
Go to youtube app (or website) -> start video -> share -> play on media center (or queue on media center)

**Comment by FunctionalHacker** [comment]
This is probably not a bug and OP got the answer they were asking. Please close

**Comment by MoojMidge** [comment]
> Yep you can "connect" your phone but you need Yatse app.

Can also use Kore, optionally with NewPipe
