### ISSUE TITLE
Message "No stream found" even latest version of plugin

### ISSUE THREAD

**Issue by enigma131** [anxdpanic/plugin.video.youtube#353]
### Context

Please provide any relevant information about your setup
* Add-on Version: 6.8.20
* Kodi Version: 19.4
* Kodi GUI Language: EN or FR
* Operating System: Linux Mint 20.3
* Operating System Language: FR

Age gate is turned off . (setting "on" result in a different message "This video is not appropriate...(in French language)
Direct link https://www.youtube.com/watch?v=XhFzKhTFY3I    is working fine in firefox on same OS/Machine.

------

### Expected Behavior

Video clip shoud be viewable
------
### Current Behavior: Get error messages and no video played.

What is the current behavior?
Not playable in Kodi, sould use Firefox instead.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use search function of plugin, search about "indochine"
2. Click on clip "La vie est belle"  (on second page other clips don't work, same error messages)

------

### Log

https://paste.kodi.tv/ebukameyer.kodi

------

### Additional Information

none
------

**Comment by DanMabee** [comment]
another example: https://www.youtube.com/watch?v=fbd3l64lECw
tried on 6.8.24 with no joy

**Comment by DanMabee** [comment]
these URLs give a different message when logged in: "this video is age-restricted and only available on youtube. learn more"
