### ISSUE TITLE
6.8.21 - Element/video for page Value - Is value it's not anymore available from addon settings...

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#366]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.21 Unofficial
* Kodi Version: 19.4 current OSMC build 
* Kodi GUI Language: Italian
* Operating System: Debian Buster
* Operating System Language: English but i'm not sure

------

### Expected Behavior and Step to Reproduce
Previously on addon settings there's a value......... for every page it's selected 50 Video for page.

Whit this updated released 6.8.21 problably there's an errors....... in this value it's not present anymore a value... it's present a OPTION to raise and low value but it's appears value like "Monday" "Thurday" "Friday" Saturday ecc. ecc. How it's possible ?

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
Currently i don't thinks it's need a log....... it's not a "real" bug.......

------

@anxdpanic thanks in advance for fixing this little issue.

**Comment by Doktor-X** [comment]
Yes i also have problem with videos i have like 1-6 videos per page

**Comment by DjDiabolik** [comment]
Temporary FIX:
https://forum.kodi.tv/showthread.php?tid=356934&pid=3120616#pid3120616

**Comment by anxdpanic** [comment]
fixed

**Comment by DjDiabolik** [comment]
Yeah fixed in 6.8.22 :) Thanks
