### ISSUE TITLE
v6.8.21 disabled Watched status reporting (possibly accidentally)

### ISSUE THREAD

**Issue by rel0aded** [anxdpanic/plugin.video.youtube#376]
### Context

* Add-on Version: v6.8.21 to v6.8.23 (current)
* Kodi Version: Matrix
* Kodi GUI Language: English
* Operating System: LibreElec
* Operating System Language: English

------

### Issue

Up to (and including) v6.8.20, watched status was reported back to YouTube and videos were visible in https://www.youtube.com/feed/history after playback was started.

The [commit that bumped the version to v6.8.21](https://github.com/anxdpanic/plugin.video.youtube/commit/6a470e5675259d22a0d44dc199af2002d2509ac4) commented out this reporting call in `update_watch_history` and replaced it with a `pass` statement, but this was not mentioned in the commit, or the changelog for any of the newer versions.

It's not clear whether this was a deliberate change (which I feel would have been more prominent if it was?), or a regression.

Changing those two lines in v6.8.23 back to how they were in v6.8.20 resolves the issue, so it doesn't appear to be a case of deprecating legacy functionality either.

**Comment by anxdpanic** [comment]
will be resolved in next version, sorry about that

**Comment by anxdpanic** [comment]
readded in latest alpha
