### ISSUE TITLE
Allow playback of content with "other-than-age-gate" restrictions

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#377]
### What Problem Does This Solve? 

YouTube appears to have added "are you sure you want to watch this" content-warning type categories, beyond "may be unsuitable for younger audiences" (or however they label the age gate feature).

Currently, such videos cannot be played on this Kodi addon.

One example of such a video: https://youtu.be/krfcq5pF8u8

Currently, YouTube's question for consent to continue playback is shown in a "cannot play item" toast.

------

### Suggest a Solution (optional)

A simple solution might be to indiscriminately click through any and all "I understand and wish to proceed" type prompts.

A slightly more sophisticated solution would put this in a setting preference.

Showing a "Continue / Skip" dialog - displaying the reason message - at the beginning of playback would best reflect YouTube's original web player's way.

------

**Comment by jmbreuer** [comment]
... adding `'CONTENT_CHECK_REQUIRED'` to the comparison list on line 757 of `youtube/helper/video_info.py` - next to `'AGE_CHECK_REQUIRED'` - achieves quick&dirty playability of the above-mentioned example stream.

**Comment by anxdpanic** [comment]
Will look into that adjustment, been stuck on it for a while. it'd be great if it's been under my nose this whole time 😄

**Comment by anxdpanic** [comment]
added to latest alpha

**Comment by jmbreuer** [comment]
(better late than never: can confirm that this works for me now.)
