### ISSUE TITLE
Needs new and updated instructions: please and thank you

### ISSUE THREAD

**Issue by YesTrustMe** [anxdpanic/plugin.video.youtube#381]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* Kodi Version:
* Kodi GUI Language:
* Operating System:
* Operating System Language:

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by YesTrustMe** [comment]
I can't get Youtube Kodi add-on to work.

**Comment by slax57** [comment]
@YesTrustMe FYI I added a little guide in this issue: https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1509319017

Hope this helps!
