### ISSUE TITLE
 Icons not red anymore 

### ISSUE THREAD

**Issue by f2hamza** [anxdpanic/plugin.video.youtube#382]
when iwatch any youtube video in kodi then go to actual YouTube site it doesn't show that I watched that video and this makes me like idont watch any video anymore while idid actually watched all of them ithink when the icons are red it works but now they are Grey for me
any help

**Comment by bshener** [comment]
i have same issue

**Comment by bshener** [comment]
its fixed 6.8.24-alpha version.

**Comment by anxdpanic** [comment]
im in the process of submitting the new version. completely forgot with the holidays! 

Should be resolved with the next update! Hope you both had a good holiday season.

**Comment by bshener** [comment]
> im in the process of submitting the new version. completely forgot with the holidays!
> 
> Should be resolved with the next update! Hope you both had a good holiday season.

i installed and tested it. its working in alpha version right now thx :)

**Comment by f2hamza** [comment]
> > im in the process of submitting the new version. completely forgot with the holidays!
> > Should be resolved with the next update! Hope you both had a good holiday season.
> 
> i installed and tested it. its working in alpha version right now thx :)

It was working earlier but now it's not working anymore is it same for you?

**Comment by f2hamza** [comment]
> im in the process of submitting the new version. completely forgot with the holidays!
> 
> Should be resolved with the next update! Hope you both had a good holiday season.

just letting you it was working earlier tonight but now it's not anymore unfortunately
