### ISSUE TITLE
Codec: add AV1 support

### ISSUE THREAD

**Issue by tiagogaspar8** [anxdpanic/plugin.video.youtube#391]
Hi!

I wanted to ask for support for the AV1 video codec.
It's already supported by inputstream adaptive so why not add support for it in youtybe? It also helps reduce bandwidth usage.

I tried changing the file resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_context.py and enable av1 but it didn't work, and I'm out of depth.

Thanks!

**Comment by MoojMidge** [comment]
Fully supported since #475
