### ISSUE TITLE
No "Watch later" playlist even if enabled in the settings

### ISSUE THREAD

**Issue by GTP95** [anxdpanic/plugin.video.youtube#397]
### Context

* Add-on Version: Latest
* Kodi Version: 19.5
* Kodi GUI Language: English
* Operating System: LibreELEC
* Operating System Language: English

------

### Expected Behavior

After completing the log-in procedure, the addon's main menu should list a "Watch later" folder to access the "Watch later" playlist, if it is enabled in the settings.

------

### Current Behavior

After completing the log-in procedure, there is no "Watch later" folder in the addon's main menu, even if it is enabled in the settings.

------

### Steps to Reproduce

1. Do the login procedure as described [here](https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys).
2. Double-check in the settings that the "Watch later" folder is enabled.
3. There is no "Watch later" folder in the addon's main menu.

------

### Log
Here is the  [debug log](http://ix.io/4n0a).

------

### Additional Information
The "Saved Playlists" folder is empty, even if I did save some playlists on YouTube. Maybe this is a permissions issue?

------

**Comment by jonisb** [comment]
Hopefully this still works: [Solution](https://github.com/anxdpanic/plugin.video.youtube/issues/69#issuecomment-766843932)

**Comment by GTP95** [comment]
It worked, thank you!
