### ISSUE TITLE
Unofficial Addons REPO for Nexus........

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#398]
### What Problem Does This Solve? 

@anxdpanic apparently on current official KODI Nexus repo this addons it's be promoted as works at latest version 6.8.24.

But there's, at today, not available a repo or source for unofficial release because the repo it's not avaialable on your personal repo.

You can add that ? Thanks in advance.

**Comment by anxdpanic** [comment]
https://download.osmc.tv/dev/anxdpanic/repositories/

Wait for 2.0.4 to appear here, (mirrors take a while to propagate.) It should be nexus compatible

**Comment by DjDiabolik** [comment]
Ok.... it's some usefull for some of users :) I have a Kodi 20 setup on NUC at my brothers home but current at my daily usage i have also use OSMC on current Kodi 19.5 current build :)

So i have about 30 seconds ago install the newest 6.8.25 alpha 2 and it's not working on Matrix....... i will try to open a new issue whit info.
