### ISSUE TITLE
Updating to 6.8.25~alpha1 on kodi 18 fails due to wrong python dependency

### ISSUE THREAD

**Issue by pitsi** [anxdpanic/plugin.video.youtube#403]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.24
* Kodi Version: 18.9
* Kodi GUI Language: Greek
* Operating System: Libreelec 9.2.x
* Operating System Language: English

------

### Expected Behavior
The python2 version should update to its latest available version from the testing repo.

------

### Current Behavior
However it does not, because it says this in the log
`2023-02-06 07:42:56.542 T:139980332193536   ERROR: CAddonInstallJob[plugin.video.youtube]: The dependency on xbmc.python version 3.0.1 could not be satisfied.`

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have a kodi 18 installation with the yt_testing repo and youtube also installed
2. Try updating youtube through kodi's update mechanism

------

### Log
Please see above

------

### Additional Information
It is weird because the addons.xml from the repo does list python2 as dependency for it
```
<addon id="plugin.video.youtube" name="YouTube" version="6.8.25~alpha1" provider-name="anxdpanic, bromix">
<requires>
<import addon="xbmc.python" version="2.20.0"/>
<import addon="script.module.six" version="1.11.0"/>
<import addon="script.module.requests" version="2.12.4"/>
<import addon="script.module.infotagger" version="0.0.3"/>
<import addon="script.module.inputstreamhelper" version="0.2.2" optional="true"/>
</requires>
```
and so does the addon's xml file
```
<addon id="plugin.video.youtube" name="YouTube" version="6.8.25~alpha1" provider-name="anxdpanic, bromix">
<requires>
<import addon="xbmc.python" version="2.20.0"/>
<import addon="script.module.six" version="1.11.0"/>
<import addon="script.module.requests" version="2.12.4"/>
<import addon="script.module.infotagger" version="0.0.3"/>
<import addon="script.module.inputstreamhelper" version="0.2.2" optional="true"/>
</requires>
```
I have already tried force-checking the repo for updates and rebooted the system,

------

**Comment by anxdpanic** [comment]
not sure what would be causing that off hand, i don't have `3.0.1` set for any of them.

**Comment by pitsi** [comment]
I am confused about that too. Removing the repo and reinstalling it does not solve the issue though.
I have no idea what version it was on before removal, but it was definitely on yesterday's 2.0.3 or newer and now it is on 2.0.4.

**Comment by oscarsfriend** [comment]
script.module.infotagger requires a newer version of python. From the addon.xml of script.module.infotagger:

`  <requires>
    <import addon="xbmc.python" version="3.0.1"/>
  </requires>`

I also can't update, but the error notification in kodi clearly says it's because of the infotagger dependency.

**Comment by anxdpanic** [comment]
nice catch, ill get that addressed

**Comment by anxdpanic** [comment]
mirrors are syncing with new version. should resolve the issue, and v20 compat.

**Comment by oscarsfriend** [comment]
This indeed fixes the update problem, however the addon is now broken. I was just about to submit a bug report but someone else [beat me to it](https://github.com/anxdpanic/plugin.video.youtube/issues/405). (The errors in my log look the same as theirs.)

**Comment by pitsi** [comment]
Can I close this now? :)
