### ISSUE TITLE
Can't Sign In... Access Denied

### ISSUE THREAD

**Issue by akeith921** [anxdpanic/plugin.video.youtube#408]
![Screenshot_20230209_053736](https://user-images.githubusercontent.com/111309314/217971117-0401b3ff-14da-4af0-ba52-ece609c4036e.png)

**Comment by akeith921** [comment]
Error 403: access_denied
Request details: access_type=offline dfi=AKXaY0efHw60a19AgSsrwsHfjou-jrwYrR81weNGKuQj-C9H4bFkSTKuwz-CcJ1RRgOJgaeHbh7Qse2FJOECbA response_type=none prompt=consent client_id=513306480488-bnsg35c9dqodfh9mtenam0fb0sv2d3et.apps.googleusercontent.com scope=https://www.googleapis.com/auth/youtube

**Comment by akeith921** [comment]
Wait is this a kodi issue?

**Comment by decryptedchaos** [comment]
same issue....

**Comment by tkjh90002** [comment]
the same problem. COuld you give me the resolution? thank u.

**Comment by slax57** [comment]
This issue looks similar to this one: https://github.com/anxdpanic/plugin.video.youtube/issues/312

If ever that helps, I also got a 403 at some point, and what solved it for me was to **Publish** the app (like suggested in [this comment](https://github.com/anxdpanic/plugin.video.youtube/issues/312#issuecomment-1148667970)).
