### ISSUE TITLE
Please show the upload date of the videos instead of just the year

### ISSUE THREAD

**Issue by pitsi** [anxdpanic/plugin.video.youtube#425]
### What Problem Does This Solve? 
Right now, when pressing "i" in order to check any video info (like its description or its duration), the addon only shows the year it was uploaded. This is pointless imho and its date would be far more useful, especially on videos that have howtos.

------

### Suggest a Solution (optional)
Since I have no idea on how youtube's api works, here is an output from some invidious instance. I have intentionally asked the api for those 3 fields only so as to avoid a huge output.
```
$ curl -s "https://vid.puffyan.us/api/v1/videos/C75GfC1y_nw?fields=videoId,title,published&pretty=1"
{
  "title": "Anser - Άνθρωπος Ίδιος / Anthropos Idios (Official video clip) Prod. by Eversor",
  "videoId": "C75GfC1y_nw",
  "published": 1637625600
}
```
After that, getting the upload date from that unix time timestamp is as easy as this in python
```
>>> import datetime
>>> x=datetime.datetime.fromtimestamp(1637625600)
>>> x=x.strftime("%x")
>>> x
'11/23/21'
```
Unfortunately, I may not be able to check the change anytime soon now that the addon is kodi 20 only :(

------

**Comment by pitsi** [comment]
It has been more than a year since I opened this and I remembered it today that I wanted to check a video's upload date.
To be honest, I expected it to be mentioned it here, which is where I described above

![screenshot00001](https://github.com/anxdpanic/plugin.video.youtube/assets/5880037/753526d1-bee2-4853-8e6d-8a664979b6fd)

but instead it is mentioned here, along with the other (useless) details, like the views and the likes it got.

![screenshot00000](https://github.com/anxdpanic/plugin.video.youtube/assets/5880037/e8bc1091-800f-4842-b79c-2b2c51aa0457)

Disabling the relevant option from the advanced submenu in the settings hides the upload date completely.
Kodi 21 on debian testing/unstable x64 and youtube 7.0.5 from the main kodi repo.

**Comment by MoojMidge** [comment]
This has already been fixed in the plugin.

**Comment by pitsi** [comment]
Yes, I noticed that. It's just I hoped it was fixed in a different way. Btw, what are the numbers next to each? I can undestand that the fist number is the views, the second number in bright green is the likes, but what is the third number in bright blue? Please tell me it's the dislikes!

**Comment by MoojMidge** [comment]
> Yes, I noticed that. It's just I hoped it was fixed in a different way.

It was fixed in the only way that it can be fixed in the plugin. Your issue is with the skin you are using. Try using another one and you should be able to see the difference.

> Btw, what are the numbers next to each? I can undestand that the fist number is the views, the second number in bright green is the likes, but what is the third number in bright blue? Please tell me it's the dislikes!

Comments. 

The stats are fully labelled in the description, where there is more room to display that detail, but you need to enable `Settings > Advanced > Views > Show channel name and video details in description`.

**Comment by pitsi** [comment]
I see. However, it looks the same in estuary as well. If you can suggest any other skin that may show it differently, please do. Skins that are lightweight and have very few or no dependencies will be appreciated.

![screenshot00000](https://github.com/anxdpanic/plugin.video.youtube/assets/5880037/24431ae3-36b2-4d04-b127-8e2392bb776d)

![screenshot00001](https://github.com/anxdpanic/plugin.video.youtube/assets/5880037/b0fdf7ec-689b-4751-ad39-444b7701d1f5)

As for the rest, I know how to enable/disable the option. Also, how cool would it be if it could show dislikes! I guess they are not provided by the api.

**Comment by pitsi** [comment]
Oh, there is a small date on the bottom right corner! And it shows up even when the forementioned option is disabled. Neat!

**Comment by MoojMidge** [comment]
> I see. However, it looks the same in estuary as well.

I'm not sure what you are talking about. The full date is clearly shown in multiple places in your screenshot, not just at the bottom right corner. 

The original issue was that it didn't show up in the info dialog, but that is a skin issue. The correct date is provided by the plugin.
