### ISSUE TITLE
2.0.5 repo......... it's can be updated on kodi 19 due Python 3.0.1 as dependency....

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#428]
@anxdpanic the current repo 2.0.5 it's can be installed/updated on kodi 19......

It's contain the dependency phyton 3.0.1 and from this same repo can be installed the current 6.8.25 unofficial version of youtube addons.

The phyton 3.0.1 it's only satisfied on Kodi Nexus setup :)

Thanks to fix.......

**Comment by anxdpanic** [comment]
@DjDiabolik See #413 
The add-on (all my add-ons) are now Nexus+ only. 

So there is nothing to fix, and it's not something I can easily support. This change removed over 4000 lines of code. (v7.0.0)
The reason for doing this is to reduce the amount of support time that's required per add-on. So I have more time to work on actual issues. That, and nexus capable devices are now cheap, so it felt like the right time to finally do this.

For this add-on alone its was 6+ repositories worth of updating which took a lot of time. This is reduced now to 2, that will take 5 minutes at most.

**Comment by DjDiabolik** [comment]
So yes... but on repository 2.0.5 it's also can available the 6.25 unofficial also for kodi 19.x and if you can't update the repository you can obtain the latest 6.x of addons :)

**Comment by anxdpanic** [comment]
Since there are no new updates coming, it's just as easy to install the zip for the last version.
for what it's worth i completely nuked the pre matrix stuff too. So they won't be able to update via repository either anymore.

**Comment by DjDiabolik** [comment]
> Since there are no new updates coming, it's just as easy to install the zip for the last version.
> for what it's worth i completely nuked the pre matrix stuff too. So they won't be able to update via repository either anymore.

So ok...... For me it makes no difference. I can reach you zip source:
http://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/kodi/youtube/python3/unofficial/zips/plugin.video.youtube/

Download and install manually this latest version for matrix version........ but until a few days ago to do that you had to update the repository to 2.0.5 but you can't do because it's request a kodi nexus.

Now i can see... the repository 2.0.5 it's support only kodi nexus....... so everything is ok.

**Comment by DjDiabolik** [comment]
I hope..... also OSMC will be updated to kodi 20 soon :)

**Comment by neo-neo1** [comment]
> 
> For this add-on alone its was 6+ repositories worth of updating which took a lot of time. This is reduced now to 2, that will take 5 minutes at most.

What's the link for your testing repo? I always can't find it after a kodi reinstall. Thanks

**Comment by DjDiabolik** [comment]
> reinstall

it's on wiki:
https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation
