### ISSUE TITLE
Enabling Hide Short Videos Causes Error When Trying to View My Subscriptions or Other Playlists

### ISSUE THREAD

**Issue by Mark112887** [anxdpanic/plugin.video.youtube#429]
Had been having some strange issues viewing my watch history, watch later and my subscriptions playlists in the YouTube add-on. At first I was able to correct the issue or so I thought by reducing the number of results per page. As it turns out that would only resolve the issue temporarily. Today I decided to create brand-new credentials and while customizing the settings back to what I prefer I discovered the true cause of the error. Everything pulls up and displays fine until the option to hide short videos is enabled

**Comment by anxdpanic** [comment]
Would need a full debug log with you reproducing

**Comment by Mark112887** [comment]
How do I get that for you? Even with the latest update 7.01 this is still
happening. When hide short videos is sent to enable I get an error when
trying to view my watch later playlist, however viewing my subscriptions
with hide short videos enabled now works fine. If you can tell me how to
get you a full debug log I will absolutely do that for you. Thank you for
your response and the great work that you do with this add-on

**Comment by Mark112887** [comment]
Here's my Kodi log file. Don't know why it says it can't find my server, it works fine. Anyway, at the bottom you'll see, this is with hide short videos switched on, my watch later playlist will not load, with it off it's fine

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10962045/kodi.log)

**Comment by Mark112887** [comment]
> Would need a full debug log with you reproducing

@anxdpanic Here's my Kodi log file. Don't know why it says it can't find my server, it works fine. Anyway, at the bottom you'll see, this is with hide short videos switched on, my watch later playlist will not load, with it off it's fine
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10962071/kodi.log)

**Comment by anxdpanic** [comment]
Can you enable debug logging and reproduce that? https://kodi.wiki/view/Log_file/Easy

**Comment by Mark112887** [comment]
> Can you enable debug logging and reproduce that? https://kodi.wiki/view/Log_file/Easy

@anxdpanic so sorry, here is the log with debug logging enabled

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10971931/kodi.log)

**Comment by anxdpanic** [comment]
perfect, thank you. that caught the error :)
Will likely have a test version up in the near future for you

**Comment by Mark112887** [comment]
Thank you so very much! Glad I could help, thank you for all of your hard
work

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev can you try the zip from there, adn let me know

**Comment by Mark112887** [comment]
@anxdpanic issue is fixed with that alpha version

**Comment by anxdpanic** [comment]
Thank you for confirming :)
