### ISSUE TITLE
Please add support for /live URLs

### ISSUE THREAD

**Issue by siliconhippy** [anxdpanic/plugin.video.youtube#432]
### What Problem Does This Solve? 

YouTube addon today only seems to support the video_id= $videoid URL format. 
However the problem with above format for live channels is that these URLs will change frequently!

However YouTube seems to keep the /live URLs constant, so these are desirable for a playlist.
 
I asked for this originally, post 1701:
https://forum.kodi.tv/showthread.php?tid=356934&page=114

YouTube live channel URLs in the /live could be /c/channel/live, or /user/live or /@channel/live. There might be more I have not come across yet !
------
### Suggest a Solution (optional)

See post #1702 by @jepzizofye in above Kodi Forum link.

----
Additionally I would appreciate any answers to  other questions in my post 1701 above !

**Comment by anxdpanic** [comment]
plugin://plugin.video.youtube/play/?channel_id=UCSrZ3UV4jOidv8ppoVuvW9Q&live=1

`live=1` means the first live stream on that channel if there are more than one, change that to `live=2` for the second live stream etc.

**Comment by siliconhippy** [comment]
Ok great !

1. So https://www.youtube.com/c/TravelChannel/live

becomes? 

 plugin://plugin.video.youtube/play/?channel_id=TravelChannel&live=1 

2. And in youtube.com/@name/live,
channel_id=name  ?

And, in youtube.com/user/name/live, channel_id=name  ?

**Comment by anxdpanic** [comment]
travel channel would be

`plugin://plugin.video.youtube/play/?channel_id=UCJUAqHnkDX15IvFoXIGTm2A&live=1`

**Comment by siliconhippy** [comment]
Thanks for the quick responses.

But I am a bit confused...is there a general rule for channel _id format as I asked above in 1 &2 questions.

Also the travel channel code you stated above...will this be stable ( the main question from original post)?

**Comment by anxdpanic** [comment]
The channel_id has to be the channels id, not name or alias.
To find it, just view source and ctrl-f for channelid and you'll find it a bunch of places in the pages source

**Comment by anxdpanic** [comment]
the travel channel code will always play the `first` live stream on that channel

So like some pages that have 3 live streams at once, it might change order. So it's better to add all three.
ie.
```
plugin://plugin.video.youtube/play/?channel_id=UCJUAqHnkDX15IvFoXIGTm2A&live=1
plugin://plugin.video.youtube/play/?channel_id=UCJUAqHnkDX15IvFoXIGTm2A&live=2
plugin://plugin.video.youtube/play/?channel_id=UCJUAqHnkDX15IvFoXIGTm2A&live=3
```
then one of those will point to the stream you're looking for. because the id changes and the index changes when a live stream stops/starts it's near impossible to be 100%

Single live stream channels should be stable though

**Comment by siliconhippy** [comment]
Ok thanks. Will try and let you know....☺️

**Comment by XxAcielxX** [comment]
Sorry for hijacking this issue. After the new changes from Google, playing of live videos is completely broken. I have tried the above method, and sadly it does not work for me. I keep getting "This video is not made available in your country" while I can play it fine on my phone.

The only way I have found to actually play a live video is to generate one time play link by doing `yt-dlp --get-url <video-link>`, then sending it to Kodi. You have to do this each time you want to play the live video.

We need a proper fix for this soon.

**Comment by siliconhippy** [comment]
@XxAcielxX Thanks for the alert!
Hopefully there will be an easier solution...
