### ISSUE TITLE
Please Return the Upload Date to the Top of the Video Description

### ISSUE THREAD

**Issue by Mark112887** [anxdpanic/plugin.video.youtube#434]
### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.
@anxdpanic In previous versions, such as 6.8.24 matrix 1 the upload date of the video was displayed at the top of the video description. Please, if it is not too difficult, could you please bring this information back in the next update? It is a great help to know while scrolling a list of videos what date they were uploaded

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

------

**Comment by pitsi** [comment]
May I ask where is the upload date located in the video description? All I see is the upload year and nothing more. That's why asked for the full date on an issue report.

I am currently running v6.8.25 on 2 kodi installations, one at v18 and one at v19.

**Comment by Mark112887** [comment]
I don't even get the year but it used to be like in version 6.8.2.4 you
could see the upload date before the description prior to clicking on a
video

**Comment by pitsi** [comment]
This is what I mean. Pictured is youtube 6.8.25, running on kodi 18.9, on libreelec 9.2.6. 
Kodi's locale is set to greek, but I think you get the idea. 

![screenshot036](https://user-images.githubusercontent.com/5880037/226923678-9af51c38-2b98-4373-8097-1eae21776a36.png)

**Comment by Mark112887** [comment]
@pitsi @anxdpanic 
This is what I mean 
6.8.24
date is on the right
![20230322_115022](https://user-images.githubusercontent.com/100076269/226963998-cc3ec9f0-0b3a-4f7d-84da-8efea439b01f.jpg)

**Comment by pitsi** [comment]
Which view type is this? I cycled through all 4 available (list, big list, thumbnail and info) and none shows it like that!  
Tbh, I am... addicted to list view and I have been using it for almost a decade now.

In case the view type is something skin specific, which skin is it? Please don't be estuary/estouchy :P

**Comment by Mark112887** [comment]
@pitsi  It is the list view type with information turned on under list settings.
I'm also using the aeon nox Silvio skin

**Comment by pitsi** [comment]
Serious question, because I tried a few skins and I still can't find a way to show the date: do you use the default youtube version from the main repo or the unofficial one from here?

**Comment by Mark112887** [comment]
@pitsi  default but 6824 matrix 1 using aeon nox silvo in list view with information turned on under list settings

**Comment by pitsi** [comment]
I installed unofficial version of 6.8.25 and now I get the dates when selecting big list, media info and media info 2. 
All the above happens on quartz, which is the skin I mainly use  On confluence, which is my backup skin, I get no dates on big list, media info 3 and thumbnails.

Long story short, have you tried the unofficial version of the addon from here?

**Comment by Mark112887** [comment]
@pitsi  I'll give it a try right now I could swear I'm not on unofficial

**Comment by Mark112887** [comment]
@pitsi no luck even on unofficial 7.02 and I double checked 6.8.24 official it shows up for me. will try unofficial 7.01

**Comment by Mark112887** [comment]
@pitsi 
6824 official
![Screenshot_20230325-160430](https://user-images.githubusercontent.com/100076269/227739353-a2210625-8c8a-4ca5-a23b-e84e366102e9.png)
![Screenshot_20230325-160517](https://user-images.githubusercontent.com/100076269/227739359-1cba237d-ff03-4376-944d-32bae6802052.png)
![Screenshot_20230325-160530](https://user-images.githubusercontent.com/100076269/227739368-25a84f98-283c-4b8c-be45-7f33a26cabf4.png)
7.01 official
![Screenshot_20230325-160830](https://user-images.githubusercontent.com/100076269/227739407-79dd6825-71a4-475d-82cd-680405
![Screenshot_20230325-160903](https://user-images.githubusercontent.com/100076269/227739413-215c5106-a26a-4951-b1a9-ef06ace4ebe3.png)
93487a.png)
![Screenshot_20230325-160915](https://user-images.githubusercontent.com/100076269/227739421-d4b2a84e-cf97-4979-947d-7098c3514812.png)
