### ISSUE TITLE
Cannot Get Subscription List Using 7.0.2 Alpha-1 with Hide Short Videos Enabled

### ISSUE THREAD

**Issue by Mark112887** [anxdpanic/plugin.video.youtube#436]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* 7.0.2.alpha1
* Kodi Version
* 20.1:
* Kodi GUI Language
* English:
* Operating System:
* Android
* Operating System Language:
* English

------

### Expected Behavior

I should be able to pull up a list of the channels I am subscribed to by selecting subscriptions in the menu list

------

### Current Behavior

@anxdpanic While hide short videos is enabled I am unable to pull up a list of the channels I am subscribed to. The test version you gave me fixed one problem but created another

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open youtube add on
2. enable hide short videos in settings
3. select subscriptions from menu NOT MY SUBSCRIPTIONS

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/10974073/kodi.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by Mark112887** [comment]
@anxdpanic Have you found the issue?

**Comment by cas--** [comment]
I encountered this and should be fixed by recent commit c13549a774
