### ISSUE TITLE
This video isn't available on this app 

### ISSUE THREAD

**Issue by f2hamza** [anxdpanic/plugin.video.youtube#443]
It says this video isn't available on this app
im on latest version btw

**Comment by FunctionalHacker** [comment]
I get the same on this video https://www.youtube.com/watch?v=OegJ6nX57KY

Most videos seem to work though

**Comment by MatthiasCoppens** [comment]
Duplicate of #442

**Comment by FunctionalHacker** [comment]
Yes, let's close this in favor of #442
