### ISSUE TITLE
Why such early removal of pre-nexus support?

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#445]
### Context

Please provide any relevant information about your setup

* Kodi Version: 19.5
* Operating System: OSMC 2023 01-01

------

### Expected Behavior

Expecting Longer Support of Matrix to allow OSMC breathing room for Kodi updating, when updates need to happen to keep this plugin functional

------

### Current Behavior

Youtube app cannot be updated to alpha pre-release to fix [bug 422
](https://github.com/anxdpanic/plugin.video.youtube/issues/442) with OSMC

------

**Comment by anxdpanic** [comment]
Simple answer is Time.
Sorry, if we get working fixes that break things I may backport the fix to a zip file for matrix. But again that depends on time.

**Comment by anxdpanic** [comment]
Side note, I also use OSMC on two veros, so I'm just as put out in the mean time.

**Comment by neo-neo1** [comment]
Anyone with the ability to help maintain Kodi 19 Matrix support in this community?

**Comment by lbriais** [comment]
I feel a bit better knowing that this problem is shared with @anxdpanic (please please) but I don't understand why such a decision has been made. I hope this will be quickly tackled, as obviously this impacts the vast majority of kodi users (OSMC user here too...).

**Comment by MoojMidge** [comment]
Matrix version is now aligned with Nexus version, pending any future Kodi changes.

Can test [v7.0.2.2](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.2.2) and report any issues.
