### ISSUE TITLE
Can't sign in as google account has 2 step

### ISSUE THREAD

**Issue by otmpp** [anxdpanic/plugin.video.youtube#45]
I can't get my api keys to work with the add-on. I think I understand why though. I believe it's because I have 2 step verification enabled which basically means google won't let me use the unsafe method of signing into my account. They instead want me to use an app password.

Any ideas on how I can use this with the youtube addon so I can sign in? I also after having played around for a bit only ever get prompted to sign in to the addon once and then it fails, it does not seem to ask a second time.

Thanks for your help

**Comment by anxdpanic** [comment]
I use 2 factor myself. There is likely something wrong with your keys, or the transcription of them.  
Why did you ignore the issue templates?

re-open with a debug log
