### ISSUE TITLE
"The following content is not available on this app" since Wed, 26th, 2023 in the early morning CET: 

### ISSUE THREAD

**Issue by vigilant4u** [anxdpanic/plugin.video.youtube#456]
VERY ANNOYING: Youtube seem to have changed the API handling as they have new ads regulation in place (they do not want anybody to see videos without any ads any more).

* Add-on Version: 6.8.25
* Kodi Version: 18.9 Leia
* Operating System: APK FireTV , MAC, Windows

But basically every youtube version up to. 7.0x and every Kodi version is showing the error message without being able to play a single youtube video:

"The following content is not available on this app" 

------

2023-04-27 12:09:13.468 T:123145571479552   ERROR:     raise YouTubeException(reason)
2023-04-27 12:09:13.468 T:123145571479552   ERROR: YouTubeException: The following content is not available on this app.
2023-04-27 12:09:13.469 T:123145571479552   ERROR: [plugin.video.youtube] None
2023-04-27 12:09:13.478 T:4788811200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=jlQTMyBhWls]

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by HeresJonny** [comment]
Don't report bugs twice

**Comment by TasPats** [comment]
get this error on YT video, which are rated 18+ from this one — "phrase "foreign agent" (Russian: иностранный агент)"
for example only, this YT video: https://www.youtube.com/watch?v=q9c3k9C648M

**Comment by upbox-org** [comment]
This bug is reported and should be fixed since days. Try the latest dev version and search for existing issues next time.

**Comment by vjuergens** [comment]
Kodi 20.1.0
youtube-7.0.1

same error message on all content. I guess the youtube API has changed.

**Comment by hugalafutro** [comment]
experiencing the same, updating to latest alpha of youtube sort of fixed the issue, but not really as in result the app is still unusable as youtube videos although "loading" are unwatchable

stable matrix + stable youtube (from the kodi repo) = random videos (about 1/3 from my subscriptions) "not available on this app"
stable matrix + latest alpha youtube (7.0.2alpha4) =  all videos buffer at snail pace regardless of network connection speed, play for 5-ish seconds, then buffer again

**Comment by TasPats** [comment]
try 7.0.2-alpha4, same YT video results in:
"One or more items failed to play. Check the log for more information about this message."

log is empty, all logging is enabled

device:
Beelink GT King Pro, v. KODI 20.1.0
restarting does not help

**Comment by Doktor-X** [comment]
7.0.2-alpha4, "fixed" problem with video not bean able to start playing, but now i have new problem that video have constant buffeeing and its unable to play properly. Do i need to recreate my api key maybe?

**Comment by upbox-org** [comment]
> 7.0.2-alpha4, "fixed" problem with video not bean able to start playing, but now i have new problem that video have constant buffeeing and its unable to play properly. Do i need to recreate my api key maybe?

That another issue. 
Yes, recreating your API credentials can fix that. It's worth a try.

**Comment by upbox-org** [comment]
It just upsets me that you don't even manage to show the minimum of respect to the developer - who does this in his spare time - and use the existing issue. Perhaps there are also solutions that will help you or us to move forward.

**Comment by hugalafutro** [comment]
> It just upsets me that you don't even manage to show the minimum of respect to the developer - who does this in his spare time - and use the existing issue. Perhaps there are also solutions that will help you or us to move forward.

The other issue (I assume you mean #442) was created 2 weeks ago, at which point I was not experiencing neither the other issue nor this one. This issue specifically mentions date and time (yesterday) at around which I have started experiencing this issue. So although the symptoms might be identical, the issues are clearly not the same.

**Comment by ThubLives** [comment]
The time and date that the issue presents itself isn't particularly relevant to the ongoing issue.  For example, #442 is full of people saying "this just started affecting me today" over a span of weeks.

Particularly when working with software that relies on a third-party service such as this, there are many confounding factors such as CDNs and server load balancing that result in different people (perhaps in different geographic locations, perhaps not) being affected at different times.  Even which ISP you use might affect when or how regularly you are affected.

Generally, it's better to keep feedback related to the same symptoms under the same issue to prevent splitting the devs' attention or causing unnecessary confusion.  If a dev or someone tasked with triage determines there is plausible evidence of multiple problems, they may decide to split the issue or ask to have another issue created.

**Comment by hugalafutro** [comment]
@ThubLives explained like that I can see how It would have been better to post in the older issue, however having previously only seen the op been told "don't post duplicates" and "it has been fixed" while neither of those being true for me nor offering any explanation why I assumed this was the right place to post as it literally 100% matched the circumstances of my experiencing the issue.

I'm subbing to the older issue and unsubbing from here.

**Comment by upbox-org** [comment]
> @ThubLives explained like that I can see how It would have been better to post in the older issue, however having previously only seen the op been told "don't post duplicates" and "it has been fixed" while neither of those being true for me nor offering any explanation why I assumed this was the right place to post as it literally 100% matched the circumstances of my experiencing the issue.
> 
> I'm subbing to the older issue and unsubbing from here.

You can't expect someone to explain everything to you - especially not in detail like ThubLives did. 
You are not at the ticket support of some paid consumer software here. 
I mean, if you had searched and read issue #442, you would already know what was explained to you here. 

Edit:
Besides, you wrote 

> stable matrix + latest alpha youtube (7.0.2alpha4) = all videos buffer at snail pace regardless of network connection speed, play for 5-ish seconds, then buffer again.

This is not the same issue reported in #442. Sounds more like #426.

**Comment by ThubLives** [comment]
@Retardium When you're not used to commenting on and creating issues, it's not always easy to learn the cultural norms unless someone explains it to you.  I know I've been in the same position before and I was embarrassed about it, but ultimately glad that someone explained it to me.  I don't think it calls for further admonishment.

But you do make a fair point about there seeming to be two different relevant issues.

**Comment by ludmilmm** [comment]
I am having the same issue. Here's part of the kodi.log. Hopefully, it could help the devs:

`2023-04-28 11:40:07.953 T:511454    info <general>: [plugin.video.youtube] Running: YouTube (7.0.1) on N***** (Kodi-20.0) with Python 3.8.10
                                                        Path: /play/
                                                        Params: {'video_id': 'dQ9eImcE9cA'}
2023-04-28 11:40:08.329 T:511454   error <general>: Traceback (most recent call last):

2023-04-28 11:40:08.329 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>:   File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)

2023-04-28 11:40:08.330 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>:   File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 101, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)

2023-04-28 11:40:08.330 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>:   File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 542, in load_stream_infos
                                                       return self._method_get_video_info(video_id)

2023-04-28 11:40:08.330 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>:   File "/home/user/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 859, in _method_get_video_info
                                                       raise YouTubeException(reason)

2023-04-28 11:40:08.330 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: The following content is not available on this app.

2023-04-28 11:40:08.330 T:511454   error <general>:
2023-04-28 11:40:08.330 T:511454   error <general>: [plugin.video.youtube] None
2023-04-28 11:40:08.346 T:508949   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=dQ9eImcE9cA]`

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev there are nexus and matrix zips available here, please try those. and please keep this issue to https://github.com/anxdpanic/plugin.video.youtube/issues/442 in the future 👍

**Comment by TasPats** [comment]
just as information for Devs — 
**plugin.video.youtube-unofficial-7.0.2.alpha5.zip** 
resolved my problem...
🫶

**Comment by Andyman14159** [comment]
Yes more information - 
plugin.video.youtube-unofficial-6.8.26.alpha3.zip 
resolved the problem for me Kodi 19.4 Win64 Thank you for all your hard work to keep the codes open
