### ISSUE TITLE
Live Streams Skips to End

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#463]
This behavior has existed for many months now. Has anyone else noticed this?

If I open a Livestream which has ended recently (few hours or so) it'll open the video to the last 5 seconds. You'll have to manually rewind to the start. 

After many hours later, if you open the same video again it'll open normally as it shouid, at the begining.

* Add-on Version: 6.8.26.Alpha4
* Kodi Version: 19.5 Matrix
* Kodi GUI Language: English
* Operating System: CoreELEC
* Operating System Language: English

**Comment by chapperino** [comment]
Yep, can confirm I've experienced this for a long time now. While it doesn't hapen every day, when it does it's a nuisance. Sometimes the (recently ended livestream) video  opens to the last 1 second and instantly ends and closes. I'll have to open it multiple times hoping my rewind keypress will register in time before video ends.

An option to auto start (recently livestreamed) videos from the begining would be desirable and much welcomed. Thanks devs for your upkeep

**Comment by netty0** [comment]
Noticed this also. Been like this for many versions

**Comment by neo-neo1** [comment]
Anyone with the technical ability able to troubleshoot this? Many thanks

**Comment by MoojMidge** [comment]
This is a Youtube issue.

> An option to auto start (recently livestreamed) videos from the begining would be desirable and much welcomed.

#320
