### ISSUE TITLE
Choppy playback on Live Streams | Kodi Nexus on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by sk3106** [anxdpanic/plugin.video.youtube#465]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2~alpha6
* Kodi Version: 20.1
* Kodi GUI Language: American English
* Operating System: Raspberry Pi OS ( Debian Bullseye )
* Operating System Language: American English

------

### Expected Behavior

Please describe the behavior you are expecting.

- Smooth playback like before with no sudden freezing or skipping ahead.

------

### Current Behavior

What is the current behavior?

- Takes a lot of tries to finally get the stream to play. Often it freezes the whole OS in the process but when the stream finally plays, the playback is not smooth. It looks like as if its skipping some frames and keeps jumping. If you look at the clock in a stream, you'll see some seconds skip, like it will go from 10:05:30 to suddenly 10:05:48. Previously I have not had this kinda issue, I've even had videos and streams playing whole day without any problems. I think the increase in issues has started after the "content not available" problem was fixed( ? ).

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Search for a live stream
2. Simply choose play, or play( ask for quality )
3. Now either the whole OS will freeze or if the stream has started playing, it's gonna look like the frames keep skipping so you see this "jumping motion".

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/ayibewirif.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

- I've tried all the recent releases so far. All have this problem. Older ones end up with the "content not available" error.

------

**Comment by popcornmix** [comment]
@sk3106 from the log it didn't look like you had DRMPrime enabled in settings/video.

**Comment by sk3106** [comment]
> @sk3106 from the log it didn't look like you had DRMPrime enabled in settings/video.

I'm unable to find that in Player/Videos. Haven't seen that setting before either

**Comment by popcornmix** [comment]
See: https://kodi.wiki/view/Settings/Player/Videos#Render_method
It's in the "platform specific hardware acceleration settings"
Make sure you have the settings level (shown bottom left) set to expert.

But DRMPRIME is enabled by default, so if it's not on, someone disabled it.

**Comment by popcornmix** [comment]
Ah:
```
2023-05-02 08:53:33.904 T:884      info <general>: Starting Kodi from Debian (20.1 Debian package version: 2:20.1+dfsg-1). Platform: Linux ARM 64-bit
2023-05-02 08:53:33.904 T:884      info <general>: Using Release Kodi from Debian x64
2023-05-02 08:53:33.904 T:884      info <general>: Kodi from Debian compiled 2023-03-12 by GCC 12.2.0 for Linux ARM 64-bit version 6.1.15 (393487)
2023-05-02 08:53:33.904 T:884      info <general>: Running on BCM2835 with Debian GNU/Linux 12 (bookworm), kernel: Linux ARM 64-bit version 6.1.21-v8+
```
You said you are running RPiOS (Debian bullseye), but it looks like you are running debian/bookworm.
That version may not have been built with RPiOS relevant acceleration options.

You should stick to the RPiOS bullseye version (which is Kodi 19), or use something like LibreELEC (which has been updated to Kodi 20), or wait for RPiOS bookworm to be released.

**Comment by sk3106** [comment]
> Ah:
> 
> ```
> 2023-05-02 08:53:33.904 T:884      info <general>: Starting Kodi from Debian (20.1 Debian package version: 2:20.1+dfsg-1). Platform: Linux ARM 64-bit
> 2023-05-02 08:53:33.904 T:884      info <general>: Using Release Kodi from Debian x64
> 2023-05-02 08:53:33.904 T:884      info <general>: Kodi from Debian compiled 2023-03-12 by GCC 12.2.0 for Linux ARM 64-bit version 6.1.15 (393487)
> 2023-05-02 08:53:33.904 T:884      info <general>: Running on BCM2835 with Debian GNU/Linux 12 (bookworm), kernel: Linux ARM 64-bit version 6.1.21-v8+
> ```
> 
> You said you are running RPiOS (Debian bullseye), but it looks like you are running debian/bookworm. That version may not have been built with RPiOS relevant acceleration options.
> 
> You should stick to the RPiOS bullseye version (which is Kodi 19), or use something like LibreELEC (which has been updated to Kodi 20), or wait for RPiOS bookworm to be released.

Ah my bad, I forgot to write I installed this bookworm version of Kodi from the Debian Testing repo on RPiOS Bullseye to be able to update the addon( there seemed to be some Python version related issues on 19 ).

I'll try to test on another compatible OS and if it doesn't work, I'll open a new issue.

Thanks for all the help! Have a good day

**Comment by LeVraiRoiDHyrule** [comment]
> > Ah:
> > ```
> > 2023-05-02 08:53:33.904 T:884      info <general>: Starting Kodi from Debian (20.1 Debian package version: 2:20.1+dfsg-1). Platform: Linux ARM 64-bit
> > 2023-05-02 08:53:33.904 T:884      info <general>: Using Release Kodi from Debian x64
> > 2023-05-02 08:53:33.904 T:884      info <general>: Kodi from Debian compiled 2023-03-12 by GCC 12.2.0 for Linux ARM 64-bit version 6.1.15 (393487)
> > 2023-05-02 08:53:33.904 T:884      info <general>: Running on BCM2835 with Debian GNU/Linux 12 (bookworm), kernel: Linux ARM 64-bit version 6.1.21-v8+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You said you are running RPiOS (Debian bullseye), but it looks like you are running debian/bookworm. That version may not have been built with RPiOS relevant acceleration options.
> > You should stick to the RPiOS bullseye version (which is Kodi 19), or use something like LibreELEC (which has been updated to Kodi 20), or wait for RPiOS bookworm to be released.
> 
> Ah my bad, I forgot to write I installed this bookworm version of Kodi from the Debian Testing repo on RPiOS Bullseye to be able to update the addon( there seemed to be some Python version related issues on 19 ).
> 
> I'll try to test on another compatible OS and if it doesn't work, I'll open a new issue.
> 
> Thanks for all the help! Have a good day

Hi, I would have a question that is not related to the youtube addon but this thread is the only one I've found with my answers.

I am using Kodi on Dietpi, which is based on RpiOS. I was previously using Dietpi Bullseye with Kodi 19 and playback of 4k HEVC HDR files was perfect. After migrating to Kodi 20 on Dietpi Bookworm, playback of those files stutter a lot, and I noticed some decoding options disappeared from the menus.

So my questions are:
- Can someone confirm that as of today, it is not possible to play 4k HEVC HDR files on Rpi4 on bookworm due to missing codecs ?
- Could it be because of something else ?
- Is there a way to add those codecs manually (without building myself) ?

Thanks in advance for any answer and sorry if it's not related to the youtube addon, have a great day

**Comment by sk3106** [comment]
Hi,

When you open Kodi, does it say "Kodi for Debian" or just "Kodi"? Mainly,
the problem is with Kodi for Debian as its missing a lot of support. In my
case, I installed Manjaro ARM and that fixed all the issues as its a
rolling release distro plus it comes with raspberry pi customized drivers.

I haven't used dietpi but if you have a spare SD Card lying around, I would
suggest trying an OS like Manjaro or Arch to see if the problem is with
dietpi. Hope this helps.

**Comment by LeVraiRoiDHyrule** [comment]
> 

Hi,
Thanks a lot for your answer on an old topic !

It is "Kodi for Debian" (which surprised me as with Bullseye, it was just Kodi and had the codecs). So I guess that is the issue. I've rarely seen differences between Dietpi and RpiOS with app behaviours.

Do you know if there is a way to install Kodi, not Kodi for Debian, via apt or similar ?

**Comment by sk3106** [comment]
No problem!

Unfortunately, the RPi customized Kodi wasn't available on Bookworm when I
last checked. It's available on Bullseye though but only Kodi 19 rather
than Nexus. If you want to install that, you'll have to edit the apt
sources.list and add the Bullseye repo. For Kodi 20, the best option in my opinion would be switching to another OS. Debian usually takes a while before making a newer version of a package available.

Bonne chance!
