### ISSUE TITLE
Trying to view video lists gets stuck on "working" (sometimes)

### ISSUE THREAD

**Issue by Tasosgemah** [anxdpanic/plugin.video.youtube#469]
### Context

Please provide any relevant information about your setup

* Add-on Version: **7.0.2~alpha6**
* Kodi Version: **20.1**
* Kodi GUI Language: **English**
* Operating System: **Windows 10**
* Operating System Language: **English**

------

### Current Behavior

Sometimes, when i make a selection to view a list of available videos (any list from my subscriptions, to liked videos, playlists or even pressing "next page" to view more available videos) i get the "working" loading message at bottom right and it stays there, loading for ever. If i try to cancel it, sometimes it takes about a full minute to go back, other times it gets completely stuck so i have to force quit Kodi.

It's completely random, most of the times it doesn't happen. The chances are 1/10 every time i select a list of available videos.

My last log, though i didn't get the bug for a while, not sure if it's there:

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/11377128/kodi.log)

I had this issue in older versions of both Kodi and the Youtube plugin. Though, in the older versions it was more rare.

**Comment by ashleysommer** [comment]
I just encountered this same error tonight. Its the first time I've seen it, but loading a video list (like subscriptions page) simply shows the loading icon for ever.

**Comment by Tasosgemah** [comment]
> I just encountered this same error tonight. Its the first time I've seen it, but loading a video list (like subscriptions page) simply shows the loading icon for ever.

You are lucky. I'm getting this bug at least once every five times i try to load any video list. It's been like this for me for a long time, even with older versions of the plugin, though it was more rare. But in this current version it's the worst it has ever been for me.

**Comment by MoojMidge** [comment]
Duplicate of #280

**Comment by MoojMidge** [comment]
Download latest version of the plugin (follow [these instructions](https://github.com/anxdpanic/plugin.video.youtube/issues/495#issuecomment-1629796150)) and install manually until a new release is pushed out.

**Comment by Tasosgemah** [comment]
> Duplicate of #280

Not really. This is a different issue. I'm not getting an empty list, im not getting a list at all since it gets stuck on "working" before showing any list.

I updated the plugin anyway, following the instructions and, as i expected, the issue is not solved so it should be re-opened.

**Comment by MoojMidge** [comment]
Can you provide a debug log?

**Comment by Tasosgemah** [comment]
> Can you provide a debug log?

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12293907/kodi.log)

I think that was the last one after the issue.

It doesn't happen all the time. It's a chance, about once every five times.

**Comment by MoojMidge** [comment]
That log file doesn't show anything because you have set the loglevel to -1 in your advancedsettings.xml file.

Change it from -1 to 1 and post the log next time you see this happen.

In the meantime try this [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip) and see if it helps with the problem.

**Comment by Tasosgemah** [comment]
I changed the log level but i couldn't recreate the issue this time. It's just luck so the next time it happens i will post it.

I also tried the test version but this only gives me an empty subscriptions videos list.

**Comment by MoojMidge** [comment]
Can you provide a log from the test version? 

The test version adds error handling and a timeout for the network requests, so it won't hang indefinitely.

If it is giving you an empty video list that indicates there is something wrong with your network. The log may provide more information.

**Comment by Tasosgemah** [comment]
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12295928/kodi.log)

Log from the test version

**Comment by Tasosgemah** [comment]
And here's the log from the regular version, after i force closed Kodi because it was stuck in "working" indefinitely: 

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12295961/kodi.log)


Also, when the list does show up it only shows me videos from a single sub, even though i have 100+. That's new to me, it never happened before, something got screwed. Should be in the log as well.

**Comment by ashleysommer** [comment]
Weighing in my experience with this. I've found for me this never happens after a fresh reboot. Watching youtube daily, I experience this bug about once a week, so not very often. So if I start experiencing this bug I simply reboot my device and it works again. For me I think it is a networking bug of some kind, probably not related to the youtube plugin, but while experiencing the issue all my other plugins are still working fine.

**Comment by MoojMidge** [comment]
@Tasosgemah - the test version had a bug in it. Can you download the [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip) again, re-install and get another log? I don't use this functionality myself, so I will need your assistance to test it.

@ashleysommer - I suspect that there is some underlying network issue. The logs provided indicate that the opened session is hanging for some reason. As the session is not being properly closed, this in turn can cause Kodi to hang as well. The test version is an attempt to stop the indefinite hang and make sure that the session is closed properly, but the real problem is what causes the session request to hang/timeout in the first place.

**Comment by Tasosgemah** [comment]
> Weighing in my experience with this. I've found for me this never happens after a fresh reboot. Watching youtube daily, I experience this bug about once a week, so not very often. So if I start experiencing this bug I simply reboot my device and it works again. For me I think it is a networking bug of some kind, probably not related to the youtube plugin, but while experiencing the issue all my other plugins are still working fine.

I reboot my system regularly but the issue comes up often either way, much more often than your case. Also, you don't need to reboot to unstuck it. You can Alt+F4 Kodi and then close it through the Task Manager where it's still stuck. The next time you open it it should be fine (for a while). Or, while the "working" message is stuck, you can press back and wait a bit (you will see the message flicker once). After about a minute it will get unstuck and let you try again (still annoying though), usually the second time it will show the list but it's not impossible to get stuck a second time in a row.


> the test version had a bug in it. Can you download the [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip) again, re-install and get another log? I don't use this functionality myself, so I will need your assistance to test it.

I tried the second test version about 10 times in a row and it didn't get stuck so far. Shows the list properly this time so that bug was also fixed. I use Kodi+Youtube daily so the testing will continue. If it gets stuck again i will report it, if not i will report again in a couple of days to confirm it's fixed for good.

Here's a log of using of the second test version regardless, in case it helps to see some difference.

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12298055/kodi.log)

**Comment by ashleysommer** [comment]
> you can Alt+F4 Kodi and then close it through the Task Manager where it's still stuck. The next time you open it it should be fine (for a while)

My OS is CoreElec on a TV-Box, not a PC. The only way to kill Kodi while it is stuck is reboot the system.

> while the "working" message is stuck, you can press back and wait a bit (you will see the message flicker once). After about a minute it will get unstuck and let you try again (still annoying though), usually the second time it will show the list but it's not impossible to get stuck a second time in a row.

In my case, once it gets stuck, I can press back and after a minute it will go back to the menu, but when I try again it will definitely get stuck again. I once tried 10 times in a row and it got stuck every time. But simply rebooting my device fixes it in less than 60 seconds, so it is a quicker solution.

**Comment by MoojMidge** [comment]
> Here's a log of using of the second test version regardless, in case it helps to see some difference.

None of the logs show what is causing the initial problem. The test version of the plugin should hopefully work to fix the symptoms of the network problem, and that is probably as much as can be done from the plugin side of things.



> My OS is CoreElec on a TV-Box, not a PC. The only way to kill Kodi while it is stuck is reboot the system.

If you can SSH into your box you can restart Kodi using the following command
```systemctl restart kod```

**Comment by Tasosgemah** [comment]
Unfortunately, a new problem has appeared. Now the videos refuse to play with an error message "playback failed, check the error log"

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12307420/kodi.log)

Restarting Kodi doesn't fix this.

**Comment by MoojMidge** [comment]
Pretty sure there is something wrong with your network or firewall that is causing these problems for you. At the very least, in your firewall configuration for Kodi you need to allow internal network connections to your local machine on the port that is setup in `Youtube > Settings > HTTP Server > Port`

Did you change your network setup in any way, install any Windows Updates, or install other programs just before the error started occurring? Can try changing `Youtube > Settings > HTTP Server > Listen on IP` from `0.0.0.0` to `127.0.0.1` or change `Youtube > Settings > HTTP Server > Port` from `50152` to something else e.g. `52152`

**Comment by Tasosgemah** [comment]
No, i didn't change any network settings, nor installed any updates. I'm not well versed in network stuff so i never touch it.

The settings you suggested solved the playback problem (for now). 

Getting stuck on "working" seems to be fixed for good since it hasn't happen for a while.

Edit: I checked my firewall settings and this is how Kodi looks there by searching for it's name

![Untitled](https://github.com/anxdpanic/plugin.video.youtube/assets/12124465/662b68a7-e435-4344-a844-8b07e69d13ce)

Not sure what that means but the green check makes it look like there are no restrictions, no?

**Comment by MoojMidge** [comment]
> The settings you suggested solved the playback problem (for now).

Which setting did you change? The `Listen on IP` or the `Port` setting or both?

Does the same problem occur if you don't use the test version and just use the default settings with v7.0.2~alpha6?

> Not sure what that means but the green check makes it look like there are no restrictions, no?

Appears so, which leaves the possibility that something is else listening on that port.

**Comment by Tasosgemah** [comment]
I changed both settings.

This problem is exclusive to the 2nd test version (the one that solved the infinite "working" problem)

The regular v7.0.2 version (the one you mentioned in the instructions, which is v7.0.2~alpha7) doesn't have the "playback failed" issue. I never had this particular issue before trying the test 2 version actually.

So basically: 

v7.0.2~alpha7 = Has the random stuck "working" issue. Doesn't have the "playback failed" issue with default HTTP settings.

Test 2 version = Has the "playback failed" issue with default HTTP settings. Doesn't have the stuck "working" issue.

**Comment by MoojMidge** [comment]
Hmm OK, I'll have to see if there is something else I changed that would cause this then.

In the meantime if changing the HTTP Server settings make it work, just stick with that.

**Comment by MoojMidge** [comment]
There was another bug in the test version - it is binding to any network interface by default but I removed the check to make sure requests are made to the loopback address by default.

You can re-download the [test version](https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip) which fixes this.

**Comment by Tasosgemah** [comment]
This fixes the HTTP defaults issue, yes?

Ok, i installed the new test version (let's call it test 3) and reverted the HTTP settings to the default values, to see if i will get the playback failed issue. But so far the videos play nicely. Though test 2 also played them with the default values for a night so i need to test further. But so far so good.

I will report here in a day or two to confirm it's working OK. Or earlier than that if a bug occurs.

Thank you for all the support so far btw.

**Comment by MoojMidge** [comment]
All good.

Yes, the latest changes to the test version is specifically intended to fix the bug with the wrong HTTP server listen IP being used. It includes all the previous fixes as well, so hopefully this should fully resolve the problem.

**Comment by malversoft** [comment]
Just a side note, in case it helps someone.

Months ago I suffered the exact symptoms described in the first messages of this issue. When a video list was shown, sometimes (apparently random) the interface got stuck, the ”working” icon showed forever, I had to unhang Kodi every time, and nothing related ever appeared in the log.

After tons of tests, the issue revealed that the Confluence skin did not handle properly some UTF-8 glyphs not well masked by Kodi. So when someone published a Youtube video with emojis in the title, my Kodi hanged just trying to list it.

If you are not using it, try Estuary skin to test if the problem persists. If the problem disappears... voilà, it was a skin problem. Update Kodi and it is gone.

The ”bad” news is that this problem should not be happening in your case, because this issue was solved with the Kodi 20.1 update, that you already have installed. But someone who uses Kodi 20.0 or less and a Confluence-based skin could come here when reading the issue title, so I leave my two cents here for that possibility.

**Comment by MoojMidge** [comment]
@malversoft - that is a different issue that has already been fixed in Kodi

**Comment by malversoft** [comment]
> @malversoft - that is a different issue that has already been fixed in Kodi

I know, please read the last part of my message. I just informed about it because the description and symptoms of that issue were exactly the same, so someone still using Kodi 20.0 or less could easily end here seeking for a solution to that one.

**Comment by MoojMidge** [comment]
I understand and appreciate the intent to help, but the issue described here (as well as for other similar network related issues in this repository), does not have the same symptoms as the unicode handling bug, even if they may seem similar. Alluding that this may be a skin issue due an unrelated bug is just as likely to mislead someone as it is to point them in the right direction.

In general the best bet for anyone who thinks they have the same problem as an already reported issue (or a previously unreported issue for that matter), is to provide a debug log, so that the problem can be better understood.

**Comment by Tasosgemah** [comment]
I think test 3 version is good.

Sometimes it takes a while to show the videos (around 30-40 seconds at most). But it does show the list in the end.

One time it showed an empty list. But when i pressed back and tried again, it showed the videos.

It never got stuck though these last few days so this particular issue can be closed i think.

**Comment by MoojMidge** [comment]
There are seemingly not many people with this exact issue, so I don't know if it is something specific to your installation or something from Youtube that has just not rolled out to a wider user group yet.

If you do see some unexpected behaviour (an empty list or something taking a long time to display) submitting debug logs will be helpful.

**Comment by MoojMidge** [comment]
Closed by #506
