### ISSUE TITLE
No subtitles working and no subtitle prompt even after enabling it

### ISSUE THREAD

**Issue by DevilBlackDeath** [anxdpanic/plugin.video.youtube#471]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2 beta 6
* Kodi Version: 20.1
* Kodi GUI Language: English
* Operating System: LibreElec 11.0.1
* Operating System Language: English

------

### Expected Behavior

After setting up subtitles properly, starting a video should prompt me with choosing the subtitles then quality (if the option for quality prompt is also enabled).

------

### Current Behavior

As it stands, starting a video prompts me with quality but I'm never prompted for the subtitles. I've tried setting up subtitles again with the "Prompt" option and I've tried both "Yes" and "No" when asked if they should be downloaded before the video starts. After setting upthe subtitles I'm not brought back to the plugin's setttings (could very well be the intended behaviour but I'd rather be accurate). I tried completely uninstalling and removing the plugin's configuration, then putting back my API informations in, but it still doesn't prompt me with a choice for subtitles. I tried using "en" or "en with fallback" but I don't get subtitles either from most videos that should have proper non-autogenerated English subtitles.

------

### Steps to Reproduce

There isn't really any steps besides enabling subtitles in the settings. My first attempt was after updating from my older libreelec (version 10) to 11.0.1 and as such upgrading the Youtube plugin from 6.8 to the current beta but I've now also tried with a clean and fresh plugin.

------

### Log

I'm not sure which log I should provide for this particular issue, beyond enabling debug, should I enable other specific log options ?

------

### Additional Information

It only happened after switching to LibreElec (which I did to avoid the "content not available on this app" issue) but since older versions, including the 7.0.1 don't work, I have no way to try whether an older version of the plugin on the LibreElec 11.0.1 would have the same issue.

------

**Comment by simpledork47** [comment]
For me to have working subtitle

tested with latest [7.0.2.alpha7.zip]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/7.x.x-dev

I had to use an alternate client, (namely # 1) 
* Settings, Advanced, Use Alternate client details: Alternate # 1
* Support alternative player    (ticked)

Default: no subtitle, and alternate # 2 hang after few seconds

**Comment by DevilBlackDeath** [comment]
Okay I'll try that and report back ! Were you able to get the prompt back after switching to said client ?

**Comment by simpledork47** [comment]
Prompt is fine, that's I'd prefer
settings,configure subtitles, prompt, download yes

curiously with alternate # 2 (which unfortunately hang after few seconds), It displayed a huge list of autotranslated sub
whereas with alternate # 1, only english

**Comment by jmbreuer** [comment]
I have the same issue.

> I had to use an alternate client, (namely # 1)

Thank you for sharing this workaround!

**Comment by DevilBlackDeath** [comment]
Finally got around to testing your workaround @simpledork47 ! And it worked. I didn't find a way to "pick" an alternate client. I just had the option for "alternate client" and it didn't add or enable any menu to pick a # 1 or a # 2 but it worked perfectly nonetheless :)

I'm leaving that open in case subtitles are supposed to work with the base client, I'll leave it up to the devs to decide whether the issue should be closed or not !

**Comment by xma** [comment]
@DevilBlackDeath it's alpha7 that have a list ( alternate # 1 and # 2 ). You didn't updated it, right ?

**Comment by MoojMidge** [comment]
Update to the latest release [v7.0.2.2](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.2.2) 

Alternative client selection should not be required any more. Stick with the default as that will work better.

**Comment by karlo2105** [comment]
Youtube Addon 7.0.2 branch breaks subtitles loading. I had to block auto update and to revert back to 7.0.1 in order to fix it.
