### ISSUE TITLE
ModuleNotFoundError: No module named 'infotagger'

### ISSUE THREAD

**Issue by nickrbogdanov** [anxdpanic/plugin.video.youtube#479]
### Context

Please provide any relevant information about your setup

* Add-on Version: May 5th master branch, commit 920a85b7d29631f508654b7f657624486f60fa4a
* Kodi Version: 20.1-Nexus (built locally from source)
* Kodi GUI Language: US/English
* Operating System: Ubuntu 22.04.1 LTS on x86_64
* Operating System Language: US/English

Since the latest released version of this add-on (v7.0.1) errors out with "content not available" on every video, I'm trying to run the git master branch by cloning the repo into `~/.kodi/add-ons`.  This yields the following error:

```
2023-05-08 23:11:29.944 T:274526   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'infotagger'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 11, in <module>
                                                       from youtube_plugin.kodion import service
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 21, in <module>
                                                       from .impl import Context
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/__init__.py", line 12, in <module>
                                                       from .xbmc.xbmc_context import XbmcContext as Context
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context.py", line 29, in <module>
                                                       from .xbmc_playlist import XbmcPlaylist
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_playlist.py", line 15, in <module>
                                                       from . import xbmc_items
                                                     File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py", line 13, in <module>
                                                       from infotagger.listitem import ListItemInfoTag
                                                   ModuleNotFoundError: No module named 'infotagger'
                                                   -->End of Python script error report<--
```

I don't understand how this "infotagger" dependency from @jurialmunkey is supposed to get installed.  If I search for it in the add-ons GUI, it does not show up.  It doesn't exist in the Kodi source tree either.  If I manually `git clone https://github.com/jurialmunkey/script.module.infotagger` in my `~/.kodi/add-ons` directory alongside the YouTube plugin and my other add-ons, it has no apparent effect.

The [home page](https://kodi.tv/addons/nexus/script.module.infotagger/) says "To download this Add-On, we highly recommend you do it via the user interface in Kodi. Simply look for the "Get More" button in the Add-Ons menu".  This button does not exist.

The only thing that worked for me was to manually copy `infotagger/listitem.py` under `~/.kodi/addons/plugin.video.youtube/resources/lib/infotagger`.  So I would suggest either:

1. Bundle infotagger with this add-on (I can send a PR if needed), or
2. Provide instructions on how to install it by hand
3. Drop backward compatibility (since the plugin only runs on Nexus anyway per #445 ) and call the new APIs directly

**Comment by crwolff** [comment]
Cloning an addon repo doesn't install any dependencies, and I'm not aware of any method to fixup missing dependencies after the fact.

You need to install the repo from a repository or from a zip first: [YouTube](https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.1/plugin.video.youtube-7.0.1.zip) This will install all the dependencies required.

You can then delete (or rename) the plugin.video.youtube directory and clone into the same location.

**Comment by nickrbogdanov** [comment]
Doesn't that mean Kodi will eventually overwrite whatever local changes I make?

What I don't understand is: why can't I manually install the dependency by cloning it to the add-ons folder or by following the instructions on its homepage?

**Comment by jurialmunkey** [comment]
> Why can't I manually install the dependency by cloning it to the add-ons folder

Add-ons that are not installed via Kodi's AddonBrowser are disabled by default as a security measure. If you clone/unzip/copy directly into the addons folder you must also manually enable the add-on in AddonBrowser. 

AddonBrowser does not display modules to install via browsing the repository. Modules generally are only available to install as a dependency of another addon.

You can manually install a dependency for an addon by going to its info page in Kodi's Addon Browser, clicking "Dependencies" and then clicking the dependency you wish to install.

> Doesn't that mean Kodi will eventually overwrite whatever local changes I make?

Go to the Youtube addon infopage in AddonBrowser and uncheck the "Auto-update" button.
If you install via zip, auto-update should be disabled by default because Kodi tracks the installation source.

**Comment by nickrbogdanov** [comment]
> Add-ons that are not installed via Kodi's AddonBrowser are disabled by default as a security measure. If you clone/unzip/copy directly into the addons folder you must also manually enable the add-on in AddonBrowser.

> AddonBrowser does not display modules to install via browsing the repository. Modules generally are only available to install as a dependency of another addon.

I suspect the special treatment of module add-ons is the root cause of the problem.  Kodi did prompt me to enable the manually-installed YouTube plugin, but it never prompted me to enable InfoTagger.  It's unfortunate that the UI just hides these add-ons rather than providing guidance on how to enable them.

I was able to install InfoTagger by pointing Kodi to the released zip file.  Maybe it would help if the InfoTagger homepage suggested this method, for situations where users need to install it by hand?

**Comment by kasi45** [comment]
For such cases I have the following two functions in my projects

```
def enableAddon(ADDONID):
    struktur = json.loads(xbmc.executeJSONRPC('{"jsonrpc":"2.0","method":"Addons.GetAddonDetails","id":1,"params": {"addonid":"%s", "properties": ["enabled"]}}' % ADDONID))
    if 'error' in struktur or struktur["result"]["addon"]["enabled"] != True:
        count = 0
        while True:
            if count == 5: break
            count += 1
            xbmc.executebuiltin('EnableAddon(%s)' % (ADDONID))
            xbmc.executebuiltin('SendClick(11)')
            xbmc.executeJSONRPC('{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","id":1,"params":{"addonid":"%s", "enabled":true}}' % ADDONID)
            xbmc.sleep(500)
            try:
                struktur = json.loads(xbmc.executeJSONRPC('{"jsonrpc":"2.0","method":"Addons.GetAddonDetails","id":1,"params": {"addonid":"%s", "properties": ["enabled"]}}' % ADDONID))
                if struktur["result"]["addon"]["enabled"] == True: break
            except:
                pass

def checkDependence(ADDONID):
    if isdebug: xbmc.log(__name__ + ' - %s - checkDependence ' % ADDONID, xbmc.LOGINFO)
    try:
        addon_xml = os.path.join(ADDON_PATH % ADDONID, 'addon.xml')
        with open(addon_xml, 'rb') as f:
            xml = f.read()
        pattern = '(import.*?addon[^/]+)'
        allDependence = re.findall(pattern, str(xml))
        #if isdebug: log_utils.log(__name__ + '%s - allDependence ' % str(allDependence), log_utils.LOGINFO)
        for i in allDependence:
            try:
                if 'optional' in i or 'xbmc.python' in i: continue
                pattern = 'import.*?"([^"]+)'
                IDdoADDON = re.search(pattern, i).group(1)
                if os.path.exists(ADDON_PATH % IDdoADDON) == True and Addon.getSetting('update.enforceUpdate') != 'true':
                    enableAddon(IDdoADDON)
                else:
                    xbmc.executebuiltin('InstallAddon(%s)' % (IDdoADDON))
                    xbmc.executebuiltin('SendClick(11)')
                    enableAddon(IDdoADDON)
            except:
                pass
    except Exception as e:
        xbmc.log(__name__ + '  %s - Exception ' % e, xbmc.LOGERROR)
```
