### ISSUE TITLE
Api key creation, documents -> video link has been removed by youtube.

### ISSUE THREAD

**Issue by DrStein99** [anxdpanic/plugin.video.youtube#483]
On this github page:

[https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys](url)

to click "[https://www.youtube.com/watch?v=4iFaY8IpTeI](url)" (Add-on API Configuration)

Links to youtube, where disclaims "video link has been removed by youtube".

-----
I can't understand the procedure, if it is a youtube video that is removed, by youtube.  Is there written procedures - somewhere that youtube can not delete ?  Please advise.

**Comment by user3287** [comment]
Yes, I also tried to do it without the guide, but I couldn't get it to work :c

**Comment by user3287** [comment]
Also, this is a duplication of https://github.com/anxdpanic/plugin.video.youtube/issues/439
where it is also described how to do it.

**Comment by mrgsi** [comment]
Not sure if the process has changed, but I have this great video saved from when I did it. https://youtu.be/dJ1oX9-zyhM

**Comment by tetsuosoft** [comment]
> Not sure if the process has changed, but I have this great video saved from when I did it. https://youtu.be/dJ1oX9-zyhM

yes this video is still accurate... thanks for the find!
