### ISSUE TITLE
Get Random Videos from You Tube Playlist

### ISSUE THREAD

**Issue by OzDrDj** [anxdpanic/plugin.video.youtube#485]
Adding a youtube channel to a playlist in Pseudo TV Live will give the same videos every day at roughly the same time. When you look at a channel like Fail Army with a playlist of a thousand plus videos Adding the channel you will only ever see the first 20 or so videos. 
If you could include a switch to randomize the videos, then everytime Pseudo adds a channel it could be a truly different channel everyday.
I hope this is possible and i think it would be a great feature.
Thanks

**Comment by MoojMidge** [comment]
Is it possible to do this on the Youtube website or app? If not it is unlikely this can be easily implemented in this plugin.

The plugin can shuffle an existing Youtube playlist, after it is loaded and when it is being played in Kodi as an internal Kodi playlist, but it doesn't create/store this internal Kodi playlist as an externally accessible playlist or directory listing that could be used by something like Pseudo TV Live.

Even if it did, it doesn't seem like it would be a good idea to do this continuously everytime you wanted to access a random Youtube video.
