### ISSUE TITLE
My subscriptions and Subscriptions not working since Youtube website redesign (empty list)

### ISSUE THREAD

**Issue by captzapo** [anxdpanic/plugin.video.youtube#49]
### Context

* Add-on Version: 6.8.7
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LibreELEC 9.2.6 (Intel CPU)
* Operating System Language: English

------

### Expected Behavior

Obtain a list of newly available videos posted on channels the signed in user is subscribed to.

------

### Current Behavior

No results are shown when accessing those sections within Kodi. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Launch the youtube plugin
2. Make sure user is logged in (using codes at https://google.com/device)
3. Browse to the My subscriptions or Subscriptions sections.

------

### Additional Information

Subscription list is working correctly (list available videos) on the Youtube website when logged with the same user.

------

**Comment by anxdpanic** [comment]
These work just fine, just double checked. Use settings - maintenance - clear caches
If that doesn't resolve the issue provide a complete debug log

**Comment by captzapo** [comment]
I did clear the caches, will provide debug log shortly.

**Comment by captzapo** [comment]
[log-2020-11-14-05.15.19.zip](https://github.com/anxdpanic/plugin.video.youtube/files/5540233/log-2020-11-14-05.15.19.zip)

**Comment by captzapo** [comment]
Thank you for the quick response, please let me know if you require anything else

**Comment by captzapo** [comment]
Source of this issue was clearly explained by anxdpanic in another thread:

_This has been expected for quite a while. My Subscriptions, Saved Playlists, and Purchases all use the API that was provided by the leanback interface (https://www.youtube.com/tv), which was discontinued October of last year iirc.

The return values for this API have changed, and don't provide the necessary information anymore. Since it is undocumented, discontinued, and no longer accessible from a public interface; it is unlikely I'll be able to resolve this. Will look into it further._

Closing this issue, hoping a workaround can be found in a near future.

Thank you for all individuals involved for their time and their willingness to share expertise.

**Comment by anxdpanic** [comment]
It's not the fastest, but it works for now. https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by durango99** [comment]
> It's not the fastest, but it works for now. https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

You are right on both parts - not the fastest but it works for now.  Thanks for the workaround.  I installed the plugin.video.youtube-6.8.9.beta1.zip and it's working well enough and that's what counts :)  Thanks!

**Comment by kiorky** [comment]
What should be working (back) with this beta ?

I tried but saved playlists aren't back there.

 ( I don't want to spam as i saw there were numerous threads in there. )

**Comment by anxdpanic** [comment]
Saved Playlists, and Purchases are currently lost due to the changes
