### ISSUE TITLE
YouTube addon for firestick Max etc

### ISSUE THREAD

**Issue by Greg0580** [anxdpanic/plugin.video.youtube#490]
### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.

Is it possible when using A Firestick Max or similar.  That you can add my own api keys.  At the moment when I try to add my own api keys and press OK and wait for a few seconds and go back they have disappeared.  
If I use the YouTube Addon from one of the other repos /addons i can change the api keys and press OK and they are still there. And I can sign in and works fine. 
Plus you add to history like if you watch part of video you can go to history later and keep watching it Like in the Github smart tube next. In it history.  At this time if want to continue watching a video I have to either watch the video from the beginning or go to smart tube next and carry on watching it from there. 
Thank you. If all possible. Thank you for a good addon . 👍

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

------

**Comment by anxdpanic** [comment]
If you're still having an issue with this on the latest versions, re-open the issue with a debug log showing reproduction of the issue.
