### ISSUE TITLE
Recommendations folder not showing up

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#491]
Recommendations folder not showing up.

* Add-on Version: 7.0.1
* Kodi Version:  20.1
* Kodi GUI Language: Polish
* Operating System: LibreELEC 11.0.1
* Operating System Language: Polish

**Comment by OliPassey** [comment]
Same here on PC & Android TV.
Can provide a debug log if helpful

**Comment by wyup** [comment]
Sorry for asking, but is it supposed to be a "Recommendations Folder"?. Never saw it on Android and RPi4 LibreElec.
I wish there was, though.

**Comment by MoojMidge** [comment]
I don't use this functionality, but I think you need to follow these steps in order to make it work:
https://github.com/anxdpanic/plugin.video.youtube/issues/68#issuecomment-746786208

**Comment by drelephant** [comment]
I have done that and Recommendations is still empty.

Using plugin 7.0.2.2 Unofficial on Matrix.

**Comment by MoojMidge** [comment]
If the Recommendations folder is visible, but empty, then it is likely due to this: https://github.com/anxdpanic/plugin.video.youtube/issues/508 - Youtube have removed this functionality from their API and it is a work in progress to implement something similar as an alternative.
