### ISSUE TITLE
API and quota exceeded

### ISSUE THREAD

**Issue by econo202** [anxdpanic/plugin.video.youtube#50]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.7
* Kodi Version: 18.9
* Kodi GUI Language: English
* Operating System: LIBREELEC
* Operating System Language: EN

------

### Expected Behavior

Search function should work normally.

------

### Current Behavior

Despite having working personal Youtube API keys when selecting "search" from the addon the message "The request cannot be completed because you have exceeded your quota." is displayed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Configure YT API key @ https://console.developers.google.com
2. Paste API details in the addon
3. Open the addon and select "search"
4. The message "The request cannot be completed because you have exceeded your quota." will be displayed and search wont happen.

------

### Additional info

Seems to be related to [this issue](https://github.com/jdf76/plugin.video.youtube/issues/856) reported earlier.

**Comment by mifrey00** [comment]
I have got the same issue some days ago.  Note sure what the problem really was but i finally had to recreate a Google project and an API key.

**Comment by kalika303** [comment]
Same issue here. API keys correctly configured and still getting the quota exceed exception. Are there other information I can gather to help sort the issue out?

**Comment by rednaz1337** [comment]
I have the same Issue.

**Comment by HugoPoi** [comment]
I had the same issue re-creating a project was workaround but I notice the API quota is fixed to 0 in the google dev console and I can't edit it very weird.

**Comment by vtolstov** [comment]
Any chance to get addon working?

**Comment by HugoPoi** [comment]
@vtolstov It's a quota issue on the Google side, I think they change something about the quota on very old project created on the dev console. Re-creating a new project and new auth keys solve the issue.

**Comment by vtolstov** [comment]
Thanks, I'm try to see how it works after recreating project.

**Comment by Atomisirsi** [comment]
I had the same issues with an API key that stopped working. After recreating the Google API project, this problem is gone. Thanks for the hint to @HugoPoi!
