### ISSUE TITLE
make links with timestamp work

### ISSUE THREAD

**Issue by unicornsandcandies** [anxdpanic/plugin.video.youtube#502]
I have a YouTube client that lets me share video with a timestamp. Unfortunately even with a timestamp link youtube on Kodi plays video from the beginning. Could this be a feature to play from a timestamp? It would make switching from watching on phone to kodi much easier.

That's how the link looks like for me:
https://youtu.be/y-cJuCMzpdA?t=18m47s

Proof that it's working:
![Screenshot_20230808-191307](https://github.com/anxdpanic/plugin.video.youtube/assets/112720004/08b6d3df-78fb-4c12-b58c-6af6aa41c452)

**Comment by MoojMidge** [comment]
How are you casting to Kodi? Can you get a debug log from when you cast a video with a timestamp and it plays from the start in Kodi?

**Comment by unicornsandcandies** [comment]
> How are you casting to Kodi? Can you get a debug log from when you cast a video with a timestamp and it plays from the start in Kodi?

I use revenced or newpipe sometimes. Here's log. Both from playing with yatse and kore.

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/12326167/kodi.log)

**Comment by MoojMidge** [comment]
Thanks, I'll see what I can do after I get a new alpha release available for testing.
