### ISSUE TITLE
Unable to update or install Kodi plugin

### ISSUE THREAD

**Issue by graysky2** [anxdpanic/plugin.video.youtube#504]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.25+matrix.1
* Kodi Version: latest git from Nexus branch
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

I am unable to update this plugin due to inputstream.adaptive being not available from the official repos.

------

### Current Behavior

What is the current behavior?

Upon trying to update this plugin, Kodi shows:

```
inputstream.adaptive
Not available
```

I get the same if I try installing this plugin from the official repos in a fresh kodi profile.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to install youtube plugin

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[Link](https://gist.github.com/graysky2/467724af9e82efba4f4097b4cd42f457) to debug log

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Isn't this expected? InputStream.Adaptive is a dependency for this plugin and you have to install the InputStream.Adaptive package for your distribution.

This is normally handled automatically for supported platforms and distribution, which Arch Linux is not, so you have to install the package yourself using the Arch Linux package manager or build it yourself.

**Comment by graysky2** [comment]
You are right... I was thinking that the plugin was supplied from the kodi repo, not the distro repo.  Installing it from the distro repo was the key.  Thank you.

```
% pacman -Ss inputstr
extra/kodi-addon-inputstream-adaptive 20.3.9-2 (kodi-addons kodi-addons-inputstream)
    InputStream client for adaptive streams for Kodi 18+
extra/kodi-addon-inputstream-rtmp 20.3.0-6 (kodi-addons kodi-addons-inputstream)
    RTMP input stream add-on for Kodi
```
