### ISSUE TITLE
[401] Invalid_client Client Id is incorrect

### ISSUE THREAD

**Issue by frmariam** [anxdpanic/plugin.video.youtube#512]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.29 
* Kodi GUI Language: EN
* Operating System: Android TV 9
* Operating System Language: EN

same as issue #259
followed a tutorial on how to get keys, type is set to "'TV and limited input device"
I followed this tut to generate the keys: https://www.firestickhow.com/youtube-api-key.html

and I used your method 3:
https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys

No matter what small changes I trid, whenever I try do Sign In in Kodi, after input the code given by Kodi in google.com/device , I get an error claiming my client ID is incorrect (but since I'm using method 3, I now it's not a typo).

------

### Expected Behavior
Would login into Youtube

------

### Current Behavior
Cannot login (nor do searches)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Youtube plugin in Kodi and exit kodi (via exit funtion in app)
2. Create the API keys following https://www.firestickhow.com/youtube-api-key.html
3. Use method 3: https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys (used X-Plore file browser to move it to folder Android/data/org.xbmc.kodi/files/.kodi/userdata/ )
4. Start Kodi and open Youtube Plugin
5. Proceed to login
6. Input generated code you your laptop browser
7. Kodi will give a message stating client Id is incorrect

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by royal-crisis** [comment]
I added my email under test users seemed to fix this issue

**Comment by frmariam** [comment]
that did the trick.
I could swear I tried it before posting (both with it published and not published)...
thank you!

**Comment by evlo** [comment]
So to sing in I still need to go to addon settings, api and pu in the keys etc.?

**Comment by MoojMidge** [comment]
Yes, you are in effect giving permission to this plugin to access and modify your Youtube account, and the plugin must have this access enabled and be able to be identified to Google, so that your login credentials can be authenticated for this third party access.
