### ISSUE TITLE
 501 - Server does not support this operation.

### ISSUE THREAD

**Issue by unvency** [anxdpanic/plugin.video.youtube#514]
Hi,

my addon works. But I thought I could also use the contents of this plugin in the browser via the activated HTTP server as a server folder structure.
Is that the case or am I misunderstanding that? What is the purpose of the HTTP server?

I am equipped with the latest Kodi_version and YouTube plugin version and have tested with GUI on both Linux and Windows.

**Comment by MoojMidge** [comment]
The HTTP server is very limited in functionality and mainly functions as a proxy, used for making, modifying and serving video manifest and license requests used for the playing of video streams.

The only end user functionality it offers is to provide a means of inputting API keys via a web interface.

It is not capable of serving any videos/playlists/channels or associated listings.
