### ISSUE TITLE
"Mount YouTube to a disk"

### ISSUE THREAD

**Issue by unvency** [anxdpanic/plugin.video.youtube#515]
Hi there,

If the addon could not only display the YouTube structures in the tool but also visualize them as a disk, it would be much easier to add YouTube videos to your media library.

What I imagine (e.g. under Windows): in the plugin settings you can activate "Mount as drive" and determine that all menu items of the YouTube plugin (with the exception of the search, because that would be difficult to implement in a file system) can be reached also under the drive letter Y:\ (freely selectable).

Example: Video in "My Channel" would then be available in "Y:\My Channel\test.mp4", e.g. also through VLC. Then you could easily integrate YouTube into applications like Jellyfin, Emby and Plex. Because no one can match the wealth of Kodi's YouTube plugin!

Another related feature request would be to be able to sort the videos into subfolders. By this I mean that if the above video "test.mp4" were from 2018, for example, I could create a folder "2018" in Windows and move the video "test.mp4" into it so that it would be available under "Y:\My Channel\2018\test.mp4" . In order to save the folder structure in YouTube, the plugin could either save the folder in the respective video description or as a tag - for example in encrypted form. However, it would make sense to save the folder structure directly on YouTube so that the folder structure is stored centrally and does not have to be transferred from the old device to the new one in cases you want/need to change the hosting device.

**Comment by MoojMidge** [comment]
This plugin cannot function independently of Kodi itself, and is probably not the right tool to try and achieve what you are describing.

It creates a virtual filesystem that is only used within Kodi and is not persistent in any useful way, nor accessible outside of Kodi.

While there are ways to integrate the plugin content into the Kodi library, I have no experience with this, and it would still require that Kodi provide the functionality to act as a media server to provide this library to other clients.

Kodi currently only provides limited media server functionality via UPNP and various web interfaces, and I don't believe it is an intended use case for Kodi to act as a source for other actual media servers. Kodi is primarily a client only.
