### ISSUE TITLE
v7.0.2.1 playback freezes on long >40-45 min videos

### ISSUE THREAD

**Issue by Asxetos21** [anxdpanic/plugin.video.youtube#521]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.2.1
* Kodi Version: v20.2
* Kodi GUI Language: Greek
* Operating System: CoreElec 20.2
* Operating System Language: English

------

### Expected Behavior

Play the hole video no matter the length

------

### Current Behavior

On longer videos >40-45 min, playback just freezes on the 40-45 min mark. Pause and resume does not help. Stopping the frozen playback causes Kodi to crash and restart.
After reverting youtube plugin back to v7.0.2.alpha7, behavior is back to normal.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Try to play any video >40 min.
2. 
3. 

------

### Log

Sorry, no debug log

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> Sorry, no debug log

No useful help can be provided in this instance without a debug log
