### ISSUE TITLE
Copy URL of a video for workaround?

### ISSUE THREAD

**Issue by admansymphonyck** [anxdpanic/plugin.video.youtube#522]
Hi! 
I don’t know if it’s just for me, but there are some restricted videos that just don’t work.

So it would be nice to have the option to copy the video URL to reuse it in another app.
Even if the plugin breaks at some point, it would also be a temporary fast option...

You could download the video in yt-dlp or play it in another application, e.g. mpc-hc+yt-dlp.
Obviously it would be better to call these apps with a command, anyway copying the url is good.

**Comment by MoojMidge** [comment]
> I don’t know if it’s just for me, but there are some restricted videos that just don’t work.

If you are logged in, all public videos that are capable of being played, should be able to be played by the plugin. If something is not working, provide some details (i.e. video link and log) and then it can be looked into.

> So it would be nice to have the option to copy the video URL to reuse it in another app.

I haven't really looked into it, but I don't think there is any cross platform way to copy text into the system clipboard through Kodi.

> Obviously it would be better to call these apps with a command

Pretty sure the plugin already supports this if you enable `Settings > Advanced > Support alternative player` and actually have an external player setup in Kodi.

I've never done this myself, but the Kodi wiki may provide some info on what is required: https://kodi.wiki/view/External_players
