### ISSUE TITLE
"The following content is not available on this app."

### ISSUE THREAD

**Issue by TheNetworkIsDown** [anxdpanic/plugin.video.youtube#523]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.2
* Kodi GUI Language: en
* Operating System: Libreelec
* Operating System Language: en

------

### Expected Behavior

Upon using Yatse app on my mobile phone with "Play on Media Center" the video should start playing in Kodi.

------

### Current Behavior

"The following content is not available on this app."

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  "Play on Media Center" using Yatse
2.  "The following content is not available on this app."
3. 

------

### Log

https://paste.kodi.tv/ezojuxitiv.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Duplicate of https://github.com/anxdpanic/plugin.video.youtube/issues/442

You need to update the addon: https://github.com/anxdpanic/plugin.video.youtube/releases/latest

**Comment by snex** [comment]
I am getting this issue on 7.0.4+nexus.1 for all videos.

**Comment by Nikolai-L** [comment]
Same here, Kodi 20, Windows 10

**Comment by xyzfre** [comment]
Update to this version and it fixes the issue https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.5+beta.2/plugin.video.youtube-7.0.5+beta.2.zip
