### ISSUE TITLE
Provide setting for default-viewmode

### ISSUE THREAD

**Issue by maxberghammer** [anxdpanic/plugin.video.youtube#526]
### What Problem Does This Solve? 

At the moment, the default-viewmode seems to be "WideList" when browsing youtube-media. Even if I have the ability to set the viewmode to "InfoWall" (Which my preferred viewmode is), I have to do this for every single page. Kodi remembers this setting in ViewModesX.db, but as the whole path of the viewed page is being stored there and this path contains the page-token, these stored settings are useless, if the token changes, which happens from time to time.

Example:
`plugin://plugin.video.youtube/channel/UClDnGiwSyTyu7gxO8X5U18g/?page=2&page_token=EAAaIVBUOkNESWlFRUV4T0RnNVFqSTJRelF6TlVORk5VVW9BUQ`

So if my token changes, Kodi won't find the entry in ViewModesX.db and displays as WideList.

------

### Suggest a Solution (optional)

Please provide a setting, where we can set the default-viewmode for the addon globally.

------

**Comment by anxdpanic** [comment]
You want to download and install the 'unofficial' version from the releases. This feature is not allow in the Kodi official repository, therefore can't be in the main release, but is available in the unofficial release.
