### ISSUE TITLE
Can't play videos - error probing input format

### ISSUE THREAD

**Issue by GTP95** [anxdpanic/plugin.video.youtube#528]
### Context

Please provide any relevant information about your setup

* Add-on Version:  6.8.25+matrix.1
* Kodi Version: 19.4
* Kodi GUI Language: English
* Operating System: Dietpi
* Operating System Language: English

------

### Expected Behavior

The videos are played

------

### Current Behavior

Trying to play videos fails with a message informing that one or more items failed to play. Looking in the log, it seems a problem detecting the input format: `2023-10-29 19:24:54.835 T:1375    ERROR <general>: Open - error probing input format, https://www.youtube.com/watch?v=RatbYqc0-jE`

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Just try to play a video

------

### Log

Here's the [debug log](https://paste.kodi.tv/imuqikupen).

------

### Additional Information
Started having problems today while playing a video: the player first stopped and started buffering very slowly, so I closed the video and started it again. Then, while playing, the player just exited a few times, but I was able to resume the video. 

------

**Comment by MoojMidge** [comment]
Update the plugin first:
https://github.com/anxdpanic/plugin.video.youtube/releases/latest

Then make sure to disable `Settings > Advanced > Use Youtube website urls`. Why did you enable this in the first place?

**Comment by GTP95** [comment]
I enabled it as part of my testing to see if I could fix it myself, sorry if I forgot to disable it before collecting the log. I'll try with the update you linked and report back. Thank you.

**Comment by MoojMidge** [comment]
All good, I was asking in order to figure out if you had an external player configured and this stopped working suddenly, or whether something else was going on, because the log shows something different compared to what you described in the Additional Information section.

See how the update goes, it should fix the issue you described.

**Comment by GTP95** [comment]
I tried installing the updated version from the zip archive, but I got a notification saying that the dependency on inputstream.adaptive version 19.0.7 could not be satisfied. What should I do?

**Comment by MoojMidge** [comment]
You need to install inputstream.adaptive

If you don't know how to do that you should seek help from the available DietPi support channels. Something like `sudo apt install kodi-inputstream-adaptive` may work.

**Comment by GTP95** [comment]
I updated the plugin, but unfortunately I'm still getting the same error. Here is the new log: https://paste.kodi.tv/ifowonoyar
The reported plugin version is now 7.0.2.2+matrix.1

**Comment by GTP95** [comment]
Nevermind, I checked the settings and the `Use YouTube URLs` option was still enabled. I disabled it, and now it seems to work. Thank you for your help.

**Comment by MoojMidge** [comment]
Glad you got it working
