### ISSUE TITLE
Frame skipping after long pause or long video

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#533]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2
* Operating System: OSMC

------

### Expected Behavior

Video plays normally after a long period of the video being paused

------

### Current Behavior

Video plays at faster speed/skipping frames after spending a while on pause

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play a video
2. Pause video
3. Keep video on pause for an extended time like an hour or so
4. Play video, it starts skipping frames.

------

### Log

None available

------

### Additional Information

There may be other issues with frame skipping without videos being paused as Ive had to exit and replay on some longer videos but its most noticeable in this circumstance.

------

**Comment by MoojMidge** [comment]
As a general rule the Youtube plugin has nothing to do with actually playing the video, it just gets the video stream details in order for Kodi to play it.

But as for anything, nothing can be determined without a log.

**Comment by MoojMidge** [comment]
You will probably be better served by reporting your issue in the OSMC forums with a log. This doesn't have anything to do with the plugin.

**Comment by ghost** [comment]
Here's a (very long) log of the whole time the video was paused and played again if you want to look

https://zerobin.net/?348c225dfa1b3db3#PwcehjUkeLmO0+i9jsEQCAOwTGDGGiH5xYTS/EXeXoI=

**Comment by ghost** [comment]
> You will probably be better served by reporting your issue in the OSMC forums with a log. This doesn't have anything to do with the plugin.

Please reopen and please don't close until proper testing is asked for and done to make sure its not a youtube only issue. As far as I can tell this only happens in Youtube as I have tried to do the same in other apps like hulu which also use widevine.

**Comment by MoojMidge** [comment]
I get that you don't like hearing this, but to the best of my knowledge this is not an issue with the Youtube plugin. Even if the issue was to be re-opened, I can't help you.

The only advice I have for you is to seek help from the OSMC team on the their forums, following their support request procedure.

**Comment by MoojMidge** [comment]
@Arndorferd - it is a bit of a long shot but can you try to see whether disabling Opus audio in the Youtube plugin improves this for you?

`YouTube Settings > MPEG-DASH > Stream features` and unselect `Enable Opus audio`
