### ISSUE TITLE
Updated to 7.0.2.2 and it segfaults Kodi after installation and all attempts to restart Kodi

### ISSUE THREAD

**Issue by bacon-cheeseburger** [anxdpanic/plugin.video.youtube#535]
* Add-on Version: 7.0.2*
* Kodi Version: 21.0b1-Omega-r64480-git+22a988aad3 (fresh git master from earlier today)
* Kodi GUI Language: English
* Operating System: Debian Linux 64bit

I noticed there was an update available (I do not have auto-updates enabled). I think my previous version was 7.0.2. After the update installed, Kodi segfaulted. When I tried to restart Kodi it just segfaults again. The update basically left Kodi in an unusable state until plugin.video.youtube is removed. I downloaded the zips for 7.0.2.2, 7.0.2.1, 7.0.2.alpha7, and 7.0.1. All of the 7.0.2* versions segfault. Only 7.0.1 installs but then isn't able to play anything and refers me to check the logs which show:

>error <general>: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
>error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/?action=play_video&videoid=kVhi8WAjJeA]

I also tested with a vanilla config dir, same results. I don't know if this is a Kodi problem of addon problem yet. The segfault backtrace is available here: https://paste.kodi.tv/nanuvilagi

**Comment by MoojMidge** [comment]
Please provide a full log, not just a couple of lines, along with the stack trace.

You are probably using an incompatible version or incorrectly compiled of InputStream.Adaptive

InputStream.Adaptive is now a required dependency of the Youtube plugin, which is why 7.0.1 "works" but later versions don't. If you are building Kodi by yourself and installing addons using the zip file, then the dependency management, especially for binary addons like InputStream.Adaptive (that need to be built for the version of Kodi you are using) is up to the user.

**Comment by bacon-cheeseburger** [comment]
I already provided a link for the backtrace but have created a new full log and attached it to this reply. I always build Kodi, along with inputstream.adaptive and vfs.libarchive, from a clean git master clone. The only additional addons I use are youtube, context.trailer, library node editor, and tagoverview. 

Again, this segfault is happening with a completely fresh vanilla config and immediately after the addon gets installed from the official repository via Kodi's gui.

Thank you for looking into this.
[crash.log](https://github.com/anxdpanic/plugin.video.youtube/files/13399256/crash.log)

**Comment by MoojMidge** [comment]
What I meant was a full log was needed in addition to only a stack trace. The crash log works too.

Unfortunately all the log shows is that the usual things that may cause this problem aren't an issue in your case.

If you remove the Youtube plugin are you actually able to open the InputStream.Adaptive settings?

**Comment by bacon-cheeseburger** [comment]
Just tried and yes, I'm able to open the inputstream.adaptive settings no prob. I also changed a setting, OK'ed it, then went back into settings and put it back just to check. No prob there, worked as expected.

**Comment by MoojMidge** [comment]
Hmm well that kind of narrows it down.

Can you start Kodi if you delete these lines?:
https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/settings.xml#L208-L212

The underlying problem appears to be with the version of InputStream.Adaptive that you have built (perhaps you can try rebuilding?) that prevents Kodi from loading it.

Unfortunately this also seems to cause Kodi to crash when it tries to get addon info from an addon instance that can't be created.

Not sure about the correct way to build for Debian, but given the recent build related changes in Kodi, perhaps the method you are using needs to be updated?

**Comment by bacon-cheeseburger** [comment]
Unfortunately removing those lines didn't help. I checked the wiki for updated build instructions but it looks the same as before. I went ahead and compiled kodi + addons on a virgin test box I recently installed. I actually copy & pasted directly from the wiki. Kodi builds fine, addons build fine. Kodi runs fine until I install the youtube addon. I get the exact same behavior. 

Is there anything else you can think of that could be the root cause of this problem? If not, is there another dev we can ping who may have any ideas? I know 7.0.2.2 says it's for Kodi 20.0+ but has anyone else actually tested this against git master recently? I'm assuming yes since 21.0 Omega is at beta1.

**Comment by MoojMidge** [comment]
> Is there anything else you can think of that could be the root cause of this problem?

The Youtube plugin isn't the cause of this problem, it is just triggering the crash in Kodi because InputStream.Adaptive can't be loaded:

```
error : IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
```

The root cause of this is usually a build failure or trying to load the wrong version of the binary addon.

> If not, is there another dev we can ping who may have any ideas?

You can try the xbmc/InputStream.Adaptive repository on Github. Maybe create an issue there and see if they have any other ideas. I believe the current maintainer of Kodi for Debian is also a Team Kodi member.

> but has anyone else actually tested this against git master recently?

I have used it with post Alpha 3 nighties on Windows, but this doesn't mean anything, because I'm pretty sure the problem is with how InputStream.Adaptive is being built.

**Comment by bacon-cheeseburger** [comment]
If the issue is with inputstream.adaptive, it's weird it loads ok, I can go into settings, etc. and only shows a problem once the youtube addon is installed. I wonder if there's any other addons that use it that I can try just to see.

Thank you for looking into this as best you can and pointing me in the next direction to pursue it further. Hopefully it will get sorted sooner rather than later. I'll close this since the root problem seems to be elsewhere.
