### ISSUE TITLE
7.0.2.2 add-on fails to launch

### ISSUE THREAD

**Issue by majikatsb** [anxdpanic/plugin.video.youtube#536]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.2.2 
* Kodi Version: 20.1.0) Git:20.1-Nexus
* Kodi GUI Language: en
* Operating System: LibreELEC (official): 11.0.1
* Operating System Language: en

------

### Expected Behavior

Please describe the behavior you are expecting.

- The add-on launches successfully.

------

### Current Behavior

What is the current behavior?

- The add-on cannot launch.  Instead just saying Youtube add-on error, check the logs.  
- I have some widgets on my homescreen powered by this add-on which also fail to load.
- The add-on settings page *does* load.  However, when choosing certain options in the menu, i.e. `Settings > General > Configure subtitles`, then it crashes.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Attempt to launch the add-on

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
[debuglog.txt](https://github.com/anxdpanic/plugin.video.youtube/files/13406090/debuglog.txt)

------

### Additional Information

Please provide any additional information that may be helpful.

I've been using this add-on successfully on Nexus since initial install.  Then about a week ago, it stopped working.  I believe this coincides with the time of the automatic upgrade of the add-on to 7.0.2.2.  

Debugging Kodi isn't necessarily my strong suit, but I've tried a couple of things which have been unsucessful.  I tried downgrading to the older version of the add-on (I've since gone back to 7.0.2.2).  I've tried using the maintenance features to clear various caches, with no success.  I also tried manually applying the [subtitle selection fix](https://github.com/MoojMidge/plugin.video.youtube/commit/b9296e699ad0cf21c2e69d2afdf777e11b273e8a) just in case it was related because the error message looked similar (although in my case, I can't even launch the add-on, it doesn't crash only on playing a video w/ subtitles)

Let me know if there's any other information which would be useful to have.  This is my first bug/issue report.
------

**Comment by MoojMidge** [comment]
Have you had any unexpected power failures or restarts of your Rasberry Pi?

The plugin is failing to start because for some reason the `access_manager.json` file, normally located at `/storage/.kodi/userdata/addon_data/plugin.video.youtube` is corrupted.

As you can open the settings it is pretty easy to fix this: `Settings > Maintenance > Delete access_manager.json`, but if you were previously logged in, will need to login again afterwards.

Might see if it is possible to add some better error handling using temporary files to try and avoid this kind of thing.

> Let me know if there's any other information which would be useful to have. This is my first bug/issue report.

All good, providing a full log is always the best first step and makes it easy to identify the problem. 👍

**Comment by majikatsb** [comment]
Thanks for the quick reply!

I'm sure I have had a hard restart at some point recently.  Kodi will occasionally fully lockup and as there is no power switch, it's down to unplugging/replugging the box.  Not ideal, but this happens maybe once every few weeks?  So yeah, that could be a cause.

Anyway, unfortunately, trying to delete "access_manager.json" via the settings still results in an error.  I then SSH'd into the box and manually removed the access_manager.json file (saving a copy first), and then tried to launch again and still got an error.  Maybe more of the userdata files are corrupted and need to be removed?

Here's the log from deleting the access_manager via the interface and then attempting to launch the add-on.
http://ix.io/4LXm

Any other recommendations to try?

**Comment by MoojMidge** [comment]
Hmm the log is still complaining about the same thing. Not sure why this would be happening

If you are comfortable accessing your device via SSH you could try the following:
```
systemctl stop kodi
rm /storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json
systemctl start kodi
```
This will stop Kodi before removing the file manually, then restart Kodi.

If the problem still occurs can you upload the copy of the `access_manager.json` file that you made?

**Comment by majikatsb** [comment]
Wooo, yeah that brought it back!

..Well actually, that triggered a Youtube add-on error too, but this was a different one.  However, I'm familiar enough with the logs now that I tracked that issue down to me messing up the subtitle fix mentioned earlier.  *facepalm*   So I restored the original subtitle file, ran the stop, remove and restart commands again, and it worked.

Thanks for your help.

**Comment by MoojMidge** [comment]
Glad you got it sorted.

Will make some changes to try and prevent invalid data being used, in the meantime I am going to re-open this issue as a reminder.
