### ISSUE TITLE
Stream Prioritization Feature for Improved Video Playback on Raspberry Pi 5

### ISSUE THREAD

**Issue by joopdo** [anxdpanic/plugin.video.youtube#539]
### What Problem Does This Solve?

I might have missed a feature already built, happy to learn more. Please hear me out.

On Raspberry Pi 5 (and perhaps other devices), 4k videos at 60fps (2160p60) using the YouTube addon are choppy with framedrops. While 80% of 4k videos without high frame-rate play smoothly, there are high framerate video where the video becomes choppy on RPI5. To get the best pixel for your buck, one would put 4k quality stream, but then, for each high framerate video, manually adjust the video settings to fall back to QHD 1440p60. This manual intervention is inconvenient and interrupts the viewing experience.

### Suggest a Solution (optional)

Proposed Feature: Stream Prioritization Setting

Introduce a new feature that allows users to set stream prioritization conditions in the YouTube addon. This would involve creating a user-configurable condition, such as disabling prioritization for 4k videos at 60fps.
Implementation:

User Preferences Section:
    Add a new section in the addon settings specifically for stream prioritization.

Stream Prioritization Options:
    Provide options for users to customize their stream prioritization preferences. For example:
        Disable prioritization for 4k videos at 60fps.
        Prioritize QHD 1440p60 as the preferred fallback resolution.

**Comment by MoojMidge** [comment]
There are multiple different ways do this manually:

1. disable 2160p60 in the Kodi video whitelist
2. limit the video resolution in the Youtube plugin settings to whatever your device is capable of handling smoothly
3. disable high framerate videos in the Youtube plugin settings
4. enable auto + quality selection in the Youtube plugin setting and then switch the resolution on the fly during playback if your device cannot play something smoothly
5. set the maximum resolution in the InputStream.Adaptive settings to whatever your device is capable of handling smoothly
6. set the maximum bandwidth in the InputStream.Adaptive settings to whatever your device is capable of handling smoothly

Options 1 and 4 are probably the best options, and I can't really see the benefit of adding yet another way to do this, just to make it a little less inconvenient to deal with your device capabilities.

**Comment by joopdo** [comment]
Thank you for the comprehensive response, @MoojMidge!

I've experimented with the recommendations you provided, but unfortunately, I haven't been able to address the 'use case' scenario.

1. I disabled 2160p60 in the whitelist (thanks for pointing out this feature!). Despite its exclusion from the whitelist, plugin.video.youtube still selects 2160p60—possibly due to the 'set as default for all media' setting.
2. Setting 1440p (QHD) as the maximum resolution resolves the issue, ensuring smooth playback (a family-friendly solution). However, this means that a 2160p30 video, which could play smoothly, is not selected.
3. Disabling high framerate videos in the YouTube plugin settings results in a downgrade to 480p video.
4. Enabling the whitelist for 1440p (QHD) is a great workaround, allowing me to choose the desired resolution when necessary.
5 + 6: I'll maintain 4K for other sources, as platforms besides YouTube don't frequently offer 2160p60.

For those interested, I'm testing with this video: [Test Video](https://youtu.be/cU0JrSAyy7o)  (available in 2160p60, 1440p60, 1080p60, 720p60, 480p, 360p, 240p, 144p)

Currently, I can't achieve my desired situation of choosing 2160p30 and skipping 2160p60. However, I'll temporarily fallback to 1440p (QHD). I acknowledge this might be device-specific, and I'm inclined to close the issue based on your suggestions. I'll leave it open for a bit in case others have additional insights.

**Comment by MoojMidge** [comment]
> 1. I disabled 2160p60 in the whitelist (thanks for pointing out this feature!). Despite its exclusion from the whitelist, plugin.video.youtube still selects 2160p60—possibly due to the 'set as default for all media' setting.

This should work the way you wanted, but there seems to be an issue with how InputStream.Adaptive is checking for the window resolution which means it doesn't seem to work reliably.

Given that this otherwise doesn't work the way it should, and it is not too difficult to add this an option that won't interfere with anything else, I am more inclined to add this to the Youtube plugin.

Edit: This won't be a full prioritisation selection as that would be way too complicated, only a single selection to specifically disable high framerate videos at the selected maximum video quality. This would then fall back to the next highest video quality automatically.

**Comment by joopdo** [comment]
Thank you @MoojMidge, let me know if you want me to test something!

**Comment by MoojMidge** [comment]
https://github.com/MoojMidge/plugin.video.youtube/commit/0245cdce0388d7932c159a95c0b7bef3190b87ae contains the option to disable high framerate video at max video quality.

If you know how to cherrypick changes using git, or are able to manually make the changes yourself, you can see if that works for you.

**Comment by joopdo** [comment]
@MoojMidge Finally tried it in V.7.0.3.2 and it works beautifully. Thank you so much!
