### ISSUE TITLE
Unofficial repo doesn't allow to be used on Matrix (repository.yt.unofficial-2.0.5.zip )

### ISSUE THREAD

**Issue by bugsyb** [anxdpanic/plugin.video.youtube#541]
Would you mind please to return back ability to add unofficial repo to Matrix?
There is Matrix version of plugin and would be great to be able to use repo.

Thanks.

**Comment by anxdpanic** [comment]
Will have a look at the repositories hopefully by the end of next week

**Comment by bugsyb** [comment]
Thanks. I'll also look to upgrade to newer version - so the problem might be inexistent for me, though other people will benefit.
Thanks again for great work.

**Comment by anxdpanic** [comment]
https://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/repositories/
Took longer than hoped, but there is a new repo zip for download, it won't auto-update this time.
