### ISSUE TITLE
Youtube plugin fails to load

### ISSUE THREAD

**Issue by lactam** [anxdpanic/plugin.video.youtube#543]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2 Nexus
* Kodi GUI Language: English
* Operating System:  QNAP QTS 5.1.4.2596
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

The add-on launches successfully.

------

### Current Behavior

What is the current behavior?

Add-on fails to launch, says to check the logs.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Attempt to launch add-on.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/13607475/kodi.log)

Please provide any additional information that may be helpful.

I don't know exactly, but it seems this is the culprit: SyntaxError: future feature annotations is not defined

------

**Comment by MoojMidge** [comment]
You are using an outdated and unsupported version of Python - Python v3.6

Not sure on the support situation for Ubuntu 18 on your NAS, but that too is outdated and possibly unsupported.

The `requests` library requires Python v3.7+, and the current supported stable release of Python is Python v3.8

**Comment by lactam** [comment]
Thank you for your quick response.  Indeed, I checked and needed to update Python.  I've now updated it to 3.10, and am now trying to figure out how to get the system to recognize v3.10 before v3.6.

**Comment by MoojMidge** [comment]
Can't really advise you on that as it is not really straightforward.

You can try to update the symlinks that your system uses for Python, but there is a good chance that may cause other packages, that depend on your current Python version, to break. You will also probably need to recompile Kodi for the new Python version.

This doesn't really have much to do with this plugin, and I would suggest seeking help through whatever specific support channels exist for your device/system instead.
