### ISSUE TITLE
Help topic contains dead video link

### ISSUE THREAD

**Issue by WallyZambotti** [anxdpanic/plugin.video.youtube#544]
The help topic on creating Personal API Keys located at : 

https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys

contains a dead video link

https://www.youtube.com/watch?v=4iFaY8IpTeI

------

Please update the topic to provide a link to a live video.

------

**Comment by anxdpanic** [comment]
YouTube pulled it down due to 'Violation' so I will have to look at creating a new one, on a new service in the future.
