### ISSUE TITLE
No history in menu

### ISSUE THREAD

**Issue by VictoriaStudios** [anxdpanic/plugin.video.youtube#547]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: OSMC
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.
On launch, the YT history should be visible and selectable.
Watched videos should be  shown in the youtube history.

------

### Current Behavior

What is the current behavior?
Liked and Disliked Videos as well as recommendations and subscriptions are shown, but **not** history.

Watched videos are not visible to other devices using the same Google Account.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create Google API Key and 0Auth client, publish 0Auth app
2. Enter API data, login using google.com/device
3. Wait for App to load data from Google

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/tinupalibi.kodi

------

### Additional Information

Please provide any additional information that may be helpful.
It is a fresh osmc install on a raspberry pi4. No major updates tweaks, etc. have been done, just the castignait netflix addon and this one.

------

**Comment by naturmensch** [comment]
I got the same issue with a fresh installation of the youtube app and fresh API setup as well on an updated libreelec 11.0.4, running on a RPI4

**Comment by anxdpanic** [comment]
If this is still an issue with the latest versions, please re-open the issue with a new debug log as the old one has expired.
