### ISSUE TITLE
Queuing from current playlist is broken

### ISSUE THREAD

**Issue by timur-davletshin** [anxdpanic/plugin.video.youtube#549]
Libreelec 11.0.4, YouTube addon 7.0.2.2

### Steps to Reproduce

1. Start video playback of some YT video, queue more videos
2. Open playlist of queued videos
3. Select any of them and press Go to NAME_OF_THE_YT_CHANNEL from drop down menu
4. Queue video from that YT channel
5. Check again current playlist of queued videos

Problem: No videos were queued from that YT channel.

**Comment by MoojMidge** [comment]
This is a bug in Kodi IMO.

It is possible to kinda fix this in this plugin, specifically for listings created by this plugin, by changing `Container.Update(blah)` to `ActivateWindow(Videos, blah, return)`, but there are going to be inconsistencies with navigating back through the window history, and possibly other unintended consequences.

The use of `Container.Update` was itself a workaround for other older problems that largely look to have been fixed, so might just change this and see who else complains.

**Comment by timur-davletshin** [comment]
Can you report it to Kodi then? Definitely you will explain it better.

**Comment by MoojMidge** [comment]
Probably won't get to it - have little spare time and different priorities (I very rarely go Channel browsing, and have never done so from the current internal playlist).

Will fix for this plugin and see what other side effects that has.

**Comment by timur-davletshin** [comment]
Thank you in advance. I'll report it later to Kodi myself. Happy holidays!
