### ISSUE TITLE
Set-up wizard of v7.0.3+beta.1

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#557]
Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.3+beta.1
* Kodi Version: 20.3
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

Expected Behavior
Starting of set-up wizard after fresh installation of  v7.0.3+beta.1 in a new installation of Kodi  20.3 Nexus

------

Current Behavior
Error message, Addon don't starting

------

Steps to Reproduce

1.  Fresh Kodi Nexus 20.3 installation
2.  Install YT Add-on Version: v7.0.3+beta.1
------

Log
https://paste.kodi.tv/taqoyenasi.kodi

------

Additional Information

Workaround to fix : Install stable Version v7.0.2.2 at first from repository and then update with v7.0.3+beta.1

**Comment by MoojMidge** [comment]
Thanks for pointing that out, forgot to remove a remnant from the unofficial release.

Fix is to simply delete this line: https://github.com/MoojMidge/plugin.video.youtube/commit/85c5b04b8135b47caace13d533f3ecc7169f9eac
