### ISSUE TITLE
YouTube Crashes Without Warning When Video ID Starts with a "-"

### ISSUE THREAD

**Issue by Wasserverlauf** [anxdpanic/plugin.video.youtube#560]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2,2
* Kodi Version: 20.3
* Kodi GUI Language: DE
* Operating System: LibreELEC 11.0.1
* Operating System Language: DE

------

### Expected Behavior

I add a YouTube video and it plays.

------

### Current Behavior

Videos whose ID starts with "-" cause the app to crash.
Example link: https://www.youtube.com/watch?v=-auejnUVH4A

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start Kodi.
2. Add a video to the playlist (done via Yatse or the "Cast Kodi" add-on).
3. The YouTube app briefly does something (loading symbol and the video's name is displayed in the top right).
4. The app crashes without any further notification.

Additional Issue:
If I fill a playlist with videos and then add another YouTube video after the problematic one, Kodi completely crashes and restarts.

------

### Log

https://paste.kodi.tv/obuluguyod

------

**Comment by MoojMidge** [comment]
This issue doesn't have anything to do with the video ID. It's probably a duplicate of #527

The Kodi crash should already be fixed in the latest development release: https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3%2Bbeta.1

**Comment by Wasserverlauf** [comment]
I tried the recommended version.
Now there's an error message, but unfortunately, the video still doesn't play.
(However, other videos continue to play without any issues.)

Regarding the "-" as a possible cause - it was definitely a misconception on my part. I specifically looked for videos and realized that it's not the reason. Other videos with a "-" at the beginning play without any problems.

And, of course, here's the log with the new version:
https://paste.kodi.tv/nefonayide

**Comment by Wasserverlauf** [comment]
now it works, after the update to the beta - 2 reboots and other YT Videos it works fine. Don't know why

**Comment by MoojMidge** [comment]
>If I fill a playlist with videos and then add another YouTube video after the problematic one, Kodi completely crashes and restarts.

To clarify, the beta version will fix Kodi crashing in the manner described above, but won't fix the original issue.

The original issue is either a network problem, or potentially some bug with Kodi/libcURL, and the only suggestions I have to prevent it re-occuring are here: https://github.com/anxdpanic/plugin.video.youtube/issues/527#issuecomment-1784236578
