### ISSUE TITLE
Addon crashes at startup

### ISSUE THREAD

**Issue by GTP95** [anxdpanic/plugin.video.youtube#561]
### Context
I have Kodi running on an up-to-date Dietpi install on a Raspberry Pi 3 B+. I noticed the Youtube addon crashing when opened, along a few others. Suspecting a Kodi issue, I tried purging it and then install it again, to have a fresh install, but it didn't solve the problem.

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 19.4
* Kodi GUI Language: English
* Operating System: Dietpi
* Operating System Language: English

------

### Expected Behavior
The addon opens.

------

### Current Behavior
The addon crashes and i get a notification telling me about the crash and to check the log for more information.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to open the addon
2. It crashes

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14000934/kodi.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Your Python installation needs to be updated, specifically the charset-normalizer package. Nothing to do with this plugin, or even Kodi really
