### ISSUE TITLE
My subscriptions isnt working in Beta Version

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#563]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.3+beta.1
* Kodi Version: 20.3
* Kodi GUI Language: English? or do you mean programing language? Skin is Unity. Doesnt Specify on github what programming languages.
* Operating System: OSMC, on a pre-release that has Kodi 20.3
* Operating System Language: English? Or do you mean programing languages,  C 44.2%, Python 22.9%, Shell 10.4%, C++ 6.6%, Assembly 4.5%, Ada 2.9%, Other 8.5%

------

### Expected Behavior

Im expecting 

------

### Current Behavior

What is the current behavior?

Instead of accessing video lists from my profile when going into My Subscriptions it throws an error. Trending works as intended. Search works as intended. Even access to my playlists shows videos in the list. But Accessing My Subscriptions throws a Youtube Error Check log for more information.
------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Upgrade to v7.0.3+beta.1
2. Sign back into account to my account
3. Try to access My Subscriptions and it throws Youtube Error Check log for more information.

------

### Log
Edit: Removed

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by ghost** [comment]
Im getting some weirdness in terms of, stuff that was broken sorting itself, seemingly for no reason. That including this issue and a playback issue where about half the videos wouldnt play. Both of which just sorted itself without really any known cause. Take a look at the log but idk maybe it was something on the end of the youtube developer api?

**Comment by MoojMidge** [comment]
Thought I replied, but there is nothing in the log. The issue was likely a duplicate of #555

**Comment by ghost** [comment]
Nope started again randomly, and I tried clearing data cache and I tried applying that fix, and it didnt help.

**Comment by ghost** [comment]
> Thought I replied, but there is nothing in the log. The issue was likely a duplicate of #555

I dont get it if it says check the log but doesnt write anything to it, that seems misleading, unless theres another log other than the kodi one? I looked through the log I posted as well and I couldnt find much either. But that log was taken when I had the error pop up.

**Comment by ghost** [comment]
Nevermind, I believe the fix wasnt applied right the save got reverted, I got it now, thanks.
