### ISSUE TITLE
Saved Playlist in 7.0.3 Beta 2

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#569]
* Add-on Version:  7.0.3 Beta 2
* Kodi Version: Nexus 20.3
* Kodi GUI Language: Default
* Operating System: Android
* Operating System Language: Default

------

Saved Playlists in settings.xml as default `<setting id="youtube.folder.saved.playlists.show" default="true">true</setting>`, it is necessary  to set manually by false `` <setting id="youtube.folder.saved.playlists.show" default="true">false</setting>``

![020124053259](https://github.com/anxdpanic/plugin.video.youtube/assets/157020721/1ec75757-4027-4431-b402-cbbf4616aeae)

------

### Current Behavior

Not possible to de-select in the addon settings (Folders)

------

Thanks a lot to @MoojMidge and @anxdpanic for your work!!!

**Comment by MoojMidge** [comment]
The saved playlist functionality will be restored, but the main menu item was enabled before this was done and before the settings toggle was re-enabled.

Have disabled the menu item for the time being, but it will take some time before I get to restoring the actual functionality.
