### ISSUE TITLE
"My Subscriptions" empty, what is the solution/workaround?

### ISSUE THREAD

**Issue by probonopd** [anxdpanic/plugin.video.youtube#57]
The bug was marked as "spam", but what is the solution/workaround?

https://github.com/anxdpanic/plugin.video.youtube/issues/56

Is this being worked on?

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/56#issuecomment-734367728 
> "Will look into it further."

**Comment by anxdpanic** [comment]
It's not the fastest, but it works for now. https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
