### ISSUE TITLE
Delete playlist in v7.0.3 Beta 2

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#573]
### Context

* Add-on Version: 7.0.3 Beta 2
* Kodi Version: Nexus 20.3
* Kodi GUI Language: Default
* Operating System: Android
* Operating System Language: Default

------

### Current Behavior

Message "Error in ContentProvider", but deletion was done.
https://imgur.com/a/PaJgrXT

------

### Steps to Reproduce

1. Create new "Test" playlist
2. Delete the "Test" playlist

------

### Log

https://paste.kodi.tv/arufofasof.kodi

**Comment by MoojMidge** [comment]
Same underlying issue as #568 
Should be fixed by  https://github.com/MoojMidge/plugin.video.youtube/commit/3716d53ea6760a6ca83291bc82def27613d51f8d and https://github.com/MoojMidge/plugin.video.youtube/commit/6635d981576b8c639077a5a447440d8315dd78fd

**Comment by Mo1967** [comment]
Working. for me. 
Big Thanks to @MoojMidge and @anxdpanic for this great support!

**Comment by MoojMidge** [comment]
Duplicate of #568
