### ISSUE TITLE
Premiers Time Is Incorrect on 7.0.3 Beta 2

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#574]
* Add-on Version: 7.0.3 Beta 2
* Kodi Version: 20.3 Nexus 
* Kodi GUI Language: English 
* Operating System: CoreELEC 
* Operating System Language: English 

7.0.3 Beta 2 shows scheduled videos to "premiere" but the time is incorrect, it's +5 hours than it should be. I'm in EST timezone. My Kodi time and regionals (America/New_York) is configured correctly. And in YouTube Addon Settings my "Location" is also correct under "Advanced".

### EXAMPLE: It should be 12:00 PM and NOT 5:00 PM for my EST (America/New_York) timezone.
![20240205_111547_copy_697x708](https://github.com/anxdpanic/plugin.video.youtube/assets/6996362/5a9218f9-9580-4201-a654-c0019b3bd368)

Thanks to Mooj for putting in massive work

**Comment by MoojMidge** [comment]
Can't test it, but it should probably be fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/c376d5b50c9785234538d208f142041cb8f8f7a3

For next time please include at least a link to an example video
