### ISSUE TITLE
Search functionality no longer working properly

### ISSUE THREAD

**Issue by psymage** [anxdpanic/plugin.video.youtube#585]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.3-Nexus
* Kodi GUI Language: English
* Operating System: CoreELEC
* Operating System Language: English

------

### Expected Behavior

Searches for videos should bring back results based on keywords.

------

### Current Behavior

Searches do not work consistently at all, whether it's the regular search or Quick Search. In fact, they now barely work at all. I just did some searches and only one or two of them gave me video results. I did try a video from that and it did work, so I don't think playback is the issue here. However, even in searches that gave me video results, nothing comes up when you go to Channels so if you search for Channels, you won't be able to pull up results. I included a log file from the last time I ran CoreELEC. Also, when you go back to a search term that previously worked, it usually doesn't work again. 

I tried putting in new API keys, new Client ID, and Client Secret, but none of that fixed the problem. I also tried updating to one of the betas and that didn't help either. 
------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to the Kodi Youtube app
2. Enter search terms
3. Press enter.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[coreelec log 2-21-24.pdf](https://github.com/anxdpanic/plugin.video.youtube/files/14367101/coreelec.log.2-21-24.pdf)

------

### Additional Information

This problem did not start until yesterday as far as I am aware. 

------

**Comment by MoojMidge** [comment]
Thanks for the log.

You are not actually logged in and the search is trying to use a backup set of credentials, and failing, likely because a lot of people are doing the same...

Try to login using your own credentials.
