### ISSUE TITLE
Hide Watched option is no longer working

### ISSUE THREAD

**Issue by dtteufel** [anxdpanic/plugin.video.youtube#586]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.3+beta.3
* Kodi Version: 20.3-Nexus
* Kodi GUI Language: English
* Operating System: OSMC Vero V
* Operating System Language: English

------

### Expected Behavior

Toggle Watched and un-watched listings from GUI Menu options
This function was working in v7.0.2.2

------

### Current Behavior

Does not do anything ...

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Display Subscriptions listing
2. Raise Left hand option Menu
3. Try to toggle 'Hide Watched'

------

### Log

------

### Additional Information

Please provide any additional information that may be helpful.

This function was working in v7.0.2.2

------

**Comment by MoojMidge** [comment]
Does 'Hide Watched' not show up, or does it not do anything? And are you sure it worked in v7.0.2.2?

Whether a video is considered watched or not by Kodi is not handled by the plugin.

Depending on the skin you are using, it may not allow you to toggle watched status for videos. The default Kodi skin, for example, does not support this even though it works just fine. OSMC has its own skin and I don't know what it allows.

The unofficial versions of this plugin workaround this by pretending that the videos are episodes, to allow the skins to provide this functionality. Maybe you were using an unofficial version previously? 

The unofficial version of the current betas do not correctly present videos as episodes, and while this will be fixed, this won't change anything for you if you are not using the unofficial version.

**Comment by dtteufel** [comment]
@MoojMidge 
Many thanks for your reply.

Yes. I was using plugin.video.youtube-7.0.2.2.unofficial.1 previously with the Confluence Skin which explains why it was working before.

Yes, the option does show up - but nothing happens. 

I now understand that you are aware of the issue and look forward to the release of the  plugin.video.youtube-7.0.33.unofficial.1.zip

Your fix https://github.com/MoojMidge/plugin.video.youtube/commit/00c6c57eaf3cf47349aa5a24fc4a6607040a4c65
resolves the issue.

Many thanks for your hard work.
