### ISSUE TITLE
Additional view types are not showing up

### ISSUE THREAD

**Issue by Mark112887** [anxdpanic/plugin.video.youtube#589]
### Context

Please provide any relevant information about your setup

* Add-on Version : 7.0.3+beta.3.unofficial.1
* Kodi Version: 20.3.2
* Kodi GUI Language: English
* Operating System: Android
* Operating System Language: English

------

### Expected Behavior
to successfully be able to change the view type

------

### Current Behavior

Additional view types which should be available in the unofficial version are not showing up despite the fact that they are not disabled in the view settings menu. The only two options available all are list and icons

------

### Steps to Reproduce

1. Install kodi
2. Install 7.0.3+beta.3.unofficial.1
3. Install Aeon knox silvo skin
4. Try to change view type inside youtube add on 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14383466/kodi.log)

**Comment by MoojMidge** [comment]
Same issue as #586, will be fixed in next beta version
