### ISSUE TITLE
7.0.2.2 - Matrix - zero videos listed

### ISSUE THREAD

**Issue by ebym** [anxdpanic/plugin.video.youtube#591]
### Context
Have been watching YT videos without signing in all these years. YouTube was working till last week and no changes made to plugin settings.

Now YT plugin have zero videos listed, all existing previous searches are there, each search contain "Channels, Playlist and Live", but none have any videos. all the plugin menus are there. 

**Note:** Playing YT videos on LibreElec using Cast Kodi plugin works !!!. 

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2 Matrix Official Version
* Kodi Version: 19.5.0 Matrix
* Kodi GUI Language: English
* Operating System: LibreElec
* Device: RPI 4
* Storage: Less than 28% storage space used.

------

### Expected Behavior
Videos should be listed on KODI.

------

### Current Behavior
Zero videos listed.

------

### Log
Edit: removed log file.

------

**Comment by MusterGit** [comment]
There's already  a fix for this problem. See #587 

You can either change one line in a python file yourself or install the latest beta [version 4](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3%2Bbeta.4)

**Comment by MoojMidge** [comment]
Just a note that v7.0.3+beta.4 probably won't work in Kodi 19.

[v7.0.3+beta.5.matrix.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3%2Bbeta.5) has been released to fix that

**Comment by ebym** [comment]
> Just a note that v7.0.3+beta.4 probably won't work in Kodi 19.
> 
> [v7.0.3+beta.5.matrix.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3%2Bbeta.5) has been released to fix that

Does the suggested edit (#587) on 7.0.2.2 fix subtitle not loading issue as well ?.

**Comment by MoojMidge** [comment]
No,  that is just one specific fix.

It is a lot easier to just use the latest release, which includes all collected fixes including fixing subtitles, rather than trying to make small changes here and there.

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.3.1
