### ISSUE TITLE
Youtube 7.03 beta 4 and 5 break subtitles loading with dash enabled

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#595]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.beta.5
* Kodi Version: 20.4
* Kodi GUI Language: French
* Operating System: Android
* Operating System Language: French

------

### Expected Behavior

Loading subtitles with dash enabled should open videos but it's not case with 7.03.beta4 and beta5 branches. 

------

### Current Behavior

Since 7.03.beta4 branch, subtitles loading has been broken with dash enabled. However, it works flawlessly without inpustream adaptive but it's limited to 720p. 

------

### Steps to Reproduce

1. Open Youtube 7.03.beta4 or 5
2. In settings, enable inputstream adaptive - MPEG-Dash
3. Choose subtitles language in video, for instance : https://www.youtube.com/watch?v=cGYMAobXNaM
4. Instead of video with subtitles, popup shall display error message

------

### Log

You can find complete debug log : https://paste.kodi.tv/sokegeyefi.kodi

------

### Additional Information

@MoojMidge 
Thanks very much for fixing progress video sync, it works flawlessly now. 

------

**Comment by MoojMidge** [comment]
Thanks for testing. I only tested with Kodi v21 so didn't pick this up

The fix is https://github.com/MoojMidge/plugin.video.youtube/commit/1f9fac45dfcbea0384007791aaf9879362865799

**Comment by Mo1967** [comment]
@MoojMidge 

with fix https://github.com/MoojMidge/plugin.video.youtube/commit/1f9fac45dfcbea0384007791aaf9879362865799 results error for below video, here the Log https://paste.kodi.tv/avinopeken.kodi
https://youtu.be/IGVZOLV9SPo?si=yg1miRzCU92h_sia

Apart from that v7.03 beta 5 working fine for me, thank you.

**Comment by MoojMidge** [comment]
@Mo1967 - that is actually a different issue fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/48bf546b2686b495472fcdbd5326780fad725b3d#diff-c4c823145b34debd557bd2c49df46e8de42cc790ab1476b2fc155aa1432c9821L247

**Comment by Mo1967** [comment]
> @Mo1967 - that is actually a different issue fixed by [MoojMidge@48bf546#diff-c4c823145b34debd557bd2c49df46e8de42cc790ab1476b2fc155aa1432c9821L247](https://github.com/MoojMidge/plugin.video.youtube/commit/48bf546b2686b495472fcdbd5326780fad725b3d#diff-c4c823145b34debd557bd2c49df46e8de42cc790ab1476b2fc155aa1432c9821L247)

I swapped all files, but again error message with en-subtitles in below videos:  Log https://paste.kodi.tv/zagurumoji.kodi
https://youtu.be/IGVZOLV9SPo?si=GheKDJf2TnxOpcsv
https://youtu.be/DJqmFFuTBjE?si=FYrlYURDTi2OCPW-

**Comment by MoojMidge** [comment]
Unfortunately the order in which the changes are made is important. When you swapped the files from https://github.com/MoojMidge/plugin.video.youtube/commit/48bf546b2686b495472fcdbd5326780fad725b3d the other fixes from https://github.com/MoojMidge/plugin.video.youtube/commit/1f9fac45dfcbea0384007791aaf9879362865799 would have been lost. 

You can see the order of the changes in the commit history https://github.com/MoojMidge/plugin.video.youtube/commits/master/

I'll push a release out for testing

**Comment by MoojMidge** [comment]
Can download a test v7.0.3 release from https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.3

If no further problems will create an official release

**Comment by karlo2105** [comment]
@MoojMidge
I just watched a dash video with subtitles. It played flawlessly. Thanks for update.

**Comment by Mo1967** [comment]
> @MoojMidge I just watched a dash video with subtitles. It played flawlessly. Thanks for update.

+1
confirm it with v7.0.3

**Comment by MoojMidge** [comment]
Great, thanks for testing.

**Comment by jetfir3** [comment]
@MoojMidge 

Still seeing a similar subtitle issue on Nexus since the 7.0.3-beta4 build. But rather than the video not play and display an error, the video plays without any subtitles (regardless if selecting them in prompt or auto-downloading them). 

b4, b5, 7.0.3, 7.0.3.1 and 7.0.3.2 don't display any subtitles UNLESS I disable MPEG-DASH. 

Turning OFF MPEG-DASH -- subtitles work on all versions listed above. 
Installing 7.0.3-beta3 with MPEG-DASH enabled - subtitles work. 

Before opening a new issue I wanted to first see if there is a Kodi/YT setting I'm overlooking or a cached file I should be removing or an addon data file I should be deleting/rebuilding? Error seems to stem from "error <general>: CCurlFile::CReadState::FillBuffer" which seems related to Input stream Adaptive issues, though I'm not sure what I could tweak there. 

Full log here - https://edited

**Comment by MoojMidge** [comment]
It's a bug in InputStream.Adaptive, where it thinks the absolute local file path of the subtitle file is a remote relative url.

```
2024-03-06 15:33:45.564 T:618      info <general>: Opening stream: 1009 source: 256
2024-03-06 15:33:45.564 T:618     debug <general>: AddOnLog: inputstream.adaptive: OpenStream(1009)
2024-03-06 15:33:45.566 T:618     debug <general>: CurlFile::Open - <[http://127.0.0.1:50152/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/plugin.video.youtube/VdOlqcg9uMQ.en.srt>](http://127.0.0.1:50152/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/plugin.video.youtube/VdOlqcg9uMQ.en.srt%3E)
2024-03-06 15:33:45.570 T:637      info <general>: running thread: CVideoPlayerAudio::Process()
2024-03-06 15:33:45.574 T:540     debug <general>: [plugin.video.youtube] HTTPServer: GET uri path |/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/plugin.video.youtube/VdOlqcg9uMQ.en.srt|
2024-03-06 15:33:45.574 T:540     debug <general>: [plugin.video.youtube] HTTPServer: Connection from |127.0.0.1| Local range: |True|
2024-03-06 15:33:45.576 T:618     error <general>: CCurlFile::CReadState::FillBuffer - (0xbe5b3560) Failed: HTTP returned code 501
2024-03-06 15:33:45.577 T:618     error <general>: CCurlFile::Open - <[http://127.0.0.1:50152/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/plugin.video.youtube/VdOlqcg9uMQ.en.srt>](http://127.0.0.1:50152/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/plugin.video.youtube/VdOlqcg9uMQ.en.srt%3E) Failed with code 501:
```

Will need to see whether it can use `special://` protocol paths instead. In the meantime just configure the subtitles to not be pre downloaded and it should work

**Comment by jetfir3** [comment]
> In the meantime just configure the subtitles to not be pre downloaded and it should work

This workaround fixed it up. My mistake for not trying that in the first place. Thanks for the info!
