### ISSUE TITLE
plugin://plugin.video.youtube/search/?q=$INFO[ListItem.Label] display error from v7.0.3+beta.4

### ISSUE THREAD

**Issue by Nanomani** [anxdpanic/plugin.video.youtube#599]
### Context

Some skin display list video Youtube in "Video Dialog Info" related to the Movie Title. 
This is broken from  v7.0.3+beta.4 (tested with the latest version 7.0.3 too) with error message : 
"Mapping for path '/search/' not found"

Rollback to v7.0.3+beta.3 fix this issue

------

### Expected Behavior

a List of Youtube Videos should be displayed

![2024-02-25_161407](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/81d26e49-ea1f-4c62-8951-3878edd580df)

------

### Current Behavior

Nothing is displayed with error message : 

![2024-02-25_162241](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/0d9faa2a-15e6-475f-bfcc-21ae8b5db4a5)

------

### Steps to Reproduce

Tested from scratch with Kodi 21 Beta 3 on Windows 11 x64 pro and all by default.
Use addon YT v7.0.3+beta.4

1. install the public skin "skin.arctic.zephyr.mod" which uses the following command line `plugin://plugin.video.youtube/search/?q=$INFO[ListItem.Label] `
2. scrape a movie
3. open "information" for this movie
4. then an error message is dsiplayed "Mapping for path '/search/' not found"

------

### Log

https://paste.kodi.tv/itawopomus.kodi

------

### Additional Information

------

**Comment by MoojMidge** [comment]
If you change https://github.com/anxdpanic/plugin.video.youtube/blob/f8e8485b66db5942df41151b3f5066db416c2ab0/resources/lib/youtube_plugin/kodion/constants/const_paths.py#L14

To
```
SEARCH = '/search'
```

Does it work?

**Comment by Nanomani** [comment]
@MoojMidge 

Sorry but no :/

![2024-02-25_171906](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/8b157b8e-fb77-4971-b543-c1ccf178b9a8)

**Comment by MoojMidge** [comment]
It should work. Can you try again after closing and re-opening Kodi, or just disabling, then re-enabling the plugin?

~Edit: Can you check if https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.3.1 fixes the issue?~

**Comment by Nanomani** [comment]
@MoojMidge 
This issue is fixed now.
Thanks again :)

PS : 
May I ask what the difference is between a "version xx" and the "version xx-unofficial"

**Comment by MoojMidge** [comment]
Turns out there are a bunch of hardcoded Youtube plugin paths scattered throughout various parts of the Kodi codebase, and third party skins also using this, so can't just change the search path. Will need to retain both types of search paths.



> May I ask what the difference is between a "version xx" and the "version xx-unofficial"

https://github.com/anxdpanic/plugin.video.youtube/wiki/FAQ#difference-between-the-official-and-unofficial-versions

**Comment by Nanomani** [comment]
Thanks for your feedback
