### ISSUE TITLE
[Bug] Language russian not support on search

### ISSUE THREAD

**Issue by VuzzyM** [anxdpanic/plugin.video.youtube#6]
Cyrillic letters are not supported in the latest version, before version is work.

**Comment by anxdpanic** [comment]
which part isn't working? A log would be best, but steps to reproduce would be fine.

**Comment by VuzzyM** [comment]
> which part isn't working? A log would be best, but steps to reproduce would be fine.

I open addon
I go to section search
I search text with cyrillic letters and i getting error.

**Comment by VuzzyM** [comment]
@anxdpanic example text cyrillic: Сотня

**Comment by anxdpanic** [comment]
Thanks, I can reproduce it now. Will try to get an alpha/beta up by Monday 👍

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/pull/8/commits/54ff18d23c4940d531905dd15f0bac72cdd604e6 should fix this, you can install master or wait for a release. hoping to get information regarding another issue, just holding out for that atm.

**Comment by VuzzyM** [comment]
@anxdpanic i wait release

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev there is a beta release up now since I think I resolved the other issue as well.

**Comment by VuzzyM** [comment]
> https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev there is a beta release up now since I think I resolved the other issue as well.

Is working
