### ISSUE TITLE
URL parameters for sorting videos in playlist

### ISSUE THREAD

**Issue by w64** [anxdpanic/plugin.video.youtube#607]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.2
* Kodi Version: 20
* Kodi GUI Language: English
* Operating System: Linux 5.15
* Operating System Language: English

------

### Expected Behavior

When user open YouTube Playlist via the addon, he will use the setting in the url parameters itself:

> plugin://plugin.video.youtube/play/?play=1&**order=shuffle**&playlist_id=PL**************

for order of the videos, without modal windows that need user intervention. That was the addon behavior to v7.0.2. Please, bring back the old addon parameters for sorting videos!

------

### Current Behavior

When i open YouTube Playlist via the addon, Kodi show's modal window, that ask for user choice which method of sorting videos in the playlist will be used. That setting is not remembered and the next time, the same modal window will ask the same question.

------

### Steps to Reproduce

1. Create a EXAMPLE.strm file with this content:
plugin://plugin.video.youtube/play/?play=1&order=shuffle&playlist_id=PL6XRrncXkMaWHdqYro173ihPrqS_mdafT
3. Open this EXAMPLE.strm file in Kodi video section
4. Modal window will pop up, asking what you want to do!?

------

### Log

It's not needed. Everything is visible in the user interface.

**Comment by MoojMidge** [comment]
@w64 - should be fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/a30f5ea24ef8f17d06e0c0b1735694b8e78e8946

**Comment by w64** [comment]
I have tested and it's working! Please include it in the next addon version.

**Comment by MoojMidge** [comment]
[v7.0.4+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.1) is available to test and should fix this issue.
