### ISSUE TITLE
A lightweight YouTube plugin

### ISSUE THREAD

**Issue by RNavega** [anxdpanic/plugin.video.youtube#608]
Hi Mooj,  
I use an old Android TV box running Kodi Leia 18.9.  
I noticed that this plugin was getting a bit heavy to run on my device (it was taking a while to load a directory, for example).  
Besides that, as well as for the intellectual challenge, I set out to write a minimalist YT add-on, like the simplest that I could do but still supporting the features that I needed (basically watching videos and removing videos from a personal playlist after I watched them). And also because, while Bromix created a very sophisticated architecture for the YouTube add-on and it stood the test of time, it's complex and therefore challenging to customize if you want to change how some menus are laid out etc.

I finished it and it's working fine.  
If you ever want to rewrite the plugin and are looking for references, the files are below:

----
/plugin.video.minyoutube/
.......... [addon.xml](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-addon-xml)
.......... [Default.py](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-default-py)

.......... /Lib/
.................... \_\_init\_\_.py (empty)
.................... [Common.py](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-common-py) (utilities, constants, common imports)
.................... [Plugin.py](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-plugin-py) (main Kodi UI and plugin flow handler)
.................... [YouTubeAPI.py](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-youtubeapi-py) (YouTube API functions and resource handling)
.................... [Web.py](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-web-py) (a simple standalone HTTP / HTTPS client module \* )

.......... /resources/
.................... [settings.xml](https://gist.github.com/RNavega/e46fd0395023b74f777f32fde8247473#file-settings-xml) (Old style settings, for Leia 18.9)

----

\* This Web.py module is probably the most interesting part. It replaces the `script.module.requests` library and all its dependencies (Edit: actually it doesn't replace them as in "it has the same functionality as them", you just don't need them around any longer). None of my personal plugins use `requests` anymore, just this Web -- as most of the time you're just concerned with getting some HTML or JSON string, so for my usecase I don't need to support more encodings than UTF-8 or ASCII.

**Comment by MoojMidge** [comment]
Nice!


> I use an old Android TV box running Kodi Leia 18.9.
> I noticed that this plugin was getting a bit heavy to run on my device (it was taking a while to load a directory, for example).

If you can it would be good to quantify this, to see where improvements can be made.

I added some profiling code to the plugin, that you could use like below to generate some stats.

https://github.com/anxdpanic/plugin.video.youtube/blob/9624d86b87cc62a97aaa184c4887c56dd5212b1f/resources/lib/plugin.py#L14-L17

Change to:
```
from youtube_plugin.kodion import plugin_runner
from youtube_plugin.kodion.debug import Profiler


profiler = Profiler(enabled=True, lazy=False)
plugin_runner.run(youtube.Provider())
profiler.print_stats()
```

Pretty sure the Profiler and the current master branch code will still run in Kodi 18.9

When I make changes I have the Profiler enabled and I try to ensure that, on my laptop, the loading of a 50 item long listing takes less than 1 second, and the reloading of the listing from cache takes less than 400 ms.

The device I actually use to watch things is a fair bit slower (around 3x slower actually) and the breakdown is something like:
- Kodi GUI stuff (listitem creation and modification) and misc processing ~20% of time
- SQLite database read/write ~20% of time
- API requests ~40% of time
- Interpreter, thread and other overheads ~20%


> Besides that, as well as for the intellectual challenge, I set out to write a minimalist YT add-on, like the simplest that I could do but still supporting the features that I needed

Sort of the same reason I started looking at this actually, but I was a little bit more lost to start off with, and modifying existing is easer than starting from scratch.


> while Bromix created a very sophisticated architecture for the YouTube add-on and it stood the test of time, it's complex and therefore challenging to customize if you want to change how some menus are laid out etc.

Yeah, quite remarkable the longevity of the framework (although it obviously needed updates over the years), but also quite complicated to understand in places.


> This Web.py module is probably the most interesting part. It replaces the `script.module.requests` library and all its dependencies

Was actually considering doing something similar, or going in the complete opposite direction and using httpx so see if there was any speedup in the API requests.

**Comment by RNavega** [comment]
> If you can it would be good to quantify this, to see where improvements can be made.
> I added some profiling code to the plugin, that you could use like below to generate some stats.

Thanks for letting me know about the profiler, that's very interesting. And it makes sense, if you know where it takes the longest, you can focus resources in optimizing those parts.

I think part of the slowdown is also the plugin having some sort of background service that checks some JSON resources. The log was flooded with things like these:

```python
2024-03-01 02:34:22.609 T:408   DEBUG: [plugin.video.youtube] Get |kodion.http.listen|: "0.0.0.0" (str, success)
2024-03-01 02:34:22.610 T:408   DEBUG: [plugin.video.youtube] send_notification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": false, "whitelist": ["127.0.0.1"], "httpd_port": 50152}|
2024-03-01 02:34:22.610 T:408   DEBUG: [plugin.video.youtube] JSONStore.load - loading:
                                            |C:\Users\Doko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.youtube\api_keys.json|
2024-03-01 02:34:22.610 T:408   DEBUG: [plugin.video.youtube] JSONStore.save - data unchanged:
                                            |C:\Users\Doko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.youtube\api_keys.json|
2024-03-01 02:34:22.611 T:408   DEBUG: [plugin.video.youtube] JSONStore.load - loading:
                                            |C:\Users\Doko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.youtube\access_manager.json|
2024-03-01 02:34:22.611 T:408   DEBUG: [plugin.video.youtube] JSONStore.save - data unchanged:
                                            |C:\Users\Doko\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.youtube\access_manager.json|
2024-03-01 02:34:22.615 T:408   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
```
But as I'm using Leia (Python 2) and on a TV box at that, there's too much noise to collect useful info IMO. The change to Python 3 might already make things slightly faster.  
Cheers

**Comment by MoojMidge** [comment]
Hmm that shouldn't be happening all the time.

Only once on service initialisation. On each plugin run, the access_manager.json will be checked, which is something that may be able to be improved, but the it's not something that ever showed up in the profiler as being a big holdup since the actual I/O operations are skipped unless something actually changed.

If you can get a debug log that may help identify what is happening, otherwise even just the debug log entry showing the profiler outputs will be useful.

Should look something like this
```
[plugin.video.youtube] Profiling stats:          58215 function calls (55561 primitive calls) in 2.450 seconds

                                                      Ordered by: cumulative time, internal time                                                                                                                                                                                                   List reduced from 990 to 50 due to restriction <50>                                                                                                                                    
                                                      ncalls  tottime  percall  cumtime  percall filename:lineno(function)
                                                           1    0.002    0.002    2.446    2.446 plugin_runner.py:30(run)                                                                                                                                                                               1    0.000    0.000    2.442    2.442 xbmc_plugin.py:38(run)                                                                                                                                                                                 1    0.000    0.000    2.368    2.368 abstract_provider.py:104(navigate)
                                                           1    0.000    0.000    2.354    2.354 abstract_provider.py:288(wrapper)
                                                           1    0.001    0.001    2.353    2.353 provider.py:393(_on_channel)                                                                                                                                                                           1    0.000    0.000    1.554    1.554 function_cache.py:71(run)                                                                                                                                                                              1    0.000    0.000    1.333    1.333 youtube.py:974(get_playlist_items)
                                                           1    0.000    0.000    1.333    1.333 youtube.py:1817(api_request)
                                                           1    0.000    0.000    1.331    1.331 requests.py:68(request)                                                                                                                                                                                1    0.000    0.000    1.205    1.205 sessions.py:502(request)                                                                                                                                                                               1    0.000    0.000    1.178    1.178 sessions.py:673(send)
                                                           1    0.000    0.000    1.170    1.170 adapters.py:434(send)
                                                           1    0.000    0.000    1.161    1.161 connectionpool.py:595(urlopen)                                                                                                                                                                         1    0.000    0.000    1.154    1.154 connectionpool.py:380(_make_request)                                                                                                                                                                   1    0.000    0.000    0.855    0.855 connection.py:435(getresponse)
                                                           1    0.000    0.000    0.853    0.853 client.py:1330(getresponse)
                                                           1    0.000    0.000    0.852    0.852 client.py:311(begin)
                                                          13    0.000    0.000    0.849    0.065 socket.py:692(readinto)                                                                                                                                                                               13    0.000    0.000    0.849    0.065 ssl.py:1267(recv_into)
                                                          13    0.000    0.000    0.848    0.065 ssl.py:1125(read)
                                                           1    0.000    0.000    0.848    0.848 client.py:278(_read_status)                                                                                                                                                                           13    0.848    0.065    0.848    0.065 {method 'read' of '_ssl._SSLSocket' objects}                                                                                                                                                          26    0.000    0.000    0.848    0.033 {method 'readline' of '_io.BufferedReader' objects}                                                                                                                                                   14    0.000    0.000    0.482    0.034 storage.py:247(_execute)
                                                           4    0.000    0.000    0.479    0.120 storage.py:162(__enter__)
                                                           4    0.001    0.000    0.479    0.120 storage.py:170(_open)                                                                                                                                                                                  4    0.472    0.118    0.472    0.118 {method 'executescript' of 'sqlite3.Cursor' objects}                                                                                                                                                   2    0.000    0.000    0.460    0.230 resource_manager.py:32(get_channels)
                                                           2    0.000    0.000    0.459    0.229 data_cache.py:27(get_items)
                                                           2    0.000    0.000    0.459    0.229 storage.py:395(_get_by_ids)                                                                                                                                                                            1    0.000    0.000    0.453    0.453 resource_manager.py:101(get_fanarts)                                                                                                                                                                   1    0.000    0.000    0.295    0.295 connectionpool.py:1088(_validate_conn)
                                                           1    0.000    0.000    0.295    0.295 connection.py:609(connect)
                                                           1    0.000    0.000    0.285    0.285 connection.py:708(_ssl_wrap_socket_and_match_hostname)                                                                                                                                                 1    0.000    0.000    0.282    0.282 ssl_.py:397(ssl_wrap_socket)                                                                                                                                                                           1    0.001    0.001    0.270    0.270 v3.py:340(response_to_items)
                                                           1    0.002    0.002    0.268    0.268 v3.py:29(_process_list_response)
                                                          37    0.241    0.007    0.241    0.007 {method 'acquire' of '_thread.lock' objects}                                                                                                                                                           3    0.000    0.000    0.240    0.080 threading.py:1080(join)                                                                                                                                                                                3    0.000    0.000    0.240    0.080 threading.py:1118(_wait_for_tstate_lock)
                                                           1    0.000    0.000    0.202    0.202 storage.py:384(_get)
                                                           4    0.000    0.000    0.191    0.048 storage.py:167(__exit__)                                                                                                                                                                               7    0.000    0.000    0.191    0.027 storage.py:236(_close)                                                                                                                                                                                 4    0.190    0.048    0.190    0.048 {method 'close' of 'sqlite3.Connection' objects}
                                                           1    0.168    0.168    0.168    0.168 {method 'load_verify_locations' of '_ssl._SSLContext' objects}
                                                           1    0.000    0.000    0.126    0.126 youtube.py:1750(_response_hook)                                                                                                                                                                        1    0.000    0.000    0.125    0.125 models.py:944(json)                                                                                                                                                                                    1    0.000    0.000    0.124    0.124 __init__.py:474(loads)
                                                           1    0.000    0.000    0.124    0.124 decoder.py:365(decode)
                                                           1    0.000    0.000    0.124    0.124 decoder.py:378(raw_decode)
```

**Comment by MoojMidge** [comment]
> I think part of the slowdown is also the plugin having some sort of background service that checks some JSON resources. The log was flooded with things like these:

I think I found out what was causing this. Can you confirm issue is resolved in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.2

**Comment by RNavega** [comment]
> > I think part of the slowdown is also the plugin having some sort of background service that checks some JSON resources. The log was flooded with things like these:
> 
> I think I found out what was causing this. Can you confirm issue is resolved in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.2

Hi. I haven't been able to test Kodi things at the moment, when I do I'll report back. Thank you for the update.
