### ISSUE TITLE
Youtube and xbmc.python version 3.0

### ISSUE THREAD

**Issue by Sobersally** [anxdpanic/plugin.video.youtube#61]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* Kodi Version:
* Kodi GUI Language:
* Operating System:
* Operating System Language:

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by Sobersally** [comment]
I have Kodi 18.9 and I used the workaround for the youtube issue of no subscriptions. However, it worked on 2 machines and now I was trying it on other machines and when I download the anxdpanic-2.0.0.zip it shows that xbmc python version 3.0 version could not be satisfied. Any ideas? It worked 2 days ago. I am on Windows 10 64bit latest version.

**Comment by anxdpanic** [comment]
The `+matrix.1 zip` are meant for Kodi 19. For 18.9 make sure you're using the zip files without that.

**Comment by Sobersally** [comment]
I figured it out thank you for replying!
