### ISSUE TITLE
Cannot access API settings via HTTP

### ISSUE THREAD

**Issue by stephematician** [anxdpanic/plugin.video.youtube#618]
### Context

Installed 7.0.3.2 on Kodi Matrix, tried to access API page after selecting 'enable API configuration page'.

* Add-on Version:7.0.3.2
* Kodi Version: 19.5.0
* Kodi GUI Language:
* Operating System: LibreELEC 10.0.4
* Operating System Language: English

------

### Expected Behavior

To see the API details page in my browser when i open `http://192.168.1.xyz:12345/api` (where the IP is assigned by the router, and the port number is selected from the menu).

------

### Current Behavior

I see the following in my browser:

```
Error response

Error code: 501

Message: Not Implemented.

Error code explanation: 501 - Server does not support this operation.
```

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Install add-on
2.  Select 'Enable API configuration page'
3.  Open browser on laptop on local network
4.  Enter `http://192.168.1.xyz:12345/api` into browser.

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14533719/kodi.log)

------

### Additional Information

None

------

**Comment by MoojMidge** [comment]
The url for the api configuration page has changed to
```
http://<ipaddress>:<port>/youtube/api
```
Note the `/youtube` at the beginning of the path.

The translations were not updated when the change was made, but that is now fixed in #613
