### ISSUE TITLE
Import / export of search history

### ISSUE THREAD

**Issue by MusterGit** [anxdpanic/plugin.video.youtube#619]
### What Problem Does This Solve?

The search history is stored in a SQLite database file.
From version 7.0.3 on there is such a file for each user.

The update from 7.0.2.2 to 7.0.3 leads to a loss of the search history, and even copying the old database file to a new place does not help since the database schema has changed.

For future schema changes and other contexts it would be nice to have an import/export feature for the search history. 

------

### Suggest a Solution

As file format it could be sufficient to have a simple text file, where each line represents a search term. The 'When' aspect of the database schema could IMHO be omitted.

------

**Comment by MoojMidge** [comment]
It would have been better to migrate the data across, but it was not something I had time to do.

It is easy enought to do a mass import of search data by just creating a playlist/strm file with the following content:
```
plugin://plugin.video.youtube/search/?q=Search 1
plugin://plugin.video.youtube/search/?q=Search 2
plugin://plugin.video.youtube/search/?q=Search 3
```
Where `Search X` can be whatever search terms you want. When you play the playlist/strm file, the searches will be stored.

Exporting the old data is another matter, and is something I am unlikely to have time to do.

Out of interest, how many search items did you lose?

**Comment by MusterGit** [comment]
Fortunately, I made a backup, so I did not lose anything so far. It's 200 entries.

I'm currently using 7.0.2.2 again with this patch [https://github.com/anxdpanic/plugin.vide...1961212166](https://github.com/anxdpanic/plugin.video.youtube/issues/587#issuecomment-1961212166) and a manual adaptation of [https://github.com/anxdpanic/plugin.vide...06f06bfaf0](https://github.com/anxdpanic/plugin.video.youtube/commit/3b83a6619736ac0f9e940e6a70c0f806f06bfaf0) to the old structure.

I have not updated definitely yet because the newer versions are much slower than 7.0.2.2, at least with me.

**Comment by tomasz-c** [comment]
I had the same problem.
I wrote a short script that converts `search.sqlite` to a new format.

Process this file with the script:
`.kodi/userdata/addon_data/plugin.video.youtube/kodion/search.sqlite`
and place it in
`.kodi/userdata/addon_data/plugin.video.youtube/<profile_id>/search.sqlite`

```python
#!/bin/python3

import sqlite3
import pickle

conn = sqlite3.connect('search.sqlite', detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES)
cursor = conn.cursor()


cursor.execute("""
CREATE TABLE IF NOT EXISTS storage_v2 (
    key TEXT PRIMARY KEY,
    timestamp REAL,
    value BLOB,
    size INTEGER
);
""")

cursor.execute("SELECT key, time, value FROM storage")
rows = cursor.fetchall()

for row in rows:
    key = row[0]
    time = row[1]
    pickled_value = row[2]

    timestamp = time.timestamp()
    str_value = pickle.loads(pickled_value, encoding="utf-8")
    encoded_value = pickle.dumps(str_value, pickle.HIGHEST_PROTOCOL)
    binary_value = sqlite3.Binary(encoded_value)
    size = len(binary_value)
    data = (key, timestamp, binary_value, size)

    cursor.execute("REPLACE INTO storage_v2 (key, timestamp, value, size) VALUES(?, ?, ?, ?)", data)
    conn.commit()

cursor.execute("DROP TABLE IF EXISTS storage")
cursor.execute("VACUUM")
conn.commit()
conn.close()
```

**Comment by MoojMidge** [comment]
@MusterGit - Someone else mentioned that the newer versions were slower, but I haven't been able to confirm this. For me the newer versions are slightly faster on non-cached activities, and slightly slower on cached activities, largely because more things are being done by the newer versions, but the API requests are also now a bit faster.

The newer version has a profiler that can be used to determine where the slowdowns are. If you are willing to help investigate I can let you know how to use it?

Alternatively, both v7.0.2.2 and v7.0.3.2 will provide an indication of how long it takes for the plugin to perform a certain action if you enable debug loggin in Kodi. You should see entries in you log similar to this:
```
2024-03-10 10:19:33.303 T:24476    debug <general>: [plugin.video.youtube] Shutdown of Kodion after |0.03344| seconds
```

For the same action in v7.0.2.2 and v7.0.3.2, how much of a difference in time do you experience?

@tomasz-c - Nicely done. I am in the process of updating the setup wizard, I can add a step in the wizard to check if an old search database exists in the original location, open it and add any old entries into the new per-user search database. That will probably be the most user-friendly way to manage the problem.

**Comment by MusterGit** [comment]
@tomasz-c - Wow, this is great! Many thanks for your script and instructions. I struggled with the app `DB Browser for SQLite`, but only managed to somehow get a semi-usable CSV export. Your script helps a lot, and I support MoojMidge's wizard idea for a most user-friendly upgrade progress.

@MoojMidge - Sure, I'm wiling to help. I will measure some actions using the builtin stopwatch and create a separate issue for that. Haven't done that so far because I could not provide any proof/figures. Might take some days, though. Again, thanks for your great support and passion for the project.

**Comment by MoojMidge** [comment]
[v7.0.4+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.1) is now available to test.

It has the ability to import old format search and playback history data when running the Setup Wizard.

Please make a backup of your data just in case.

This release will also log runtime profiling data to the Kodi log when debug logging is enabled, that can be posted to a new issue to try and identify the cause of any slowdowns.
