### ISSUE TITLE
Failed to get response for video id 

### ISSUE THREAD

**Issue by f2hamza** [anxdpanic/plugin.video.youtube#620]
My iPad 2 have ios9. 3.5 can't install any kodi above the 17.4  and it was a life saver knowing how kodi to use YouTube since the YouTube app isn't supported anymore yesterday YouTube stopped working in the add on 6.8.25 i did check on my phone and there's a 7.0.3 version but latest add on in repository in the 17.4 is the 6.8.25 
i will really really really really appreciate if you guys support it as well it will mean alot i appreciate you guys work more than you can imagine to make my iPad usable i hope you guys can support it it will mean alot and thanks for the work past few years it was amazing 

* Add-on Version:6.8.25
* Kodi Version: 17.4
* Kodi GUI Language: 
* Operating System: ios 
* Operating System Language: English 

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
The Kodi Wiki indicates that you should be able to install a newer version of Kodi

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_iOS

Don't know whether that is true or not, but regardless, no further updates of this plugin are planned for Kodi 17.
