### ISSUE TITLE
[Winerror 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by joobert** [anxdpanic/plugin.video.youtube#622]
Whenever Kodi is launched or I try to play a trailer with YouTube via Arctic Horizon 2, this message error occurs. After appearing, the trailer will still play after a delay, but this is quite annoying. I was previously on version 7.0.2 and figured upgrading to 7.0.3.2 would solve this problem but this was not the case.

### Setup

* Add-on Version:  7.0.3.2
* Kodi Version: 20.0 (Nexus)
* Kodi GUI Language: English
* Operating System: Microsoft Windows [Version 10.0.23560.1000] (Windows 11 22H2)
* Operating System Language: English

------

### Expected Behavior

No error.

------

### Current Behavior

Getting error message "[Winerror 10013] An attempt was made to access a socket in a way forbidden by its access permissions" every time I interact with this plugin.

------

### Steps to Reproduce

* Open Kodi and wait for YouTube to load

OR

* Play a trailer/interact with the plugin in any way

------

### Relevant Log Messages

    2024-03-11 03:39:07.756 T:5968     info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: plugin.video.youtube v7.0.3.2 installed

    2024-03-11 03:39:13.595 T:25488   error <general>: [plugin.video.youtube] HTTPServer: Failed to start |0.0.0.0:50152| |[WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions|

------

### Additional Information

I wish I had a better understanding of the root of this issue, but this worked completely fine in the past. Haven't used Kodi in about 3 months or so until now.

------

**Comment by woodside007** [comment]
Try going to settings/HTTP Server and bump up the port number. I set mine to 56652 and it fixed it for me. Cheers.

**Comment by joobert** [comment]
> Try going to settings/HTTP Server and bump up the port number. I set mine to 56652 and it fixed it for me. Cheers.

You are a godsend. Such a simple fix. Thank you!
