### ISSUE TITLE
return filepath in _get_url() function in subtitles.py seems wrong

### ISSUE THREAD

**Issue by linzack** [anxdpanic/plugin.video.youtube#624]
### Context

Hi,
it's because the inputstream.adaptive addon will fetch mpd url, which is
```
http://127.0.0.1:PORT/youtube/manifest/dash/VIDEO_ID.mpd
```
also in the ideal situation, subtitle file need to be in the same directory of mpd file
```
BASE_PATH/VIDEO_ID.mpd
BASE_PATH/VIDEO_ID.LANG.srt
```
and the subtitle file path in mpd file need to be 
```
<BaseURL>VIDEO_ID.LANG.srt</BaseURL>
```
then the subtitle file can be accessed through
```
http://127.0.0.1:PORT/youtube/manifest/dash/VIDEO_ID.LANG.srt
```

if you return full filepath, the path will become
```
http://127.0.0.1:PORT/youtube/manifest/dash/BASE_PATH/VIDEO_ID.LANG.srt
```
which is a invalid path

IMO, this line 
https://github.com/anxdpanic/plugin.video.youtube/blob/92a87466c5d7a74c2838f114878b328289c854bf/resources/lib/youtube_plugin/youtube/helper/subtitles.py#L338

may need to be changed as
```
            return filename
```
Thank you!

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.2
* Kodi Version:  21.0-BETA2
* Kodi GUI Language: english
* Operating System: libreelec
* Operating System Language:

------

### Expected Behavior

kodi can select correct subtitle file

------

### Current Behavior

kodi cant find subtitle file

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. choose a youtube video with subtitle 
2. play in youtube addon
3. cant find subtitle 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
 info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=ID
 info <general>: Creating InputStream
rning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.manifest_type" property is deprecated and will be removed next
                 If you are using a proxy remember to add the appropriate "content-type" header to the HTTP manifest response
                 See Wiki page "How to provide custom manifest/license" to learn more about it.
 info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 3840x2160, Adjust refresh rate: 0
 info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 21, Type: VOD)
 info <general>: Creating Demuxer
 info <general>: Opening stream: 1001 source: 256
 info <general>: Creating video codec with codec id: 167
 info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem VP9 decoder wrapper
 info <general>: CDVDVideoCodecDRMPRIME::Open - unable to open codec
 info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder Google VP9
 info <general>: Creating video thread
 info <general>: running thread: video_thread
 info <general>: Opening stream: 1017 source: 256
 info <general>: Finding audio codec for: 86018
 info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
 info <general>: Creating audio thread
 info <general>: running thread: CVideoPlayerAudio::Process()
 info <general>: Opening stream: 1019 source: 256
error <general>: CCurlFile::CReadState::FillBuffer - (0x7f285c6a20) Failed: Couldn't connect to server(7)
error <general>: CCurlFile::Open - <http://127.0.0.1/storage/.kodi/temp/plugin.video.youtube/ID.LANG.srt> Failed with code 0:

error <general>: AddOnLog: inputstream.adaptive: Open: CURLOpen failed
error <general>: AddOnLog: inputstream.adaptive: Download failed, internal error: http://127.0.0.1/storage/.kodi/temp/plugin.video.youtube/ID.LANG.srt
```

------

### Additional Information

Please provide any additional information that may be helpful.

this do not solve when casting to kodi, it still append the BASE_PATH in mpd subtitle path, no idea why..

------

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/595#issuecomment-1981742937

Returning the filename only, so that InputStream.Adaptive won't mangle the url, won't achieve anything as the http server is not configured to serve subtitles. Even if it were configured to do so, that effectively means that the subtitles end up being downloaded twice.

The only solution is to disable pre-downloading the subs when using InputStream.Adaptive for the subtitles, or disable using InputStream.Adaptive when using pre-downloaded subs.

This is already done in https://github.com/anxdpanic/plugin.video.youtube/pull/615/commits/529e5caf44cb45883eb8939afeb05de3af5cc720 and will be available in the next release.

In the meantime change your subtitle options to disable the pre-download.

**Comment by linzack** [comment]
thank you for taking time to look into this, I'll test it when I have access to my device.

**Comment by MoojMidge** [comment]
[v7.0.4+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.1) is available to test and should fix this issue.
