### ISSUE TITLE
wrong addon build 7.0.3.2+matrix.1 in kodi nexus addon repos

### ISSUE THREAD

**Issue by allixx** [anxdpanic/plugin.video.youtube#628]
Wrong build of addon (for matrix specifically) is pulled in during addons update in kodi Nexus.

Looks like wrong addon package was submitted to kodi Nexus addons pipeline: https://kodi.tv/addons/nexus/plugin.video.youtube/

### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.2
* Kodi Version: 20.4

------

### Expected Behavior

I'd expect that kodi Nexus will have https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.3.2/plugin.video.youtube-7.0.3.2.zip 

------

### Current Behavior

Currently matrix build is downloaded and installed in kodi nexus during addon update: https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.0.3.2/plugin.video.youtube-7.0.3.2.matrix.1.zip

**Comment by MoojMidge** [comment]
Strange. It was submitted to the correct place, but the Matrix release has been used in both the Nexus and Matrix addon repositories.

**Comment by allixx** [comment]
Another thing worth mentioning is that kodi considers 7.0.3.2+matrix.1 version newer than 7.0.3.2. So if you manually install correct 7.0.3.2 build, autoupdate still replaces it with 7.0.3.2+matrix.1 on next update cycle.

My random guess is `.1` suffix makes version comparator consider 7.0.3.2+matrix.1 a newer version than 7.0.3.2

**Comment by benyamin-codez** [comment]
Yes, this got me too - but just now...
Had to install from zip, patch for #529 and #617, and make sure auto-updates was disabled.
8^d

**Comment by MoojMidge** [comment]
v7.0.4 should be available now, with the correct release in the correct repository
