### ISSUE TITLE
Some videos don't play, looks like an Age Gate issue

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#631]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.2+matrix.1
* Kodi Version: Local build of https://github.com/xbmc/xbmc/commit/348313a4335d14be88c8c91e70bdb3a67a5d542b
* Kodi GUI Language: English
* Operating System: LibreELEC
* Operating System Language: English

------

### Expected Behavior

All videos including e.g. https://youtube.com/shorts/V8lcY6a1BDc should play normally.

------

### Current Behavior

The video mentioned above does not play, there is no error notification on the UI, either.

But see the log below.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

0. Have an Android device with Yatse installed
1. Navigate to https://youtube.com/shorts/V8lcY6a1BDc on the device
2. Use 'Share' => 'Play on Kodi'

------

### Log

I've taken the liberty to reduce this to what look like the only relevant lines to me - if more context is useful, just let me know.

```
2024-03-13 09:29:51.618 T:1027176    info <general>: [plugin.video.youtube] Running: YouTube (7.0.3.2+matrix.1) on Omega (Kodi-21.0) with Python 3.11.8
                                                   Path: /uri2addon/
                                                   Params: {'uri': 'https://youtube.com/shorts/V8lcY6a1BDc'}
[...]
2024-03-13 09:29:51.737 T:1027176   debug <general>: [plugin.video.youtube] Unknown hostname "consent.youtube.com" in url "https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fshorts%2FV8lcY6a1BDc%3Fcbrd%3D1&gl=DE&m=0&pc=yt&cm=2&hl=en&src=1"
2024-03-13 09:29:51.738 T:1027176   debug <general>: [plugin.video.youtube] Shutdown of Kodion after |0.1196| seconds
```

------

### Additional Information

The LibreELEC system can successfully ping `consent.youtube.com`.

------

**Comment by MoojMidge** [comment]
I was wondering when this would popup.

The consent process has changed a while ago depending on the video and region, but I've never seen it.

It's never normally a problem because this plugin does not do any scraping, but I guess the `uri2addon` endpoint is triggering the new process when trying to resolve the underlying video url

I'll see if there is a way to bypass this without the initial redirect.

**Comment by jmbreuer** [comment]
> It's never normally a problem because this plugin does not do any scraping, but I guess the `uri2addon` endpoint is triggering the new process when trying to resolve the underlying video url

From looking at the code a while back, I remember I was wondering why the `uri2addon` entry point seems to work so much differently from the 'normal' one. At the time I thought it might be valuable (simply from a (no unnecessary) code duplication/consistency perspective) to try to call from `uri2addon` into the 'normal' process as early as possible; and use the separate resolving done in the former only when that's impossible (e.g. URL for a shortening service or such).

And, maybe that "once there's a known video ID, use the 'usual' process" should be tried as early as possible after each round of such redirect/scrape/...

I half-remember making a quarter-assed attempt at that, but found that it was way less easy/straightforward than I'd bargained for (not really understanding how Kodi and Python call each other WRT those endpoints doesn't help much, either).

Anyway, what I want to say, I'm happy to help out with this, but I could use a couple of pointers probably.

**Comment by MoojMidge** [comment]
Yes it would be possible to use a regexp to extract the videoid, but it gets messy with all the different possible url formats and video types.

In the meantime, try this and see if works. Change:
https://github.com/anxdpanic/plugin.video.youtube/blob/8d6bb622a11826244ee2048a91db327aeee6fe32/resources/lib/youtube_plugin/youtube/helper/url_resolver.py#L126-L129

to
```
        response = self.request(url,
                                method=method,
                                headers=self._HEADERS,
                                cookies={'SOCS': 'CAA'},  # no consent given
                                allow_redirects=True)
```

or 
```
        response = self.request(url,
                                method=method,
                                headers=self._HEADERS,
                                cookies={'SOCS': 'CAI'},  # consent given
                                allow_redirects=True)
```

**Comment by jmbreuer** [comment]
I've tried adding the cookie as described, no change for me - I still get `Unknown hostname "consent.youtube.com"` in the log.

**Comment by MoojMidge** [comment]
Can you visit the same video using a web browser and check what cookies have been set when the page loads?

**Comment by MoojMidge** [comment]
Your log snippets are a little too pared back so didn't realise this before, but the reason why this won't work is because the common resolver is probably being redirected to `consent.youtube.com`, before the youtube resolver with the consent cookies set, even gets to it.

Try both of the following changes together:
https://github.com/MoojMidge/plugin.video.youtube/commit/fb40d578183b79f780d0658e0359c7aa36fb86b5
https://github.com/MoojMidge/plugin.video.youtube/commit/68a6c750669f978743ad3737dcc9632c1bbdf1a2

and provide everything YouTube related between
```
[plugin.video.youtube] Running: YouTube (7.0.3.2+matrix.1) on Omega (Kodi-21.0) with Python 3.11.8
                                                   Path: /uri2addon/
                                                   Params: {'uri': 'https://youtube.com/shorts/V8lcY6a1BDc'}
```
and 
```
2024-03-13 09:29:51.737 T:1027176   debug <general>: [plugin.video.youtube] Unknown hostname "consent.youtube.com" in url "https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fshorts%2FV8lcY6a1BDc%3Fcbrd%3D1&gl=DE&m=0&pc=yt&cm=2&hl=en&src=1"
```

**Comment by jmbreuer** [comment]
... is there a repository I could install the pre-release versions from?

**Comment by jmbreuer** [comment]
Anyway, the problematic video plays fine for me in 7.0.4+beta.2. Great!

**Comment by MoojMidge** [comment]
The development releases are only available on Github at the moment, but the intent is to get the development repository back up and running at some stage.
