### ISSUE TITLE
1080p60Hz video jittery in 7.0.3.2 but stable on 7.0.2.2 (raspberry pi3)

### ISSUE THREAD

**Issue by arprakash27** [anxdpanic/plugin.video.youtube#635]
### Context

Please provide any relevant information about your setup

* Add-on Version:7.0.3.2
* Kodi Version:20.3
* Kodi GUI Language: English
* Operating System: OSMC [2024.02-1](https://ftp.fau.de/osmc/osmc/download//installers/diskimages/OSMC_TGT_rbp2_20240205.img.gz)
* Operating System Language: English

Hardware: Raspbery Pi 3 1GB Ram

------

### Expected Behavior
1080p 60Hz videos working fine till youtube7.0.2.2, 
Please describe the behavior you are expecting.

------

### Current Behavior
1080p 60Hz videos are now verry jittery(but plays) in youtube 7.0.3.2 
also gets auto fastforwaded as video lags behind audio and after a while of drift in audio and video.
1080p 24Hz videos plays fine.
What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install osmc on raspberry pi 3
2. install kodi addon
3. search for oled demo video (there is a lg demo video thumbnail of honey)
4. play the video.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Post a debug log as requested, otherwise nothing can be done

**Comment by MoojMidge** [comment]
I don't think the RPi3 is capable of 1080p60 without an overclock, or even 1080p30 depending on the video codec being used.

Next release will add recommended settings for the RPi3 or similar devices to limit playback to 1080p30. It will still have VP9 enabled as I am unsure whether the RPi3 can handle 1080p30 VP9. If it can't then unfortunately many videos will be limited to 720p.
