### ISSUE TITLE
New version works great! Only one problem, plugin://plugin.video.youtube/play/?playlist_id=$PLAYLISTID plays only the first video ...

### ISSUE THREAD

**Issue by Lenten1965** [anxdpanic/plugin.video.youtube#640]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* Kodi Version:
* Kodi GUI Language:
* Operating System:
* Operating System Language:

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by musicmagix** [comment]
Please fill in (all) the issue details above. Otherwise no-one can help you.

**Comment by w64** [comment]
When playlist is loaded via plugin://plugin.video.youtube/play/?play=1&order=shuffle&**playlist_id**=.........,
the player stops after first video is over. Playlists are listed correctly, order is applied too, but continuous playback isn't working. Logs shows only loss of synchronization between video and audio streams.

    Add-on Version: v7.0.4+beta.1
    Kodi Version: 20.5
    Kodi GUI Language: English
    Operating System: Ubuntu 22.04
    Operating System Language: English

**Comment by musicmagix** [comment]
You haven't filled in any issue details. What version of the plugin do you use on what hardware? What Kodi version? 
I'm far from being a pro here but it should be apparent that an issue can only be addressed when there is enough information about what to look for.  Check the other issues for this plugin. The first post shows you the important facts.

**Comment by MoojMidge** [comment]
How do you expect anyone to help you when you don't provide any information?

Everything works fine for me and continuous playback within a playlist doesn't have anything to do with this plugin anyway, it is core Kodi functionality.

Could play guessing games to try and figure out what addons or settings you have that would cause that, but I am not going to bother.

If you want help post a debug log.
