### ISSUE TITLE
Feature Request: Disable Date Field 

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#644]
Can there please be an option to disable the Date Field when using the "WideList" view. I do believe WideList is the default Kodi view. 

Thanks for all your work MoojMidge

**Comment by MoojMidge** [comment]
You will need to be a little bit more specific. Can you post a screenshot with what you want to disable highlighted? 

Alternatively this may have already been implemented. Try disabling `Settings > Advanced > Show video details in video lists` and see if that does what you want.

**Comment by neo-neo1** [comment]
> You will need to be a little bit more specific. Can you post a screenshot with what you want to disable highlighted?
> 
> Alternatively this may have already been implemented. Try disabling `Settings > Advanced > Show video details in video lists` and see if that does what you want.

Thanks, that did it. I was on an older beta, I believe the testing Kodi repo is out of date?

However, is it possible to still enable the date field when searching? It makes more sense to see a video's date when searching rather than subscriptions - where I prefer it disabled. 

Also, is would it be possible to have an option to enable the channel's name on the same line? Similar to how the Twitch Addon has it: "Channel Name" - "Video Title" as in the attached photo:

![IMG_20240328_171417](https://github.com/anxdpanic/plugin.video.youtube/assets/6996362/126ad1ba-dccd-4210-b13f-e3f8f5f25e14)

**Comment by MoojMidge** [comment]
My plan is to eventually make the unofficial versions support different sort orders and directions for different views, but it is not straightforward as Kodi does not properly support this functionality for plugins.

The details in the listing changes depending on the sort used which can be changed by opening the side menu.

However if you have disabled `Show video details in video lists` then none of the details will show up regardless of the sort order used.

There are only two sort orders that support the required masking to show these details ‐ default/unsorted and (live TV) channel sorting, so it is not practical to make the `Show video details in video lists` setting something that can be changed on the fly using the UI, which was why the setting needed to be created in the first place.

I am not keen to create even more settings for this, too much work, and very few people would make use of it. However I can see whether the live TV channel sorting can be used to display the Youtube channel name.
