### ISSUE TITLE
Sporadically next video in play list will not start

### ISSUE THREAD

**Issue by wagnerch** [anxdpanic/plugin.video.youtube#649]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4+nexus.1
* Kodi Version: 21.0rc2
* Kodi GUI Language: English
* Operating System: LibreELEC 12 nightly
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Next video in playlist should start/play.

------

### Current Behavior

What is the current behavior?

After current video is finished, bails out to home screen.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add videos to play list
2. Wait for failure
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

This seems to be the relevant error:
2024-03-25 20:38:34.351 T:2584906   error <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist reloaded to prevent Kodi crash
...
2024-03-25 20:38:34.357 T:2584807   error <general>: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.youtube/play/?video_id=vZSbnZiBq5s&incognito

https://paste.libreelec.tv/magical-fly.log

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by wagnerch** [comment]
Removing [these lines](https://github.com/anxdpanic/plugin.video.youtube/blob/6ca0b94ad198ddcfccbc7180eabcb3c747f09574/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py#L119-L124) seems to solve this issue.

The crashing that this code is trying to solve is indeed a problem, but usually it only happens if I am adding an video to the play list or manipulating the play list while the next video is being cycled in the play list.  I usually use the Cast Kodi browser plug-in to add videos & manipulate the play list.

**Comment by MoojMidge** [comment]
A few things to note:

1. The lines that were removed are a workaround to a core Kodi bug, and acts to prevent a whole class of issues that result in Kodi crashing when using this plugin.
The crashes are reproducible and can happen without any user interaction at all, not just when the user is performing completely normal user actions.
Simply removing the workaround is not a fix I am willing to consider, since it will simply result in all those other crashes re-occuring.
2. The workaround may also activate in situations where Kodi does not end up crashing (a false positive) as the ability for the plugin to detect when the crash may occur is limited to when the plugin is actually running, while the crash occurs in between plugin invocations and depends on the timing of specific Kodi internal actions, that may end up not triggering the crash depending on when they start and how long they take to complete.

If you are willing to help testing then I think the workaround may be able to be improved to either:
a) automatically resume after a delay; or
b) open the playlist window and provide a notification to restart playback manually.

Can you reliably replicate a scenario where the next video in playlist does not start? If so can you provide a link to the videos and/or playlist? I know one way to do this is to have a playlist with private or deleted videos in it. When the unavailable video tries and fails to play, Kodi may crash when starting the next video.

Can you provide a copy of your plugin settings? Normally with debug logging activated, the plugin settings should get logged, but this doesn't seem to work when debug logging is active using `advancedsettings.xml`.
The plugin settings are located at `/storage/.kodi/userdata/addon_data/plugin.video.youtube/settings.xml`.
Please ensure to remove the following settings before sharing:
```
<setting id="youtube.region">XXX</setting>
<setting id="youtube.location">XXX</setting>
<setting id="youtube.api.key">XXX</setting>
<setting id="youtube.api.id">XXX</setting>
<setting id="youtube.api.secret">XXX</setting>
```


Instead of removing the [lines you identified previously](https://github.com/anxdpanic/plugin.video.youtube/blob/6ca0b94ad198ddcfccbc7180eabcb3c747f09574/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py#L119-L124), can you instead make the following changes:
https://github.com/anxdpanic/plugin.video.youtube/blob/6ca0b94ad198ddcfccbc7180eabcb3c747f09574/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py#L45-L57
Change to:
```
            if ui.busy_dialog_active():
                context.log_error('Multiple busy dialogs active - Kodi may crash')
                ui.show_notification('Multiple busy dialogs active - Kodi may crash')
                '''
                playlist = XbmcPlaylist('video', context)
                playlist.clear()

                xbmcplugin.endOfDirectory(self.handle, succeeded=False)

                items = ui.get_property('playlist')
                if items:
                    ui.clear_property('playlist')
                    playlist.add_items(items, loads=True)
                    context.log_error('Multiple busy dialogs active - '
                                      'playlist reloaded to prevent Kodi crash')
                return False
                '''
```
This will log an error in the Kodi log and show a visible notification if the workaround would normally activate. If you start seeing this but don't see Kodi actually crash then we can prove that these are false positives and look to try and improve the workaround.

**Comment by wagnerch** [comment]
I made the changes suggested, so when it switched video it:
a) worked fine
b) saw the notification


settings.xml (with noted keys removed);
```
<settings version="2">
    <setting id="kodion.setup_wizard">false</setting>
    <setting id="kodion.setup_wizard.forced_runs">2</setting>
    <setting id="kodion.mpd.videos" default="true">true</setting>
    <setting id="kodion.mpd.stream.select">1</setting>
    <setting id="kodion.video.quality.ask" default="true">false</setting>
    <setting id="kodion.mpd.quality.selection" default="true">4</setting>
    <setting id="kodion.video.quality">4</setting>
    <setting id="kodion.mpd.stream.features">avc1,hfr,vorbis,opus,mp4a,ssa,ac-3,ec-3,dts,filter</setting>
    <setting id="kodion.audio_only" default="true">false</setting>
    <setting id="kodion.subtitle.languages.num" default="true">0</setting>
    <setting id="kodion.subtitle.download" default="true">false</setting>
    <setting id="kodion.content.max_per_page" default="true">50</setting>
    <setting id="youtube.hide_shorts" default="true">false</setting>
    <setting id="youtube.suggested_videos" default="true">false</setting>
    <setting id="youtube.post.play.rate" default="true">false</setting>
    <setting id="youtube.post.play.rate.playlists" default="true">false</setting>
    <setting id="kodion.safe.search" default="true">0</setting>
    <setting id="kodion.age.gate" default="true">true</setting>
    <setting id="youtube.allow.dev.keys" default="true">true</setting>
    <setting id="youtube.api.config.page" default="true">false</setting>
    <setting id="youtube.folder.sign.in.show" default="true">true</setting>
    <setting id="youtube.folder.my_subscriptions.show" default="true">true</setting>
    <setting id="youtube.folder.my_subscriptions_filtered.show" default="true">false</setting>
    <setting id="youtube.filter.my_subscriptions_filtered.blacklist" default="true">false</setting>
    <setting id="youtube.filter.my_subscriptions_filtered.list" default="true" />
    <setting id="youtube.folder.recommendations.show" default="true">true</setting>
    <setting id="youtube.folder.related.show" default="true">true</setting>
    <setting id="youtube.folder.popular_right_now.show" default="true">true</setting>
    <setting id="youtube.folder.search.show" default="true">true</setting>
    <setting id="youtube.folder.quick_search.show" default="true">false</setting>
    <setting id="youtube.folder.quick_search_incognito.show" default="true">false</setting>
    <setting id="youtube.folder.my_location.show" default="true">true</setting>
    <setting id="youtube.folder.my_channel.show" default="true">true</setting>
    <setting id="youtube.folder.purchases.show">true</setting>
    <setting id="youtube.folder.watch_later.show" default="true">true</setting>
    <setting id="youtube.folder.watch_later.playlist" default="true" />
    <setting id="youtube.folder.liked_videos.show" default="true">true</setting>
    <setting id="youtube.folder.disliked_videos.show" default="true">true</setting>
    <setting id="youtube.folder.history.show" default="true">true</setting>
    <setting id="youtube.folder.history.playlist" default="true" />
    <setting id="youtube.folder.playlists.show" default="true">true</setting>
    <setting id="youtube.folder.saved.playlists.show">true</setting>
    <setting id="youtube.folder.subscriptions.show" default="true">true</setting>
    <setting id="youtube.folder.browse_channels.show" default="true">true</setting>
    <setting id="youtube.folder.completed.live.show" default="true">true</setting>
    <setting id="youtube.folder.upcoming.live.show" default="true">true</setting>
    <setting id="youtube.folder.live.show" default="true">true</setting>
    <setting id="youtube.folder.switch.user.show" default="true">true</setting>
    <setting id="youtube.folder.sign.out.show" default="true">true</setting>
    <setting id="youtube.folder.settings.show" default="true">true</setting>
    <setting id="youtube.folder.settings.advanced.show" default="true">false</setting>
    <setting id="youtube.client.selection" default="true">0</setting>
    <setting id="kodion.support.alternative_player" default="true">false</setting>
    <setting id="kodion.alternative_player.web.urls" default="true">false</setting>
    <setting id="kodion.video.quality.isa" default="true">true</setting>
    <setting id="kodion.live_stream.selection.1" default="true">2</setting>
    <setting id="kodion.live_stream.selection.2" default="true">0</setting>
    <setting id="kodion.history.local">false</setting>
    <setting id="kodion.history.remote" default="true">false</setting>
    <setting id="kodion.cache.size">10</setting>
    <setting id="kodion.search.size" default="true">10</setting>
    <setting id="youtube.view.description.details" default="true">true</setting>
    <setting id="youtube.view.label.details" default="true">true</setting>
    <setting id="youtube.view.label.color.viewCount" default="true">ffadd8e6</setting>
    <setting id="youtube.view.label.color.likeCount" default="true">ff00ff00</setting>
    <setting id="youtube.view.label.color.commentCount" default="true">ff00ffff</setting>
    <setting id="kodion.thumbnail.size" default="true">1</setting>
    <setting id="kodion.fanart.show" default="true">true</setting>
    <setting id="youtube.channel.fanart.show" default="true">true</setting>
    <setting id="youtube.language">en</setting>
    <setting id="youtube.location.radius" default="true">500</setting>
    <setting id="kodion.play_count.percent" default="true">85</setting>
    <setting id="youtube.playlist.watchlater.autoremove" default="true">true</setting>
    <setting id="youtube.post.play.refresh" default="true">false</setting>
    <setting id="requests.ssl.verify" default="true">true</setting>
    <setting id="requests.timeout.connect" default="true">9</setting>
    <setting id="requests.timeout.read" default="true">27</setting>
    <setting id="kodion.http.listen" default="true">0.0.0.0</setting>
    <setting id="kodion.http.port" default="true">50152</setting>
    <setting id="kodion.http.ip.whitelist" default="true" />
    <setting id="kodion.access_token" default="true" />
    <setting id="kodion.access_token.expires" default="true">0</setting>
    <setting id="kodion.mpd.hdr" default="true">true</setting>
    <setting id="kodion.mpd.limit.30" default="true">false</setting>
    <setting id="kodion.mpd.live_stream.selection.1" default="true">0</setting>
    <setting id="kodion.mpd.live_stream.selection.2" default="true">0</setting>
    <setting id="kodion.mpd.live_streams" default="true">true</setting>
    <setting id="kodion.mpd.proxy.port" default="true">50152</setting>
    <setting id="kodion.playback.history" default="true">true</setting>
    <setting id="kodion.refresh_token" default="true" />
    <setting id="kodion.video.quality.mpd" default="true">true</setting>
    <setting id="simple.requests.ssl.verify" default="true">true</setting>
    <setting id="youtube.api.last.hash" default="true" />
    <setting id="youtube.view.description.show_channel_name" default="true">true</setting>
</settings>
```

**Comment by wagnerch** [comment]
Just to add, this problem happens on any video pretty much.  I don't use Youtube playlists, what I do is use Cast Kodi browser plugin, right click on the video and hit Cast Kodi -> Play (on the 1st one)/Queue (on subsequent ones).  So I am dropping individual YouTube videos into the playlist.

I have an Allwinner H6 device (Orange Pi 3 LTS) and it is running same/similar version of both LE & addon and it doesn't seem to have any issue.  Not sure if that is because the H6 is slightly slower (CPU-wise) than the RPi4 or it's something else, but I am assuming it is "timing sensitive".  There is also cases where the RPi4 can play next video without an issue (but usually not).

**Comment by MoojMidge** [comment]
> I made the changes suggested, so when it switched video it:
> a) worked fine
> b) saw the notification

That is good to know - these are all false positives.

> but I am assuming it is "timing sensitive"

Yep, that's why it is difficult to try and do anything about it from within the plugin, but let's see what can be done.

I'll create a new branch for you to test a bit later on.

**Comment by MoojMidge** [comment]
Can you test whether https://github.com/MoojMidge/plugin.video.youtube/tree/master allows playback to resume properly?

**Comment by wagnerch** [comment]
> Can you test whether https://github.com/MoojMidge/plugin.video.youtube/tree/master allows playback to resume properly?

I got the notification and the playlist was empty.  (EDIT: The notification was after the 1st video finished, there was only 2 videos in the playlist, so perhaps an off-by-one or some other cause)

**Comment by MoojMidge** [comment]
Can you provide a log?

**Comment by wagnerch** [comment]
> Can you provide a log?

This time the playlist appears to be intact.

https://paste.libreelec.tv/endless-sunfish.log

I also had the notification once before but it resumed with the playlist without an issue.

**Comment by wagnerch** [comment]
Here is the same debug log, where the 2nd occurrence it popped the notification but resumed anyways (which I assume is by design based on the retry/busy wait loop).

https://paste.libreelec.tv/main-killdeer.log

**Comment by MoojMidge** [comment]
It's complicated.

The actual loading of the playlist is done asynchronously to what the plugin is doing and the loading creates its own busy dialogs as well.

Not sure if it is going to be possible to automatically restart playback.

**Comment by MoojMidge** [comment]
https://github.com/MoojMidge/plugin.video.youtube/tree/master is updated. Can you test if that works any better?
