### ISSUE TITLE
my subscriptions Empty

### ISSUE THREAD

**Issue by StyleHack** [anxdpanic/plugin.video.youtube#650]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4
* Kodi Version: 20.5
* Kodi GUI Language: German
* Operating System: Windows 11
* Operating System Language: German

------

As of today, I no longer have any entries in "my subscriptions"

Update: 7.0.4-beta.1-matrix works on nexus

**Comment by StyleHack** [comment]
Why was it closed? The error still exists.

**Comment by MoojMidge** [comment]
Directly above your last post is a message saying this issue is closed as `not planned (Won't fix, can't repro, duplicate, stale)`. Can't reproduce to be specific.

**Comment by MoojMidge** [comment]
If you are having this problem, a debug log is required to investigate further.
