### ISSUE TITLE
Endless "Configure Settings?"

### ISSUE THREAD

**Issue by M-Reimer** [anxdpanic/plugin.video.youtube#652]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4
* Kodi Version: 21.0
* Kodi GUI Language: English
* Operating System: LibreElec
* Operating System Language: English

------

### Expected Behavior

Setup Wizard should stop bugging me at some point

------

### Current Behavior

I can choose "Yes" up to the "IP geo location step" (which I would rather answer with "No") and then the setup wizard stops. Any future selection (like starting a video) will now always bring up the setup wizard again and I have to choose "No" to make it disappear.

I have setup wizard turned off in settings but it still keeps appearing.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Open YouTube Add-on. That's all it needed in my case.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Can't reproduce.

A debug log is required to investigate further.

**Comment by M-Reimer** [comment]
I had some time today and as YouTube watching really sucked with the reappearing setup wizard, I decided to either find the reason or get a debug log.

So I started with upgrading to the latest LibreElec Beta release. And with that the setup somehow got fixed. It only appeared once. I still got some error before selecting the language, but seems to not have caused any problems. And the setup wizard did not run all the way to "8 of 8" but stopped before that. I don't know what "8 of 8" would have been and why it decided to not offer me that.

**Comment by MoojMidge** [comment]
> So I started with upgrading to the latest LibreElec Beta release. And with that the setup somehow got fixed. It only appeared once.

You were probably using a really old version of Kodi v21, alpha 1 or earlier, which had a bug where the settings didn't get saved.

> I still got some error before selecting the language

What is the error?

> And the setup wizard did not run all the way to "8 of 8" but stopped before that. I don't know what "8 of 8" would have been and why it decided to not offer me that.

There are a number of steps that are only run if required, such as offering to migrate old user data if it exists. If it doesn't exist then the steps are skipped.
