### ISSUE TITLE
Youtube Addon crashes right after startup after freshly installing on Kodi...

### ISSUE THREAD

**Issue by cbladeOfficial** [anxdpanic/plugin.video.youtube#658]
### Context

Please provide any relevant information about your setup

I made an HTPC from an old computer, I couldnt install libreelec so I used windows7 to get the job done. The addon installed properly but keep showing me the same error "Youtube error: Check log ...". I have tried script.module.request.zip install fix but still does not work. Nothing more than that. I really need to fix this no matter how.

I spent the whole day trying to fix this.

Please help if you can. Thank you in advance.

log: https://paste.kodi.tv/anakokihuv.kodi

* Add-on Version: 7.0.4 nexus
* Kodi Version: 20.5 Nexus
* Kodi GUI Language: english
* Operating System: Windows 7 32-Bit
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Should not crash after startup and should be able to play videos after API configuration...

------

### Current Behavior

What is the current behavior?

Crashing right after startup and installing the addon, even when nothing was configured...

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the addon on Windows 7 Kodi
2. Run it
3. It should show the message "Youtube error: check log for more info."

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

log: https://paste.kodi.tv/anakokihuv.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

I have not found a fix for this...

------

**Comment by MoojMidge** [comment]
There is no error with plugin.video.youtube in your log, you don't even have it installed.

Your Kodi installation is broken and appears to either be missing or has the wrong version of a bunch of binary Python modules.

**Comment by cbladeOfficial** [comment]
I had it but then removed it.../
I will check  the modules later...

**Comment by cbladeOfficial** [comment]
Also what version of modules do i need?
And the errors for the other plugins are the same as this, also I will again post a log with Youtube addon this time...

**Comment by MoojMidge** [comment]
A log with this plugin installed will serve no purpose. Your problem has nothing to do with this plugin.

Your Kodi installation is broken. Maybe your hard drive is failing, maybe your antivirus quarantined/deleted the required files, maybe you installed over an old installation and the installer was not able to install the upgraded files. Could be any number of reasons. Try reinstalling to a new location.

But this is not a general support forum and no further assistance can be provided.
