### ISSUE TITLE
The following content is not available on this app. Watch this content on the latest version of YouTube

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#659]
![Screenshot_20240328-163356](https://github.com/anxdpanic/plugin.video.youtube/assets/6996362/d6715548-1241-4442-93ec-b15307baab63)

### Context

Opening a specific video causes said error:

[YouTube Video Link](https://www.youtube.com/watch?v=Qa4VEGwO0js)

* Add-on Version: 7.0.4 Nexus.1
* Kodi Version: 20.5
* Kodi GUI Language: English 
* Operating System: CoreELEC
* Operating System Language: English 

------

### Note

Revanced YouTube 19.04.37 (Side loaded Android App) also has the same error on this video. Which is several versions behind the current YouTube app in Google Play Store.

------

**Comment by karlo2105** [comment]
Update to the latest Youtube 7.0.5 beta 1 [development build](https://github.com/anxdpanic/plugin.video.youtube/archive/refs/heads/master.zip) which resolves issues.

**Comment by neo-neo1** [comment]
> Update to the latest Youtube 7.0.5 beta 1 [development build](https://github.com/anxdpanic/plugin.video.youtube/archive/refs/heads/master.zip) which resolves issues.

Thanks that fixed it.

I checked for updates on my Kodi device before posting and it didn't have anything newer. Seems the beta repo is out of date.

Also I noticed there is no specific Nexus release. I used: plugin.video.youtube-7.0.5+beta.1.matrix.1.zip

**Comment by stephematician** [comment]
I updated the app as per these instructions, but it now fails to do any search/video playing. Will attempt a clean install and see how it goes.

**Comment by MoojMidge** [comment]
If you have a problem then post a debug log.

No one has provided a debug log, can't do much when no information is provided.

**Comment by stephematician** [comment]
Will do once I have some more time to investigate. Thanks.

**Comment by DjDiabolik** [comment]
Try to upgrade right now to 7.0.5 beta 1...... lol

*EDIT*
It's now the (Matrix/Nexus/Omega) version as join in a single zip files ??

**Comment by Bingo-Joe** [comment]
@stephematician I experienced the same behaviour as you described, and found the cause to be a small bug in the code, which this PR fixes:
https://github.com/anxdpanic/plugin.video.youtube/pull/662

Exception showed up in `kodi.log` as:
```
2024-03-29 09:22:48.652 T:922     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'str' object is not callable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 61, in run
                                                       plugin.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 120, in run
                                                       items = [
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 123, in <listcomp>
                                                       else video_listitem(context, item, show_fanart)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 626, in video_listitem
                                                       set_info(list_item, video_item, props)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 73, in set_info
                                                       value = item.get_premiered(as_info_label=True)()
                                                   TypeError: 'str' object is not callable
                                                   -->End of Python script error report<--
```
Bug seems to have been introduced by this commit: https://github.com/anxdpanic/plugin.video.youtube/commit/5ffe33403d5eca6b2125997385f09678608e9af1

**Comment by teodoryantcheff** [comment]
can confirm: 

```
2024-03-29 19:11:15.174 T:1241     INFO <general>: [plugin.video.youtube] Running: YouTube (7.0.5+beta.1+matrix.unofficial.1) on Matrix (Kodi-19.5) with Python 3.8.9
                                                   Path: /play/
                                                   Params: {'video_id': 'MWjOAIihKjU'}
2024-03-29 19:11:15.205 T:1241    ERROR <CSettingInt>: error reading <control> tag of "youtube.view.label.color.viewCount"
2024-03-29 19:11:15.205 T:1241  WARNING <CSettingGroup>: unable to read setting "youtube.view.label.color.viewCount"
2024-03-29 19:11:15.205 T:1241    ERROR <CSettingInt>: error reading <control> tag of "youtube.view.label.color.likeCount"
2024-03-29 19:11:15.205 T:1241  WARNING <CSettingGroup>: unable to read setting "youtube.view.label.color.likeCount"
2024-03-29 19:11:15.206 T:1241    ERROR <CSettingInt>: error reading <control> tag of "youtube.view.label.color.commentCount"
2024-03-29 19:11:15.206 T:1241  WARNING <CSettingGroup>: unable to read setting "youtube.view.label.color.commentCount"
2024-03-29 19:11:17.343 T:1241    ERROR <general>: EXCEPTION: Invalid setting type
2024-03-29 19:11:23.405 T:1241     INFO <general>: Skipped 2 duplicate messages..
2024-03-29 19:11:23.405 T:1241    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'str' object is not callable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 61, in run
                                                       plugin.run(provider, context)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 113, in run
                                                       return self._set_resolved_url(context, result, show_fanart)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 169, in _set_resolved_url

                                                       item = playback_item(context, base_item, show_fanart)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 646, in playback_item
                                                       return video_playback_item(context, base_item, show_fanart)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 414, in video_playback_item

                                                       set_info(list_item, video_item, props)
                                                     File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 73, in set_info
                                                       value = item.get_premiered(as_info_label=True)()
                                                   TypeError: 'str' object is not callable
                                                   -->End of Python script error report<--

2024-03-29 19:11:24.621 T:1241     INFO <general>: Python interpreter stopped
2024-03-29 19:11:24.701 T:709     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=MWjOAIihKjU]
2024-03-29 19:11:40.849 T:1295     INFO <general>: initializing python engine.```

**Comment by MoojMidge** [comment]
Try https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.2 and provide a debug log, even if it works.

Only one single person has provided so far, and there is simply not enough information being provided by the seemingly large number of people who are effected by this, to determine if the current fixes are sufficient or whether more needs to be done.

If people don't provide information then nothing can be done to fix the problems.

**Comment by das-osi** [comment]
@MoojMidge 
https://pastebin.com/raw/sk38XCBh
this is a working log with the current beta

**Comment by Jkh62** [comment]
Youtube 7.0.5 beta update fixed it for me.
Nice work!

**Comment by xyzfre** [comment]
Same 7.0.5 beta 2 fixed the issue for me thank you💯

**Comment by MoojMidge** [comment]
@das-osi - thanks for that. Unfortunately I specifically need a debug log to provide the required information to confirm whether the problem is fully resolved or needs further changes. If you can, please install https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.2 
and create a debug log showing the successful playback https://kodi.wiki/view/Log_file/Easy

Everyone else - this problem does not apply to everyone and has not effected me. I have no way to test whether the changes will work or whether they will simply fail again at some point. The only way to resolve the issue is if you provide a debug log. Simply saying it works or it doesn't work serves no purpose. If you want the problem fixed you need to provide the information required to fix it.

**Comment by BobbyBabes** [comment]
> @das-osi - …..
If you want the problem fixed you need to provide the information required to fix it.

How about you making the YT add-on more robust?
It should recognise these rejections and then display information relevant to you, the developer. Yes corrupt the screen to screenshot it (with Ctrl+s). And also explain what to do, on screen, for the end user. E.g. how to enable debug logging, and then (when enabled) send the debug log from the add-on, if Kodi permits.

**Comment by MoojMidge** [comment]
> How about you making the YT add-on more robust?

Sure, go ahead and submit a PR to do so.

> It should recognise these rejections and then display information relevant to you, the developer.

It already does.

> And also explain what to do, on screen, for the end user. E.g. how to enable debug logging, and then (when enabled) send the debug log from the add-on, if Kodi permits.

How is displaying it on the screen with limited real estate for a short duration going to be clearer? I explained what should be done, the issue template describes what needs to be done, the Kodi wiki eplains what needs to be done, and yet you still decided it was more worthwhile to contribute nothing useful.

**Comment by BobbyBabes** [comment]
> > How about you making the YT add-on more robust?
> 
> Sure, go ahead and submit a PR to do so.
> 
> > It should recognise these rejections and then display information relevant to you, the developer.
> 
> It already does.
> 
> > And also explain what to do, on screen, for the end user. E.g. how to enable debug logging, and then (when enabled) send the debug log from the add-on, if Kodi permits.
> 
> How is displaying it on the screen with limited real estate for a short duration going to be clearer? I explained what should be done, the issue template describes what needs to be done, the Kodi wiki eplains what needs to be done, and yet you still decided it was more worthwhile to contribute nothing useful.

Ostrich policy.
Like big corporations. Marketing what they can do for you. But when issues are pointed out, they only tell you what they can’t do for anybody.
Go ahead and mark my comment as off-topic again. Enjoy your day. I know that I will. Especially without you.

**Comment by MoojMidge** [comment]
> Ostrich policy.
> Like big corporations. Marketing what they can do for you. But when issues are pointed out, they only tell you what they can’t do for anybody.

Lol...

Your comments are of no useful value and you are not pointing out any issues.

I already identified what can be done to help. You don't have to contribute of course, but rather than just do nothing, you would rather provide useless complaints instead.

> Go ahead and mark my comment as off-topic again

Sure.

**Comment by BobbyBabes** [comment]
Ostrich policy.
Like a dictator of a banana republic.

**Comment by BobbyBabes** [comment]
@MoojMidge What you refuse to (or cannot) understand is that not many users of this add-on are aware of GitHub, and even less are able to produce a debug log. Even when chewed up for them. Because all they want, and know to do, is to play their YT videos on their TVs, and other devices. Each user of your add-on posting on GH, most likely represents thousands of others with the same issue. What I’m saying is that you need to gather the information yourself. You will then have it from thousands of different users. And I t probably needs you to acquire them to give up some of their privacy for reporting back to you. But if you prefer to misinterpret my first comment, I wish you luck and respect your decision(s).

**Comment by MoojMidge** [comment]
> What I’m saying is that you need to gather the information yourself

I don't need to do anything. Do you bring your car to a mechanic and ask them to guess what the problem may be? How about ordering food at a restaurant - do you ask the waiter to guess what you want to eat?

I don't owe you anything. If you want help, you need to provide the information required to get that help. Otherwise just move on, rather than wasting everyones time.

> You will then have it from thousands of different users.

Are you offering to manage thousands of bug reports and logs? Why would I want to?

> And I t probably needs you to acquire them to give up some of their privacy for reporting back to you.

And now you are starting to think a little about the practicalities of what you are suggesting.

> But if you prefer to misinterpret my first comment, I wish you luck and respect your decision(s).

I would prefer it if you just provided a debug log, that's all.

**Comment by BobbyBabes** [comment]
> > What I’m saying is that you need to gather the information yourself
> 
> I don't need to do anything. Do you bring your car to a mechanic and ask them to guess what the problem may be? How about ordering food at a restaurant - do you ask the waiter to guess what you want to eat?
> 
> I don't owe you anything. If you want help, you need to provide the information required to get that help. Otherwise just move on, rather than wasting everyones time.
> 
> > You will then have it from thousands of different users.
> 
> Are you offering to manage thousands of bug reports and logs? Why would I want to?
> 
> > And I t probably needs you to acquire them to give up some of their privacy for reporting back to you.
> 
> And now you are starting to think a little about the practicalities of what you are suggesting.
> 
> > But if you prefer to misinterpret my first comment, I wish you luck and respect your decision(s).
> 
> I would prefer it if you just provided a debug log, that's all.

You can suck the answer to all of your responses out of my poop hole and swallow. Now please report me, you loser.

**Comment by BobbyBabes** [comment]
You @MoojMidge are such a cunt. And a sorry ass developer.

**Comment by xyzfre** [comment]
Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.

**Comment by MoojMidge** [comment]
@xyzfre - thanks for the kind words. There are lots of people who contribute time and effort to others for free, never really understood why that brings out such a sense of entitlement in some.

**Comment by Jkh62** [comment]
It can't be fixed when you don't know what's broke.
I understand log files are a huge help in trouble shooting. I will try to get some log entries after I figure out how to grab a them.

**Comment by MoojMidge** [comment]
@Jkh62 - please hold off, as a few people have already provided logs now, and that is sufficient for the moment. A new release will be available shortly which should resolve the issue.

**Comment by BobbyBabes** [comment]
> Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.

Did you swallow?

**Comment by xyzfre** [comment]
> > Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.
> 
> 
> 
> Did you swallow?

Thank you so much this got me cracking up on top of that. You like your own comment 6 times you are pathetic man let it go bro get a life I just can't stop laughing. Thank you so much 😂🤣😂

**Comment by xyzfre** [comment]
> > Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.
> 
> 
> 
> Did you swallow?

You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again lol

**Comment by xyzfre** [comment]
> > > Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.
> > 
> > 
> > 
> > Did you swallow?
> 
> You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again and keep liking your own comments that's the saddest thing a person can do on these posts so sad when you have to like your own😂🤣😂🤣😂🤣😂

**Comment by xyzfre** [comment]
> > > Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.
> > 
> > 
> > 
> > Did you swallow?
> 
> You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again lol

You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again and keep liking your own comments that's the saddest thing a person can do on these posts so sad when you have to like your own😂🤣😂🤣😂🤣😂

**Comment by BobbyBabes** [comment]
> > > > Thank you @MoojMidge you are an amazing developer. You have done so much work YT addon and that's why it continues to work. Glad to see you deleted those stupid post people can be so ignorant but anyway, keep up the great work my friend.
> > > 
> > > 
> > > Did you swallow?
> > 
> > 
> > You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again lol
> 
> You're talking Hella shit, but when he gets it working, you're gonna be swallowing it too ahh man This is so fucking funny dude thank you again and keep liking your own comments that's the saddest thing a person can do on these posts so sad when you have to like your own😂🤣😂🤣😂🤣😂

That’s why you added smileys to your own comment. You rent boys swallow. Just Do It!

**Comment by MoojMidge** [comment]
@BobbyBabes - don't you have anything better to do? I really don't understand why you decided that the request for a debug log was so unreasonable, but your opinions and comments are of no use here. Just move along.

**Comment by MoojMidge** [comment]
~https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.3~

**Comment by MoojMidge** [comment]
v7.0.5+beta.3 was buggy, v7.0.5+beta.4 should resolve the problem:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4
