### ISSUE TITLE
Bug: Watch Later gives error; url watch later changed

### ISSUE THREAD

**Issue by vermope** [anxdpanic/plugin.video.youtube#66]
Hi, I've got following error: 

2020-12-14 11:46:29.954 T:139673262163712   ERROR: [plugin.video.youtube] Error reason: |playlistNotFound| with message: |The playlist identified with the request's playlistId parameter cannot be found.|
2020-12-14 11:46:29.959 T:139675842225920   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/channel/mine/playlist/%20WL/

Could it be that the url on Youtube has changed? 
https://www.youtube.com/playlist?list=WL

**Comment by AlexNk** [comment]
Same error with the same log.
Re-trying one or more times usually helps. 
First observed with rev. 6.8.8

I guess it's something about extra "%20" before the playlist name.

**Comment by anxdpanic** [comment]
It hasn't worked well/consistently for a long time. the `%20` in intended.

Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as Watch Later`
That will be your Kodi watch later playlist, it's a pita but it's the only alternative atm.

**Comment by vermope** [comment]
Okido, was already thinking in that direction. The weird thing it's working perfectly in the add-on but used as a widget it gives the error. Thanks for thinking along.

**Comment by Rialtho-the-Magnificent** [comment]
I did create a new (youtube) playlist and moved my videos into that new list. Than I used the option to 'show playlists' and selected the one I created. This does work, but I do not understand why this is all of a sudden necessary.  Now, selecting 'later bekijken' (Watch later) does not work at all all of a sudden. Yesterday I was still able. The option to 'set as Watch Later'  I cannot find. Where does that option reside? In the YT add-on ? Or somewhere else in Kodi? Is it a SKIN dependant option?

**Comment by anxdpanic** [comment]
Why? 
> It hasn't worked well/consistently for a long time.

How?
> open `Main Menu` (in the add-on) - `Playlists`, use the `context menu` on the playlist you created, and choose `Set as Watch Later`
This won't show if already set to this playlist. You can check by going to the addon `Settings - Folders - Custom watch later playlist id` will have a playlist id when configured.

**Comment by Rialtho-the-Magnificent** [comment]
> > open `Main Menu` (in the add-on) - `Playlists`, use the `context menu` on the playlist you created, and choose `Set as Watch Later`
> > This won't show if already set to this playlist. You can check by going to the addon `Settings - Folders - Custom watch later playlist id` will have a playlist id when configured.

Unfortunately, I do not see any of these options in either the setting in the add-on itself as in the settings of OSMC. I just use a manually created playlist and have named it AAAAA so it appears as one of the first ones.
