### ISSUE TITLE
Long titles scrolling in video OSD

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#660]
### What Problem Does This Solve? 
When there is a video with long title, it's cropped on OSD and you can't read missing part. 

------

### Suggest a Solution (optional)
It would be great to add top title scrolling feature which shall display long titles entirely when OSD is hit or video is paused. 

------

**Comment by neo-neo1** [comment]
Truncated titles scroll when you select it.

Which view are you using?

**Comment by karlo2105** [comment]
When i start video and make a pause it pops out top title and bottom time frame. Long title isn't scrolling.

**Comment by neo-neo1** [comment]
OSD when a video is paused isn't specific to this Addon, I believe. It's Kodi system wide from what I gather. 

I use Estuary Mod V2 (Skin) and it does scroll OSD when paused. Consider changing your Kodi Skin. Or look through Interface settings, could be an option for all I know.

**Comment by MoojMidge** [comment]
As @neo-neo1 mentioned this is not something controlled by the plugin, it is skin dependent.
