### ISSUE TITLE
Recent videos play a 5 mn "The following content is not available on this app. Watch this content on the latest version of YouTube" still video message on screen.

### ISSUE THREAD

**Issue by bolet** [anxdpanic/plugin.video.youtube#663]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4
* Kodi Version: Kodi Media Center 20.3 (20.3.0) Git:20.3-Nexus
* Kodi GUI Language: en-GB
* Operating System: LibreELEC (official): 11.0.6 (H3.arm)
* Operating System Language: en-GB

------

### Expected Behavior

Play the video

------

### Current Behavior

It displays a "fake" 5 mn video with a large message on the screen :
The following content is not available on this app. Watch this content on the latest version of YouTube

------

### Steps to Reproduce

Try to play a recent video from YT (since about March 25). Old videos still work as they used to.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
2024-03-29 19:05:07.520 T:9023     info <general>: Skipped 1 duplicate messages..
2024-03-29 19:05:07.520 T:9023     info <general>: [plugin.video.youtube] Running: YouTube (7.0.4+nexus.1) on Nexus (Kodi-20.3) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'ca1y45kret4', 'incognito': False}
2024-03-29 19:05:10.661 T:3509     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=FKp04zqZeHk&incognito=false
2024-03-29 19:05:10.685 T:10374 warning <general>: OutputPicture - timeout waiting for buffer
2024-03-29 19:05:10.729 T:10364    info <general>: Creating InputStream
2024-03-29 19:05:11.192 T:10364    info <general>: Creating Demuxer
2024-03-29 19:05:11.258 T:10364    info <general>: Opening stream: 0 source: 256
2024-03-29 19:05:11.264 T:10364    info <general>: Creating video codec with codec id: 27
2024-03-29 19:05:11.265 T:10364    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2024-03-29 19:05:11.285 T:10364    info <general>: Opening stream: 1 source: 256
2024-03-29 19:05:11.286 T:10364    info <general>: Finding audio codec for: 86018
2024-03-29 19:05:11.289 T:10364    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-03-29 19:05:11.293 T:10375    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 22 ms
2024-03-29 19:05:11.294 T:10375    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2024-03-29 19:05:11.325 T:3518     info <general>: CActiveAESink::OpenSink - initialize sink
2024-03-29 19:05:11.524 T:3518     info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=allwinnerhdmi,DEV=0"
2024-03-29 19:05:11.538 T:3518     info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=allwinnerhdmi,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2024-03-29 19:05:11.539 T:3518     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-03-29 19:05:11.539 T:3518     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4

```

------

### Additional Information

I believe YT changed some API for recent videos.

------

### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4
* Kodi Version: Kodi Media Center 20.3 (20.3.0) Git:20.3-Nexus
* Kodi GUI Language: en-GB
* Operating System: LibreELEC (official): 11.0.6 (H3.arm)
* Operating System Language: en-GB

------

### Expected Behavior

Play the video

------

### Current Behavior

It displays a "fake" 5 mn video with a large message on the screen :
The following content is not available on this app. Watch this content on the latest version of YouTube

![photo_5780410623727878474_y](https://github.com/anxdpanic/plugin.video.youtube/assets/487091/8d27af97-f8d3-4b39-800e-67500fc6bbb3)

------

### Steps to Reproduce

Try to play a recent video from YT (since about March 25). Old videos still work as they used to.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

```
2024-03-29 19:05:07.520 T:9023     info <general>: Skipped 1 duplicate messages..
2024-03-29 19:05:07.520 T:9023     info <general>: [plugin.video.youtube] Running: YouTube (7.0.4+nexus.1) on Nexus (Kodi-20.3) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'ca1y45kret4', 'incognito': False}
2024-03-29 19:05:10.661 T:3509     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=FKp04zqZeHk&incognito=false
2024-03-29 19:05:10.685 T:10374 warning <general>: OutputPicture - timeout waiting for buffer
2024-03-29 19:05:10.729 T:10364    info <general>: Creating InputStream
2024-03-29 19:05:11.192 T:10364    info <general>: Creating Demuxer
2024-03-29 19:05:11.258 T:10364    info <general>: Opening stream: 0 source: 256
2024-03-29 19:05:11.264 T:10364    info <general>: Creating video codec with codec id: 27
2024-03-29 19:05:11.265 T:10364    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2024-03-29 19:05:11.285 T:10364    info <general>: Opening stream: 1 source: 256
2024-03-29 19:05:11.286 T:10364    info <general>: Finding audio codec for: 86018
2024-03-29 19:05:11.289 T:10364    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-03-29 19:05:11.293 T:10375    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 22 ms
2024-03-29 19:05:11.294 T:10375    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2024-03-29 19:05:11.325 T:3518     info <general>: CActiveAESink::OpenSink - initialize sink
2024-03-29 19:05:11.524 T:3518     info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=allwinnerhdmi,DEV=0"
2024-03-29 19:05:11.538 T:3518     info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=allwinnerhdmi,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2024-03-29 19:05:11.539 T:3518     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-03-29 19:05:11.539 T:3518     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4

```

------

### Additional Information

I believe YT changed some API for recent videos.

------

**Comment by bolet** [comment]
Workaround for me : send a mp4 stream URL instead of a YT URL.
YT downloader extensions can extract those stream URLs from YT pages.

**Comment by snakebte75** [comment]
I just did a reinstall after a factory reset of my TV and I'm experiencing the same issue on 7.0.4

**Comment by luckylukz02** [comment]
Had the same issue on YouTube Revanced on my phone earlier today. Updating to latest version seemed to solve the issue.

Having the same problem on my Libreelec now....

**Comment by luckylukz02** [comment]
> Had the same issue on YouTube Revanced on my phien earlier today. Updating to latest version seemed to solve the issue.
> 
> Having the same problem on my Libreelec now....

Just tried 7.0.5 beta (uploaded yesterday)
Not getting above message anymore

**Comment by TheNetworkIsDown** [comment]
Hmm using the 7.0.5 beta I'm getting a python 2.26.0 dependency error on libreelec 20.3 (nexus)

**Comment by snakebte75** [comment]
> > Had the same issue on YouTube Revanced on my phien earlier today. Updating to latest version seemed to solve the issue.
> > Having the same problem on my Libreelec now....
> 
> Just tried 7.0.5 beta (uploaded yesterday) Not getting above message anymore

Same here. Upgraded to 7.0.5. Beta and videos now play. However, I am now getting bumped all the way back to my home screen when the video is over.

**Comment by Erudition** [comment]
This just started happening to me yesterday

**Comment by CadillacCab** [comment]
For me, I have to go back to 7.0.3.2

**Comment by barslmn** [comment]
> > > Had the same issue on YouTube Revanced on my phien earlier today. Updating to latest version seemed to solve the issue.
> > > Having the same problem on my Libreelec now....
> > 
> > 
> > Just tried 7.0.5 beta (uploaded yesterday) Not getting above message anymore
> 
> Same here. Upgraded to 7.0.5. Beta and videos now play. However, I am now getting bumped all the way back to my home screen when the video is over.


Upgrading to 7.0.5 fixed the issue in my case too.

**Comment by ghost** [comment]
I upgraded to 7.0.5-beta1 and I still get this on every video from YouTube, so 7.0.5 does not fix the issue.

**Comment by TheNetworkIsDown** [comment]
> I upgraded to 7.0.5-beta1 and I still get this on every video from YouTube, so 7.0.5 does not fix the issue.

If that is the case you should provide a debug log.

**Comment by saibaaimo** [comment]
I've resolved the issue by setting alternate client details in (Plugin 7.0.4) Settings->Advanced->Use alternate client details = `Alternate #1`
Looks like another youtube shenanigans around user agent.

**Comment by neo-neo1** [comment]
Already asked and answered. 

https://github.com/anxdpanic/plugin.video.youtube/issues/659

**Comment by bolet** [comment]
For future reference, it could help to keep #659 or #663 open as long as there is no "release" version available. That could help prevent other users from opening new bug reports about the same issue.

Thanks for your help.

**Comment by TasPats** [comment]
this was yesterday video, it starts with "5 minutes", but when I try to start again, from recent played (about 1:00) it plays this video properly
(may be somewhat helps our devs)

I now go and try with 7.0.5-beta1

**Comment by MoojMidge** [comment]
Try https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.2 and provide a debug log, even if it works. 

Only one single person has provided so far, and there is simply not enough information being provided by the seemingly large number of people who are effected by this, to determine if the current fixes are sufficient or whether more needs to be done.

If people don't provide information then nothing can be done to fix the problems.

**Comment by MoojMidge** [comment]
This problem does not apply to everyone and has not effected me. I have no way to test whether the changes will work or whether they will simply fail again at some point. The only way to resolve the issue is if the people currently impacted by this provide a debug log.

Please install https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.2 
and create a debug log showing the unsusuccessful or successful playback https://kodi.wiki/view/Log_file/Easy

**Comment by MarcoViti** [comment]
Windows 11 pro, YouTube plugin version 7.0.5 beta2 installed, the plugin seems to work but when switching from one video to another on the screen it displays a problem

https://paste.kodi.tv/nexewerexu.kodi

**Comment by MoojMidge** [comment]
@MarcoViti - thanks for that. It shows there is still a problem with the main Android client but that the other Android client fallbacks work, without needing to use the more limited client fallbacks.

> when switching from one video to another on the screen it displays a problem

Can you describe what you see?

**Comment by MarcoViti** [comment]
![IMG20240331151521](https://github.com/anxdpanic/plugin.video.youtube/assets/59185173/6bbc59b9-7210-4bcb-9b8a-df5557b8b283)
![IMG20240331151524](https://github.com/anxdpanic/plugin.video.youtube/assets/59185173/254baaaa-efa1-4516-b105-08135236f5ea)
My O.S. id Windows 11... not Android

**Comment by TheNetworkIsDown** [comment]
So for the record
"Multiple busy dialogs active - Kodi may crash"
(Not sure why we need two pictures for that)

But now that you say it, I think I've seen it once as well after installing the current beta and when a video didn't start at all. I started another one which worked fine and it also didn't crash.

**Comment by wa3573** [comment]
> This problem does not apply to everyone and has not effected me. I have no way to test whether the changes will work or whether they will simply fail again at some point. The only way to resolve the issue is if the people currently impacted by this provide a debug log.
> 
> Please install https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.2 and create a debug log showing the unsusuccessful or successful playback https://kodi.wiki/view/Log_file/Easy

This beta release solved the issue for me. ~~Here's a debug log with unsuccessful (on 3/30) and then successful (today, 3/31) playback.~~

~~There are some unrelated issues present in the log, just FYI, like an OAuth issue when I tried to log in. That might be an API key thing. Like I said, separate issue.~~

Edit: BTW, thanks and good job to the people maintaining this addon. I've had to fix other addons myself when they aren't as popular and it's nice to see someones already done the work for me in this case :relaxed:

**Comment by MoojMidge** [comment]
@MarcoViti - but apart from the notification there is no actual problem? The notification was added for testing a separate issue in the beta version, and won't be shown normally.

> My O.S. id Windows 11... not Android

The reference to Android is in relation to what the plugin is doing in requesting video details, not your system.

@TheNetworkIsDown - if you see this again please provide a debug log. Refer #649
> I think I've seen it once as well after installing the current beta and when a video didn't start at all

@wa3573 - thanks but I specifically need a debug log to get the required information. For the moment though I have sufficient information to work with.

Will create another beta release with additional changes for testing, that will also include some of the relevant information in non-debug logs.

**Comment by wa3573** [comment]
@MoojMidge, Oh whoops, thought I had debug logging enabled already.

**Comment by kadeschs** [comment]
Is anyone else having issues with beta2 fixing the playback for all menu items except "My Subscriptions"?  It's really the only one I use and YouTube errors on this even when setting to Alternate #1.

2024-03-31 11:26:11.380 T:22698939   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?category_label=My%20Subscriptions

2024-03-31 11:26:11.391 T:22698465   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/?category_label=My%20Subscriptions) failed

**Comment by neo-neo1** [comment]
> So for the record "Multiple busy dialogs active - Kodi may crash" (Not sure why we need two pictures for that)
> 
> But now that you say it, I think I've seen it once as well after installing the current beta and when a video didn't start at all. I started another one which worked fine and it also didn't crash.

On 7.0.5 beta 1 and 2 I've been also getting such dialogs nearly every time a new video starts playing from my playlist. I assume this is for development testing so I didn't bother posting a log.

**Comment by MoojMidge** [comment]
@wa3573 - no problem, new beta release will be available shortly that should resolve this. It will also provide warnings in the log if there are player request failures, and further full debug info in the debug log, either of which will be sufficient to verify the changes are working correctly. 

@kadeschs - no problems here. Full debug log is required to investigate further. 

@neo-neo1 - as long as Kodi doesn't crash and the playlist keeps playing, then yes, the notification can be ignored (and it will be removed in a final release). If Kodi does crash or the playlist fails to play then post a log in #649

**Comment by dribgnikcom** [comment]
@MoojMidge - "Recommendations" is not working anymore, it is empty...  Can you please look at that for the next beta release?  Thanks

**Comment by kadeschs** [comment]
> @kadeschs - no problems here. Full debug log is required to investigate further.
> 
@MoojMidge 
Well, as you can see from the snippet of the logs, there is an issue.  Is there a difference between the official and unofficial one that could potentially cause this sort of problem?  Which one should we be using?  Which one are you using?  Why don't we have just one working solution for now?

**Comment by smoonlee** [comment]
> > Had the same issue on YouTube Revanced on my phien earlier today. Updating to latest version seemed to solve the issue.
> > Having the same problem on my Libreelec now....
> 
> Just tried 7.0.5 beta (uploaded yesterday) Not getting above message anymore

This worked, Had to reboot my OSMC Pi4 after but its fixed 👌

**Comment by MoojMidge** [comment]
@dribgnikcom, @kadeschs - can't do much if you don't provide a log. I'm not having any problems, and there are no similar reports from anyone else.

**Comment by MoojMidge** [comment]
~https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.3~

**Comment by MoojMidge** [comment]
v7.0.5+beta.3 was buggy, v7.0.5+beta.4 should resolve the problem:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4

**Comment by kadeschs** [comment]
MoojMidge mentioned
> v7.0.5+beta.3 was buggy, v7.0.5+beta.4 should resolve the problem

My Subscriptions (YouTube error)
Browse Channels (Request Failed)
Completed Live (YouTube error)
Live (YouTube error)
All other menu items work fine.

**Comment by MoojMidge** [comment]
@kadeschs - The problem that has been resolved is this issue, nothing to do with whatever you are going on about.

You keep on bringing up stuff that is not related to this issue, and I have no idea what you are talking about because you haven't bothered to provide any details.

If you have a problem, open up a new issue and post a debug log, otherwise nothing can or will be done about it.
