### ISSUE TITLE
Notification "The request's playlistId parameter cannot be found"

### ISSUE THREAD

**Issue by baltzis** [anxdpanic/plugin.video.youtube#667]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4+nexus.1
* Kodi Version: 20.1
* Kodi GUI Language: Greek
* Operating System: Android TV box KM6 (MECOOL), Version 10 
* Operating System Language: Greek

------

### Expected Behavior

After viewing a video, it should be marked as viewed and no warning or notification should be produced.

------

### Current Behavior

After viewing any video, it is marked as viewed and the following notification appears:
"The playlist identified with the request's playlistId parameter cannot be found."

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Play any video to the end
 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
Sorry. I am not don't know how to provide a log file from an Android TV Box.

------

### Additional Information

This notification does not appear on a Windows installation, all specifications being the same (Kodi and addon version).

------

**Comment by MoojMidge** [comment]
> Please include a complete [debug log](https://kodi.wiki/view/Log_file).
> Sorry. I am not don't know how to provide a log file from an Android TV Box.

Instructions are provided at the link. Did you read it? https://kodi.wiki/view/Log_file/Easy

Nothing can be done without a log, but even without a log you haven't provided details on what playlist you are playing, or what plugin settings you are using.

How do you expect anyone to help you If you don't provide any useful information?
