### ISSUE TITLE
version for Leia unicode-related errors

### ISSUE THREAD

**Issue by raven428** [anxdpanic/plugin.video.youtube#668]
### Context

Please provide any relevant information about your setup

* Add-on Version: `plugin.video.youtube-7.0.5+beta.2.leia.unofficial.1.zip`
* Kodi Version: 18.9
* Kodi GUI Language: english
* Operating System: windows
* Operating System Language: english

------

### Expected Behavior

Playing videos and show lists with national characters (Cyrillic for example)

------

### Current Behavior

Unicode related errors in log when trying to open:
1. my subscription
2. playlists
3. watch later

and all of these tries finished by failures

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. add a few channels to subscriptions, playlists and watch later
2. try to open my subscription, playlists and watch later
3. kodi show failures and logs will contain unicode-related errors

------

### Log

[kodi.zip](https://github.com/anxdpanic/plugin.video.youtube/files/14814283/kodi.zip)

------

### Additional Information

none

------

**Comment by MoojMidge** [comment]
@raven428 - the releases for Kodi 18 (Leia) are unsupported.

Is there a reason you are using such an old, unsupported version of Kodi on a relatively modern PC?

Some of the errors also seem to indicate that you have tried to copy user data from a newer version of Kodi, is this the case?

While some of the errors appear to be easy enough to fix, I have no way to test this, and without a compelling reason don't want to introduce changes that may cause other problems.

**Comment by raven428** [comment]
> Is there a reason you are using such an old, unsupported version of Kodi on a relatively modern PC?

It's only a test setup to debug addon. The main reason I use unsupported version of Kodi are ancient s905x devices with LibreELEC 9 fork (AlexELEC). It can't be updated to LibreELEC 11 with Nexus because most of codecs unstable, others crashing, while OpenELEC builds are crashing even while startup

> Some of the errors also seem to indicate that you have tried to copy user data from a newer version of Kodi, is this the case?

You're right, I took addon configuration from Nexus version. This is my failure, sorry. Here is [the log](https://github.com/anxdpanic/plugin.video.youtube/files/14821418/kodi2gh.zip) from the clean install and configuration. Anyway, an issues are the same

> While some of the errors appear to be easy enough to fix

I performed a bit investigations and assume there is some inconsistency with `kodi-six` module. It developed especially to fix these unicode related issues, but are not affecting these issues for some reason. Unfortunately I'm not enough skilled to debug and fix these 😢

> I have no way to test this

I'm ready to cover the tests Leia builds of addon

Due to inability of usage updated LibreELEC and OpenELEC I'll try to put Nexus to some kind of container (`docker` either `systemd-nspawn`) at current fork. I assume this took a lot of time and in case of an inability I'll will chose and order updated devices. So I'll will still use Leia for for a long time from now

Also, I overcustomized confluence with shortcuts skin at my Leia installation. It won't convert automatically to Nexus or even Matrix. So, when I'll start the Nexus on my devices, I'll also will need to reconfigure all of these overcustomizations

> without a compelling reason don't want to introduce changes that may cause other problems

Of course I'm ready to donate the addon, but don't see any buttons to do this. I spent lot of a good time with addon and the Kodi starting from Jarvis. About 8 years already, wow. Most of my relationships with girlfriends was much shorter 😆

**Comment by MoojMidge** [comment]
> I performed a bit investigations and assume there is some inconsistency with `kodi-six` module.

`kodi-six` is for the Kodi specific Python modules, but the problem is with Python 2 itself. Different parts of the standard module handle non-ascii text differently and have assorted bugs related to this.

I added some potential fixes to the next beta release, because they were caused by recent changes targetting Kodi 20, but I don't know if that is enough, or whether it will just expose more problems in Kodi 18.

You can test it and raise a new issue if you encounter problems, but I don't really have enough time to look into it further.

**Comment by MoojMidge** [comment]
~https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.3~
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4

**Comment by MoojMidge** [comment]
v7.0.5+beta.3 was buggy, v7.0.5+beta.4 should resolve the problem:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4
