### ISSUE TITLE
When using playlist ‘watch later’ in YT add-on I get message playlistid not found  

### ISSUE THREAD

**Issue by Rialtho-the-Magnificent** [anxdpanic/plugin.video.youtube#67]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.8
* Kodi Version: OSMC
* Kodi GUI Language: 
* Operating System: No idea, but I'm running OSMC on RASP Pi 3b+
* Operating System Language:

Since the option ‘my subscriptions’ no longer works (since beginning of Dec 2020) I now use the option to add videos to my ‘watch later’ playlist. When I use the youtube add-on on my OSMC raspberry pi3b+ I get a lot of errors when getting back to that playlist, be it after a video has ended or by selecting the playlist. The error message appears briefly on the screen and when I try again either the playlist is shown, or I get the same error a number of times. Eventually I do get my playlist. But it is very annoying. Anybody has any idea what is going on?

------

### Expected Behavior
Return to playlist "watch later" after video ends or when selecting that playlist.
------

### Current Behavior

Getting error message stating **playlistid** cannot be found or similar. (I have to write down the exact error but will do that in an update of this reported issue later)

------

### Steps to Reproduce

1. select "watch later" -> get either the list of items or an error message, sometimes multiple times, but eventually I get to the playlist.
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/uzivaxiquy.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

This started recently (Dec. 2020) when switching from the 'my subscription' option that no longer seems to work

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/66#issuecomment-744576230

**Comment by Rialtho-the-Magnificent** [comment]
closing this issue as I have found a way around the problem.
