### ISSUE TITLE
Why look down on others?

### ISSUE THREAD

**Issue by BobbyBabes** [anxdpanic/plugin.video.youtube#670]
@BobbyBabes - don't you have anything better to do? I really don't understand why you decided that the request for a debug log was on so unreasonable, but your opinions and comments are of no use here. Just move along.

_Originally posted by @MoojMidge in https://github.com/anxdpanic/plugin.video.youtube/issues/659#issuecomment-2028936525_

            You not spending time on the real issue at hand (the bug) but making my comments (that call you out) the issue, shows that you cannot concentrate on what matters. You cannot work as a team member. You cannot work solo. You are a hermit. Just don’t become an extremist. Like all other dictators.

**Comment by ThubLives** [comment]
How does this apply to the software?  This seems like nothing more than a personal grievance.
