### ISSUE TITLE
HDR and surround sound not working when disabling AV1 streams

### ISSUE THREAD

**Issue by vwghub** [anxdpanic/plugin.video.youtube#673]
* Add-on Version: 4.0.5 beta 3
* Kodi Version: 21.0 rc2
* Kodi GUI Language: English
* Operating System: Windows 11
* Operating System Language: English

Please describe the behavior you are expecting.  both HDR and surround sound work in beta 2 with this setting

What is the current behavior?  VP9 streams will play at 4k resolution but no HDR and only 2ch sound. 

Please provide detailed steps for reproducing the issue.

1.  Use MPEG-DASH for videos, stream selection set to Quality selection, Maximum video quality to 4320p (8k), All stream features are default except for Enable AV1.   
2.   Play a video with HDR and/or surround sound.  

Please provide any additional information that may be helpful.  I have reverted back to 7.0.5 beta 2 and turned off auto updates for now.

**Comment by MoojMidge** [comment]
Two possibilities:

1. Typo resulted in falling back to a client that doesn't support those stream features
2. You accessed a video that has now become a live stream with DVR streams

No log, no video link, so nothing further to look into.

You can try the next beta release and check again if you want.

**Comment by MoojMidge** [comment]
See how you go with the latest beta:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4
