### ISSUE TITLE
Still getting playback error in 7.0.5+beta.4

### ISSUE THREAD

**Issue by C-O-D** [anxdpanic/plugin.video.youtube#679]
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/14832020/kodi.log)
### Context

Please provide any relevant information about your setup

* Add-on Version: [7.0.5+beta.4](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4)
* Kodi Version: 20.5
* Kodi GUI Language: German
* Operating System: Manjaro
* Operating System Language: German

------

### Expected Behavior

Playing a video when clicking on it

------

### Current Behavior

Error Message (Watch log...)

------

### Steps to Reproduce

Try to play a video

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
Yikes, so many typos. Thanks for the log.

Delete the comma here:
https://github.com/anxdpanic/plugin.video.youtube/blob/8456e80b244b6fec4186ec2ad42910c81be971d9/resources/lib/youtube_plugin/youtube/helper/video_info.py#L599
So it becomes:
```
    }
```

Or don't enable the no fractional frame rate hinting option for the moment, until release is updated.

**Comment by C-O-D** [comment]
Nice, everything working as expected - thanks for the help 👍
