### ISSUE TITLE
Recomedations ListItem not showing

### ISSUE THREAD

**Issue by Mutronics** [anxdpanic/plugin.video.youtube#68]
Add-on Version: 6.8.9-beta3
Kodi Version: 18.9
Kodi GUI Language: Russian
Operating System: COREELEC
Operating System Language: EN
Recomedations ListItem not showing

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.youtube/blob/master/changelog.txt#L4

Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History`
That will be your Kodi watch history playlist. It will only track your Kodi playback but the playlist will be available to other devices, it is also used to generate the list of recommendations and `Recommendations` won't be shown until you've configured the watch history playlist.

This is another casualty of the recent changes, sorry it's a bit of a pita but it's the current alternative.
