### ISSUE TITLE
Can't seek back in live stream video with Youtube 7.0.4 or Youtube 7.0.5

### ISSUE THREAD

**Issue by Nanomani** [anxdpanic/plugin.video.youtube#680]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4.x or 7.0.5x
* Kodi Version: latest build Kodi 21 (libreelec 12) or Latest build Kodi 21 RC2 (x64 windows)
* Kodi GUI Language: Fr
* Operating System Language: Linux or Windows 11 x64 pro

------

### Expected Behavior

With Yotube 7.0.3.2 I can seek back in live stream video 
(Max back 1H59 but it is enough ).

------

### Current Behavior

Seek back in live stream video is not possible with Youtube 7.0.4.x and newer (7.0.5 beta4)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  install Youtube 7.0.3.2
2.  open a real live stream
3.  seek back is possible 

5.  update to Youtube 7.0.5 beta 4
6. open the same live stream where seek back works with Youtube 7.0.3.2
7.  seek back is not possible (you can see only current live stream)

------

### Log

Log with Addon  Youtube 7.0.5 beta 4 : 
https://paste.kodi.tv/ukemecuwoz.kodi

Log with Addon Youtube 7.0.3.2 : 
https://paste.kodi.tv/akecebehaw.kodi

------

### Additional Information

Screenshot with Addon  Youtube 7.0.5 beta 4 : 

Seek back is not possible

![screenshot00004](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/3f253927-17ce-42e9-a986-7eeb6d1cf0a3)

![screenshot00029](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/257f6842-0752-4ffa-9bf7-7f2688c77de6)

Screenshot with Addon  Youtube  7.0.3.2 : 

Seek back is possible

![screenshot00033](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/e2f2d3cb-8a2a-46fb-9751-1dee69df6d9b)

![screenshot00030](https://github.com/anxdpanic/plugin.video.youtube/assets/3939543/c81b92e5-b9d1-4768-bb78-cf82eab15890)

------

**Comment by MoojMidge** [comment]
Thanks for providing all that detail, really helpful.

Essentially nothing has changed in the plugin related to this, but what did change was the client that was used. Will need to examine the manifests to determine if the content is different.

Live streaming is still not fully working, but the info you have provided should help to workaround the problems. The preferred method would be to use MPEG-DASH, but that is still buggy and will result in low quality streams being selected. Will need to investigate further and create a bug report for InputStream.Adaptive

**Comment by XxAcielxX** [comment]
I was able to seek backwards with 7.0.5-beta.4 using InputStream.Adaptive, there is no issue.

**Comment by MoojMidge** [comment]
@XxAcielxX - you may not see the same issue depending on what options you have selected and also what version of InputStream.Adaptive you are using.

**Comment by MoojMidge** [comment]
@Nanomani - Can you update InputStream.Adaptive to https://github.com/xbmc/inputstream.adaptive/releases/tag/21.4.5-Omega from the LibreELEC repo and change `Settings > Advanced > InputStream Adaptive > Use for live stream` from `Adaptive HLS` to `MPEG-DASH`?

There have been recent fixes to InputStream.Adaptive to resolve some regressions and address some issues, that should now enable the MPEG-DASH manifests to work properly. Lots of good work happening with InputStream.Adaptive, but the rapid pace of development has meant that some regressions may have also crept into the handling of HLS, that are causing the issues you have observed. Will need to test a bit more to confirm.

I don't really play any live streams, but from what I can see most of the issues that initially prompted the change away from using MPEG-DASH for YouTube live streams have been resolved. If you can confirm, then can change the default setting back.

**Comment by Nanomani** [comment]
@MoojMidge 
Thank you for your comprehensive comments.
I make a try when possible. And I back you the result ...

**Comment by Nanomani** [comment]
@MoojMidge 
Indeed all works fine now 
Tested with Addon Youtube 7.0.5 and 7.0.6 beta1
Thanks you very much :)
