### ISSUE TITLE
The following content is not available on this app

### ISSUE THREAD

**Issue by giaur500** [anxdpanic/plugin.video.youtube#682]
* Add-on Version: 7.0.4+matrix.1
* Kodi Version: 19 Matrix
* Kodi GUI Language: PL
* Operating System: Coreelec
* Operating System Language: EN

### Expected Behavior

Video + audio playback
------

### Current Behavior

Video playback starts without any errors thrown, however, instead actual video I'm getting this:

![image](https://github.com/anxdpanic/plugin.video.youtube/assets/26817206/4a247135-cdaf-4dc3-9ad5-a4b8cb29cdbd)

------

### Steps to Reproduce
 Try with to play this video to reproduce: 
https://www.youtube.com/watch?v=9rLHZTWXgAw
------

### Log

https://pastebin.com/ATCZepw1
------

------

**Comment by giaur500** [comment]
Please note: <strong>That's not the same issue as here (already fixed) </strong>: https://github.com/anxdpanic/plugin.video.youtube/issues/442

This time, there's no any error when starting playback. Playback starts, but Google keeps serving message as shown on pic instead of video.

**Comment by colonnello89** [comment]
same problem!

**Comment by broadcastyourseb** [comment]
Same screenshot with all youtube video

**Comment by giaur500** [comment]
Hello,

In my case, 7.0.5+beta 4 solves the problem.

**Comment by broadcastyourseb** [comment]
Great news. Work fine with 7.0.5+beta 4 update.

**Comment by liaolingfen4** [comment]
same issue has appear, how to solve it

**Comment by MoojMidge** [comment]
> same issue has appear, how to solve it

Step 1. Open a new issue with a debug log
