### ISSUE TITLE
Can't play videos with kore

### ISSUE THREAD

**Issue by stemy2** [anxdpanic/plugin.video.youtube#686]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.4
* Kodi Version: 20.5
* Kodi GUI Language: fr
* Operating System: kde neon
* Operating System Language: fr

------

### Expected Behavior

I can't play videos with kore.

------

### Current Behavior

Shows a steady spinning wheel on the screen. Shows the usual video metadatas on the app, except the title, wich is replaced by "Video not available" and the duration is alwats 5 minutes, no matter the real video's duration.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to play a video with kore.

------

### Log

https://paste.kodi.tv/egumumubeb

------

### Additional Information

------

**Comment by 4utomator** [comment]
Same on LibreELEC 20.3 addon version 7.0.4 nexus.

**Comment by MoojMidge** [comment]
You need to update to v7.0.5

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5

It will also be available for automatic updates shortly
