### ISSUE TITLE
Audi and video out of sync, skipping

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#688]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.5
* Kodi Version: 20.3 (20.3.0) Git:20.3-Nexus
* Kodi GUI Language: Swedish
* Operating System: LibreELEC (official): 11.0.6
* Operating System Language: English

------

### Expected Behavior

When I play a video, I expect audio and video to be in sync and I expect that the video plays without skipping twice or thrice every minute.

------

### Current Behavior

Certain videos (not all) have audio and video sync out of sync by 1-3 seconds, and periodically (2 or 3 times per second) the audio and video will skip forward.

An example of a problematic video is: https://www.youtube.com/watch?v=wMOsbiIYeVg

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install LibreELEC
2. Install youtube add-on from repository through gui
3. Play video https://www.youtube.com/watch?v=wMOsbiIYeVg (for example, by going to the youtube addon, search for "We have a ton of Amstrad computer goodness" and choose the video)

------

### Log

https://paste.kodi.tv/sezosuxami.kodi

### Additional Information

------

**Comment by MoojMidge** [comment]
You are trying to play a 1080p60 VP9 encoded video stream on a Raspberry Pi 1 so your expectations are going to have to be adjusted. This is something that a Raspberry Pi 4 can have problems with.

Did you go through the Setup Wizard when it asked to run? Use the recommended settings when asked, and select the Raspberry Pi 3 performance settings when prompted.

See if that improves things, otherwise you will need to further reduce some settings.

**Comment by ghost** [comment]
Ah. It never asked me to run the wizard before, but enabling it in the settings it did ask to run when I opened the add-on. Using the automatically selected settings fixes the issue. Thanks and apologies for bothering you.

**Comment by MoojMidge** [comment]
No problem.

To confirm, on this video https://www.youtube.com/watch?v=wMOsbiIYeVg and others,  the Raspberry Pi 3 settings allowed for smooth playback?

**Comment by ghost** [comment]
@MoojMidge I don't know whether those are the Raspberry PI 3 settings, but it's set to 720p (HD) now, and that works fine, video is in sync and no skipping.

**Comment by MoojMidge** [comment]
Thanks for the feedback. It means that the Raspberry Pi 3 settings are not quite appropriate for the older Raspberry Pi devices. Will add another preset to cater for those.
