### ISSUE TITLE
"Play using" missing from the context menu

### ISSUE THREAD

**Issue by Solarunit** [anxdpanic/plugin.video.youtube#692]
"Play using" option missing from the context menu. 
It's missing for videos inside addon, and YT videos added to kodi favorites too.

* Add-on Version: 7.0.5
* Kodi Version: 21.0
* Kodi GUI Language: Eng
* Operating System: Linux
* Operating System Language: Eng

------

### Expected Behavior

"Play using" option should be available for all videos

------

### Current Behavior

What is the current behavior?

"Play using" option missing from the context menu. 

------

### Steps to Reproduce

1.  open context menu
2.  there is no longer "Play using" option

**Comment by MoojMidge** [comment]
Works fine for me if enabled. If you think it doesn't then provide a debug log.

Edit: It won't work for Favourits AFAIK. Are you sure it worked before? You would need to raise a Kodi feature request or bug report for that.

**Comment by Solarunit** [comment]
>Works fine for me if enabled. If you think it doesn't then provide a debug log.

What should be enabled? In advanced settings I enabled `Support alternative player`  it adds `Play with` option in context menu. Is it the same as `Play using` that opens external players options? `Play with` does nothing for me.


>Edit: It won't work for Favourits AFAIK. Are you sure it worked before? You would need to raise a Kodi feature request or bug report for that.

It worked inside folders, when you favorite the whole youtube channel. I guess it's just Kodi issue.

**Comment by MoojMidge** [comment]
> `Play with` does nothing for me.

What are you trying to do? Without a debug log can't see what you have actually done and don't feel like playing 20 questions to investigate further.

I am not exactly sure how `Support alternative player` was intended to work as it should really be called `Support remote player` since it won't use an external player unless playback has already started, after which you can then switch to an external player. Regardless, I am pretty sure how it actually works hasn't changed in years.

There may be an issue with `Use YouTube website urls`, but without a debug log don't know if that has any bearing on what you are talking about.

**Comment by Solarunit** [comment]
Well, "Play using" option was always there for youtube videos, I could select internal player or external (mpv) to play it.
Just recently the option was gone. Not sure if it's Kodi or YT plugin issue. I will try to see logs on old Kodi version where "Play using" option is still there.

**Comment by Solarunit** [comment]
Here is log when I pressed `Play with` from the context menu:

ContextMenu is triggered by `C` button:

```
debug <general>: HandleKey: c (0xf043) pressed, window 10025, action is ContextMenu

```

YT video can be played by 2 players, internal one and mpv, but such menu doesn't appear:

```
debug <general>: CPlayerCoreFactory::GetPlayers: added 2 players

```

and then some errors in context menu:

```
 info <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
debug <general>: ------ Window Init (DialogContextMenu.xml) ------
debug <general>: Keyboard: scancode: 0x74, sym: 0x112, unicode: 0x00, modifier: 0x0
debug <general>: HandleKey: down (0xf081) pressed, window 10106, action is Down
debug <general>: Keyboard: scancode: 0x74, sym: 0x112, unicode: 0x00, modifier: 0x0
error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
debug <general>: Keyboard: scancode: 0x74, sym: 0x112, unicode: 0x00, modifier: 0x0
debug <general>: HandleKey: down (0xf081) pressed, window 10106, action is Down
debug <general>: Keyboard: scancode: 0x74, sym: 0x112, unicode: 0x00, modifier: 0x0
error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
debug <general>: Keyboard: scancode: 0x24, sym: 0x0d, unicode: 0x0d, modifier: 0x0
debug <general>: Keyboard: scancode: 0x24, sym: 0x0d, unicode: 0x00, modifier: 0x0
debug <general>: HandleKey: return (0xf00d) pressed, window 10106, action is Select
debug <general>: ------ Window Deinit (DialogContextMenu.xml) ------
error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices

```

@MoojMidge maybe that's the issue:
 `error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices` 

--
tested on:
Add-on Version: 7.0.5
Kodi Version: 21.0 flatpak

**Comment by MoojMidge** [comment]
I'm not sure what you want me to do. I have asked for a log twice previously.

It's fine if you don't understand the log, I can look at it, but posting bits and pieces of it won't won't achieve anything.

As I said before the "Play with..." option may not work as expected if you just have an external player configured. "Play using" is core Kodi functionality and I don't recall it working with plugins.

Not sure how you have things setup, but not going to waste time by trying to guess.

**Comment by MoojMidge** [comment]
Post a debug log playing a video using mpv by default

**Comment by Solarunit** [comment]
ok, I will post it tomorrow

**Comment by Solarunit** [comment]
I pasted debug log in the linked issue

**Comment by MoojMidge** [comment]
Give https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6%2Bbeta.1 ago and see how the "Play with" menu item works for you

**Comment by Solarunit** [comment]
I installed YT addon v7.0.6+beta.1 on Kodi flatpak 21. MPV is set as default player.

I tried all possible combinations in `Advanced` > `Support Alternative Player` section:

- MPV can play every video, regardless of settings
- I don't see "Play with" menu at all

Maybe I should set internal player as default to see it? 

>Fix 6s delay on video playback start

thanks, that delay was annoying, now playback starts a lot faster.


UPDATE:

After I set `<rules action="prepend">` instead of append for MPV I see "Play with" menu.

- after I press "Play with" video starts playing in MPV
- players selection dialog opens only when I stop the playback
- I can select internal player after that (but I noticed that quality degraded to 720p)
- I tried it several times and now I see `One ore more items failed to play` error after selecting Internal player.

UPDATE2: now I see "Play with" menu when <rules action="append>`, maybe Kodi restart helped, not sure.

____

So here is my use-case: I have MPV set as default player for youtube videos and in case MPV couldn't play a video (for various reasons) I want a quick method to fallback to internal player. This is how "Play using" global option worked for me before.

**Comment by MoojMidge** [comment]
> So here is my use-case: I have MPV set as default player

`Settings > Advanced > Use YouTube website urls with default player` and just open videos normally

> I want a quick method to fallback to internal player.

`Settings > Advanced > Use adaptive streaming formats with external player` and use Play with

**Comment by Solarunit** [comment]
`Use YouTube website urls with default player` setting name is confusing, because default player can be internal VideoPlayer or MPV external player when set as default in playercorefactory file.

when I use `Use YouTube website urls with default player` option, video starts playing immediately in mpv after pressing `Play with` from the context menu and player selection menu only pops up exactly after I close MPV.

Is there a way to show player selection menu before the playback starts?

**Comment by Solarunit** [comment]
also to be clear when **only** `Use YouTube website urls with default player` enabled pressing enter on video thumbnail starts playback in mpv.

**Comment by MoojMidge** [comment]
> `Use YouTube website urls with default player` setting name is confusing, because default player can be internal VideoPlayer or MPV external player when set as default in playercorefactory file.

Yes, and that is what the setting does. It uses website urls for your default player to use. The internal player cannot use website urls though.

> when I use `Use YouTube website urls with default player` option, video starts playing immediately in mpv after pressing `Play with` from the context menu and player selection menu only pops up exactly after I close MPV.

Kodi also cannot stop an external player, so using `Play with` with an external player set as default probably wont work.

> Is there a way to show player selection menu before the playback starts?

For technical reasons, no. So your best option would be to keep the internal player as default, then using `Play with` will allow you to select mpv

**Comment by Solarunit** [comment]
>For technical reasons, no. So your best option would be to keep the internal player as default, then using Play with will allow you to select mpv

I have better experience with mpv for youtube videos, so it makes sense to set it as default player. Imagine pressing context menu and select `Play with` for every youtube video every time. I hope mpv will keep working..

**Comment by MoojMidge** [comment]
> I have better experience with mpv for youtube videos, so it makes sense to set it as default player.

The way you were using it, you never used any functionality of mpv, specific to playing YouTube videos. The plugin was doing everything it would normally do, but instead of Kodi actually putting pixels on your screen, mpv was doing it instead.

Doesn't really make sense why you would want to do that, but if you insist on doing so, then you can keep doing so either as default, without `Play with`, or as an option using `Play with`.

**Comment by Solarunit** [comment]
>The way you were using it, you never used any functionality of mpv, specific to playing YouTube videos. The plugin was doing everything it would normally do, but instead of Kodi actually putting pixels on your screen, mpv was doing it instead.

Is it basically the same thing as copy and pasting youtube url link from the browser in mpv?


>Doesn't really make sense why you would want to do that, but if you insist on doing so, then you can keep doing so either as default, without Play with, or as an option using Play with.

mpv has many options (customizable 3rd party UI, shortcuts, etc) , especially you can configure cache.

**Comment by MoojMidge** [comment]
As I said:

> The way you were using it, you never used any functionality of mpv, specific to playing YouTube videos. The plugin was doing everything it would normally do, but instead of Kodi actually putting pixels on your screen, mpv was doing it instead.

So it makes no sense that you had a better experience using mpv. mpv wasn't doing anything except.displaying the video on your screen

Now it will basically do this, and everything will be up to mpv.

> copy and pasting youtube url link from the browser in mpv?

**Comment by Solarunit** [comment]
>Now it will basically do this, and everything will be up to mpv.

Nice!
Even when `Support alternative player` is disabled and InputStream Adaptive enabled?

**Comment by MoojMidge** [comment]
I will be changing the settings display to make it clearer.

`Support alternative player` and `Use YouTube website urls with default player` will become separate.

Enabling `Support alternative player` will disable `Use YouTube website urls with default player`.

In order to enable `Use YouTube website urls with default player`, `Support alternative player` will need to be disabled.

**Comment by Solarunit** [comment]
One more thing I noticed when testing all these addon settings, you need to restart Kodi to make sure options are applied.

**Comment by MoojMidge** [comment]
Context menu items are generated when the video data is retrieved and are stored along with all those details in the data cache

If you change the options then you need to refresh the video data or video listing, as the data and listitems are cached in various ways.

You don't need to restart Kodi to do that, but you can if you want.
