### ISSUE TITLE
What is the 'unofficial' release?

### ISSUE THREAD

**Issue by doko-desuka** [anxdpanic/plugin.video.youtube#7]
Hi, I love your add-on!   
In your Releases page there's two flavors of release, one normal and one "unofficial". 

What would be the difference?

**Comment by anxdpanic** [comment]
There is also a repository for the unofficial if that's the version you choose.
But the answer to your question can be found; https://github.com/anxdpanic/plugin.video.youtube/wiki/FAQ#difference-between-the-official-and-unofficial-versions

**Comment by doko-desuka** [comment]
Whoops, should've looked better. Thanks a lot.

**Comment by anxdpanic** [comment]
No worries at all :D
