### ISSUE TITLE
Playlist Changes in 6.8.8

### ISSUE THREAD

**Issue by TwoYoots** [anxdpanic/plugin.video.youtube#70]
Hi ANXD,

     I apologize as I’m brand new to Git & I see this is already reported.  But I wanted to state that this definitely worked fine before this latest update; something changed either due to that or a YT change at the same time.  As previously reported, History & Recommendations now return no results, and Watch Later gives the invalid playlist error.  Is there a quick .py that I could just update on my device so that the right URL gets sent to YT?  I know that I can establish a new Kodi-only history, but I really want the global history to work again if at all possible.

**Comment by anxdpanic** [comment]
If there was a way to resolve this, I would have already implemented it given how integral watch history and watch later are.

Sorry it's not better news, but it is currently where we are.

**Comment by TwoYoots** [comment]
Thanks, and sorry for the one 
liner mess; I was rushing to update 
how ugly it came out.  Won’t 
happen again!!!!

**Comment by TwoYoots** [comment]
But just one more comment, why do you think then that it 
actually <was> working so consistently for me for months, just
up until 2 weeks ago?

**Comment by anxdpanic** [comment]
It's because YouTube discontinued the undocumented API that we were using for these things. It's been discussed in the other issues surrounding this. You'll notice if you do a new login with the current beta you'll only have to enter the code once now as well.
