### ISSUE TITLE
Option to hide Ask for quality, Play with subtitles, Play audio only from the context menu

### ISSUE THREAD

**Issue by Solarunit** [anxdpanic/plugin.video.youtube#708]
### What Problem Does This Solve? 

It would be nice to hide these items from the context menu to make context menu more compact, you have to scroll though a lot of items at the moment.

in v7.0.6+beta.1 there was a change:

>Ask for quality, Play with subtitles, Play audio only context menu items only displayed if
associated setting is not already enabled

I have these options disabled and also don't want to have them in the context menu

------

### Suggest a Solution (optional)

Either a new option to hide these items or hide them by default. 

------

**Comment by MoojMidge** [comment]
Too many options for little benefit and too much work.
