### ISSUE TITLE
Default language subtitle

### ISSUE THREAD

**Issue by dieselwine** [anxdpanic/plugin.video.youtube#71]
### Context

* Add-on Version: 6.8.8
* Kodi Version: 18.9
* Kodi GUI Language: PL
* Operating System: Win 10
* Operating System Language: PL

------

### Expected Behavior

I want pl (polish) subtitles on the list same as in the [screenshot](https://www.wykop.pl/cdn/c3201142/comment_0UwflnfRrDK2iQif3gEQXNhI8xkNqgpgQVNxiLpRZD7dzmlu0lnk5F8CYbwfrHFyMR5Zf0z6Na3iMS5lc0TAMbUlA0sqyoHRP4Cy,w600.jpg)
------

### Current Behavior

I've got two PC's with Kodi. When I get into settings of youtube addon and then to "Configure subtitles" I can see the screen as I put above. However, on one of PC's it shows similar five options, but those three that refers to PL language are related to EN. I'm not sure if I can call this behaviour as a bug, but I'm curious on what exactly it depends, because both PC's are on same OS, same language, same add-on revision etc. Do you know on what specifically it is based? Then, maybe I would be able to fix it for myself.

**Comment by anxdpanic** [comment]
This is tied to the add-on language. Open the YouTube addon `Settings -> Advanced -> Enabled Setup Wizard`, Choose `Polish` as your language during that wizard and your subtitle choices should resemble the other install.

**Comment by ma1ko** [comment]
It it possible to choose the subtitle language per video? I watch videos in different languages and usually want subtitles in the language that is spoken in the video. 
As I understand it, I would have to execute the setup wizard before each video to change the subtitle language, which is very annoying. Is there a simpler way?

**Comment by dieselwine** [comment]
You can choose "Prompt" in settings as shown in my screenshot
