### ISSUE TITLE
Unable to sign-in; Login exception

### ISSUE THREAD

**Issue by Forlorn-Hope** [anxdpanic/plugin.video.youtube#711]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.5
* Kodi Version: 20.3 Nexus
* Kodi GUI Language: English
* Operating System: LibreElec 11.0.6
* Operating System Language: English

------

### Expected Behavior

I should be able to login and authenticate the plug-in at google.com/device

------

### Current Behavior

The authentication code is accepted, but there is a login exception in the plugin

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Launch youtube plug-in
2. Screen states I have to login-in twice
3. Click continue, and the code appears
4. I go to google.com/device and enter the code
5. I choose the account to use
6. Click allow
7. Google says the device is ready to use, but in the plug-in there is a login exception, invalid client type
8. I have tried the different client types, but receive the same error

------

### Log

[log file](https://paste.kodi.tv/ixijohitex)

------

### Additional Information

This just happened all of a sudden.  I have been trying multiple combinations for a week and I get the same error.

------

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/583#issuecomment-1953173154

**Comment by Forlorn-Hope** [comment]
Took a while, but I finally got there.  Bless You.

**Comment by MoojMidge** [comment]
Glad you got it working, hopefully shouldn't re-occur in the future.
