### ISSUE TITLE
YouTube Test Repo (Official) is not being updated

### ISSUE THREAD

**Issue by XxAcielxX** [anxdpanic/plugin.video.youtube#712]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.6-beta.1
* Kodi Version: Kodi 20.3
* Kodi GUI Language: English
* Operating System: LibreELEC 11.0.6
* Operating System Language: English

------

### Expected Behavior

They Repo should show newly added beta versions when released right away.

------

### Current Behavior

Repo version is stuck on 7.0.2~alpha7.

------

**Comment by Nanomani** [comment]
@XxAcielxX 

you have all you need here : 
https://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/repositories/

source : 
https://github.com/anxdpanic/plugin.video.youtube/issues/651#issuecomment-2050495669

**Comment by XxAcielxX** [comment]
Reinstalled https://ftp.fau.de/osmc/osmc/download/dev/anxdpanic/repositories/repository.yt.testing_official-2.0.7.zip and now it is showing proper beta versions. Thanks
