### ISSUE TITLE
Setting for using thumbnail as fanart

### ISSUE THREAD

**Issue by homestreamer** [anxdpanic/plugin.video.youtube#716]
### First, thanks for this great addon!

I thought to use video thumbnails as fanart to display in large widgets on the TV Screen.
Say for fullscreen widgets, 
could we give an option for thumbnail to be shown as fanart?

------

### An option in settings to use video thumbails as fanart

I have no coder atm - no idea how to go about this, so helps will be much appreciated!

is there any way this can be achieved by messing with skin files - set fanart as thumb maybe?

damn sure this will be nice to browse through as a fullscreen widget on Jurial's skins, coaceptic, etc....

------

**Comment by MoojMidge** [comment]
Why would you want the thumbnail as fanart? It is often low resolution, and for widget or skin views that show full screen fanart, it is almost universally as a background behind the video thumbnail or poster, which means it would just be an enlarged, blurred version of whatever is already in the foreground.

Do you have a screenshot of what you want to see?

**Comment by homestreamer** [comment]
![ytbg](https://github.com/anxdpanic/plugin.video.youtube/assets/164910098/8db5e045-a750-4c6a-b4c0-fc081c99c644)
Thanks for looking into this
Got it figured out
as you said its a blurry low res image
tho i hope it will serve its purpose well as an easy interface for my grandparents to navigate....

Thanks again for your support!

**Comment by MoojMidge** [comment]
Oh, there is nothing in the foreground at all? Just the text? Is that a custom widget view you have created for your own use?

There might be something that can be done to improve the quality, as sometimes the quality of the default thumbnail is actually better than the high quality thumbnail, but the plugin currently does not check the actual resolution to confirm this.

**Comment by MoojMidge** [comment]
You can test https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.1 and see if that does what you want.

Has options for the following (read the changelog for further details):
- load higher quality thumbnails in plugin advanced setting (not needed for your use as you are not using thumbnails)
- use thumbnails as fanart for all videos in plugin advanced settings
- use thumbnails as fanart specifically for each widget path
