### ISSUE TITLE
In Estouchy skin, when playing a video, it doesn't show the channel name.

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#717]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.5
* Kodi Version: 19.4, 20.5, 21.0
* Kodi GUI Language: English
* Operating System: iOS, Windows 10
* Operating System Language: English

------

### Expected Behavior

When playing a video, at the moment when the player interface is visible, the channel name should be displayed next to the video title.

------

### Current Behavior

During video playback, when the player interface is visible, the channel name is not displayed.

------

### Additional Information

![kodi_2wotni501p](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/a97ddce0-9181-426f-b088-e17ea513ad4d)
![Telegram_OUMOPNkf8Z](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/66dab604-42f0-4768-bb3f-e36d1eabd876)

I don't know what version of the plugin is in the "correct" screenshot. I made it from my video with a demonstration of the plugin. It shows that the plugin icons are still red.

------

**Comment by MoojMidge** [comment]
I'm unlikely to fix this because doing so has some unintended consequences and won't work universally across different skins or even between the official and unofficial versions.

Kodi isn't quite full flexible enough to dynamically support different video types and the associated metadata.

One possibility may be to have a setting to choose how the channel name is used, but I'm not keen to add more settings.

**Comment by demouser007** [comment]
> One possibility may be to have a setting to choose how the channel name is used, but I'm not keen to add more settings.

Perhaps a setting with such a name may overload the interface and indeed it seems undesirable. But what if you put a small item "enable Estouchy skin compatibility" in the "advanced" category? I don't know how popular Kodi is on touch devices, but it's great on them, and I wish it would continue to work on them with a user-friendly interface (Estouchy skin).

**Comment by MoojMidge** [comment]
Wasn't thinking about something quite so specific.

It would be something like `Settings > Advanced > Views > Use channel name as` with the following options as a multi-select dialog:

- `Cast` - for additional display in info dialog
- `Studio` - old usage, triggers a bunch of file system requests for non-existent studio icons

By default channel name is used as artist for sorting purposes, this won't be configurable. Additional options may be added in future for unofficial version, to use as TV show title.

**Comment by demouser007** [comment]
> It would be something like `Settings > Advanced > Views > Use channel name as` with the following options as a multi-select dialog

That would be awesome.

**Comment by MoojMidge** [comment]
You can test https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.1 and see if that does what you want.

Has the option for how channel name is used.

**Comment by demouser007** [comment]
Wow, that was quick, thank you! Checked v7.0.7+beta.1 and it crashes at startup. Both on iOS and Windows, here's the [log](https://paste.kodi.tv/zumugijosu.kodi). I didn't add APIs, because without them, usually the plugin interface appears and some videos are played (for example in trends).

**Comment by MoojMidge** [comment]
Ah, yep, there are some bugs with that release which is why I haven't merged it into this repository yet. Thanks for the log.

In the meantime, you can still test that release out using https://github.com/MoojMidge/plugin.video.youtube/releases/download/v7.0.7%2Bbeta.1/plugin.video.youtube-7.0.7+beta.1.unofficial.1.zip

**Comment by demouser007** [comment]
This version doesn't crash. And the new setting works as it should, the channel name is now displayed in the Estouchy skin. Thanks!

**Comment by MoojMidge** [comment]
No problem, thanks for confirming.
