### ISSUE TITLE
unable to login: LoginException: Invalid_client' 'error_description': 'Invalid client type.' 'code': 401}

### ISSUE THREAD

**Issue by graysky2** [anxdpanic/plugin.video.youtube#718]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.6+beta.1
* Kodi Version: Omega
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

Youtube plugin should allow login

------

### Current Behavior

What is the current behavior?

Plugin does not allow login

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to log in
2. Enter the google code in another device and allow access on that device

------

### Log

Please include a complete [debug log](https://gist.github.com/graysky2/bb7554e5a397a9af957c4c5bbbb85f17)

------

### Additional Information

Initially experienced this on v7.0.5 so I tried the current beta 7.0.6.beta1 but both experience the problem.

------

**Comment by homestreamer** [comment]
Are you using the api key, clientid and client secret? fill it first and then log in, should work just fine...

**Comment by graysky2** [comment]
Yes, I have all of those fields populated. I’ve tried logging in several times over several days and I get that error each time.

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/583#issuecomment-1953173154

**Comment by graysky2** [comment]
Thank you.  I should have searched first.  Recreating the client ID (and API key although not needed) then following step 3 from the below link worked.

https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys

THANK YOU for all the work you do with this terrific plugin.

**Comment by MoojMidge** [comment]
All good, need to find time to update the Wiki and FAQ

**Comment by graysky2** [comment]
Agreed!
