### ISSUE TITLE
Bookmarks don't work in v7.0.6+beta.2

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#720]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.6+beta.2
* Kodi Version: 20.5 Nexus
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

------

### Expected Behavior

Add files from watch later/play lists or My Subscriptions to Bookmarks folder.

------

### Current Behavior

Error message and empty Bookmarks folder.

------

### Steps to Reproduce

Add file from watch later or My Subscriptions to Bookmarks folder 

------

### Log

https://paste.kodi.tv/aqohevuyuw.kodi

------

### Additional Information
Would be nice to provide a manual fix till next release.

Thanks a lot for support!

------

**Comment by MoojMidge** [comment]
I really shouldn't try to fix these issues with Kodi 18 without testing.

I'll push a fixed release out shortly, but the bookmarks database will contain invalid entries because of this mistake, which will mean that they will continue to create errors.

It is easy enough to fix on Linux/Windows/Mac using a sqlite database editor, but that may not be so easy on Android.

**Comment by MoojMidge** [comment]
Can you confirm whether the following release fixes the issue and the database?

https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.6%2Bbeta.3

**Comment by Mo1967** [comment]
Bookmarks workimg with beta3 in Android to fix issue and the database, thank you.
Log:
https://paste.kodi.tv/damoquxowa.kodi

**Comment by Mo1967** [comment]
Little wish, missing dialog to confirm if added or removed a file in Bookmarks.

**Comment by MoojMidge** [comment]
Great! Will push out a v7.0.6+beta.3 release with the temporary code to fix the database, then a final v7.0.6 without the temporary code.

Btw thanks for testing and opening these issues, it's been of great help.

> Little wish, missing dialog to confirm if added or removed a file in Bookmarks.

Bookmarks will be worked on in the future, to add some more features such as local playlists, and also add the notifications

**Comment by MoojMidge** [comment]
[v7.0.6+beta.3](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6%2Bbeta.3) is now available to fix this. Same as the release linked above.

**Comment by Mo1967** [comment]
@MoojMidge
It's not important, just a little reminder to add notifications for bookmarks in the future. Thanks for your great support.
https://github.com/anxdpanic/plugin.video.youtube/issues/720#issuecomment-2080096429

**Comment by MoojMidge** [comment]
It won't happen for a while. Other things are a higher priority

**Comment by Mo1967** [comment]
This weekend test trial. Thank you

**Comment by MoojMidge** [comment]
That linked commit is a straightforward change, but everything else in that branch is a bit of a mess. Not sure if it will even run. 

Don't waste your time using https://github.com/MoojMidge/plugin.video.youtube/tree/master

Will tidy it up and create a new beta for testing in this repository.

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.2

**Comment by Mo1967** [comment]
> https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.2

Confirm it, the notifications of bookmarks working fine. Thanks for your creative work.
[kodi.log](https://github.com/user-attachments/files/16114677/kodi.log)

**Comment by Mo1967** [comment]
Excuse delay, at last screencapture 
https://youtu.be/P284-ss-Qzk

**Comment by Mo1967** [comment]
@MoojMidge 
simple question on the edge, where save Kodi set bookmarks ? 
.......Have you great day

**Comment by MoojMidge** [comment]
On your system it would be located in
```
/storage/emulated/0/Android/data/net.kodinerds.maven.kodi21.firetv/files/.kodi/userdata/addon_data/plugin.video.youtube/
```

Within this folder will be one or more subfolders with names like `7e48e08402e540b7902f473f8eb7cb33` (as an example), based on the user profiles setup in the addon.

All files for that profile are located in the same profile subfolder. Bookmarks are contained in the `bookmarks.sqlite` file.

You can see which subfolder belongs to which profile by having a look in the `access_manager.json` for the `id` and `name` fields of the `users` collection e.g. `7e48e08402e540b7902f473f8eb7cb33` is used for the profile named `Default` in the addon. 

```
{
    "access_manager": {
        "current_user": 0,
        "developers": {},
        "last_origin": "plugin.video.youtube",
        "users": {
            "0": {
                "access_token": "",
                "id": "7e48e08402e540b7902f473f8eb7cb33",
                "last_key_hash": "",
                "name": "Default",
                "refresh_token": "",
                "token_expires": -1,
                "watch_history": "HL",
                "watch_later": "WL"
            }
        }
    }
}
```
