### ISSUE TITLE
More details in video description

### ISSUE THREAD

**Issue by mhomak** [anxdpanic/plugin.video.youtube#721]
### What Problem Does This Solve? 

In Kodi player, when "info" button is pressed currently channel name, views, likes, comments and video description is displayed.

I suggest it'd be useful if below are also displayed:
* full video upload date (day-month-year) (Youtube web site shows this on the top line)
* URL of the video ( e.g. https://www.youtube.com/watch?v=......) . This would be useful e.g. when you display info screen on Yatse, you can click/copy the link and open the video page in your phone.

**Comment by MoojMidge** [comment]
> * full video upload date (day-month-year) (Youtube web site shows this on the top line)

This is a skin issue. While it doesn't show up in the default Kodi skin as part of the player video info, it does show up in the regular video info and is also shown in the video listings.

Adding the date to the description (plot) will mean it is doubled up in the regualar video info window, and in any other skin that shows more details of the playing video.

There is also limited space available to show the description, so adding more details to it, means that even less of the actual description gets displayed without scrolling.

> * URL of the video ( e.g. https://www.youtube.com/watch?v=......) . This would be useful e.g. when you display info screen on Yatse, you can click/copy the link and open the video page in your phone.

This is a good idea. Will consider adding it to the end of the description.

**Comment by mhomak** [comment]
Thanks for your response. I have few more requests in mind but they're less trivial so I'll open separate issues for them in following days.

> This is a skin issue. While it doesn't show up in the default Kodi skin as part of the player video info, it does show up in the regular video info and is also shown in the video listings.

I'm using the default Estuary skin and I'll look into it if it has an option/modification for showing video info. 

Thanks!

**Comment by MoojMidge** [comment]
The video link should be shown at the botton of the video description in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7%2Bbeta.2 can you confirm this works?

**Comment by mhomak** [comment]
It works a treat, thanks!
