### ISSUE TITLE
This Video is not available

### ISSUE THREAD

**Issue by karldixon1986** [anxdpanic/plugin.video.youtube#729]
If i try to play a video (mainly music videos) I get a failed to play. This video is not available notfication.

I have installed a blank copy of Kodi V21 Omega and I have only installed the latest beta version of the youtube addon. Version 7.0.6+Beta.3

If I go back to version 7.0.6+Beta.1 the problem goes away but the problem with not being able to queue up a playlist still exists.

here is a copy of my log https://paste.kodi.tv/gixelowili

Please provide any relevant information about your setup

* Add-on Version: 7.0.6+Beta.3
* Kodi Version: Kodi V21 Omega
* Kodi GUI Language: English
* Operating System:  Android (Firestick)
* Operating System Language: English

------

### Expected Behavior

I expect the video to play as it did in beta version 1 of 7.0.6 with the ability to queue up tracks as I used to be able to.

------

### Current Behavior

Video fails to play with notification 'This Video is not available'

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Downloaded the latest 32bit Android APK of the Latest Omega V21 of Kodi and side loaded to firestick
2. Downloaded and installed the latest Beta3 version of youtube plugin Version 7.0.6
3. Went through complete configuration wizard
4. Inputed my personal API keys
5. Signed in and used the search function to find a music video, in this case Ren. Short name. Tried all and none played.
6.

------

### Log

https://paste.kodi.tv/gixelowili

Thanks for all your great work, if I was a little better at python and all things youtube I would be trying to help sort this issue. Unfortunately im not.

**Comment by woodside007** [comment]
See... https://github.com/anxdpanic/plugin.video.youtube/issues/730#issuecomment-2080612367

**Comment by MoojMidge** [comment]
There is a bit more detail in #730, can continue the discussion there.
