### ISSUE TITLE
”History” list is empty

### ISSUE THREAD

**Issue by malversan** [anxdpanic/plugin.video.youtube#73]
First of all, thanks a lot for your good work.

Add-on Version: 6.8.8
Kodi Version: 18.9
Kodi GUI Language: Spanish
Operating System: MS Windows 8.1
Operating System Language: Spanish

The ”History” list appears empty since some days ago, with no entries at all. I suppose it may be related to the changes exposed in #56 (I wanted to just add this information there, but now the comments are closed in that issue).

In fact I've seen that ”History” seems to have been removed from the 6.8.9 beta. Could it be possible to reimplement ”History” in a way similar to ”My subscriptions”?

<Not_about_the_issue_itself>
”History” may not seem an important shortcut for everyone, but I used it a lot to review things and specially as the easiest way to create short-lived lists of related videos to view just after search navigation. For example, with the mobile you can fastly search for and visit the videos you want to see and go visiting related ones without actually seeing them; then you go to ”History” in Kodi and voilà, there are all they, ready for the big screen. That has been very useful for me since now.
</Not_about_the_issue_itself>

Thanks in avance for your help.

**Comment by anxdpanic** [comment]
If I could add a fix at this time I would, it's on the list to keep an eye for a solution for future versions.

**Comment by anxdpanic** [comment]
btw for a kodi only history.

Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History`
That will be your Kodi history playlist, it's a pita but it's the only alternative atm.

**Comment by malversan** [comment]
Thanks for the quick response and the workaround.
