### ISSUE TITLE
Increase maximum "items per page" to more than 50

### ISSUE THREAD

**Issue by MarkWieczorek** [anxdpanic/plugin.video.youtube#732]
### What Problem Does This Solve? 

In the settings, the user is allowed to set the maximum number of "items per page", but the maximum allowable value is 50. I request that we change this to a larger value, somewhere closer to 100 or 200.

**Comment by MoojMidge** [comment]
https://developers.google.com/s/results/youtube/v3/?q=maxresults&text=maxresults

Not possible without extra requests, which increases complexity and slows everything down
