### ISSUE TITLE
No audio stream options available.

### ISSUE THREAD

**Issue by dezibelkarate** [anxdpanic/plugin.video.youtube#747]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.6.3
* Kodi Version: 20.3
* Kodi GUI Language: English
* Operating System: LibreELEC 11.0.6
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

In video player settings -> audio settings -> Audio stream I can change between different available audio streams/languages available for the current video.

------

### Current Behavior

What is the current behavior?

In video player settings -> audio settings -> Audio stream I cannot change the audio stream. Only the default audio stream is available, even for videos that should have multiple audio streams/languages available.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

You can reproduce this with e.g. this Youtube video: https://www.youtube.com/watch?v=sVMVd1vPtF0&t=5s

When viewing this in a browser, you can see that the video does have mutliple language options, however none of them show up on the Kodi youtube addon except for the default language option.

I could add a log file if it is neccessary.
------

**Comment by MoojMidge** [comment]
The plugin will allow you to switch between whatever audio streams it can access.

The default fallback clients that are being used do not allow for access to anything except the default audio stream. This won't change until the web client or main client is re-enabled.

If you want access to the alternate audio streams, then you can try to change the default client `Settings > Advanced > Use alternate client details > Alternate #1`, but available video qualities may be effected.

**Comment by dezibelkarate** [comment]
Your suggestion with `Use alternate client details` has helped me. The YT plugin now selects the correct default Audio stream. Thanks for your help.
