### ISSUE TITLE
It kicks me out of the app

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#748]
It kicks me out of the app when I use the back button.

_YouTube 7.0.6.3, RPi4, LibreELEC 11.0.6_

**Comment by MoojMidge** [comment]
Follow the issue template and get a debug log

**Comment by drrak** [comment]
Check it yourself, it will be faster. This is a common failure. Just play the video and use the Back button.

**Comment by MoojMidge** [comment]
If you want some help with your problem, then you need to provide full details of your problem, with a debug log.

**Comment by drrak** [comment]
Maybe I'll do it someday.
Now I turned off MPEG-DASH and it doesn't kick me out of the app, but it means I have 720p30 and I can't play only sound, which also sucks.
