### ISSUE TITLE
The ability to hide Live videos, similar to hiding shorts

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#755]
The ability to hide shorts is very useful. The demand for this feature exists because people want to watch more high quality videos and less low quality ones. The idea is that less effort is put into creating shorts. This implies that they are of lower quality and that they can be neglected. The same reasoning applies to streams. So, they can also be neglected if you want to watch only the highest quality videos. 

I don't know if this is technically possible, but the ability to hide streams would perfectly complement the ability to hide shorts.

**Comment by MoojMidge** [comment]
What do you mean by stream? A currently live stream or future live stream that has not premiered?

**Comment by demouser007** [comment]
I meant all Live videos. Future, current and completed. In essence, it's a separate genre of videos that strongly characterizes their quality, just like the Shorts genre.  In the web version of YouTube, on the channel page they are placed under a separate "Live" tab, and in subscriptions they are marked with a red "Live" label for current ones, a "Streamed" caption for completed ones, and a "Scheduled" caption for future ones.

**Comment by demouser007** [comment]
Also, these genres can be characterized by similarities with other services. For example, Shorts are the TikTok part of YouTube, and Live videos are the Twitch part of YouTube. And regular videos are the core part of YouTube. So, if these genres are not your favorite, the desire to turn off "TikTok" and "Twitch" inside YouTube feeds is quite rational.

**Comment by neo-neo1** [comment]
I always thought having the ability to hide scheduled streams would be a welcome improvement. Even better would be to hide scheduled streams which priemere longer than x minutes in the future.

**Comment by MoojMidge** [comment]
You will both need to be more specific. Please post a screenshot of what you want filtered out and from where.

Live streams are already separately categorised in channels.

When they are displayed, scheduled streams are already distinguished by being displayed in italics with premiering details in the description. Can't see where this would regularly occur except in My Subscriptions though.

Where else is there mix of normal videos and live or scheduled streams? Searches?

**Comment by demouser007** [comment]
The idea is to hide Live videos as a genre. All of them, upcoming Live videos, finished Live videos, and current Live videos. Specifically, I want them not to be in "My Subscriptions" and "Subscriptions". In "My Subscriptions", after enabling the suggested setting, Live videos (all three of their kinds) should just disappear as Shorts. In "Subscriptions", upcoming Live videos, finished Live videos, Live videos within playlists saved by the channel, Live videos in search results and the "Live" folder (which, as I understand, refers to the current Live video) should disappear.
I don't use the other "Folders" of the plugin. But if I did, I would like to have no Live videos in the other "Folders" either. I think people who don't want to watch this genre, would also like its absence in all parts of YouTube. That is, global disabling of Live videos would be appropriate, as it is now done with short videos. But it is important to be able to hide Live videos in "My Subscriptions" and "Subscriptions" folders, because these parts of YouTube are controlled not by algorithms, but by the user.

In the attached screenshots, current Live videos are marked in red, completed Live videos in blue, and upcoming Live videos in green.

Here's how I see it. Enabling the "Hide Live videos" setting should hide red, blue and green at the same time, in all folders of the plugin (except those specifically about Live). Or, enabling the "Hide Live videos in My Subscriptions and Subscriptions" setting should hide red, blue and green in those folders.

![01](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/32d67b99-f59d-4410-b584-9eb909c7236e)

![02](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/8097d4db-26bc-41ba-b5be-737959e19ef3)

![03](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/d98d6544-87e5-43c0-a9bd-ca35e1950d17)

![04](https://github.com/anxdpanic/plugin.video.youtube/assets/11842977/2c9fb893-ae48-464d-b6ff-ef0ed6ca1fe7)

**Comment by neo-neo1** [comment]
> You will both need to be more specific. Please post a screenshot of what you want filtered out and from where.
> 
> Live streams are already separately categorised in channels.
> 
> When they are displayed, scheduled streams are already distinguished by being displayed in italics with premiering details in the description. Can't see where this would regularly occur except in My Subscriptions though.
> 
> Where else is there mix of normal videos and live or scheduled streams? Searches?

Really the subscriptions feed is the one that matters.

**Comment by MoojMidge** [comment]
@demouser007 - thanks for explaining what you want clearly.

The plugin currently does not currently identify completed live videos, but filtering out curent or future live videos can be done

**Comment by demouser007** [comment]
Of course, filtering out curent and future live videos is better than nothing. But most live videos in feeds are actually completed live videos. So, to get rid of this Twitch genre on YouTube, they should be hidden in the first place.

"The plugin currently does not currently identify completed live videos"

But in principle, is it technically possible? That would be very useful.

I don't know about everyone, but it seems to me that YouTube in Kodi is best suited for thoughtful, slow viewing of high-quality videos. Because in terms of interface speed, in terms of convenience of switching to different parts of YouTube there is a strong gap in comparison with the official application. Accordingly, the plugin development in this direction, where speed and responsiveness are not ideal, but the user's awareness and control over what is happening is higher, seems to be the most rational.

**Comment by MoojMidge** [comment]
> But in principle, is it technically possible? That would be very useful.

This information is not officially provided by the YouTube API, so there is no reliable method to do this, without making some fairly extensive changes. There may be a semi-reliable way to do it, but don't know how accurate it will be.

If it works reliably enough, will change the display of all channels/searches to not include any live streams (past, present or future). All live streams will instead only be displayed in the corresponding Live sub-folder, unless the folder is hidden. There won't be a global option to disable this folder, only the existing plugin url parameter.

There will be an additional filter, similar to and replacing the filter for short videos, that will apply to all video listings including My Subscriptions, that will allow the user to select any of the following to hide:
- shorts (globally)
- live videos
- upcoming videos
- upcoming live videos (if possible to distinguish from premiering videos)
- premiering videos (if possible to distinguish from upcoming live videos)
- completed live videos (if possible)
- filter live folders

That should achieve what you are after

**Comment by demouser007** [comment]
This all sounds very impressive. Hopefully the unofficial way to determine Live videos will be reliable enough. One thing I don't really understand, will it be possible to hide Live sub-folder but not to disable it? Seems like from a user perspective it's pretty much the same thing. Being able to hide that folder certainly solves the problem.

**Comment by MoojMidge** [comment]
> unofficial way to determine Live videos will be reliable enough

It is not live videos, it is **_completed_** live streams that are problematic to identify, or distinguish from completed non-live videos i.e. "Premieres" on YouTube.

> One thing I don't really understand, will it be possible to hide Live sub-folder but not to disable it?

This has been possible using the `hide_folders=true` or `hide_live=true` plugin url query parameter for a long time.

**Comment by demouser007** [comment]
@MoojMidge thank you so much! The way you implemented everything is beyond expectations.

I found a small problem after adding the ability to hide videos, which is that "items per page" takes into account all hidden videos. 

Also, due to the ultimate versatility of the "Hide videos from listings" setting, it seems reasonable to add keyword filtering there as well.

**Comment by MoojMidge** [comment]
> I found a small problem after adding the ability to hide videos, which is that "items per page" takes into account all hidden videos.

When filtering, items per page can only be considered a maximum value. It is not practical to fix it as the filtering can only be done after all the data is retrieved from YouTube, and creating additional requests to fill the listings will slow things down too much.

> Also, due to the ultimate versatility of the "Hide videos from listings" setting, it seems reasonable to add keyword filtering there as well.

Yes it is possible, but it is too much additional work for me to look at for the moment. Most of the current live filtering stuff was something that had already been done to filter out upcoming videos. Maybe later if I feel bored when travelling and remember it.
