### ISSUE TITLE
[Leia] Noticeable delays after the update to v7.0.x

### ISSUE THREAD

**Issue by pitsi** [anxdpanic/plugin.video.youtube#757]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.6.3+leia.1
* Kodi Version: 18.9
* Kodi GUI Language: Greek
* Operating System: LibreELEC (official): 9.2.6 x64
* Operating System Language: en_US.UTF-8

------

### Expected Behavior

Kodi should be faster in opening searches, bookmarked channels and other things that return a LIST of videos.

------

### Current Behavior
However, because all of those warnings and errors you can see in the log below, there is a noticeable and annoying delay every time.

------

### Steps to Reproduce

1. (probably optional) Under settings > advanced > views, disable "show channel name and video details in description" and "show video details in video lists".
2. Search for something. Or use something that would return a list of videos, e.g. a bookmarked channel or a submenu like live or subscriptions.
3. Notice the time kodi takes to create the list of the videos. It was almost instant at v6.2.x.

------

### Log
Not a complete one, but long enough to show the issue
```
2024-05-15 12:28:10.048 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.049 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.049 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.049 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.049 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.commentCount"
2024-05-15 12:28:10.049 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.commentCount"
2024-05-15 12:28:10.285 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.285 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.285 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.285 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.285 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.commentCount"
2024-05-15 12:28:10.285 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.commentCount"
2024-05-15 12:28:10.387 T:140626435979008  NOTICE: [plugin.video.youtube] Running: YouTube (7.0.6.3+leia.1) on Leia (Kodi-18.9) with Python 2.7.16
                                            Path: /channel/UCSJPFQdZwrOutnmSFYtbstA/
                                            Params: {'incognito': True}
2024-05-15 12:28:10.394 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.394 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.viewCount"
2024-05-15 12:28:10.394 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.394 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.likeCount"
2024-05-15 12:28:10.394 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.commentCount"
2024-05-15 12:28:10.394 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.commentCount"
2024-05-15 12:28:22.160 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.viewCount"
2024-05-15 12:28:22.160 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.viewCount"
2024-05-15 12:28:22.160 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.likeCount"
2024-05-15 12:28:22.160 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.likeCount"
2024-05-15 12:28:22.160 T:140626435979008   ERROR: CSetting: error reading <control> tag of "youtube.view.label.color.commentCount"
2024-05-15 12:28:22.160 T:140626435979008 WARNING: CSettingGroup: unable to read setting "youtube.view.label.color.commentCount"
```
------

### Additional Information

For the log above, I used a channel I have bookmarked (in kodi's bookmarks) years ago. I open it from there all those years, e.g. I do not search for it from the addon. Until yesterday and before applying the patch mentioned at #754, the channel would not even open! And it was not the only one. I did not keep a log from that failure, but if i come accross another bookmarked channel that does the same, I will open a new report.

------

**Comment by MoojMidge** [comment]
Kodi 18 is not supported

**Comment by pitsi** [comment]
Well, YOU approved a commit for python2 issue just yesterday! If you, as the main dev right now, do not want to do something for it, either completely remove support for python2 or let someone else do it, like @JimmyS83. Btw, I would like to publically thank him (and anyone else invoilved) for all the backporting he has done to keep 6.2.x running on python2 until today.
 
Ontopic now. As it seems, the whole delay happens because the addon can not read some variable, e.g. `youtube.view.label.color.viewCount` from the settings.xml file. I used the addon to do less than 10 times today searches (searches and listing of my bookmarked channels) today and its delay was very annoying. 

Let's assume that the missing variables are missing because of the upgrade from 6.2.x to 7.0.x. What are my options now?
I remove the addon completely, with its settings, reinstall it, reconfigure it (which is the most time consuming procedure) and hope that they will now be registered in settings.xml. Or I remove it completely, reinstall 6.2.x and hope that it's settings are the files I see in here and can be restored instantly
```
# ls .kodi/userdata/addon_data/plugin.video.youtube/f1a1452f58ec4ca4925ec2dd1389e5cf/
cache.sqlite       data_cache.sqlite  history.sqlite     search.sqlite
```
If anyone can confirm that these files are indeed the backups from 6.2.x, I will do it during the weekend and forget 7.0 forever... or until those idiots behind youtube's api break something important again.

**Comment by MoojMidge** [comment]
> either completely remove support for python2

There is no reason to do that, just more unnecessary work at this point.

A significant number of recent issues have been caused by trying to maintain support for Kodi 18, and when it becomes too burdensome to do so I will simply stop bothering to do so.

Responding to things like this is also a time burden that will hasten that occuring.

Anyone else is free to do what they want.

> Ontopic now. As it seems, the whole delay happens because the addon can not read some variable

There may indeed be a slowdown but it is not caused by the lines in the log you have posted. 

One of the reasons #754 was fixed was because identifying and fixing the problem was trivial and has no impact on supported Kodi versions. 

"Fixing" the errors and warnings in your log would involve removing features from supported Kodi versions, which Kodi 18 does not implement, and I wont be doing that. 

However by itself, what you have identified has no impact on the speed of the plugin apart from filling up your log, which may have some small mpact on really slow devices with slow I/O.

If you have an issue follow the issue template and post a complete debug log.

**Comment by pitsi** [comment]
I agree with everything you say but:

The reason I am mentioning the missing variables is because they do exist on my pc's installation of kodi 21 + youtube 7.0.5. I do not care about some extra lines in the logs logs and more read/writes.

Moreover, removing the addon and reinstalling is something I want to avoid because I have 47 bookmarked channels, videos and playlists. I thought they were 25 to 30, but they are more.
```
# cat .kodi/userdata/favourites.xml | grep youtube | wc -l
47
```
These will be deleted from the favorites the moment the addon is uninstalled, but they won't be added back when I reinstall it, which means I will have to add them back one by one, provided that I can remember them. But I don't :(
Yes, I know how to back up stuff etc, but this is stll an issue. 

Last but not least, the new version has broken another addon which relies on youtube for some reason (it even lists it as a mandatory dependency). Here is a small part from the log which proves that the addon simply fails.
`File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/__init__.py", line 13, in <module>`

Please note that I do not ask help on those 2, I am just mentioning them. So, what is left to do other than revert to 6.2.x and hope that the files in the forementioned folder are really a backup from it?

**Comment by pitsi** [comment]
Small recap of what happened during the weekend. Every time I say folder below, I mean `~/.kodi/userdata/addon_data/plugin.video.youtube/`.

On my first try, I only deleted the settings.xml file from the folder. Launching the addon forced the wizard to run again, I answered the questions again like I did before, ommiting the ones I consider pointless, e.g. the one about my region/location. Sadly, the delay and the errors were still there.

On my second try, I deleted every file from the folder (except the keys). Launched the addon, the wizard started again and I answered yes (and set up) to every single question, even on the pointless ones! And magically, the delay is now gone! Maybe the deleted files, which were probably imports from 6.2.x, were causing some issue. The errors and the warnings of the missing variables in the log are still there though, but I don't care.
So, if anyone has the same delay issues after the upgrade, answer YES to every question the wizard asks. I know it is mentioned at the top of each release and in an "important" tag, but the wizard should also accept no as an answer :D 

On the other hand, the addon that uses youtube internally for its functions fails because of this bit, which is a shortcoming of python2. I will post on the other issue about it.
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)`

**Comment by MoojMidge** [comment]
> If you have an issue follow the issue template and post a complete debug log.

As I said, there may be an issue, but it is not caused by those lines in your log. Even if I wanted to figure out what was happening, I can't given the lack of information.

**Comment by pitsi** [comment]
I got the update to 7.0.7 an hour ago and, let me be honest, if this is what I have to do after each update of the addon, I'd rather ditch youtube 7.x on kodi 18 completely. The first run wizard showed up, again. I answered yes to all of its questions and configured everything on the dialog boxes that followed them, again. This means I practically reconfigured it without first deleting its existing files like last time, but some settings do not seem to apply. E.g. now the shorts and the like/view/comment count appear everywhere, although I had disabled them both.

Last but not least the delays, are also back! Yes, 15+ seconds to load a channel and its 20 video entries (limit set in the settings), with each video being 3-5 minutes long, is a lot! I am very disappointed.

**Comment by MoojMidge** [comment]
> E.g. now the shorts and the like/view/comment count appear everywhere, although I had disabled them both.

Lol... shorts aren't configured using the Setup Wizard, and Kodi 18 does not even have the ability to show the video statistics in the listings as the functionality that is used to enable that was only introduced in Kodi 19.

> I'd rather ditch youtube 7.x on kodi 18 completely.

I agree that is the best option. I won't make any further concessions for Kodi 18 compatibility. Trying to appease a vocal minority is just a waste of time.

Kodi 18 releases will still be automatically generated until I get around to removing that as well, but from now on they probably won't even load.

**Comment by pitsi** [comment]
First and foremost, I have to admit that it was unfair to complain about the shorts because its setting is now under a submenu that has more options in it. 

I would apologise for the wizard as well, but I saw some other settings being reset to their default values and I think the forced wizard run is to blame. For instance, I have disabled inputstream adaptive and fanart (and some more settings), since ever, and they got re-enabled. 
Honestly, I respect your work, but some things need to be said. I hate youtube's api and the issues it randomly causes on the addon (e.g. right now I have a recently uploaded video that buffers even at 360p), so the extra work I have to do on the addon itself to have a proper youtube experience, annoys me more.

**Comment by MoojMidge** [comment]
You don't need to apologise, just don't have time for random complaints. 

> but some things need to be said

No, not really. If you have an issue the only way it can be resolved is if you provide a log, because there is obviously something very odd with your specific setup.

Nothing can be done by just saying a bunch of stuff. It wastes your time typing it up, and my time reading and responding.

You have had plenty of opportunities to provide a log. If you don't want to, that is fine. Just move along.
