### ISSUE TITLE
Ubuntu 22.04 LTS - Can't login anymore to my account (API always used and working)...

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#759]
### Context
**2nd EDIT**
Remove the sign about 7.0.6.3... apparently it's back to work after a clean reinstall of addons. Info in last reply.

* Add-on Version: 7.0.7 beta 1 unofficial ~~but also tryed to step back to stable 7.0.6.3~~
* Kodi Version: flatpak 21.0 (21.0.0) Git:20240406-60c4500-dirty compiled 2024-05-10
* Kodi GUI Language: Italian
* Operating System: Ubuntu 22.04 LTS
* Operating System Language: Italian

------

### Expected Behavior
Addons works as ever.... apparently about 48 hours ago the addons work. At right now i run kodi and youtube addons apparently not logged in.

------

### Current Behavior

I can try to re-login (open the two tabs google.com/device) but after put the second code create it's appears a notification about kodi log related and addons remain unlogged.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Simply run Kodi 21.0
2. Open Youtube addons 
3. If i want try to re-login and fail 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/15327586/kodi.log)

------

### Additional Information
Now try to obtain a full debug kodi.log.... after i obtain this i will try to add it whit an edit.

*1st EDIT*
Can UPLOAD a complete and FULL DEBUG LOG.....
On this i can also tryed to re-login my account (whit two browser tabs open at google.com/devices) and after second code it's fail and addons remain unlogged.
At the end i have also tryed to open various time "My Subscription" and also "My Subscription (filted)" and both fail....

Simply Youtube addons NOT works at all.......... 
How i can fix ?
And this is the full debug log........ i hope it's usefull:
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/15327659/kodi.log)

------

**Comment by DjDiabolik** [comment]
Right now i have tryed to update the Youtube addons also on Windows 10........... apparently 7.0.7 Beta 1 it's not work also here... on kodi.log appears also so many error:
https://pastebin.com/TmrBpH5M

**Comment by MoojMidge** [comment]
> also tryed to step back to stable 7.0.6.3

Are you sure? The bug does not exist in this version.

v7.0.7 will probably in beta for a while, suggest using a stable release if you are having issues.

**Comment by Eontech** [comment]
> > also tryed to step back to stable 7.0.6.3
> 
> Are you sure? The bug does not exist in this version.

My mistake.  7.0.6.3 Does, allow me to sign in.
The only difference I see is that 'My channel' is now empty (sometimes with an error, I'll try and dig it up in the logs), but Search, Playlists and Subscriptions are now there which is all I care about.  Thanks.

Regarding Search history... I did go through the wizard and somehow got my very old searches back but lost the new ones after confirming 'Delete search.sqlite3?'  which is a shame but at least I now know which file to backup :)

This is the only entry when requesting 'My Channel'
```
2024-05-17 00:20:23.869 T:37366    info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-17 00:20:24.843 T:37366    info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_02.0.hdmi-stereo in pcm mode with Buffersize 200 ms Periodsize 50 ms
2024-05-17 00:20:26.066 T:41224    info <general>: [plugin.video.youtube] Running: YouTube (7.0.6.3) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /channel/mine/
                                                   Params: {'category_label': 'My Channel'}
2024-05-17 00:20:26.355 T:41224   error <general>: [plugin.video.youtube] API error: playlistNotFound
                                                   exc: |"error" in response JSON data|
                                                   message: |The playlist identified with the request's playlistId parameter cannot be found.|
                                                   Request response:
                                                   {'error': {'code': 404, 'message': "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.", 'errors': [{'message': "The playlist identified with the request's <code>playlistId</code> parameter cannot be found.", 'domain': 'youtube.playlistItem', 'reason': 'playlistNotFound', 'location': 'playlistId', 'locationType': 'parameter'}]}}
```

**Comment by DjDiabolik** [comment]
I have some news. @MoojMidge 
I have just EDITED the first post because about 5 minutes ago i have made a clean full reinstall of current stable 7.0.6.3 unofficial on kodi 21 flatpak and apparently NOW all it's works flawlessy.
I can use my usual API keys and i have correctly login my usual account..

So... i thinks right now i can update to 7.0.7 beta 1 but I had already done it in the past and I wouldn't want this version to stop working after X many hours.
