### ISSUE TITLE
Only getting 360/720p options to play

### ISSUE THREAD

**Issue by Tomte-Fan** [anxdpanic/plugin.video.youtube#761]
### Context

When "casting" a video from my phone/tablet to kodi it only plays in low resolution, I've enabled asking for quality so it shows 360p and 720p as the only options. If I dismiss this dialog and try again I usually get a 1080p/4k option as well, sometimes I have to try again.

* Add-on Version: 7.0.6.3
* Kodi Version: 21.0
* Kodi GUI Language: EN
* Operating System: Libreelec
* Operating System Language: EN

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Send video to kodi via Kore on android
2.  Video is playing in low resolution
3. ....

------

### Log

Debug log of the first attempt to play a video and only getting 360p and 720p as quality options:
[kodi_only_360_720p.log](https://github.com/anxdpanic/plugin.video.youtube/files/15369831/kodi_only_360_720p.log)

Second attempt, this time I get a 4k option as well plus some other extras:
[kodi_4k.log](https://github.com/anxdpanic/plugin.video.youtube/files/15369832/kodi_4k.log)

**Comment by MoojMidge** [comment]
Can you post a complete debug log? The snippet provided is not enough to identify the cause of the issue

I think I know what it is, and believe it is already fixed, but need a log to confirm

**Comment by Tomte-Fan** [comment]
Here is a log, it has a few successes and the last only gives 360 and 720p.
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/15377402/kodi.log)

**Comment by MoojMidge** [comment]
Thanks. Should be fixed by https://github.com/anxdpanic/plugin.video.youtube/commit/8ac77074a534f90a11de16e39d340273a6431565

Available in current beta release for testing.

**Comment by Tomte-Fan** [comment]
Thanks, yes it seems to solve the problem.
