### ISSUE TITLE
A quirk in beta

### ISSUE THREAD

**Issue by OldManJax** [anxdpanic/plugin.video.youtube#763]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7+beta.1
* Kodi Version: 21.0
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.
Normal display

------

### Current Behavior

What is the current behavior?
For some reason this beta causes my screen to flash like it's trying to load, or reload something.
It only happens on the menus not during video playback.
Sorry I can't troubleshoot any further, I don't have much spare time and already gone back to 7.0.6.3. Just thought I'd give your beta a test run while enjoying my morning coffee. lol

------

**Comment by MoojMidge** [comment]
The beta releases are reliant on user testing and reporting issues.

Unless you are testing, or if there is a known issue that is fixed in a test release, the current stable release will generally always be the better option for normal usage.
