### ISSUE TITLE
Youtube 7.0.7+beta.1 : Add video broken

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#764]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.7+beta.1
* Kodi Version: 20.5
* Kodi GUI Language: FR
* Operating System: Android
* Operating System Language: FR

------

### Expected Behavior

Adding video for later viewing shall save it in folder. 

------

### Current Behavior

It displays error message. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Select video to save 
2. Hit middle button to show menu
3. Choose more ->add to

------

### Log

[Here](https://paste.kodi.tv/qafadunuha.kodi)

**Comment by MoojMidge** [comment]
Another typo snuck in.

If you are able to, the following line: https://github.com/anxdpanic/plugin.video.youtube/blob/0faec8bba361ad6c74084cadc2bdca7597e62c9b/resources/lib/youtube_plugin/youtube/helper/yt_playlist.py#L181

Needs to change to:
```
    thumb_size = context.get_settings().get_thumbnail_size()
```

**Comment by karlo2105** [comment]
@MoojMidge 
I edited Youtube 7.0.7 beta 1 plugin with your fix and adding video works now. ;-)
The only reason I skipped 7.0.6 branch was a playing video update bug.
