### ISSUE TITLE
'Failed to add a suggested video' warning

### ISSUE THREAD

**Issue by Vichman67** [anxdpanic/plugin.video.youtube#77]
### Context

* Add-on Version: 6.8.8
* Kodi Version: 18.9.0
* Kodi GUI Language: English
* Operating System: Ubuntu 18.04.5 LTS (Linux x86 64-bit)
* Operating System Language: English

------

### Expected Behavior

It is supposed for YouTube Kodi addon to play next suggested videos after the current one being viewed finishes.

------

### Current Behavior

Since the last 2 or 3 weeks YouTube addon fails to play suggested videos. With the option 'Autoplay suggested videos' on, every time a video playback starts it shows a pop-up window on the upper right corner of the screen with the message 'Failed to add a suggested video'.

The video playback runs fine and, when ending, of course it doesn't automatically play next suggested video.

This happens not only on Linux (from where I'm posting the debug log) but also from Raspberry Pi (2+ and 3) and LibreElec OS.

------

### Steps to Reproduce

1. Start Kodi and configure YouTube addon settings so it enables autoplay of suggested videos.
2. Start YouTube addon and make a simple video search.
3. Play any video resulting from that search.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.ubuntu.com/p/Jd79fhBk8g/

The kodi.log file referred covers all steps from starting Kodi through launching a video playback under YouTube addon until Kodi normal closing.

------

### Additional Information

Maybe you've yet realized this anomaly, but I didn't find anything regarding it on the open issues section...

Is perhaps this bug related to the change in YouTube automatic playing functionality? I've realized that previously the button for enabling automatic playing was positioned in the upper right part of the youtube.com web screen (prior to the list of recommended videos) but now it's positioned as a small button in the video frame bottom bar...

Thanks for your great work, mates!

------

**Comment by ntzb** [comment]
I have the same issue - I tried adding a new recommendation playlist according to other issues and https://github.com/anxdpanic/plugin.video.youtube/blob/master/changelog.txt#L4, but it doesn't change anything.

I get the exact same error 'Failed to add a suggested video', and while it previously had the ability to auto play suggested vidoes, it no longer works.
are we missing something?

**Comment by Vichman67** [comment]
No, we aren't missing anything. It seems Google changed its YouTube API (or something like this) so some of the previous Kodi YouTube addon facilities are not working. We just hope the kind group of developers have time enough to check the software code and modify it, but we have no right to complain. They've done a great job up to date, so we can only express our gratitude. Keep your fingers crossed!

**Comment by damnms** [comment]
facing the same problem - would love to have that working again
