### ISSUE TITLE
"Show channel name in video lists" in Views

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#773]
Now there is an option to enable simultaneous display of channel name and video details in description. There is no such option for video lists. Obviously, there is no such option because video lists have little space. But I think the channel name is more important than the number of views, likes and comments. It would be good if there was a choice between "Show video details in video lists" and "Show channel name in video lists". Specifically, such a setting would be useful for those who prefer the "wall" viewtype or Estouchy skin.

**Comment by MoojMidge** [comment]
This was already implemented a while ago.

Change the video listing sort method.

Sort by `Channel` will use default sort order, but also display the channel name
Sort by `Artist` will  display and also sort by the channel name
