### ISSUE TITLE
Youtube 7.0.7 : Next page error

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#779]
### Context

* Add-on Version: 7.0.7
* Kodi Version: 20.5
* Kodi GUI Language: FR
* Operating System: Android
* Operating System Language: FR

------

### Expected Behavior

Next page shall display page 2 with 50 results.

------

### Current Behavior

After having updated to 7.0.7, i can't access next page in subscription tab. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click on Youtube addon
2. Subscription
3. Scroll down to next page

------

### Log

Please include a complete [debug log](https://paste.kodi.tv/muwewiveba.kodi).

**Comment by MoojMidge** [comment]
Silly typo again. Can make this change yourself until I push an updated release out

https://github.com/MoojMidge/plugin.video.youtube/commit/e0b42c208e06f0c38f0688b577bad94930f6973e

**Comment by rwlove** [comment]
After applying manual change I can't even open "My Subscriptions".

EDIT: I guess this was user error on my part. I made the change again, rebooted and it's working fine.

**Comment by DjDiabolik** [comment]
@MoojMidge Same Issue also on Ubuntu 22.04 LTS whit 7.0.7 unofficial.
I also have a request to make:
While browsing a youtuber channel i can watch all "fanart" instead the usual and problably default "Watched or not Watched" Icons on video list. can this be changed?

**Comment by karlo2105** [comment]
@MoojMidge 
I updated Youtube addon with your fix, it works fine now.

**Comment by MoojMidge** [comment]
@DjDiabolik 
> I also have a request to make:

Please open a new feature request, rather than bringing it up in an unrelated issue. Provide as much detail as possible (screenshots help), as I don't really understand what you are looking for, but I suspect it will be skin dependant.

**Comment by DjDiabolik** [comment]
@MoojMidge 
I can confirm.... in my cause use the 7.0.7 unofficial. Download the RAW file here:
[resources/lib/youtube_plugin/youtube/helper/yt_specials.py](https://github.com/MoojMidge/plugin.video.youtube/blob/e0b42c208e06f0c38f0688b577bad94930f6973e/resources/lib/youtube_plugin/youtube/helper/yt_specials.py)

Copy this file over the original included in 7.0.7 and all back to work also next page on "My Subscription"

About strange views style over "Channel" i try to open a different issue.

**Comment by MoojMidge** [comment]
Can you confirm that this also fixed in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1
