### ISSUE TITLE
Switch User and My Subscriptions don't work  in v7.0.7

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#780]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.7
* Kodi Version: 20,5
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

------

### Expected Behavior

Switch User and open My Subscriptions with content from selected user.

------

### Current Behavior

My Subscriptions works for one user, but nothing happen if select another user and will open My Subscriptions.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Select another user in folder Switch User
2. Open My Subscriptions
3. Nothing happen ?!

------

### Log

Please include a complete [debug log]
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/15463469/kodi.log)

------

### Additional Information

With 7.0.7beta.3 no problems with My Subscriptions for all selected user.

Thanks for support

------

**Comment by MoojMidge** [comment]
There is a problem with not correctly changing the user data when the user is switched, but I can't replicate this exact problem. If anything what you should be seeing is that the previous users subscriptions show, not nothing at all. Must be some other change that I haven't committed yet that is effecting this.

Will try to get a test release out shortly

**Comment by MoojMidge** [comment]
Can you check if this is fixed in https://github.com/MoojMidge/plugin.video.youtube/releases/tag/v7.0.7.1

**Comment by MurDocgz** [comment]
Shortly after updating from 7.0.7 beta3 to 7.0.7 I could not access my subscriptions, I reset access manager but just the same, just tried 7.0.7.1 and now able to get back in to my subscriptions, thank you

**Comment by Mo1967** [comment]
Now it works for both users with  v7.0.7.1
..., although errors in the log.
[kodi(v7.0.1.1).log](https://github.com/anxdpanic/plugin.video.youtube/files/15492304/kodi.v7.0.1.1.log)

Thanks again

**Comment by MoojMidge** [comment]
> ..., although errors in the log

The plugin errors are of no consequence, just Kodi logging that the plugin url that performed the user switch action did not provide a directory listing for display.
