### ISSUE TITLE
Livestream plays old content

### ISSUE THREAD

**Issue by Jusix** [anxdpanic/plugin.video.youtube#783]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.0.7
* Kodi Version: Kodi 21.0 Omega
* Kodi GUI Language: German
* Operating System: Ubuntu 24.04
* Operating System Language: German

------

### Expected Behavior

Please describe the behavior you are expecting.

When I start the Livestream of 24h Nürburgring 2024 I expect the current timestamp to be played.

------

### Current Behavior

What is the current behavior?

Instead I get old stream content from the Livestream some hours ago and I can't fast-forward to the current content.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start https://www.youtube.com/watch?v=CyXzTK_bFSU in kodi
2. Start https://www.youtube.com/watch?v=CyXzTK_bFSU in a Webbrowser
3. Content is not the same

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/ecimagutay.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

-

------

**Comment by MoojMidge** [comment]
Can you get a debug log? A regular log is not useful in this instance.

Also if you open the context menu on the Live stream and select `Play (Ask for quality)`, do any of the video options listed play at the current time?

**Comment by Jusix** [comment]
Found the reason, it's a regression in inputstream.adaptive https://github.com/xbmc/inputstream.adaptive/issues/1517 sadly it's not easy to update this in an Linux Flatpak env.
