### ISSUE TITLE
Crash during transition between pages

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#784]
### Context
* Add-on Version: v7.0.7.1
* Kodi Version: kodi-20240525-13f294c1fd
* Kodi GUI Language: English
* Operating System: iOS 15.8.2
* Operating System Language: English
------

After updating the plugin from v7.0.7+beta.3 to v7.0.7.1 Kodi started crashing frequently when navigating between pages. [Log](https://paste.kodi.tv/sifofadoji.kodi).

**Comment by MoojMidge** [comment]
iOS... that's new for me. No experience with it and won't be able to anything without a crashlog. Don't know where that would be located, or if it is even generated. 

See if there is anything in `/var/mobile/Documents/Kodi/temp` or `/var/mobile/Documents`

**Comment by demouser007** [comment]
I did a downgrade to v7.0.7+beta.3 to make sure there were no crashes on that version. Indeed there were no crashes. But after upgrading back to v7.0.7.1 I can't reproduce them.
