### ISSUE TITLE
A few videos in "My Subscriptions" when there are few subscriptions

### ISSUE THREAD

**Issue by demouser007** [anxdpanic/plugin.video.youtube#785]
### Context
* Add-on Version: v7.0.5 - v7.0.7.1
* Kodi Version: 21
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English
------
I'm not sure if it's a bug, and I don't know how it should be. But there is a problem that when a channel (youtube account) has few subscriptions (I tested from 2 to 5), the "My Subscriptions" feed shows a few fresh videos and no link to a new page with videos from the past. Although the channels have been around for years and there are tons of videos on them. If you go to individual channels in "Subscriptions" all videos are displayed. I tested this problem on a new channel (youtube account) with new subscriptions. I can't test how it would be if there was an old channel with a couple of old subscriptions.

That said, the "My Subscriptions" feed on the old channel (youtube account) with lots of subscriptions to rarely updated or dead channels flips back in time without limit, a couple years back in time at least.

**Comment by MoojMidge** [comment]
Need to see the channel that you are trying to subscribe to, but the feeds won't show old videos, unless they are the most recent available. 

If you have lots of subscriptions, including some with very few videos from a long time ago, then it may appear as if you are able to view videos from a longer period, but that is just because that is the latest available from that specific channel.

**Comment by demouser007** [comment]
> Need to see the channel that you are trying to subscribe to

I tested this problem with different channels. Whatever they are, the result is the same. The constant here is that if you add some new subscriptions to an empty youtube account, the pages with past videos don't show up. For example, I've now tested this effect on these channels:
Technology Connections
Game Maker's Toolkit
Veritasium

>but the feeds won't show old videos, unless they are the most recent available.

Is this some kind of limitation of youtube's API?

> If you have lots of subscriptions, including some with very few videos from a long time ago, then it may appear as if you are able to view videos from a longer period, but that is just because that is the latest available from that specific channel.

I have a youtube account "archive" with over a hundred subscriptions to very rarely updated or dead channels. "My Subscriptions" in this account shows all the videos with no problem, no matter how far back in time I flip through the pages. That's what confused me, because I also thought at first that "My Subscriptions" was only showing new stuff.

**Comment by MoojMidge** [comment]
> I have a youtube account "archive" with over a hundred subscriptions to very rarely updated or dead channels. "My Subscriptions" in this account shows all the videos with no problem, no matter how far back in time I flip through the pages.

Can you provide an example of a channel that allows to view all the videos? 

> That's what confused me, because I also thought at first that "My Subscriptions" was only showing new stuff.

Not necessarily new stuff, just the most recent available, which could be from years ago. 

> Is this some kind of limitation of youtube's API?

Partially. It is a [feed](https://wikipedia.org/wiki/Web_feed), and typically feeds are meant to be fetched regularly and provide details of what has changed, so it doesn't make sense to include a full list of everything that the feed is for. Some sources do provide this ability, but I don't think the Youtube feeds do. You can see what is available for the Veritasium feed as an example https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA

This where the feed client plays a part. When the feed is downloaded, the client can store the results, allowing the history of the feed to be viewed.

This plugin is not a full featured feed client and does not have this functionality. A partial implementation of this could be added fairly simply, but it would be stored in the data cache, which is not suitable for long term persistent storage e.g. in #786 you identified the desire to clear this cache every time you sign out.

**Comment by demouser007** [comment]
> Can you provide an example of a channel that allows to view all the videos?

Carefully compared the subscription feed in the web version of YouTube and "My Subscriptions" in Kodi. I apologize, it was my illusion. Not all the videos are showing up. Just the old ones, but not all of them. It's actually like this "just the most recent available, which could be from years ago". Thanks for all the explanations. Too bad youtube doesn't give the full feed with all the videos.

**Comment by MoojMidge** [comment]
There are other ways to get the My Subscriptions list, that would show all the videos. Will see if it practical do so.

Edit: No, not practical. Too slow and uses up too much quota.

**Comment by MoojMidge** [comment]
The My Subscription content will now be cached per feed, ~so as long as the cache content is not cleared it~ with the data stored in a new feed history database which will store the history of each feed within reasonable limits (max of 1000 items per channel/feed, ~and further limited by the overall cache size~ up to a maximum of 1000 channels/feeds). Additional limits may be applied in future if it ends up storing too much data (should max out at ~60 MB)
