### ISSUE TITLE
Kodi crashes on Ubuntu

### ISSUE THREAD

**Issue by hunhejj** [anxdpanic/plugin.video.youtube#791]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* Kodi Version: 20.05+dfsg-1build2
* `kodi-inpustream-adaptive` version: 20.3.18+ds-1build1
* Operating System: Ubuntu Desktop LTS 24.04

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Ubuntu Desktop LTS (same with Kubuntu btw.)
2. `sudo apt install kodi`
3. `sudo apt install kodi-inputstream-adaptive`
4. Launch Kodi
5. Install the YouTube add-on
6. (Eventually wait for some time)
7. Kodi crashes.

**Comment by MoojMidge** [comment]
#738
#753

**Comment by hunhejj** [comment]
Why do you think they are related @MoojMidge ? I read those threads but no one reported that kodi crashes right away.

**Comment by MoojMidge** [comment]
Why do you think they are not? Have you done any investigation or tried anything suggested in those other issues?

You haven't provided a debug log or a crash log, so I'm not going to spend any time looking into this, but the magic crystal ball says it is the same issue anyway.

> I read those threads but no one reported that kodi crashes right away.

Neither did you. Regardless, the presumed underlying cause can result in an immediate crash.

> * (Eventually wait for some time)
> * Kodi crashes.
