### ISSUE TITLE
Videos only run on 480p sd 

### ISSUE THREAD

**Issue by f2hamza** [anxdpanic/plugin.video.youtube#807]
When i click to play video it's only play at 480p and when i turn on ask quality before video max resolution is 360p 
the problem started yesterday on some videos and now it's every video

**Comment by MoojMidge** [comment]
Follow the issue template.

**Comment by RNavega** [comment]
It seems to be related to this:  
https://github.com/yt-dlp/yt-dlp/issues/10206#issuecomment-2182856898

That is: itag 22 (720p MP4 video+audio), which was fast and great, was removed by YouTube. A few weeks ago playing the video again a few times would find some response that had it, but now (from what I'm experiencing) it seems the vast majority of responses --if not simply all of them-- have it missing.

An earlier comment in that thread points to **itags 95 and 96**, which have the same traits (multiplexed/muxed, AKA video+audio), and 95 has the same 720 height: https://github.com/yt-dlp/yt-dlp/issues/10206#issuecomment-2181003851

**Comment by MoojMidge** [comment]
Yes I am aware. Issues with the muxed streams have been occurring for at least a few months now.

For Kodi, there is no purpose in using these streams exclusively. Other tools need to use FFmpeg to re-mux these streams but Kodi has InputStream.Adaptive and the ability to use custom MPEG-DASH manifests.

Simply enable MPEG-DASH, select the stream features you want, and select the quality you want in the settings, or during playback. Or just use the Setup Wizard to do all of this for you.

In any case the other client was already added to this plugin 3 months ago and can be accessed by enabling Alternate client 2, if you really don't want to use MPEG-DASH

**Comment by RNavega** [comment]
It's really just for performance reasons.  
Here on my MXQ box w/ Kodi 18.9 and Mpeg-DASH playback, it completely crawls if using the VP9 codec -- I think it's doing things in software, because H264 will work fine with DASH if not for some occasional sound stutter.

Thanks a lot btw!

**Comment by MoojMidge** [comment]
I'm pretty sure the Setup Wizard and the stream features setting works in Kodi 18. Either one can be used to disable VP9 video, with the Wizard offering some easy preset configurations. The RPi2 preset is probably the most appropriate (MPEG-DASH and alternative client 2).

This may be problematic if you want 1080p or better video, but at 720p the h264 video streams should be available for just about everything

**Comment by f2hamza** [comment]
> I'm pretty sure the Setup Wizard and the stream features setting works in Kodi 18. Either one can be used to disable VP9 video, with the Wizard offering some easy preset configurations. The RPi2 preset is probably the most appropriate (MPEG-DASH and alternative client 2).
> 
> This may be problematic if you want 1080p or better video, but at 720p the h264 video streams should be available for just about everything

even when i enable mpeg dash some videos show as 720p as i want but some of them stays as 480 sd and doesn't show anything higher than that i feel like it's random sometimes 720p show up consistently but sometimes nothing more than 480 sd no matter what i try this problem started for me recently everything before was working well

**Comment by MoojMidge** [comment]
No further support will be offered about your issue.

Everything you need to do is identified in the previous messages, however in addition to providing no actual details about your problem, you have also not properly read those other posts.

**Comment by f2hamza** [comment]
> No further support will be offered about your issue.
> 
> Everything you need to do is identified in the previous messages, however in addition to providing no actual details about your problem, you have also not properly read those other posts.

first of all i don't need support from the admin I'm asking normal people like me that may have or had same I'm not asking the programmer that think everyone is an expert mate
and literally minutes before my post u closed another post that said that even after turning mpeg on some videos still don't offer all qualities and stuck on low ones
and yes i did read all posts that u said turn on mpeg dash or client 2 which I didn't even understand what that means cos I'm not a programmer and not everyone knows everything and since I know the mpeg trick and literally what i replied with it did fix it but not for every video
and we appreciate the people that do this plugin in general but u need to understand not everyone an expert and understand everything cheers mate have nice day
