### ISSUE TITLE
v7.0.8+beta.3 - not playing all videos

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#808]
_Translator:_
In short:
v7.0.8+beta.1 - all videos play without problems
v7.0.8+beta.2 - for several movies I tried to play, none of them started
v7.0.8+beta.3 - it's better here, but this guy's video won't run anymore:
https://youtu.be/T1ixqgyC3VM?si=zYxQij7GVH4ZG82F

Sorry for reporting a bug without logs.

_LibreELEC 12, RPi4_

**Comment by DjDiabolik** [comment]
Please check your kodi.log and see if you have a similar issue reported by me here:
https://github.com/anxdpanic/plugin.video.youtube/issues/801#issuecomment-2178300883

**Comment by DjDiabolik** [comment]
Ah.... simply add also so more addictional info about your setup. why did you delete all the required information from the default template? It's perhaps the most useful thing there is...

Simply say... you use MPEG-DASH or not ? Whit BETA 3 if i disabled it's better but all it's limited at 720P.

**Comment by drrak** [comment]
When I wanted to check the latest version of YT and post the logs, everything started working properly. I have no idea what could have happened because I didn't change any options. Sorry for the confusion.

PS. Yes, I use MPEG-DASH.
