### ISSUE TITLE
7.0.8 beta 4 - Possibly not a BUG or unrelated issue whit this addons but can't EXIT/TERMINATE Kodi after watched a youtube video... 

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#813]
ATTENTION:
***Some news founded***
look at kodi debug log. whit disabled plugins.video.kod on Kodi made this issue/trouble disappears.
So the situation it's whit beta 3 and kod enabled no issue. With beta 4 and kod disabled no issue. Whit beta 4 and kod enabled this issue appear.
I have right now reported the same kodi.log posted here also at kod developers......

*** Edit num. 2 - ANOTHER EDIT AFTER SOME ADDICTIONAL TEST ***
Addictional testing........ Try to change my Kodi Skin.
If i enable and use the ORIGINAL AND STOCK Estuary (and not the V2 MOD From kodiners) all issue disappear also whit this beta 4 and same Kod addons enabled.
So.. It's the Skin can cause the issue ? Possibly that.... I don't have the necessary skills to find a real culprit but in incipit all it's start after update to beta 4 this addons and sorry me if i made a useless issue here.
I have also link this issue to italian Kod developers... maybe they can also confirm that the problem is external to the two addons..

*** EDIT Part 3 - Just to confirm ***
Re-Enabled and switch back to "Estuary Mod V2" Skin and damn... this issue reappears.
at this point, as far as I know, the skin in question takes precedence over the other addons in creating this problem...
I hope can have some help or info if someone can determinate some things directly from my kodi debug log :)
I'm also little sure, however, that it's watching a YouTube video that brings up the problem. opening any content kod addons not create this issue. if i try to open a single video from youtube this issue append. Really a lot of confusion over my head.

There's no urgent... it's weekend and it's July for all if you can if you can go to the seaside friends :)

### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.8 Beta 4
* Kodi Version: 21 Flatpak
* Kodi GUI Language: Italian
* Operating System: Ubuntu 22.04.4 LTS
* Operating System Language: Italian

------

### Expected Behavior

Related to this comment here:
https://github.com/anxdpanic/plugin.video.youtube/commit/9406152eaeafc1feddd4f076a502ef2487942413#commitcomment-143421396

------

### Current Behavior

Kodi Remain freezed on exit screen..

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open kodi
2. Watch also a single short video... try to exit from kodi
3. Kodi remain freeze.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[kodidebuglog.txt](https://github.com/user-attachments/files/15936304/kodidebuglog.txt)

I have to upload the kodi debug log here because when try to copy/paste on pastebin i obtain an error say "You have exceeded the maximum size of 512 kilobytes per Paste." 
I hope it's same things and can check the debug log also in this mode...

------

### Additional Information

I have step back to BETA 3 of youtube addons. Whit BETA 3 can exit correctly from kodi...

------

**Comment by DjDiabolik** [comment]
Also edited the title of issue.... after recent discoveries the new title seems correct or most adapt... if can help to resolve this issue thanks in advance.

**Comment by MoojMidge** [comment]
Yes, it is a problem with the v7.0.8+beta.4 change.

Can determine this because you have provided a debug log. Would be impossible to investigate otherwise.

**Comment by DjDiabolik** [comment]
@MoojMidge can I ask you a question ? How did you manage to isolate and interpret the debug log that I provided and extrapolate the problem that caused the incorrect closure of Kodi itself?
when one activates the same debug log, is there a way to log only what combines a specific component such as a single specific addon?

Meantime i try to update my to this beta 5.... :)

**Comment by DjDiabolik** [comment]
with beta 5 kodi it's closed/terminate whitout any issue..... very thanks for fix this issue and for all other can you do whit make ever better this addon...

**Comment by MoojMidge** [comment]
> How did you manage to isolate and interpret the debug log that I provided and extrapolate the problem that caused the incorrect closure of Kodi itself?

By knowing what Kodi does when it shuts down and seeing what it didn't do in your log. Then tracking down which jobworker didn't get shutdown, which thread that was, what it was last trying to do in the log, and how many other threads were trying to do the same thing at the same time.

> when one activates the same debug log, is there a way to log only what combines a specific component such as a single specific addon?

Not to an addon specific level, no. In any case doing so would not have provided the necessary information to determine what the problem was. Without the full debug log it would have been impossible to do.

Please keep this in mind next time you open an issue.

**Comment by DjDiabolik** [comment]
This time I managed to get the debug log because I could simply reproduce the problem (lol only need to open a youtube video and try to exit from kodi).

I then tried to take a look at it myself but there really are too many irons in the fire :)
I didn't understand anything.
