### ISSUE TITLE
Completed video always added to WL (with error)

### ISSUE THREAD

**Issue by RandoTTTest** [anxdpanic/plugin.video.youtube#818]
Add-on Version: 7.0.8 beta 5
Kodi Version: 21.0
Kodi GUI Language: English
Operating System: Android / FireTV 4K
Operating System Language: English
Reproducible: Yes

I have been reviewing my API use after hitting quota and found this : after playing a video from WL, there will always be an attempt to add it back to WL and it will always fail because the video is already there.
Toggling 'auto-remove' from 'no' to 'yes' cause a delete operation then a successful insert.

I believe the insert is from this code section but I am uncertain if the 'refresh_only' condition is not working as intended  or if it is but my config is not right to fall in this case
https://github.com/anxdpanic/plugin.video.youtube/blob/7ec53de6df26335daeac3895131e1540020af726/resources/lib/youtube_plugin/kodion/monitors/player_monitor.py#L254C24-L254C45

config:
custom wl playlist ID : set and working
use local playback history : yes
update playback history on YT : no
auto remove from wl : no
refresh after watching : yes

Can you advise how to avoid this playlist inset operation ? 

Thank you

**Comment by MoojMidge** [comment]
> Reproducible: Yes

Can't confirm. 

> I believe the insert is from this code section

That is for your watch history list, not your watch later list. Have you configured them both to be the same playlist?

> Can you advise how to avoid this playlist inset operation ?

Need a debug log.

**Comment by RandoTTTest** [comment]
Thank you  for reviewing my query

> > I believe the insert is from this code section
> 
> That is for your watch history list, not your watch later list. Have you configured them both to be the same playlist?
> 
oh wow, I must have set it mistakenly a while ago . It is indeed set to the same value as watch later but 'history' was ticked off so the ID was hidden.

I cleared the watch list ID value and made sure 'history' is ticked off
[kodi.log](https://github.com/user-attachments/files/15946401/kodi.log)
, enabled debug logs, restarted Kodi and collected the attached logs after playing 1 video.

I still get the the insert attempt in my API usage graph and the log shows a trace mentioning the same code location:

HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /youtube/v3/playlistItems?mine=true&part=snippet&prettyPrint=false (Caused by ResponseError('too many 500 error responses'))
                                                   Stack trace (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 1002, in _bootstrap
                                                       self._bootstrap_inner()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
                                                       self.run()
                                                     File **"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/player_monitor.py", line 254, in run
                                                       client.add_video_to_playlist(history_id, self.video_id)**
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 348, in add_video_to_playlist

insert is 50 quota x multplie retries, it gets high pretty fast.


EDIT Looking at the log, it looks like the history playlistID is still detected even though it shows at empty in the GUI - do I need to clear some cache in the maintenance menu ?

**Comment by RandoTTTest** [comment]
I found the offending playlist ID still set as history playlist in the access_manager.json file . After cutting the offending line, restarted Kodi and I do not get the playlist inserts anymore.

issue resolved, sorry for the disturbance

**Comment by MoojMidge** [comment]
> I found the offending playlist ID still set as history playlist in the access_manager.json file .

Yes there may be an issue where the access manager details are not being refreshed in all contexts when the settings are changed. Will have to check a bit later.
