### ISSUE TITLE
playback with MPD crashes Kodi

### ISSUE THREAD

**Issue by das-osi** [anxdpanic/plugin.video.youtube#825]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.8 beta 5
* Kodi Version: 21.0.0
* Kodi GUI Language: English
* Operating System: Windows 10 21H2
* Operating System Language: English

------

### Expected Behavior

Playback

------

### Current Behavior

Problem started 2 days ago with no change from my side.
Can't playback any video with MPD, it simply crashes Kodi.
Playback without MPD (360p) works just fine.

------

### Steps to Reproduce

Unknown

------

### Log

https://pastebin.com/raw/iaYR1y9N

------

### Additional Information

-

------

**Comment by GPIforGit** [comment]
Same here 
The problem is the InputStream-Addon, which the YT-Addon needs. 
With 21.4.9 everything works, with 21.4.10 it crashes.

Workaround - install the old version and disable the automatic-update of this addon - or use the 360p option, which doesn't need the input-stream-addon.

**Comment by das-osi** [comment]
downgraded to 21.4.9 of InputStream Adaptive and everything is fine again. 
Thank you @GPIforGit

**Comment by xyzfre** [comment]
@das-osi  How can I downgrade input stream adaptive to the previous version really appreciate the feedback please having the same issue

**Comment by das-osi** [comment]
@xyzfre Add-ons -> My add-ons -> VideoPlayer InputStream -> InputStream Adaptive -> C Button or context menu -> Information -> Versions

**Comment by xyzfre** [comment]
> @xyzfre Add-ons -> My add-ons -> VideoPlayer InputStream -> InputStream Adaptive -> C Button or context menu -> Information -> Versions

Unfortunately, I must've clean my packages recently because when I go to versions I only see the current one but the issue is definitely coming from input stream because if I disable it trailers play fine but of course quality sucks ,, is there any other way to downgrade I tried from GitHub but I get an error when trying to download the zip file

**Comment by alphaleonis** [comment]
> @das-osi How can I downgrade input stream adaptive to the previous version really appreciate the feedback please having the same issue

Version 21.4.9 of InputStream can be downloaded from [here](https://mirrors.kodi.tv/addons/omega/inputstream.adaptive+windows-x86_64/inputstream.adaptive-21.4.9.zip?mirrorlist)

**Comment by Wanderer189** [comment]
I also had to revert back. Was also crashing when I tried to use official version as well

**Comment by xyzfre** [comment]
@alphaleonis  thank you reverting back to previous version of inputstream adaptive. Definitely fix the issue for now hopefully this can be addressed.

**Comment by alexgit2k** [comment]
Same error here at Windows 10 22H2. It crashes every time starting to play any YouTube video.
Downgrading InputStream Adaptive to 21.4.9 and disabling automatic updates solved the problem.

It has been already reported at InputStream Adaptive: https://github.com/xbmc/inputstream.adaptive/issues/1589

**Comment by jeff2900** [comment]
Same issue solved with latest version 14.40.33810.0 of Microsoft Visual C++ Redistributable
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by GPIforGit** [comment]
Can confirm, updating the Visual C++ Redistributable solve the problem too.
But it would be nice to get a warning instead of the crash of kodi.
It is possible to check the version and then decide to use inputstream or not?

**Comment by xyzfre** [comment]
> Same issue solved with latest version 14.40.33810.0 of Microsoft Visual C++ Redistributable
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

Newbie question and would really appreciate the help. Never done it before on the link you posted. Which one does the update for. Microsoft visual C++ ,, I'm on Windows 11 Pro

**Comment by GPIforGit** [comment]
> Newbie question and would really appreciate the help. Never done it before on the link you posted. Which one does the update for. Microsoft visual C++ ,, I'm on Windows 11 Pro

normaly this should be a 64-bit-Windows Version, so download the "X64" on the top.

**Comment by xyzfre** [comment]
> Same issue solved with latest version 14.40.33810.0 of Microsoft Visual C++ Redistributable
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

Thank you💯💯, my friend this fix the problem for me as well I was able to update input stream adaptive

**Comment by MoojMidge** [comment]
Closing as latest Kodi release should ensure this is no longer a problem moving forward.
