### ISSUE TITLE
new(?) API Client-IDs too long & get truncated by Kodi: plugin broken

### ISSUE THREAD

**Issue by ballerburg9005** [anxdpanic/plugin.video.youtube#83]
The client-IDs look like this:

555556789012-bmgkdk50969gkdk3lroti5934846hjfdss.apps.googleusercontent.com

It can only be entered and saved in full length via the HTTP interface http://localhost:50152/api. Saving the settings of the plugin from within Kodi, or completing the second final activation step, causes the ID to truncate to something like this:

555556789012-bmgkdk50969gkdk3lroti59

Consequently the plugin can't use the client-id to login and fails with the screen to enter correct API information.

Plugin version: 6.8.9
Kodi version: 2:18.6+dfsg1-2ubuntu1 (Ubuntu MATE, bullseye)

**Comment by anxdpanic** [comment]
I would need the complete debug log showing adding the key, this is expected behavior though.
`555556789012-bmgkdk50969gkdk3lroti5934846hjfdss.apps.googleusercontent.com` would truncate to `555556789012-bmgkdk50969gkdk3lroti5934846hjfdss` in all cases.

**Comment by ballerburg9005** [comment]
No, please read again: It doesn't just truncate after the dot. It truncates about 5 or 10 characters of the actual unique client-id portion before the dot. I am sure that the client-ids that Google gave out used to be a lot shorter back a few month ago. Now they are like 12 characters longer and they don't fit the field anymore. Like I said, you can't even enter them directly in Kodi anymore, because they are too long. You have to use the web interface to go over the field's max length (since it isn't enforced in the web browser). And when you do and complete the Oauth process, they truncate to the max length of the field again, clipping away the unique part of the client-id needed to identify correctly with Google and thus authorization fails.

To put it exaggeratedly, suppose this was the new and longer actual client-id:

555556789012-bmgkdk50969gkdk3lroti5934846hjfdssaflkjq43jlvdaslvkh5t43ljahf396qjc063980.apps.googleusercontent.com

Then Kodi truncates it to this:

555556789012-bmgkdk50969gkdk3lroti59

Because the field's character limit is lower than the actual client ID's characters. Thus the plugin can't auth because a shortened client-id can't work just like a shortened secret can't. (Don't forget that the truncation only happens in the settings inside Kodi and after the last activation step.)

**Comment by ballerburg9005** [comment]
555556789012-bmgkdk50969gkdk3lroti5934846hjfdss.apps.googleusercontent.com is the actual length and form of the client-id I received. I got it from my mother's Google account though, which is 10 years younger than my Google account that gave me the shorter IDs that did fit the field in Kodi a few month back. If you test against this, make sure that your account gives you the newer, longer IDs. If there is any difference at all that is.

**Comment by ballerburg9005** [comment]
I checked again today and the character limit was gone, so I entered the full ID and it is working now.

This is really strange, I didn't update anything either.

**Comment by xuandat09** [comment]
I have the same issue with client's ID, even copy and paste but after that the key didn't show the characters of ".apps.googleusercontent.com" and the login was fail. Please check and fix.

**Comment by ballerburg9005** [comment]
It does not matter if it doesn't show the ".apps.googleusercontent.com" part. This part is not important. In my case it was so that it was not showing "XXXXX.apps.googleusercontent.com", whereas XXXXX is part of the client id that must not be truncated, and the full Id would be something like "YYYYYYYYYYYYYYYYYYXXXXX.apps.googleusercontent.com". If it truncates to YYYYYYYYYYYYYYYYYYXXXXX this is good and it should work right. If it truncated so something like YYYYYYYYYYYYYYYYYY then this cannot work.
