### ISSUE TITLE
Hidden videos are not hidden

### ISSUE THREAD

**Issue by timur-davletshin** [anxdpanic/plugin.video.youtube#834]
* Add-on Version: 7.0.9 beta 2
* Kodi Version: 21.0
* Kodi GUI Language: English
* Operating System: Libreelec 12.0
* Operating System Language: English
* Reproducible: Yes

------

### Expected Behavior

Hide hidden videos like other YT clients do (at least make it as default behavior). Probably the best way to fix it is to make it configurable. YT WebUI allows to see hidden videos at least in Likes if user click it.

------

### Current Behavior

Hidden videos are shown everywhere in UI, no specialized error when user tries to play those. It is not clear why it fails to play.

------

### Steps to Reproduce

Example of such video: https://www.youtube.com/watch?v=jJSe_cxiBoY - you can try sending it to Kodi via Android app or just search it by channel name, visit it and see that it is available regardless of hidden status.

**Comment by MoojMidge** [comment]
Unlisted/hidden videos are hidden.

The linked video is not unlisted/hidden.

If you have a problem post a debug log. Can't keep trying to guess what you are talking about when you don't provide the required information.

**Comment by timur-davletshin** [comment]
Yep, my fault. Probably it is just blocked in my country.

![Screenshot 2024-07-09 a](https://github.com/anxdpanic/plugin.video.youtube/assets/143790409/c6eb1e24-34f1-4ebd-98d0-5ebfd62ec2e0)
