### ISSUE TITLE
Youtube 7.0.6.3 freezes Kodi on Xbox at boot

### ISSUE THREAD

**Issue by tpaniaki** [anxdpanic/plugin.video.youtube#839]
### Context

Please provide any relevant information about your setup

* Add-on Version:
* 7.0.6.3
* Kodi Version:
* 21.0
* Kodi GUI Language:
* French
* Operating System:
* Xbox
* Operating System Language:
* French

------

### Expected Behavior

Booting Kodi without crash.

------

### Current Behavior

Youtube add-on freezes Kodi at start-up on Xbox.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start Kodi 21.0 on Xbox with Youtube add-on installed.
2. Wait a couple of seconds without interacting with th UI and witness the freeze.

------

### Log

Don't have crash log on Xbox. Logs are not helpful in that case I'm afraid.

------

### Additional Information

If interacting with Kodi directly at boot (with the controller) the freeze won't happen (strange but true).

I pinpointed this add-on by disabling / re-enabling it.

------

**Comment by MoojMidge** [comment]
Nothing can be done without a debug log

**Comment by tpaniaki** [comment]
- [The freeze](https://paste.kodi.tv/atiqutojot).
- [When the controller is activated at boot](https://paste.kodi.tv/eyafeyedat).
- [When the add-on is disabled](https://paste.kodi.tv/ajepisolir).

**Comment by MoojMidge** [comment]
Try a newer version
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.3

**Comment by tpaniaki** [comment]
> Try a newer version https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.3

Same symptoms.

**Comment by MoojMidge** [comment]
Can you get a debug log when using the newer version?

**Comment by tpaniaki** [comment]
> Can you get a debug log when using the newer version?

- [Freeze v7.0.9beta.3](https://paste.kodi.tv/izadorazur)

**Comment by MoojMidge** [comment]
Hmm problem isn't what I thought it may be.

Can you instead test whether disabling these other addons, one by one in the following order, and see if the freezes stop?

1. plugin.video.cumination
2. script.tubecast
3. plugin.video.rtsplaytv
4. plugin.video.umbrella

**Comment by MoojMidge** [comment]
Can you also confirm whether the problem only started with v7.0.6.3? Was it working fine with v7.0.5?

**Comment by tpaniaki** [comment]
> Hmm problem isn't what I thought it may be.
> 
> Can you instead test whether disabling these other addons, one by one in the following order, and see if the freezes stop?
> 
> 1. plugin.video.cumination
> 2. script.tubecast
> 3. plugin.video.rtsplaytv
> 4. plugin.video.umbrella

The issue persists at the end of the test.



> Can you also confirm whether the problem only started with v7.0.6.3? Was it working fine with v7.0.5?

I unfortunately cannot be 100% sure that it started with 7.0.6.3 (I usually directly use the controller when I start Kodi). However, it's highly likely.

**Comment by MoojMidge** [comment]
Thanks for testing, few more possibilites eliminated. If you can, a last thing to check - can you install these version of the plugin and see if any of them don't freeze up?

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip (almost the same as v7.0.9+beta.3 but with a few additional commits that should be unrelated to the problem you are experiencing, expect no change)
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/force_idle_on.zip (forces the plugin to go into its idling mode immediately. The idle mode was added in v7.0.6)
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/force_idle_off.zip (prevents the plugin from entering its idle mode)

**Comment by tpaniaki** [comment]
Master doesn't work but both idle options solve the freeze.

**Comment by MoojMidge** [comment]
Good news is that this means there is nothing wrong with the plugin.

Bad news is that it means the problem is with Kodi itself, and seemingly specific to the Xbox platform.

I don't have any means to investigate further as the problem doesn't occur on Windows. 

Seemingly the same issue was [already raised](https://github.com/xbmc/xbmc/issues/25501), but you will need to clean up your installation if you want it investigated further.

**Comment by MoojMidge** [comment]
Made some changes to see if this issue can be worked around

Check if https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip works

**Comment by tpaniaki** [comment]
> Made some changes to see if this issue can be worked around
> 
> Check if https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip works

Yes this works. Shall I close the thread?

Many thanks for your responsiveness.

**Comment by MoojMidge** [comment]
You can close it if you want, but the issue will be closed automatically anyway when the changes are merged.

If you are willing to test I would still recommend that you clean up your system and try to raise a bug report with Kodi itself. I can try to create a minimal reproducible example plugin that you can use to create the bug report with clean logs.
