### ISSUE TITLE
Youtube History missing

### ISSUE THREAD

**Issue by Goobor** [anxdpanic/plugin.video.youtube#84]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.9
* Kodi Version: 9.2.5
* Kodi GUI Language: Hungarian
* Operating System: Coreelec
* Operating System Language: Hungarian

------

### Expected Behavior

Please describe the behavior you are expecting.

I like to see Youtube History.
------

### Current Behavior

What is the current behavior?

At Youtube Add-on History does not appear

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/cevijiseru.kodi

------

### Additional Information

Please provide any additional information that may be helpful.

Thank you for the Youtube Add-on. :)

------

**Comment by anxdpanic** [comment]
No way to fix that currently.

But for a kodi only history.

Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History`
That will be your Kodi history playlist, it's a pita but it's the only alternative atm.

**Comment by Goobor** [comment]
Thank you!

**Comment by 43Rageon** [comment]
> No way to fix that currently.
> 
> But for a kodi only history.
> 
> Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History` That will be your Kodi history playlist, it's a pita but it's the only alternative atm.


Hello, I am having the same problem. Can you tell me how I can do it for Watch later playlist and History playlist sections? I exported from Takeout, but I couldn't find Watch later playlist and History playlist. I think Google has changed it.

**Comment by usmc8408** [comment]
> 

Check to make sure you're in the right account in the top right when in Takeout. That's what I was doing wrong when I couldn't find my watch later playlist.

**Comment by usmc8408** [comment]
> > No way to fix that currently.
> > But for a kodi only history.
> > Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History` That will be your Kodi history playlist, it's a pita but it's the only alternative atm.
> 
> Hello, I am having the same problem. Can you tell me how I can do it for Watch later playlist and History playlist sections? I exported from Takeout, but I couldn't find Watch later playlist and History playlist. I think Google has changed it.

Check to make sure you're in the right account in the top right when in Takeout. That's what I was doing wrong when I couldn't find my watch later playlist.

**Comment by 43Rageon** [comment]
> > > No way to fix that currently.
> > > But for a kodi only history.
> > > Create a new playlist, open `Main Menu - Playlists`, use the context menu on the playlist you created, and choose `Set as History` That will be your Kodi history playlist, it's a pita but it's the only alternative atm.
> > 
> > 
> > Hello, I am having the same problem. Can you tell me how I can do it for Watch later playlist and History playlist sections? I exported from Takeout, but I couldn't find Watch later playlist and History playlist. I think Google has changed it.
> 
> Check to make sure you're in the right account in the top right when in Takeout. That's what I was doing wrong when I couldn't find my watch later playlist.

I fixed the watch later playlist issue but I couldn't find my History playlist id. Where exactly is it write?
