### ISSUE TITLE
Add-on choosing SD resolution on first play of a youtube video

### ISSUE THREAD

**Issue by drelephant** [anxdpanic/plugin.video.youtube#842]
### Context
* Add-on Version:
7.0.6.3
* Kodi Version:
20.2
* Kodi GUI Language:
English
* Operating System:
Ubuntu 20.04.6 LTS
* Operating System Language:
English
------
### Expected Behavior

Kore is an App on Android that I use to control kodi on my LAN.

I use Kore App on Android to send the link to youtube videos to play on my Ubuntu HTPC by choosing "Share-Play on Kodi" from Youtube App.

Since the last Youtube Add-on update it plays in SD resolution when I do this.

If I then share the same video again, it will then play in 4k (which is what I want).

I have also seen this happen also when playing videos directly from Kodi but almost all of the time it correctly chooses 4k.

This seems like a bug to me, but perhaps it's doing some kind of bandwidth analysis and choosing SD by mistake?

Is there any way to force it to choose the highest resolution the first and every time? I don't ever want to watch any videos in SD if I can avoid it.

My internet connection is 100Mbps so should be easily enough to support 4k.

**Comment by MoojMidge** [comment]
> This seems like a bug to me

This is an issue with v7.0.6 and was fixed in v7.0.7

Latest version is https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.3

**Comment by drelephant** [comment]
Thanks for that. Sorry I didn't realize I was so far out of date on the add-on version.

**Comment by MoojMidge** [comment]
Submission of later versions hasn't occurred just yet, so v7.0.6.3 is the latest version available in the official Kodi repository, and being a little behind on updates is to be expected. No need to apologise for that.
