### ISSUE TITLE
Subtitles not working with HLS streams

### ISSUE THREAD

**Issue by DevilBlackDeath** [anxdpanic/plugin.video.youtube#843]
### Context

Please provide any relevant information about your setup

* Add-on Version: Tested with 7.0.8, latest and variour 7.0.2/3
* Kodi Version: 20
* Kodi GUI Language: English
* Operating System: LibreElec
* Operating System Language: English

------

### Expected Behavior

I would expect Subtitles to work with HLS streams and show up, like they do when selecting a non-HLS stream.

------

### Current Behavior

As it stands, I'm using HLS streams from the Alternate #1 source (which is unfortunately the only way for me to get good quality on the latest version, selecting the FHD stream shows a stream that looks like 480p in terms of quality). Unfortunately, the subtitles won't show up. Selecting 360p or FHD 1080p will properly show the subtitles. Not that when selecting HLS streams I still get the pop-up to pick subtitle languages, and in Kore's interface, I do get a list of available subtitles that is definitely the expected list on the videos I tried it with, the subtitles simply don't show up.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use Alternate #1 as a source
2. Start a video that has subtitles included in it.
3. Pick the desired subtitles
4. For video pick HLS, then pick any quality from the HLS list
5. Subtitles aren't displayed.
6. Do the same, but select 360p or 1080p instead of HLS, the subtitles will show up.

------

Thanks in advance ! I expect the problem may come from a configuration issue on the Kodi side or something like that but I've looked a bit and found nothing.

**Comment by MoojMidge** [comment]
> I expect the problem may come from a configuration issue

Impossible to determine without a debug log.

Regardless nothing is done to the HLS manifests, they are used as-is and are created by YouTube.

If subtitles are not showing up then that would be an issue with the version of InputStream.Adaptive that you are using with Kodi 20.

> As it stands, I'm using HLS streams from the Alternate #1 source (which is unfortunately the only way for me to get good quality on the latest version, selecting the FHD stream shows a stream that looks like 480p in terms of quality).

Use the Setup Wizard to set the recommended settings, choose the performance settings appropriate for your device, and setup the subtitles.

Problem solved

**Comment by DevilBlackDeath** [comment]
I have used the wizard, but it always picks the default source (which has been terrible with subtitles for years now), and the quality is not there either. If I request to be asked for the quality then picking FHD looks terrible (no matter the source), and if I let the plugin autopick by picking the best quality then it seems to be picking by itself that same FHD that looks like it's actually 480p. Which for some reason doesn't happen with the HLS streams.

Yeah but isn't it weird that it happens specifically with HLS ? Not changing the source but only changing the stream when asked to pick the quality makes the subtitles work.

I'll try to get a debug log tomorrow. What settings should I use for the most helpful log again ? (both plugin and kodi settings) ? I think I've left them set-up from my previous issue, but I'd rather be safe than post a useless log.

**Comment by MoojMidge** [comment]
> but it always picks the default source (which has been terrible with subtitles for years now)

This is not true. The alternate client settings were only introduced in May last year and they initially all used the original subtitle sources.

This has changed so that most clients now use the exact same subtitle sources, with the exception of the one you are using, because it uses the unmodified provided HLS manifest, which means that it will have fewer subtitle options than all other clients.

> and the quality is not there either

This is also not true. Alternate client 1 may have higher bitrate 1080p streams for some videos, but in all other ways is worse than the default.

> If I request to be asked for the quality then picking FHD looks terrible (no matter the source),

Only alternate clients 1 and 2 may provide individual FHD streams, 1 generally being better quality than 2. Neither will look terrible.

> if I let the plugin autopick by picking the best quality then it seems to be picking by itself that same FHD that looks like it's actually 480p.

The default will always provide all available streams and won't be limited to 1080p. It will only look terrible if you have configured it to choose a terrible quality stream.

> Which for some reason doesn't happen with the HLS streams.

The HLS manifests are not configurable. If you are seeing a big difference in quality then the only reason would be that you have configured the plugin to choose a low quality stream when using the default client.

> Yeah but isn't it weird that it happens specifically with HLS ?

No, like I said it will be an issue with the version of InputStream.Adaptive you are using. You will need to upgrade LE/Kodi to use a newer version. 

> Not changing the source but only changing the stream when asked to pick the quality makes the subtitles work.

Doing this means you are no longer using the original HLS manifest, but the individual streams from that manifest.

It is also not recommended to do this. If you want to select streams, use the default client and choose the streams from the video OSD options.

> What settings should I use for the most helpful log again ? (both plugin and kodi settings) ? I think I've left them set-up from my previous issue, but I'd rather be safe than post a useless log.

Just follow the Setup Wizard, use the recommended settings and choose what quality you want to use in the performance settings.

**Comment by DevilBlackDeath** [comment]
Edit : My bad just realized you already said "last year". So yeah indeed it was not may 2024.

Well the FHD stream just looks bad. Compared to the HLS one I'm losing a ton of detail. It barely reaches what I'm getting by plugging a computer and setting Youtube at 720p. If need be I can provide a video showing the difference but I can guarantee you selecting 1080p in any of the sources is not getting me 1080p. HLS looks like it does, not 100% it does but it looks like it. Selecting 1080p or FHD always gets me blurry hair and messy details.

I'm not configuring it for anything I'm requesting to be asked everytime and everytime I pick the highest quality one. I'm not provided with anything higher because I set the max quality to provide in InputStream Adaptive as 1440p (my tv is 1080p so while 1440p can get some better quality in some given circumstances I wouldn't gain anything from higher res).

Well it did point out there was an update to InputStream, and I did update it. It looks like it's latest but I'll have to check the exact version tomorrow. Unfortunately I'm not sure I can update Kodi yet because I'm using a couple other plugins, namely my theme and Amazon Video, and I know the Amazon one sometimes takes a while to bring updates that work with the latest Kodi.

As I said I've used the wizard with the recommended settings multiple times already (both with full recommended and with "ask quality" settings), and I'm still getting that quality issue I mentioned. Again I can provide a video if need be. I'm a programmer and computer artist, I know to see by eye differences in resolutions, and looking for specific details to figure out differences of quality between similar images, and I can guarantee there is a difference between picking the HLS stream (which I understand is not preferable, this was mostly to test before making a report) and picking the FHD stream or using the recommended settings without picking.

**Comment by MoojMidge** [comment]
As I mentioned before, you need to update LE/Kodi to update InputStream.Adaptive in order to resolve your original issue.

Everything else is misconfiguration based on some misunderstandings like this:

> I'm not configuring it for anything I'm requesting to be asked everytime and everytime I pick the highest quality one. I'm not provided with anything higher because I set the max quality to provide in InputStream Adaptive as 1440p (my tv is 1080p so while 1440p can get some better quality in some given circumstances I wouldn't gain anything from higher res).

As mentioned before you should not do this. The default selection will use all available streams based on your quality selections, the best available will be selected by default, and you can change the selection during playback.

It is not possible to select an individual FHD stream prior to playback starting, when using the default client, because such streams don't exist. 

Alternate 1 may provide better quality streams for some videos at 1080p, but otherwise will be the same or worse than the default.

> Well the FHD stream just looks bad. Compared to the HLS one I'm losing a ton of detail. It barely reaches what I'm getting by plugging a computer and setting Youtube at 720p.
> ...
> I can guarantee there is a difference between picking the HLS stream (which I understand is not preferable, this was mostly to test before making a report) and picking the FHD stream or using the recommended settings without picking.

It is not possible for the default stream to appear worse than the 720p stream using the website, unless you have configured it to choose a worse quality stream.

I have a pretty good idea what each client is capable of, but if you are certain something is different for you then there is not much more I can say. You can provide a log if you want, but I'm pretty sure the only problem will be with how you have configured the plugin or InputStream.Adaptive

**Comment by DevilBlackDeath** [comment]
After further tinkering :
I've run the wizard around 10 times trying to figure what's the expected default. In any case, no matter what I picked, the default behaviour of the plugin was always to ask me the maximum video quality (which includes the HLS streams in Alternate 1).

Selecting 1080p kept resulting in bad video quality. Tinkering with some more settings, I found out that the default behaviour of "Ask + Automatic + Quality Selection" (I did not pick that in the wizard, and I agreed to the wizard using the recommended settings every time, in fact I could not find any setting that would make it so I don't have to pick video quality when starting a new video) was what was causing the issue. Anything other than just "Quality selection" alone resulted in bad quality. And I've tested a few videos, they run without issues or any noticeable stutter, so I doubt it's a matter of the Raspberry not getting good signal or the network being bad (it COULD be mind you if automatic uses that to determine the stream to use). Maybe a problem specific to LibreElec ? Or could that also be due to the InputStream Adaptive update incorrectly "adapting" quality ? (do note I'm making assumptions here, I have no idea what InputStream does at a low level, so I have no idea if it is responsible for picking the streams the Youtube plugin presents it or if it's the Youtube plugin actually doing it, excuse any misconceptions on my end).

If based on my explanation that's considered satisfactory and expected behaviour, feel free to close the issue :)

Edit : I also want to point out there may have been some miscommunications on my part. The "FHD" streams I was mentioning were offered to me when starting a video (and still are btw). I've also been trying all sorts (including basic recommended) settings with the wizard, I was pointing out the main one I was using, but this was by no means the only, and I have followed your suggestions. I'm not a stubborn casual user and I know that if you ask to try something, there's a reason for it, and rest assured that I did try it.

**Comment by MoojMidge** [comment]
> In any case, no matter what I picked, the default behaviour of the plugin was always to ask me the maximum video quality

Asking for quality is not on by default, but having it enabled shouldn't be detrimental unless the wrong stream is manually selected. As such the Setup Wizard won't override this, if someone has chosen to enable it.

> Selecting 1080p kept resulting in bad video quality.

Can you clarify? Is this in the Setup Wizard or the quality selection prompt prior to playback?

> the default behaviour of "Ask + Automatic + Quality Selection" (I did not pick that in the wizard, and I agreed to the wizard using the recommended settings every time, in fact I could not find any setting that would make it so I don't have to pick video quality when starting a new video) was what was causing the issue.

The default is Automatic + Quality Selection, but if you have enabled asking for quality previously, that setting will be retained.

> Anything other than just "Quality selection" alone resulted in bad quality.

This is basically manual selection, defaulting to the best available. "Automatic" adds automatic/adaptive selection on top of that. "Ask" adds the pre-play prompt before anything else.

> I doubt it's a matter of the Raspberry not getting good signal or the network being bad (it COULD be mind you if automatic uses that to determine the stream to use). Maybe a problem specific to LibreElec ? Or could that also be due to the InputStream Adaptive update incorrectly "adapting" quality ? (do note I'm making assumptions here, I have no idea what InputStream does at a low level, so I have no idea if it is responsible for picking the streams the Youtube plugin presents it or if it's the Youtube plugin actually doing it, excuse any misconceptions on my end).

The plugin provides data to InputStream.Adaptive about the stream, based on the configured quality and stream options. InputStream.Adaptive selects the stream to use based on its resolution and bandwidth settings, as well as the available network bandwidth.

If it is consistently selecting poor quality streams then it seems likely that there is an issue in how InputStream.Adaptive is configured.

> rest assured that I did try it

Fwiw the suggestion to post a log was not fatuous, there is obviously something misconfigured on your system (perhaps not within this plugin itself) and if you provide a log I can have a look.

**Comment by DevilBlackDeath** [comment]
https://youtu.be/eSIfuYJBwh8

Here is a video of me showing the following :
- "Quality selection" being set without "Ask" or "Automatic"
- Reenabling the wizard
- Going through the wizard with what seems like the recommended settings :
    - Saying yes to recommended settings
    - Setting performance to 1080p/60FPS as recommended for RPi4 and similar devices
    - Setting regional preferences to English and France
    - Setting subtitles to "Prompt" and not downloading
    - Setting video titles to minimal information
- Going back in the settings and showing that "Ask + Automatic + Quality selection" has replaced "Quality selection"

As for the log I did say I'd try to do it today. Posting logs from the RPi4 is unfortunately (very unfortunately) far less trivial than on a computer. It means connecting through the samba server, going through the linux-based folder structure, grabbing the correct log and then uploading it. I will do it, but it may be today or in a few days, depending.

For InputStream.Adaptive I'll give it a look, but I've tried resetting to defaults, I've tried the option that "forces" best qualityand the option that "asks" (though I'm not sure how that works alongside the Youtube "ask" option).

It's worth noting, as shown in the video, I'm on 7.0.6.3, which is not the actual Github latest. On the Kodi repo that's the latest available to me but I assume this is related to  my LibreElec being v11 and Kodi being v20 ? The behaviour may have changed somewhere in between ?

Edit : For completeness sake I went through all InputStream Adaptive settings again, while using "Automatic + Quality Selection". I've tried "Adaptive", "Fixed Resolution", "Manual OSD" and "Ask", while setting the plugin back to all its defaults. With these settings I'm still getting bad quality unless I use "Quality selection" only. Any of these settings also don't seem to affect what is set as the default behaviour on the Youtube plugin (I thought maybe setting ISA to "Ask" would make Youtube default to "Ask + Automatic + Quality selection", but no, all ISA settings make Youtube still default to that when following the wizard as shown in the video).

When doing the log I'll also try and see if I can update to LibreElec 12 based on my add-ons selection, and see if the behaviour is repeatable there, I'll update here based on this.

**Comment by MoojMidge** [comment]
Not disputing that what you are saying is happening is actually happening, just that the reason is almost certainly a configuration issue or perhaps some specific issue that has already been resolved in newer versions of InputStream.Adaptive, and the best way to determine this is with a log.

There are a few easy ways to get logs out:
- https://kodi.wiki/view/Log_file/Easy
- https://wiki.libreelec.tv/support/log-files

> It's worth noting, as shown in the video, I'm on 7.0.6.3, which is not the actual Github latest. On the Kodi repo that's the latest available to me but I assume this is related to my LibreElec being v11 and Kodi being v20 ? The behaviour may have changed somewhere in between ?

v7.0.6.3 is just the latest version that has been submitted to the official addon repository.

The subtitle issue is related to InputStream.Adaptive for Kodi 20, will need to update to LE12 for that.

The issue with low quality stream selection is unlikely to have any relationship to newer version of this plugin.

> For completeness sake I went through all InputStream Adaptive settings again, while using "Automatic + Quality Selection". I've tried "Adaptive", "Fixed Resolution", "Manual OSD" and "Ask", while setting the plugin back to all its defaults. With these settings I'm still getting bad quality unless I use "Quality selection" only. Any of these settings also don't seem to affect what is set as the default behaviour on the Youtube plugin (I thought maybe setting ISA to "Ask" would make Youtube default to "Ask + Automatic + Quality selection", but no, all ISA settings make Youtube still default to that when following the wizard as shown in the video).

When "Automatic" is selected in this plugin, it will tell InputStream.Adaptive to use "Adaptive". The adaptive selection depends on the maximum bandwidth and resolution settings that have been selected.

**Comment by DevilBlackDeath** [comment]
Oh ok glad to know the version number has nothing to do with my LE not being up to date.

Well the subtitle issue only appears with HLS streams, which I don't need now that I selected "Quality selection" as the behaviour.

Oh don't worry I know how to get the log but since it requires actually accessing the machine to get the log that means turning on my computer at the same time, doing the procedure then getting the log, it's just a matter of me having the time to turn on both machine and so on. I'll probably do it on wednesday or thursday (but not before for sure).

Hmmm I may never have setup the bandwidth in ISA. I definitely set the target resolution but bandwidth I'm not sure !

**Comment by MoojMidge** [comment]
> Oh don't worry I know how to get the log but since it requires actually accessing the machine to get the log that means turning on my computer at the same time

You dont need to do that. The wiki links describe use of the Kodi Logfile Uploader addon, that is used from the machine that you are collecting the log from.

> Hmmm I may never have setup the bandwidth in ISA. I definitely set the target resolution but bandwidth I'm not sure !

You should just keep things as default. The way you have set it up with the setting resolution greater than your actual TV resolution won't work anyway.

The log will reveal all.

**Comment by DevilBlackDeath** [comment]
Huh, sorry, I always assumed this was only good for sharing logfiles with Kodi's team so I didn't bother reading that up. Didn't know it actually provided a shareable URL. I'll do that next time I run my RPi then ;)

**Comment by MoojMidge** [comment]
Closing. Not an issue with the plugin, and alternate client selections will be removed shortly too.
