### ISSUE TITLE
Playlist is Unstable

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#849]
When you open a YouTube video from your Playlist Queue and it finishes (or you manually stop it), you won't be able to open that same video after 10-15 minutes.

Steps to Reproduce:
1) Use the "Add to Queue" from context menu and add ~15 or ~20 YouTube videos.
2) Open your playlist, open any YouTube Video from your Playlist which you added.
3) Either wait for the entire video to finish or stop the video manually (stop button) when it's playing.
4) Wait 10-15 minutes
5) Try opening that same video from the playlist. Only now it won't open.

Using 7.0.9 Beta 3 (beta 4 doesn't work for me, errors opening anything)

**Comment by MoojMidge** [comment]
#810
