### ISSUE TITLE
[Errno 10013] / HTTP Sever is not running

### ISSUE THREAD

**Issue by azumukupoe** [anxdpanic/plugin.video.youtube#86]
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.9
* Kodi Version: 18.9
* Kodi GUI Language: English (US)
* Operating System: Windows 10
* Operating System Language: Japanese

------

### Expected Behavior

functional HTTP sever

------

### Current Behavior

HTTP sever won't run

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable API config page
2. Check my IP
3. 

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/5824054/kodi.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by jaylfc** [comment]
Same problem here

**Comment by lundeen-bryan** [comment]
same problem

**Comment by anxdpanic** [comment]
Steps to resolve:

1. Disable Settings - MPEG-DASH - Use MPEG-DASH
2. Disable Settings - API - Enable API configuration page
3. Restart Kodi
4. Change Settings - HTTP Server - Port to `60140` (doesn't have to be this specific port just a working example.)
5. Enable Settings - MPEG-DASH - Use MPEG-DASH
6. Enable Settings - API - Enable API configuration page (if needed)
7. Restart Kodi (Just for good measure to restart the service)

**Comment by mmeiwenlong** [comment]
> 解决步骤：
> 
> 1. 禁用设置-MPEG-DASH-使用MPEG-DASH
> 2. 禁用设置-API-启用API配置页面
> 3. 重新启动Kodi
> 4. 将设置-HTTP服务器-端口更改为`60140`（不必是此特定端口，只是一个工作示例。）
> 5. 启用设置-MPEG-DASH-使用MPEG-DASH
> 6. 启用设置-API-启用API配置页面（如果需要）
> 7. 重新启动Kodi（请采取适当措施重新启动服务）

为啥我的都装好了也能看了，却发现启用不了MPEG-DASH这个选项，变成灰色不可选，以前装的时候是可以选的，

**Comment by anxdpanic** [comment]
@mmeiwenlong 
https://forum.kodi.tv/showthread.php?tid=338327&pid=2799680#pid2799680
If using linux, `apt install kodi-inputstream-adaptive` or equivalent before that.

**Comment by Chris3773** [comment]
It looks like Kodi was blocked by my firewall. I needed to allow Kodi through my firewall.

Following @anxdpanic steps will allow for Kodi to prompt you for allowing in through your firewall, at least on Windows.
