### ISSUE TITLE
Unable to play any video at all

### ISSUE THREAD

**Issue by XxAcielxX** [anxdpanic/plugin.video.youtube#861]
### Context
* Add-on Version: 7.0.9+beta.8
* Kodi Version: v21
* Kodi GUI Language: English
* Operating System: LibreELEC 12.0.0
* Operating System Language: English

------

### Expected Behavior
Videos should play without throwing any errors.

------

### Current Behavior
All videos fails to play.

------

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Play any video through the Addon or shared from Yatse Android App
2. Fail to play error shows up instantly

------

### Log
https://dpaste.com/8G3GDPHAC

------

### Addition info
Oops forgot to turn back on `Force check SSL Certificate`, even with it on, still doesn't play at all.

------

**Comment by MoojMidge** [comment]
🤦
Should be fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.9
