### ISSUE TITLE
Plese consider adding support for SponsorBlock

### ISSUE THREAD

**Issue by tv21** [anxdpanic/plugin.video.youtube#870]
### What Problem Does This Solve? 

Allows automatically skipping annoying parts of YouTube videos:  "SponsorBlock is an open-source crowdsourced browser extension and open API for skipping sponsor segments in YouTube videos. Users submit when a sponsor happens from the extension, and the extension automatically skips sponsors it knows about using a privacy preserving query system. It also supports skipping other categories, such as intros, outros and reminders to subscribe, and skipping to the point with highlight."

------

### Suggest a Solution (optional)

Please provide support for SponsorBlock (see https://sponsor.ajay.app/) or in the alternative please consider making an easy way to add the Kodi SponsorBlock addon (https://github.com/siku2/script.service.sponsorblock) as a supported addon if you feel it is safe to do so.  My only issue with that addon is it is only available from a third-party repository and we are always being warned about addons from third-party repos so I have no idea if it is safe to use, plus when I tried to search for it in the Kodi forum I saw no mention of it at all, which also makes me a little concerned.  The only reason I found it at all was because it is mentioned as a third-party port of SponsorBlock on this page:  https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports#kodi

------

**Comment by MoojMidge** [comment]
The linked addon as of this commit https://github.com/siku2/script.service.sponsorblock/tree/f7a383f1a10fcf9e8a45fe845c10669c280330a7 doesn't appear to have anything nefarious in it, so if you are comfortable with using sponsor block then there shouldn't be any harm in using the addon. 

This is just from a superficial look and carries no guarantee, express or implied, that it is safe to use, now or in the future.

I also don't use it myself so can't comment on how well it works.

Regardless don't have plans to integrate support, but that doesn't stop anyone else from doing so.

**Comment by neo-neo1** [comment]
Would be nice to have Sponsorblock Integration
