### ISSUE TITLE
Youtube add on login

### ISSUE THREAD

**Issue by asaidac** [anxdpanic/plugin.video.youtube#871]
### Context

Please provide any relevant information about your setup

* Add-on Version:  420.7.0.9+beta.9.unofficial.1
* Kodi Version: 21
* Kodi GUI Language: English
* Operating System: Android 11 (Nvidia shield host)
* Operating System Language: English
------

### Expected Behavior

Going through login process, entering the required authentication code and user results in:

Invalid client OAuth client not found Error 401

Verifying the API settings there no info (empty fields) on any of the of the required 
API Key, API Id, ApiSecret

Note:
Youtube Live option Error "Enter a valid API key"

------

### Current Behavior

What is the current behavior?
Unusable, no functionality available

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Sign in
2. Entering the code on google.com/device =>error 401
3. Entering the 2nd code same error

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.
No API keys / App ID keys provided so I assume that 401 error is normal
How can I obtain the required API settings?

------

**Comment by MoojMidge** [comment]
If you want to login then you need to create an API key and OAuth credentials, they are not provided for you. The OAuth credentials in particular allows for access to your account details, so you are the only one who can create those.

You can search the internet for instruction on how to do this, there are plenty of tutorials about this topic. There are also instructions provided if you search the issues in this repository and also in this pinned issue: https://github.com/anxdpanic/plugin.video.youtube/issues/439

**Comment by asaidac** [comment]
Hello
I do not believe that your
statement is correct.
Nvidia as a host has YouTube add on - no keys required.
I could use it but I am tired to switch Kodi/Nvidia in ordrt to use Youtube.
Why even bother to add Kodi add on?
To create an Google API is not for the faint of heart. Expecting that user
is required to create an API is strange.
More so there a discrepancy in the version number posted on Github and the
version available from repositories . What is the story here?
All this started when I've updated Kodi Diggz guest

**Comment by ThubLives** [comment]
> Hello I do not believe that your statement is correct. Nvidia as a host has YouTube add on - no keys required. I could use it but I am tired to switch Kodi/Nvidia in ordrt to use Youtube. Why even bother to add Kodi add on? To create an Google API is not for the faint of heart. Expecting that user is required to create an API is strange.

@MoojMidge's statements are accurate.  Feel free to use whatever YouTube client suits your needs, but this Kodi add-on requires an API key and OAuth credentials in order to do what it does.  It would be fantastic if that wasn't the case, but for now at least, those are the breaks.  There are alternatives out there like Invidious which uses other means than the YouTube/Google APIs so maybe they will suit you better.

> More so there a discrepancy in the version number posted on Github and the version available from repositories . What is the story here? All this started when I've updated Kodi Diggz guest

As for the versioning, my understanding is that the github repo is typically ahead of the Kodi repos while some brave users do some testing and new versions get pushed to the Kodi repositories once there is a little more confidence in the code.

**Comment by asaidac** [comment]
Hello
1st thank you for pushing me to get my APIs feet wet !

After getting my knowledge updated, I've created the API, ID and secret
keys.
Google is very slow to make those keys available (24 hours +)

Now the disappointment:
the YouTube kodi add on, is stripped of custom configurations.
It will not allow ANY Dolby surround sound even if the host will allow all
decoding up to Atmost
Even if my HW will allow 4k/60Hz the Youtube add-on streaming is "chopped"
- I believe there is a limited bandwidth allocation in between host / guest

It was a fun ride!

**Comment by MoojMidge** [comment]
> the YouTube kodi add on, is stripped of custom configurations. It will not allow ANY Dolby surround sound even if the host will allow all decoding up to Atmost Even if my HW will allow 4k/60Hz the Youtube add-on streaming is "chopped" - I believe there is a limited bandwidth allocation in between host / guest

This is not correct. The addon will provide 8k video and 6ch AAC/AC3/DTS if they exist for a video. It is all fully configurable.
