### ISSUE TITLE
Feature Request: Using a proxy

### ISSUE THREAD

**Issue by extremelyonline** [anxdpanic/plugin.video.youtube#883]
### What Problem Does This Solve? 

Proxy settings can be helpful In many ways, such as getting around geo-blocking or allowing Youtube access when the TV itself is quarantined from the internet.

It would be great if the addon would be able to follow Kodi's system-wide proxy settings (#32). A menu to set a proxy for the addon only is another method.

------

### Suggest a Solution (optional)

This may be of help: [ YouTube addon don't use Kodi's proxy #795 ](https://github.com/jdf76/plugin.video.youtube/issues/795)

------

**Comment by MoojMidge** [comment]
Why is this required?

https://github.com/anxdpanic/plugin.video.youtube/issues/841#issuecomment-2251489067

This seems to indicate that the Kodi proxy settings are being used.

Note that implementing different proxies for the requests this plugin makes won't effect video playback, only the video listings.

**Comment by extremelyonline** [comment]
I am sorry. I reinstalled the addon, and the Kodi proxy settings do work.
