### ISSUE TITLE
invalid escape sequence

### ISSUE THREAD

**Issue by heitbaum** [anxdpanic/plugin.video.youtube#885]
Error when using Kodi with Python 3.12

```
error <general>: /storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/methods.py:316: SyntaxWarning: invalid escape sequence '\g'
return re.sub(r'([?&/])ip([=/])[^?&/]+', '\g<1>ip\g<2><redacted>', url)
```

https://github.com/anxdpanic/plugin.video.youtube/blob/23c1824fbe6e9a33f6d73cb42abafeec3f3dd243/resources/lib/youtube_plugin/kodion/utils/methods.py#L316

ref:
- https://stackoverflow.com/questions/13989640/regular-expression-to-match-a-dot/66666859#66666859

**Comment by MoojMidge** [comment]
Will be fixed in next release.
