### ISSUE TITLE
Problem with My subscription

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#888]
_Translator:_
They just don't work properly.

_RPi 4,, LibreELEC 12.0.0, YouTube 7.0.9.1_

**Comment by MoojMidge** [comment]
Post a log

**Comment by Mo1967** [comment]
I think that's true.
With v7.0.9.1 get old (deleted) content in My Subscriptions, only. 

### Here different to  v7.0.9 with current content:
[kodi with v7.0.9.log](https://github.com/user-attachments/files/16739050/kodi.with.v7.0.9.log)
[kodi with v7.0.9.1.log](https://github.com/user-attachments/files/16739052/kodi.with.v7.0.9.1.log)

### Screenshot with v7.0.9 (current right content)
![My Subscriptions  v7 0 9](https://github.com/user-attachments/assets/6f363756-1963-4746-938f-8c52486d4bcf)

### Screenshot with v7.0.9.1 (wrong content, from old deleted subscriptions only)
![My Subscriptions  v7 0 9,1](https://github.com/user-attachments/assets/f04c4c88-16ee-4c11-9b5d-d1b93fbc355c)

**Comment by MoojMidge** [comment]
Thanks for that. Unfortunately your device doesn't actually log debug info even when it is enabled.

Can you get me a normal log using the following test version?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/extra_logging.zip

**Comment by Mo1967** [comment]
@MoojMidge 
let me know for further support.
[kodi with  v7.0.9.1 test version.log](https://github.com/user-attachments/files/16739237/kodi.with.v7.0.9.1.test.version.log)

**Comment by MoojMidge** [comment]
Thanks. It's a bit strange, but I can see what the problem is. Need to figure out what can be done

**Comment by Mo1967** [comment]
> Thanks. It's a bit strange, but I can see what the problem is. Need to figure out what can be done

Great.
BTW: In 'My Subscription' for the the other user (wife), the content are up to date in v 7.0.9.1

**Comment by MoojMidge** [comment]
Yeah it is a timing issue. For some reason the threads are being delayed and depending on the number of subscriptions or bookmarks you have, the fetching of new videos may be stopped before the delayed threads fully complete

**Comment by Mo1967** [comment]
Tested......
Maintenance -> Clear bookmarks list-> now for both user the right content of 'My Subscription'.
With errors in the log, but working correct
[kodi.with.v7.0.9.1.test.version Part II.log](https://github.com/user-attachments/files/16739384/kodi.with.v7.0.9.1.test.version.Part.II.log)

**Comment by MoojMidge** [comment]
> With errors in the log, but working correct

Those are fake errors, just normal debug log entries but changed to error messages, otherwise they wouldn't show up in your logs because of the particular device you are using.

You had one bookmark previously which was enough to trigger the problem because of the delay in thread execution. Can you bookmark one channel again and confirm that the issue re-occurs?

Can you then try with this new test version and confirm that it now works correctly?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Mo1967** [comment]
confirm it, works for both user with  bookmarked channel. Thank you.
[kodi with YT master.log](https://github.com/user-attachments/files/16739626/kodi.with.YT.master.log)

**Comment by MoojMidge** [comment]
Great, thanks for testing!

**Comment by MoojMidge** [comment]
@DjDiabolik, @C-O-D, @DJMix-I-Can - can you test this version as well and confirm your issues with My Subscriptions do not re-occur:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by C-O-D** [comment]
I'd say this looks pretty good - no problems so far: [kodi.log](https://github.com/user-attachments/files/16739840/kodi.log)

But maybe you could take a look at why the corresponding widget always disappears after starting a video from the widget? The problem has existed for a very long time and occurs with all of my skins and only with the YT addon: [kodi_widget.log](https://github.com/user-attachments/files/16739858/kodi_widget.log)

**Comment by DJMix-I-Can** [comment]
Just tested it out & it's working fine. I noticed something last night when I was going to sleep. I have a Meditation playlist folder with misc ambience videos. I usually highlight the video, long press for the context menu & select "Play Audio Only".  I do this so the screen can go dark.  We were more focused on the "My Subscriptions" issue that I never thought about testing that out.  On version 7.0.9.0 it was working, on 7.0.9.1 it works when it wants to. I would get an error BUT as soon as I back out of the playlist, the audio kicks in. I posted a log of it happening. 7.0.9.2 My Subscriptions & Play Audio Only are working fine. Even though, Play Audio Only is working now. I thought I'd mention it & provide a log for future references.  Thanks.
[kodi.log](https://github.com/user-attachments/files/16741554/kodi.log)

**Comment by MoojMidge** [comment]
> on 7.0.9.1 it works when it wants to. I would get an error BUT as soon as I back out of the playlist, the audio kicks in.

Yes, this was a side-effect of trying to fix #873. Was fixed by https://github.com/anxdpanic/plugin.video.youtube/commit/4377cc3db2a92be24df0e92a95562d5a61b312c3 in v7.0.9.2

**Comment by DjDiabolik** [comment]
I'm problably come back later for testing. On my side today i have used a lot the current 7.0.9.2.

With both option disabled:
- Refresh after watching
- Delete from "Watch Later" after watching

This version it's apparently have a good stable usage....... about 2 minutes ago maybe i'm going to exit from kodi and all it's freeze at during exit operation. 

The last line on kodi.log speaking about another addons:
`024-08-26 02:05:27.831 T:7       error <general>: CPythonInvoker(118, /home/diabolik/.var/app/tv.kodi.Kodi/data/addons/plugin.video.kod/default.py): script didn't stop in 5 seconds - let's kill it`

a similar problem had already existed in the recent past...  I had posted the debug log and the problem then disappeared with subsequent updates.
Could the same problem have reappeared? 

*EDIT*
The old issue it's there:
https://github.com/anxdpanic/plugin.video.youtube/issues/813
Looking the log the issue it's different.... now need more test. If i can repeat the issue or i open new issue or i can add another debug log on the old issue like similar.

*EDIT 2nd*
Warning... possible sporadic case. I have tryed to reproduce this issue (kodi can't exit) in this last 30 minutes... can't reproduce the issue.
maybe after more heavy use ? Only the future can say that :)

**Comment by MoojMidge** [comment]
> With both option disabled:
> 
> * Refresh after watching
> * Delete from "Watch Later" after watching

Planning to remove the refresh after watching setting, but in the meantime try with these enabled and see if there is an improvement compared to what was happening previously.


> If i can repeat the issue or i open new issue or i can add another debug log on the old issue like similar.

None of the recent changes would be able to cause the previous problem to reoccur. If you are having an issue and suspect this plugin then you can open a new issue when you can get a debug log.

**Comment by DjDiabolik** [comment]
> None of the recent changes would be able to cause the previous problem to reoccur. If you are having an issue and suspect this plugin then you can open a new issue when you can get a debug log.

Yeah this it's ever valid..... Also today until 5 minutes ago i have watched about 8 / 9 youtube video in a row whitout any issue.
After that i exit from kodi whitout any issue and whitout any freeze.

I think Kodi itself is probably not new to these cases/problems that appear once and then disappear the next time you use it.
Already yesterday evening when I failed to "replicate" the issue i have editing previous reply :)
