### ISSUE TITLE
Widget reload failing after playback starts

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#891]
I'd say this looks pretty good - no problems so far: [kodi.log](https://github.com/user-attachments/files/16739840/kodi.log)

But maybe you could take a look at why the corresponding widget always disappears after starting a video from the widget? The problem has existed for a very long time and occurs with all of my skins and only with the YT addon: [kodi_widget.log](https://github.com/user-attachments/files/16739858/kodi_widget.log)

_Originally posted by @C-O-D in https://github.com/anxdpanic/plugin.video.youtube/issues/888#issuecomment-2308773082_

**Comment by MoojMidge** [comment]
For how long has this been happening?

**Comment by C-O-D** [comment]
> For how long has this been happening?

I'd say since early this year or something, don't know exactly
Thanks for your great work btw :-)

**Comment by MoojMidge** [comment]
When Kodi plays or stops something it will refresh the current list container. Ostensibly this is done to ensure that the watched status of the played item is updated in the list, but Kodi will actually refresh all open list containers, all at once, including any widgets you have open.

This can actually cause Kodi to crash, so there is a crash workaround that was implemented in this plugin to cancel the plugin invocation if it was likely to trigger this crash.

Unfortunately this will mean that the widget which is filled by the plugin will effectively be empty and, depending on the skin, may be collapsed/hidden.

The crash workaround is not a perfect solution and has a number of side effects, including what you have noticed, but it does cut down on the number of crashes.

There is an updated version of the crash workaround that will probably work a bit better in this situation. Will add it into the next beta and you can see if it resolves this problem.

**Comment by C-O-D** [comment]
Great, thank you very much for the detailed explanation and of course for your efforts 👍

**Comment by MoojMidge** [comment]
Does this resolve the problem?

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Nanomani** [comment]
@MoojMidge 
Your update 7.1.0 beta1 fix this issue.
When à video is launch from Widget all works fine now. 
Thanks a lot for your hard works to make this addon always better.

**Comment by C-O-D** [comment]
I don't want to be too hasty just yet, but I think a new life has begun 🙏

**Comment by MoojMidge** [comment]
Keep an eye on things, and if you see it happen again try and get a log.

A regular log will do from the time that it happens, but if you can reproduce it a debug log will be better.
