### ISSUE TITLE
ERROR INVALID CLIENT "THE OAUTH CLIENT WAS NOT FOUND" CODE 401

### ISSUE THREAD

**Issue by PirlouitJambon** [anxdpanic/plugin.video.youtube#893]
Hello,

Everytime that I try to configuree my youtube account, I get an error message just after the code in google.com/device and autorizing.
Can you help me to solve this problem ?
Thank you.
![Bug Kodi Youtube](https://github.com/user-attachments/assets/73f1d501-4fd8-47fe-a245-a6335eea641d)
Kodi version 21.1
Youtube plugin version 7.0.9.2

**Comment by MoojMidge** [comment]
If you want to login then you need to create an API key and OAuth credentials.

There are instructions provided in this pinned issue: https://github.com/anxdpanic/plugin.video.youtube/issues/439

**Comment by PirlouitJambon** [comment]
Hello MooMidge,
I followed you instructions dut it's still not working :(

**Comment by MoojMidge** [comment]
Can't help you any further unfortunately.

There are only two possibilities:

1. You haven't followed the instructions fully
2. Something else is wrong (very unlikely) and you haven't provided any information to be able to determine what that is. 

If you are absolutely certain you have followed the instructions, then you will need to provide the details, including a debug log, requested in the issue template that should be followed when creating an issue.

**Comment by PirlouitJambon** [comment]
Thank you, it was just an API problem.
