### ISSUE TITLE
Stream hungs after 10 minutes

### ISSUE THREAD

**Issue by TasPats** [anxdpanic/plugin.video.youtube#897]
### Context

ordinary stream, after about 10:15 min:sec stream hungs, after few minutes still image strange sounds (not audio track)

* Add-on Version: 7.0.9.2
* Kodi Version: Omega (Kodi-21.1)
* Kodi GUI Language: English
* Operating System: Android 6.0.1
* Operating System Language: English

------

### Expected Behavior

just stream to end of video

------

### Current Behavior

after about 10:15 min:sec stream hungs, after few minutes still image strange sounds (not audio track)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. restart media player device
2. start KODI
3. start video stream

------

### Log

1000x
warning <general>: ActiveAE - large audio sync error: -65730.916207

error <general>: AddOnLog: inputstream.adaptive: [AS-2] Download failed, internal error: https://rr2---sn-c5aupjvh-gpms.googlevideo.com/videoplayback?expire=1726182783&

full .LOG contains personal and confidential information, sorry
------

### Additional Information

traceroute youtube.com

22 hops
few of them with:
*.retn.net (.ru related international data network prowider)
and this all start when .ru start slowing Youtube

------

**Comment by MoojMidge** [comment]
This plugin can't change how data is getting routed to you or what your ISP is doing.

It may be possible to adjust some settings to try and help the situation, but without a log can't comment about that either.

Have a search through the closed issues. There are some comments about running a proxy to try and bypass the issues.
