### ISSUE TITLE
My Subscription Added to Favorites Shows Old Videos

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#898]
I've had "My Subscriptions" set to Favorites for several years when using this YouTube Addon.

However, several versions back this functionality became buggy.

Often when opening My Subscriptions from favorites, it shows older cached videos. I have to refresh the list.

And sometimes opening My Subscriptions from favorites opens Page 2 of of the list with older cached videos

**Comment by MoojMidge** [comment]
Works fine for me.

Sounds like there is something wrong with your system. If you figure out what it is, feel free to update this issue.

If you need help figuring out what the problem may be then you will need to provide some actual details including a log.

**Comment by neo-neo1** [comment]
Worked fine for years until that version came out which changed how My Subscriptions was cached.

**Comment by MoojMidge** [comment]
The issue template exists for a reason. I have no idea what you are talking about because you are not provinding any useful details of what your problem actually is.
