### ISSUE TITLE
[BUG] Error when using 'vod' item type in item_filter query parameter

### ISSUE THREAD

**Issue by inb4after** [anxdpanic/plugin.video.youtube#901]
### Context

* Add-on Version: 7.1.0+beta.2
* Kodi Version: 21.1
* Kodi GUI Language: English
* Operating System: Windows 10 64-bit
* Operating System Language: English

------

### Expected Behavior

No error and the container loads correctly.

------

### Current Behavior

Error is thrown and container does not load when trying to use the 'vod' item type.

------

### Steps to Reproduce

1. Conduct a search using 'vod' in item_filter query parameter
2. Error when trying to load the container content

------

### Log

https://paste.kodi.tv/ilicipusac.kodi

------

### Additional Information

All the other item types work as intended. As soon as you add 'vod' to the list, it will fail to load the content with the above error.

------

**Comment by MoojMidge** [comment]
You are getting an error because the plugin VFS directory listing for the provided url is empty.

It is empty because you are filtering out all available results.

`vod` is Videos On Demand i.e. the vast majority of the videos on YouTube that aren't live streams.

It is used internally by the plugin, but is probably not something you want to filter out.

**Comment by inb4after** [comment]
Ah, I thought the vod item type was actually those listings for Youtube Movies that would be paid (rent/buy). 

These result in "Video is not available" issue when trying to play them.

For example:

https://i.imgur.com/FrFpAqT.jpeg

**Comment by MoojMidge** [comment]
Haven't looked into paid videos. Can you post a log snippet of trying to play one of them so I can get the id of the video?

**Comment by inb4after** [comment]
> Haven't looked into paid videos. Can you post a log snippet of trying to play one of them so I can get the id of the video?

https://paste.kodi.tv/oyulijexic.kodi

This is the same item as the one from the screenshot, the paid video ID of Deadpool 2016.

**Comment by MoojMidge** [comment]
Doesn't seem possible to identify paid videos. Can identify if a video containes licensed content, but while all paid videos appear to be licensed, not all licensed videos are paid.

**Comment by inb4after** [comment]
> Doesn't seem possible to identify paid videos. Can identify if a video containes licensed content, but while all paid videos appear to be licensed, not all licensed videos are paid.

What about manually blocking the uploader's channel ID?

For example, YouTube Movies (not sure about TV shows, but it may be a similar channel).

**Comment by MoojMidge** [comment]
That is an option, but from what I can see it is not quite that simple.

I think there are other channels that offer this type of content, and not all the content on that specific channel is paid.

**Comment by inb4after** [comment]
Would `videoSyndicated=true` parameter have the desired effect?

**Comment by MoojMidge** [comment]
I don't believe so. Doesn't seem to be linked afaics
