### ISSUE TITLE
Did YouTube just disable guest/logged out search?

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.youtube#905]
### Context

* Add-on Version: 7.0.9.2
* Kodi Version: kodi-21.1-Omega-x64
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English

![image](https://github.com/user-attachments/assets/891150dd-dbb6-475c-9e54-08f8ffdf934a)
Just a few days ago searching for YouTube videos or channels while logged out worked just fine. In fact I never logged in. My bookmarked channels still play but searching for more stuff gets this error (The Caller Does Not Have Permission). Maybe YouTube is screwing with something?

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
https://forum.kodi.tv/showthread.php?tid=356934&pid=3209756#pid3209756

You need to provide your own API key.

If you don't want to use your own API key, then you will need to login. If you don't want to login, get your own API key.
