### ISSUE TITLE
The OAuth client was not found

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#910]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.0+beta.5
* Kodi Version: Nexus 20.5
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

------

### Expected Behavior

Sign-in with 2factor Auth.

------

### Current Behavior

Error (see LOG)

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open YouTube Addon
2. Check if you sign-in with your account or sign-out ?!
3. 

------

### Log

https://paste.kodi.tv/ulefokidak.kodi

------

### Additional Information

Didn't sign-out manually

------

**Comment by Mo1967** [comment]
Switched back to v7.1.0+beta.4 and 2factor sign-in working. I know, https://github.com/anxdpanic/plugin.video.youtube/issues/583#issuecomment-1953173154
but with  v7.1.0+beta.4 and earlier no sign-in (2factor) problems.

![Screenshot 2024-09-27 041012](https://github.com/user-attachments/assets/50363daf-7671-4f92-9d6b-db4081f2ec14)

**Comment by Abbaddon911** [comment]
I'm getting the exact same issue, even tried with freshly created API Key and OAuth Client (TV and limited input setting), but the error is still present.

Going back down to beta4, I'm able to log in again.

System and Addon version with the issue:
_______________________________________________
- Add-on Version: v7.1.0+beta.5
- Kodi Version: Omega 21.1
- Kodi GUI Language: DE
- Operating System: LibreELEC 12.0.1
- Operating System Language: DE

**Comment by benyamin-codez** [comment]
I can confirm reverting https://github.com/anxdpanic/plugin.video.youtube/commit/6d652927047df05d7022a6bde6a10cfbe1acfd3c fixed this.

Removing the "extra" commas was not sufficient. It needed the values under `youtube-tv` added back in...

**Comment by MoojMidge** [comment]
Well that was silly...

Should be fixed if you can test and confirm https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Mo1967** [comment]
> Well that was silly...
> 
> 
> 
> Should be fixed if you can test and confirm https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip
> 
> 

Works out of the box with 1Factor (!) Auth., Thank you!

**Comment by MoojMidge** [comment]
It's not actually multi factor authentication, but different authorisations for different projects. However now the old TV app authorisation doesn't seem to work and also doesn't seem to be required, so moving forward will probably only need to login once to the project you have individually created when creating your own API key and OAuth credentials.

**Comment by MoojMidge** [comment]
Don't think that will fully fix the issue, missed a couple of checks for the refresh tokens, so you might get signed out automatically after some time. Will have a look again later in the day.

**Comment by MoojMidge** [comment]
Can you retest https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

I think it should be fixed but no opportunity to test it myself.

**Comment by Mo1967** [comment]
Confirm it, v7.1.0 working for both user on my device. Tested sign-out and sign-in again with 1factor auth.

**Comment by Liqianyu** [comment]
I should have checked the issues page sooner 😶
I checked the API key input multiple times and recreated OAuth. all to no avail. It wasn't until using the latest beta that the issue was fixed.
It's also worth mentioning that beta.5 would report an error when opening it, it wouldn't open, you had to turn off Enable Setup Wizard in settings to open it, and you couldn't open Setup Wizard after that either (it would report an error), has this been fixed as well?

**Comment by MoojMidge** [comment]
> It's also worth mentioning that beta.5 would report an error when opening it, it wouldn't open, you had to turn off Enable Setup Wizard in settings to open it, and you couldn't open Setup Wizard after that either (it would report an error), has this been fixed as well?

What was the error?

**Comment by Liqianyu** [comment]
> > It's also worth mentioning that beta.5 would report an error when opening it, it wouldn't open, you had to turn off Enable Setup Wizard in settings to open it, and you couldn't open Setup Wizard after that either (it would report an error), has this been fixed as well?
> 
> 
> 
> What was the error?

Forgot to add that the problem occurs with the latest nightlies version and is on the UWP platform. So wait for me to see if I need to report this issue.
