### ISSUE TITLE
Wiki page about API keys is misleading

### ISSUE THREAD

**Issue by springjools** [anxdpanic/plugin.video.youtube#914]
### Context

Please provide any relevant information about your setup
https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys

### Additional Information

The page should mention which api from google that we are supposed to enable. There are dozens of different apis. It would also be nice to explain why we need to use our own api keys suddenly.

------

**Comment by psp2111-ADSLGATE** [comment]
Here a detailed guide on how to great one: https://github.com/anxdpanic/plugin.video.youtube/issues/439

**Comment by MoojMidge** [comment]
> It would also be nice to explain why we need to use our own api keys suddenly.

https://forum.kodi.tv/showthread.php?tid=356934&pid=3209756#pid3209756
