### ISSUE TITLE
Crash when launching the plugin

### ISSUE THREAD

**Issue by contremaitre** [anxdpanic/plugin.video.youtube#916]
### Context

Please provide any relevant information about your setup

* Add-on Version: Please see
* Kodi Version: 20.5
* Kodi GUI Language:
* Operating System: Kernel: Linux 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024
 Release: Ubuntu 24.04.1 LTS (Noble Numbat)
* Operating System Language: French

------

### Expected Behavior

Launch  the plugin and have the setup wizard

------

### Current Behavior

Crashes after a freeze of several seconds

------

### Log

https://paste.kodi.tv/latovucedo.kodi

------

### Additional Information

I installed latest version of youtube add-on, entered my API keys, but could not launch the add-on. It freezes for a few seconds, then kodi crash (it closes completely). I did not see any setup wizard 

------

**Comment by MoojMidge** [comment]
Your version of Kodi is incompatible with the version of Python 3.12 used in Ubuntu 24.04

https://github.com/xbmc/xbmc/issues/24069

You can try running the Flatpak version and see how that works instead.
