### ISSUE TITLE
Latest youtube plugin on KODI doesn't play films with music (clips)

### ISSUE THREAD

**Issue by gembiart** [anxdpanic/plugin.video.youtube#92]
Hello, since yesterday I found that youtube plugin on Kodi does'nt want to play music videos (officials), The error apperas: look into a event viewer but there is no event.
Other films goes correctly. Only officaial videoclips no. I tested on many, Celine Dion - Titanic official Videoclip not working.

I was desperate and I reinsatll my kodi and only one youtube plugin (ofcourse with API, SECRET KESY ETC.) the same situation, what's going on ?

Regrads
Artur

**Comment by anxdpanic** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
