### ISSUE TITLE
7.1.0 - Possible Bug when you use "Go to <ChannelName>" after a search complete. miniature instead Watched/Not Watched icon appear.

### ISSUE THREAD

**Issue by DjDiabolik** [anxdpanic/plugin.video.youtube#922]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1 unofficial
* Kodi Version: 21.1 Flatpak
* Kodi GUI Language: Italian
* Operating System: Ubuntu 24.04.1 LTS
* Operating System Language: Italian

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Made a search... some.
2. Select a video. Open context menù and try to use "Go to <User>" feature
3. Instead the watching status at the left of title the minuature appears.

Similar issue if you use "Go to <xxx>" from "My Subscription feed

**Comment by MoojMidge** [comment]
Should be fixed by https://github.com/MoojMidge/plugin.video.youtube/commit/4d6e7ee03f926d88cca07f0511ce22652b827c0b

Will be availabe in next beta or you can try to make the change yourself if you like

**Comment by DjDiabolik** [comment]
@MoojMidge can i download the raw file [xbmc_plugin.py] individually and apply that on current 7.1.0 ?

**Comment by Mister-Denis** [comment]
THX, the workaround is ok for me.
I didn't want to do edit through ssh so i unpacked the "7.1.0." zip, edit the file withN++ and repack the directory as a zip, then copy + reinstall in the librelec box.

**Comment by DjDiabolik** [comment]
@Mister-Denis how did you modify the file? On my side i can edit directly the file whit gedit because i use kodi on ubuntu :)
But i'm not understand if i can directly change the xbmc_plugins.py :)

**Comment by MoojMidge** [comment]
> @MoojMidge can i download the raw file [xbmc_plugin.py] individually and apply that on current 7.1.0 ?

May cause some issues because there are other unrelated changes in that file and because you are using the unofficial version.

Best bet is to make the changes manually using gedit or wait for a new fix release.

**Comment by Mister-Denis** [comment]
> @Mister-Denis how did you modify the file? On my side i can edit directly the file whit gedit because i use kodi on ubuntu :) But i'm not understand if i can directly change the xbmc_plugins.py :)

My kodi is an librelec box, i did not want to use ssh to access it to edit.. I just opened the zip file of the plugin in a  windows pc using notepad++, repack and upload. 
If your kodi is  an unbuntu, you probably have a text editor to directy edit the file. 
I dont know where plugin files are stored on a linux.

BTW, i used the official version

**Comment by DjDiabolik** [comment]
> > @MoojMidge can i download the raw file [xbmc_plugin.py] individually and apply that on current 7.1.0 ?
> 
> May cause some issues because there are other unrelated changes in that file and because you are using the unofficial version.
> 
> Best bet is to make the changes manually using gedit or wait for a new fix release.

Lol... I honestly didn't understand what the right changes to make to the file were.
Anyway from now using the 7.1.0.1 unofficial :) Thanks for fixing this issue :)
