### ISSUE TITLE
Setup Wizard fails in v7.1.0 (unofficial version)

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#924]
2 x Log files attached
1. full debug log!
2. extracted portion of log showing point at which YT Plug-in crashes when calling the setup option.
[kodi.log](https://github.com/user-attachments/files/17275622/kodi.log)
[extract from log.txt](https://github.com/user-attachments/files/17275624/extract.from.log.txt)

_Originally posted by @dtteufel in https://github.com/anxdpanic/plugin.video.youtube/issues/920#issuecomment-2396281423_

**Comment by MoojMidge** [comment]
Thanks - that is due to an incorrect merge in the unofficial version following a tidy up in the official version.

Easily fixed but probably not the same issue then.

_Originally posted by @MoojMidge in https://github.com/anxdpanic/plugin.video.youtube/issues/920#issuecomment-2396358711_

**Comment by dtteufel** [comment]
Many thanks, that fixed it.
