### ISSUE TITLE
Cannot play most of the videos anymore

### ISSUE THREAD

**Issue by SoraSuiseki** [anxdpanic/plugin.video.youtube#93]
### Context

* Add-on Version: 6.8.9
* Kodi Version: 18.9.0
* Kodi GUI Language: English (Skin: Confluence)
* Operating System:  Libreelec: 9.2.6 (ARM on raspberry Pi 3B+)
* Operating System Language: English

------

### Expected Behavior

When i search for a video, i get all results in a list. When i select any, it should actually play it.

------

### Current Behavior

What is the current behavior?
It's not playing most of the videos anymore. You get an error message to take a look in the log files

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open youtube addon
2. search for "funk music"
3. select any video from list to play
4. get the error message

------

### Log

http://paste.kodi.tv/ogixoyisof

------

### Additional Information

I have tested it several times with different search keys. It seems to happen for most of my searches, but not all of them. Some videos are working fine. But most of them not.

------

**Comment by deadspool** [comment]
Hello,

Exacly the same issue on my kodi:

    Add-on Version: 6.8.9
    Kodi Version: 18.9
    Kodi GUI Language: French (Skin: Estuary)
    Operating System: Libreelec: 9.2.6 (ARM on raspberry Pi 4)
    Operating System Language: English

Some exemples:

these videos can't be played:

https://www.youtube.com/watch?v=LjxcJj4-wE4
https://www.youtube.com/watch?v=-XN3aZ3ZKWY
https://www.youtube.com/watch?v=xtszgIRPLMQ

Some other video are played without problem:
ex: https://www.youtube.com/watch?v=hhznMCnUqis

**Comment by jonisb** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by deadspool** [comment]
Hello,
the 6.8.10 alpha1 version provided correctly fix the issue.
