### ISSUE TITLE
Play Audio Only

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#931]
_Translator:_
This option always starts playback from the beginning. Continuing is not possible.

_YouTube 7.1.0.1, LibreELEC 12.0.0, RPi4_

**Comment by MoojMidge** [comment]
Post a debug log.

**Comment by drrak** [comment]
I'm too lazy for this. Sorry. 
Maybe someone else will do it.

**Comment by MoojMidge** [comment]
🤷 Works fine for me fwiw
