### ISSUE TITLE
Installing v7.1.1+beta.1

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#932]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1+beta.1
* Kodi Version: 20.5
* Kodi GUI Language: DE/EN
* Operating System: Android
* Operating System Language: DE/EN

------

### Expected Behavior

Override v7.1.0 with v7.1.1+beta.1 and upgrade works.

------

### Current Behavior

Error message, please find below LOG.

------

### Log

https://paste.kodi.tv/wifujeyaju.kodi

------

### Additional Information

Back to stable v.7.1.0

------

**Comment by MoojMidge** [comment]
Should be fixed in https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Mo1967** [comment]
> Should be fixed in https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

..running, confirm it: https://paste.kodi.tv/kiyufebumo.kodi
But external and foreign links (green marked) in the folder view ?! 
![101224073135](https://github.com/user-attachments/assets/9be54ea7-1807-489a-8b29-5833d6aba3e6)

**Comment by MoojMidge** [comment]
Just some test code from an unrelated commit. Removed now. Can redownload if you want.

https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by Mo1967** [comment]
Now clean💪🏼Thank you very much, great work
