### ISSUE TITLE
 Super Favourites Playback Issues

### ISSUE THREAD

**Issue by rogermae** [anxdpanic/plugin.video.youtube#938]
### Context

Please provide any relevant information about your setup

Firestick 4k max  English 
Kodi 21.1
MEC build 6.0
Super Favourites 2.3.7
YouTube 7.1.0, 7.0.9.2, 7.0.5+unofficial.1
------

### Expected Behavior

All items in a folder should play one after the other. When selecting a file or folder to play next, that item should play and not go back to previous item played.  

------

### Current Behavior

I have several issues with this addon and any of the Youtube versions listed above. All of my files are from YouTube. Some are added in created Super folders, then others are added individually.

When selecting play Captain Midnight super folder, I cannot get the folder to begin playing. I have to open the folder, select a subfolder with episodes then select PLAY ALL. Instead of going to the next episode, I get a PLAYBACK FAILED message. I then have to close out and reopen the addon.

When selecting play the Green Hornet super folder it's plays fine, autoplays next subfolder within.

If I should stop playing the folder and try to start a different super folder then I get the busy spinner stopping and starting a few seconds then I have to shutdown the addon and open it again.

After getting a FAILED PLAYBACK message and exiting out of the Super Favourites addon to open the YouTube addon it will open in the page that lists Files, Playlists and Video add ons. I hit the back button a few times to get to the YouTube menu.

When in YouTube and select an item then close out and go to another item, the previous item will replay. I'll close out again it goes to the page with Files, Playlists and Video add-ons. I'll hit the back button and it takes me to the YouTube main page.

This would happen in the Super Favourites addon but now I get the Failed Playback message.

------

### Log

Please include a complete [debug log]

https://paste.kodi.tv/gutemayeme

**Comment by MoojMidge** [comment]
There are a bunch of issues in your log that I have seen before, but never all together.

I know what the problem is, but unfortunately your device uses FireOS which restricts the information that is logged as part of a debug log, so don't have enough details to try and figure out how to avoid the issue.

Can you upgrade to the latest beta version:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.2

And provide a new log after enabling the new setting to enable debug logging via the addon:
`Setting > Advanced > Logging > Enable debug logging`

**Comment by rogermae** [comment]
I need a source code to add this zip on a firestick, right. The above is not working


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
Not sure exactly what you mean, but this is the zip file that you can use to install manually.
https://github.com/anxdpanic/plugin.video.youtube/releases/download/v7.1.1%2Bbeta.2/plugin.video.youtube-7.1.1+beta.2.zip

If you need to install from a repository refer to instructions in link below, and install the development repository
https://github.com/anxdpanic/plugin.video.youtube/wiki/Installation#repositories

**Comment by rogermae** [comment]
Sorry for the delay. I've updated the addon. Here are the logs. It looks like there is still a problem with playing the next episode/file.

Old log: https://paste.kodi.tv/ezeyefojos
New log: https://paste.kodi.tv/ronusolaue



Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
A few things:

- The new log can't be accessed using the provided link (https://paste.kodi.tv/ronusolaue).
- You have a number of settings enabled that shouldn't be enabled if you don't know what they do, and a number of settings configured in such a way that will reduce video quality and decrease the speed at which videos can load.
- Your system takes an extremely long time to respond to JSON-RPC calls. Do you use some kind of Kodi remote control app?

I would suggest the following next steps:
1. Update to https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.4 - it has some changes that may improve things for your device
2. Run the Setup Wizard and ensure that you select settings appropriate for your device
3. Get another log with `Setting > Advanced > Logging > Enable debug logging` enabled

**Comment by rogermae** [comment]
I'm using he remote from my firestick 4k max
I've updated the address to beta..4

Log: https://pastebin.com/Mi359fiY



Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
No luck with that log. It may be marked as private, or expired

**Comment by rogermae** [comment]
Try this link
https://paste.kodi.tv/isedakoriq


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
I think this is the same underlying issue as #633 / #699

Can you try selecting your actual IP (10.117.1.90 or similar) using `Settings > Advanced > HTTP Server > Select listen IP`?

**Comment by MoojMidge** [comment]
Can you get a log using this test version:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

Please enable
`Setting > Advanced > Logging > Enable debug logging`

And use `0.0.0.0` as the listen address
`Settings > Advanced > HTTP Server > Select listen IP`

**Comment by rogermae** [comment]
https://paste.kodi.tv/natufugulu



Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
Another test version to try:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

Can you get another log?

> https://paste.kodi.tv/natufugulu

In this log you have MPEG-DASH disabled. Is there a reason for this?

**Comment by rogermae** [comment]
No particular reason.
Log: https://paste.kodi.tv/oqakegewot

________________________________

**Comment by rogermae** [comment]
After further review it appears that the MPEG-DASH must be off for the links to play in the Super Favorite folders.


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
> After further review it appears that the MPEG-DASH must be off for the links to play in the Super Favorite folders.

Are you saying that the videos do play correctly now if MPEG-DASH is disabled? Or are you still having the same original problems?

Additional fixes in another test version:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

This time can you get a full Kodi debug log?
https://kodi.wiki/view/Log_file/Easy

**Comment by rogermae** [comment]
The videos go back to the original problem. They won't play at all if turned on.

And there is a new problem of the playlists in YT not opening but the individual videos included in the playlists will play. Whether MPEG-DASH is enabled or not.

Logs: https://paste.kodi.tv/yikejajuzo
https://paste.kodi.tv/levagucuza

I've been doing these uploads the same way as instructed in the wiki link.



Kind Regards,
Roz Artis

**Comment by MoojMidge** [comment]
> The videos go back to the original problem. They won't play at all if turned on. And there is a new problem of the playlists in YT not opening but the individual videos included in the playlists will play. Whether MPEG-DASH is enabled or not.

To be clear:

- with MPEG-DASH on videos don't play?
- with MPEG-DASH off
  - videos play correctly when opened through the plugin?
  - videos don't play when opened through Super Favourites?

> I've been doing these uploads the same way as instructed in the wiki link.

Your device seems to have a number of issues that I can't understand and a debug log is required to determine what is actually happening.

I forgot that the instructions for how to produce a log won't work on your device.

There are some details on how to enable the logging here: https://forum.kodi.tv/showthread.php?tid=371987

If you are unable to figure out how to do that, then there is unfortunately not much more I can do, but one last try:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.5

Also try and disable script.logviewer

**Comment by rogermae** [comment]
With MPEG-DASH off plugin videos play but in Super Favourites the videos will not play consecutively.
I think this is the debug log you are looking for.

Log of beta.5: https://paste.kodi.tv/okabecidad.

I reverted back to v7.0.8 but the log is too big to upload. Everything is working as it should except in the plugin the Search doesn't open however the Quick Search does.


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
> I think this is the debug log you are looking for.

Thanks for that, unfortunately even this doesn't provide any more useful information. The entire addon service endpoint is not even attempting to load for some reason. Really very strange. Will need to have a look at the Kodi code to see if there is anything that may cause this.

> With MPEG-DASH off plugin videos play but in Super Favourites the videos will not play consecutively.

Give the following test version a try:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

The previous log doesn't include any playback attempts. Can you get a log using the test version and using Super Favourites? Doesn't need to be a Kodi debug log, just enable `Setting > Advanced > Logging > Enable debug logging`

**Comment by rogermae** [comment]
Figured out how to capture the large debug log.

But need to figure out how to reset the debug log back to its original settings.

Kind Regards,
Roz Artis

________________________________

**Comment by MoojMidge** [comment]
`adb shell setprop persist.log.tag I` should restore the original log settings
`adb shell setprop persist.log.tag.Kodi D` enables the debug logging for Kodi only
`adb shell setprop persist.log.tag.Kodi I` should restore the original log settings for Kodi only

**Comment by rogermae** [comment]
👍🏾


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
One other strange thing about your logs is that every plugin invocation seems to create a new thread and interpreter instance, which should not normally happen because this addon uses the `reuselanguageinvoker` feature in Kodi.

Are you modifying the addon.xml of this addon by any chance? Or using some other addon that changes this?

**Comment by rogermae** [comment]
System crashes when trying to autoplay next file

https://paste.kodi.tv/upudeweqar

https://paste.kodi.tv/qaweyugube



Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
I don't think this problem can be resolved.

The addon plugin invocation is crashing due to a bug in Kodi that is unlikely to be resolved in the near future.

This addon tries to workaround around this bug by intercepting the addon plugin calls using the addon service, and processing the plugin calls in a way that won't crash.

However on your system the service is never started so the workaround cannot be applied, and the plugin invocations are done in a way that they are not configured for.

Can't figure out why the service is not started or why the plugin threads aren't being reused. The only thing that I can think of is that the addon.xml for this addon has been modified in some way.

**Comment by rogermae** [comment]
Okay thanks for letting me know.


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
One thing you can test out is whether playback works through Super Favourites immediately after you have (re-)installed the previously linked test version:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

Can then confirm whether it stops working the next time you stop and restart Kodi.

**Comment by rogermae** [comment]
See photos. I'm getting this error when installing the master zip file



Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
Don't think any email attachments will be automatically added to a reply you make. Will need to attach those directly to the post you make on github.com

**Comment by rogermae** [comment]
![20241110_193237](https://github.com/user-attachments/assets/cfe0b08b-3528-4696-bfb8-bc01fa0f7bda)
![20241110_193137](https://github.com/user-attachments/assets/0d4e1b1f-9dac-4004-ab0a-8a7b6ecc6b6a)
![20241110_192900](https://github.com/user-attachments/assets/559182e1-634a-489b-8e8a-fa604964cac1)

**Comment by MoojMidge** [comment]
Oh silly merge error, should be fixed now. Can you try again and check the following?

> whether playback works through Super Favourites immediately after you have (re-)installed the previously linked test version: https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip
> 
> Can then confirm whether it stops working the next time you stop and restart Kodi.

**Comment by rogermae** [comment]
It worked immediately after I updated the addon. But after rebooting of Kodi, I went back into the Super Favourites folder and tried to play a subfolder. When it was time to go to the next episode/folder, the busy spinner started flashing and then it crashed. See log below.


https://paste.kodi.tv/opehohavoj


Kind Regards,
Roz Artis
________________________________

**Comment by MoojMidge** [comment]
> It worked immediately after I updated the addon.

This is good news and means that the issue you have raised has actually now been resolved.

Thanks for providing the logs.


> But after rebooting of Kodi, I went back into the Super Favourites folder and tried to play a subfolder. When it was time to go to the next episode/folder, the busy spinner started flashing and then it crashed.

Unfortunately it seems likely that one of the other addons you have on your system is preventing this addon from starting its service.

As explained here https://github.com/notifications#issuecomment-2466541538 there is nothing that can be done to resolve this from within this addon.

Couple more things you could try:

1. After a restart, disable and then re-enable the YouTube addon. Check whether playback from Super Favourites works.
  1.a) If it works then the addon.xml hasn't been modified and instead something is just preventing it from loading
  1.b) If playback from Super Favourites doesn't work then it means that something has modified the addon.xml

2. Disable all your other addons, then re-install https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip and restart. Check whether playback from Super Favourites works.
  2.a) If the Super Favourites playback works then re-enable your other addons one by one. Restart after each addon is enabled and check which one prevents this addon from loading by checking playback in Super Favourites.
  2.b) If the Super Favourites playback doesn't work initially then it is your Kodi installation that is broken. There are errors associated with your addon database, try deleting it and/or re-installing Kodi.

I can't really offer any more support for this, but would recommend you make a backup before deleting files or re-installing Kodi.
