### ISSUE TITLE
Watch later playlist ID not persistet

### ISSUE THREAD

**Issue by rico-kerscha** [anxdpanic/plugin.video.youtube#939]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.0.1 / 7.0.9.2
* Kodi Version: 21.1.0
* Kodi GUI Language: German
* Operating System: Windows 10 22H2
* Operating System Language: German

------

### Expected Behavior

Please describe the behavior you are expecting.

If i set a custom watch later playlist ID it should be persistet in settings.xml and not get lost.

------

### Current Behavior

What is the current behavior?

If i set a custom watch later playlist ID it isn't stored in settings.xml under youtube.folder.watch_later.playlist and after some time i can't open it within the player anymore.
Then i reset the playlist ID, it continues to work for some time and it will get lost again.
If i add it manually to the settings.xml it get's immediatly removed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set a custom watch later playlist ID
2. check settings.xml if it's persistet
3. use the playlist for some time (it will get lost)

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

[kodi.log](https://github.com/user-attachments/files/17477726/kodi.log)

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment]
> If i set a custom watch later playlist ID it should be persistet in settings.xml and not get lost

Why?

You can have multiple user profiles in the plugin and storing the playlist ID in the addon settings would mean that every user would have to use the same playlist.

The playlist ID is instead stored in access_manager.json for each user.

> after some time i can't open it within the player anymore
> use the playlist for some time (it will get lost)

What does this mean? Are you unable to open the Watch Later folder after some time?

**Comment by rico-kerscha** [comment]
My problem is that after a few days i can't open my custom watch later playlist. A empty playlist is shown.
Then i have to restart Kodi and enter my playlist ID again.

Then it's working again for a few days and the same problem occurs.

My access_manager.json contains the correct playlist ID at any time (no matter if it's working or not  - the ID doesn't change).

I thought this has to do with the empty setting in the xml - it looked for me as at some point in the code this setting was used but maybe i was wrong.
Any idea what could cause this issue?

**Comment by MoojMidge** [comment]
> Any idea what could cause this issue?

Nope. Try to get a debug log next time your watch later playlist fails to load and I can have a look.

**Comment by rico-kerscha** [comment]
I think i solved it.
I switched the watch later old value in the access_manager.json file from wl to my playlist id.
Since then the issue didn't occur anymore.

**Comment by MoojMidge** [comment]
> I switched the watch later old value in the access_manager.json file from wl to my playlist id.

That is unrelated. The old value is just a backup that is kept when the current ID is changed. By default the ID is WL so the first time you set it to a correct ID the old value will be backed up as WL. The only time the old value won't be WL is if you change a previously set ID.
