### ISSUE TITLE
YouTube Plugin Fails to Load

### ISSUE THREAD

**Issue by KweenMother** [anxdpanic/plugin.video.youtube#940]
### Context

Please provide any relevant information about your setup

* Add-on Version:
  7.1.0
* Kodi Version:
  21.1
* Kodi GUI Language:
  English
* Operating System:
    Xbox Series S
* Operating System Language:
  English

------

### Expected Behavior

Please describe the behavior you are expecting.
To open YouTube and play videos and trailers in FENtastic Kodi

------

### Current Behavior

What is the current behavior?
YouTube Error: Check the log for more information. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click the YouTube Addon
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/upadigisam
https://paste.kodi.tv/ifujasoqag

------

### Additional Information

Please provide any additional information that may be helpful.

I created an API Key, Client ID and Secret ID , but still it will not open.

------

**Comment by MoojMidge** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/923

**Comment by MoojMidge** [comment]
Use https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.0.1

**Comment by KweenMother** [comment]
Thank you for such a speedy reply, I appreciate you taking the time.  How do I install this zip file to an Xbox Series S Kodi?

Thank you,
-KM

**Comment by KweenMother** [comment]
I figured out how to load the zip file to the xbox.  Quite simple.  Thank you for your assistance.

**Comment by MoojMidge** [comment]
No problem, glad you got it sorted
