### ISSUE TITLE
Is there fork for an older Kodi versions, such as 17.6 or 16.1?

### ISSUE THREAD

**Issue by Lirk88** [anxdpanic/plugin.video.youtube#944]
I have an old TV-Box with LE 8.2, newer versions of LE is not compatible with hardware (IR control). So, is there way to make a new separate version, compatible with old Kodi versions?

**Comment by MoojMidge** [comment]
Not aware of any forks that target Kodi versions that old.

The minimum version that this will work with this addon is Kodi 18. It is probably possible to make minor changes to make it work with Kodi 17, but that is something that you will need to figure out how to do yourself.
