### ISSUE TITLE
Auto-generated (translated) subtitles not available for some videos

### ISSUE THREAD

**Issue by MoojMidge** [anxdpanic/plugin.video.youtube#945]
I can't play this video 
https://youtu.be/hRS_yZy_qsw?si=kqhLj_LrFEObgGHf
with polish auto-generated subtitles. Last working version with polish auto-generated subtitles is 7.0.8.

_Originally posted by @kedarz in https://github.com/anxdpanic/plugin.video.youtube/issues/634#issuecomment-2442699870_

**Comment by kedarz** [comment]
I changed 5 files from your github and now subtitles are working. 
Thank you

**Comment by MoojMidge** [comment]
Fix included in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.3
