### ISSUE TITLE
Items in Q (playlist) do not repeat

### ISSUE THREAD

**Issue by kingsombra3265** [anxdpanic/plugin.video.youtube#951]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1 B3 (and all other versions)
* Kodi Version: 21.1
* Kodi GUI Language: English
* Operating System: Windows 10 22H2 and Android 12
* Operating System Language: English

------

### Expected Behavior

When a youtube video pointer, stored in a STRM file, is Qed up in the playlist and repeat is one or all, then the video should repeat.

Example:
Continental_Suit.strm:
plugin://plugin.video.youtube/play/?video_id=ftetdzHNtg

------

### Current Behavior

Video plays once then errors on repeat.

This is consistent through all versions of the addon and kodi

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. New install of addon in kodi 21.1 without an API 
2. Save an example STRM file
3. Q the file in the playlist and set repeat one
4. Let video play once and observe crash on the repeat

------

### Log

https://paste.kodi.tv/rucesokoqu.kodi

------

### Additional Information

N/A.

------

**Comment by MoojMidge** [comment]
I already responded to you previously: https://forum.kodi.tv/showthread.php?tid=356934&pid=3214277#pid3214277

> Works fine for me. It may be related to this: #810 but if you have a problem then would need to see a [debug log](https://kodi.wiki/view/Log_file/Easy)

**Comment by MoojMidge** [comment]
This is the same issue as #810 and you can apply the same workaround.

Alternatively the next beta release will improve the workarounds for the underlying issue so that they apply automatically.
