### ISSUE TITLE
Low FPS Video

### ISSUE THREAD

**Issue by StridentBread37** [anxdpanic/plugin.video.youtube#964]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.9.2
* Kodi Version: 21.1 (21.1.0)
* Kodi GUI Language: Russian (Русский)
* Operating System: Android TV
* Operating System Language: Russian (Русский)

Hi. Why while video playing my framerate is low? I restarted system many times, but still low FPS. What is the reason?

**Comment by MoojMidge** [comment]
> What is the reason?

Your guess is as good as mine. 

If you need assistance, post a debug log as requested in the issue template.
https://kodi.wiki/view/Log_file/Easy

**Comment by StridentBread37** [comment]
Hello, I already sole problem. If I need any help, I contact with Kodi.

чт, 7 нояб. 2024 г., 15:34 MoojMidge ***@***.***>:
