### ISSUE TITLE
MPEG-DASH : Youtube plays lower quality only

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#966]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.9.2
* Kodi Version: 20.5
* Kodi GUI Language: FR
* Operating System: Android
* Operating System Language: FR

------

### Expected Behavior

When MPEG-DASH is enabled, Youtube shall play the highest quality automatically. 

------

### Current Behavior

Since today, Youtube plays lower quality only instead of the highest.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Youtube addon
2. Hit middle button and select play with quality
3. It lists one video quality only despite having multiple ones

------

### Log

https://paste.kodi.tv/zobuyidame.kodi

------

### Additional Information

You can take a look with this [video](https://www.youtube.com/watch?v=zT7AFrnqIew). 
In web, several qualities are available and highest is : 1080p60. In Youtube addon 7.0.9.2, it plays 480p only. 

------

**Comment by MoojMidge** [comment]
This should already be fixed in [v7.1.0.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.0.1)

**Comment by karlo2105** [comment]
@MoojMidge 
I updated to the latest Youtube development, after having tried 7.1.0.1. Although, it lists all available resolutions, it still plays lower quality by default on some channels like [this](https://www.youtube.com/watch?v=zT7AFrnqIew). 
Take a look at [log](https://paste.kodi.tv/werecinifi.kodi).

**Comment by MoojMidge** [comment]
Seems to work fine for me.

The log snippet doesn't have debug logging enabled, so it only indicates that there was no problem getting the video streams.

Note that the particular video you linked to only has 720p and 1080p streams available with a 60FPS framerate, so if you have disabled high framerate video in the addon settings then all you will see is a 480p video by default.

**Comment by 03stevensmi** [comment]
@MoojMidge midge! It's NOT disabled! Please re-open! This issue is still here and was never fixed! It's mentioned here: #1280  and the same issue but the other way round here: #1268 

If you want, I can offer a full debug log... but not if this is going to just be ignored after multiple issues raised!
Would it be helpful to you if I gave you my debug log?
