### ISSUE TITLE
v7.1.1+beta.5 stopped working with proxy

### ISSUE THREAD

**Issue by timur-davletshin** [anxdpanic/plugin.video.youtube#967]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1+beta.5
* Kodi Version: -
* Kodi GUI Language: English
* Operating System: LibreELEC 12.0.1
* Operating System Language: English

------

### Current Behavior

v7.1.1+beta.5 stopped working with proxy server while beta.4 works fine. Proxy server (SOCKS5 with DNS) specified in Kodi settings.

**Comment by MoojMidge** [comment]
Not aware of any changes to the proxy support between v7.1.1+beta.4 and v7.1.1+beta.5

How do you know it stopped working?

I have no way of testing this functionality so without a debug log can't do anything.

**Comment by MoojMidge** [comment]
No response, can't reproduce.
