### ISSUE TITLE
some links do not open ...

### ISSUE THREAD

**Issue by mmtest1** [anxdpanic/plugin.video.youtube#97]
hello,
sorry for my bad english....
during a youtube search the results display the links but they do not always open and return a reading error

Please provide any relevant information about your setup

* Add-on Version: latest plugin.video.youtube 6.8.9 (install for repo)
* Kodi Version: 18.7
* Kodi GUI Language: french, xonfluence
* Operating System: raspberry pi os buster
* Operating System Language: french
* system : rasberry pi 4 4g ram
* api developers : ok
* network : ok

log : 
[kodi.log](https://github.com/anxdpanic/plugin.video.youtube/files/6023214/kodi.log)

Please provide detailed steps for reproducing the issue.

1.search for example  'DUVAL MC' 
2. links appears
3. launch 'SI TU VOIS LE PERE NOEL'
4. error 

on the other hand some live works or links of channels, whereas everything worked a few days ago

**Comment by anxdpanic** [comment]
See #10 and alpha zips with the fix are available from https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev
