### ISSUE TITLE
Watch later don't work with v7.1.1+beta.6

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#971]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1+beta.6
* Kodi Version: 21.1 Omega
* Kodi GUI Language: EN
* Operating System: Android
* Operating System Language: EN

------

### Expected Behavior

Open Watch later with content.

------

### Current Behavior

Cannot open Watch later, the rest (Playlists, Bookmarks;...) working fine.

------

### Log

Please include a complete [Addon debug log]
[kodi(2).log](https://github.com/user-attachments/files/17728102/kodi.2.log)

------

### Additional Information

The same with beta 5.

Thanks for your support!

------

**Comment by MoojMidge** [comment]
If you are able to modify the file yourself, changing this:

https://github.com/anxdpanic/plugin.video.youtube/blob/4cee6a111525a3c401e73467aa76ee1171990697/resources/lib/youtube_plugin/youtube/helper/utils.py#L896

From:
```
                    item_name=media_item.get_name(),
```
To:

```
                    video_name=media_item.get_name(),
```

Should fix the problem.

Thanks for testing!

**Comment by Mo1967** [comment]
It works, thanks a lot.
![Screenshot 2024-11-14 094504](https://github.com/user-attachments/assets/4f2c8204-c4c7-4c14-83e1-1e5bfc38dc32)

**Comment by MoojMidge** [comment]
v7.1.1+beta.7 is now available with this fix plus a couple more:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1%2Bbeta.7

Hopefully the last beta before a new stable release
