### ISSUE TITLE
"Sign In" doesn't do the plugin related OAuth so I get precondition required

### ISSUE THREAD

**Issue by A11st0r** [anxdpanic/plugin.video.youtube#979]
### Context

I remember the sign in once did an OAuth dance for the Kodi Youtube Plugin and once for the OAuth Client made by the user with Google Cloud. It does only the latter.  I get success via the google.com/device but failure on Kodi GUI.

* Add-on Version: 7.1.1
* Kodi Version: Kodi Media Center 20.2 (20.2.0) Git:20230630-5f418d0b13
* Kodi GUI Language: English
* Operating System: Ubuntu 22.04.3 LTS
* Operating System Language: English

------

### Expected Behavior

Successful Sign in

------

### Current Behavior

Failed Sign in with red X

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Kodi on Ubuntu
2. Install Youtube addon using the zip file
3. Sign in on the addon
4. follow google.com/device instructions

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/ojilapahax.kodi

------

### Additional Information

To be clear I can see my client consent screen following google.com/device and it shows success there.

If clean reinstall mean uninstalling and deleting temp via maintenance menu and even deleting .kodi/userdata/addon_data/plugin.video.youtube I did them.

------

**Comment by MoojMidge** [comment]
Silly mistake. Thanks for the log.

Can you confirm that the sign-in works using the following version?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

**Comment by balgerion** [comment]
I had exactly same issue like OP, after installing version from ZIP , everything is working.  Thank you :)

**Comment by DjDiabolik** [comment]
@MoojMidge apparently i have a similar issue....
About 5 minutes ago open Kodi on my Ubuntu 24.04.1 LTS whit kodi flatpak and update the addons from repo to 7.1.1 unofficial.
Installation it's ok... 
Apparently i need to relogin my account... and i try to complete both procedure:
- Register to obtain first code
- Open google.com/device from my phone
- Put the code appear on TV
- Click on Advanced and after click to accept the connection
On TV it's appears an error report on kodi.log:
https://paste.kodi.tv/efosorewom.kodi

If it's correct i need to install the same 7.1.1 from your repo..... You have to update this to this anxdpanic repo and push it to a unofficial and upgraded version ?

**Comment by DjDiabolik** [comment]
@MoojMidge can also i confirm... istalled this:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

Resolve the issue.....

**Comment by MoojMidge** [comment]
> You have to update this to this anxdpanic repo and push it to a unofficial and upgraded version ?

The previously linked zip file is just a test version with a fix for this specific problem.

There are some changes to the data stored in access_manager.json that caused this and at least one other problem.

Once the fixes are confirmed as working a v7.1.1.1 will be released

**Comment by yggdr** [comment]
Hello MoojMidge. I might have problems that are related, but I'm not sure. 2 days ago it started to not being able to play videos anymore. After trying around and installing 7.1.1, and then the other 7.1.1 you linked above, it still wouldn't work, with `YouTubeException('"error" in response JSON data')` and `Message:   The caller does not have permission` in `kodi.log`

With your modified 7.1.1 installed, I signed out and tried to sign in again, but I get
```
2024-11-15 22:35:53.993 T:23120    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.9.2
                                                        Path:   |/sign/in/|
                                                        Params: |{'category_label': 'Sign In'}|
2024-11-15 22:35:57.155 T:23120   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                        Device/user code request - Failed
                                                        Exception: LoginException('"error" in response JSON data')
                                                        config_type: |YouTube-Kodi|
                                                        client_id:   |480...t.com|
                                                        Response:   {'error': 'invalid_client', 'error_description': 'Invalid client type.', 'code': 401}
2024-11-15 22:35:57.159 T:23120   error <general>: [plugin.video.youtube] LoginException: {'error': 'invalid_client', 'error_description': 'Invalid client type.', 'code': 401}
```

Is this related to this error, or should I open a separate issue?

**Comment by MoojMidge** [comment]
> Is this related to this error, or should I open a separate issue?

This is a separate issue, but it is due to incorrectly configured OAuth credentials.

You can refer to the instructions here for how to create this correctly:
#439 (comment)

Pay particular attention to Step 10.

**Comment by MoojMidge** [comment]
Fix is now available in v7.1.1.1
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.1

**Comment by A11st0r** [comment]
still dont work neither with the zip file here nor with 7.1.1.1

https://paste.kodi.tv/zeselizaxu.kodi

I remember I should see authorizing the youtube plugin before when it worked but I dont see that now. only my clinet.

**Comment by MoojMidge** [comment]
Login seems to be working according to your log. Playback fails because you don't have InputStream.Adaptive and/or MPEG-DASH enabled. Run the Setup Wizard and set the addon up correctly and it should work.

**Comment by ypcyc** [comment]
@MoojMidge I'm on 7.1.1.6 and it looks like I still have similar issue. When I try to "Sign In" I'm prompted about several login prompts and then nothing happens.

https://paste.kodi.tv/nobejerile

**Comment by MoojMidge** [comment]
Nothing happens because you likely have not entered any of the required details in `YouTube addon > Settings > API`. Can't just sign in without any OAuth credentials setup.

There are some instruction here: https://github.com/anxdpanic/plugin.video.youtube/issues/1086#issuecomment-2613975245

**Comment by ypcyc** [comment]
@MoojMidge Thank you for quick reply! 
1. I had this API settings set back in 2021 and that time "Sign In" was working without them, so I believe now in Sign In message it would be useful to add that API keys should be set first, but there is nothing about it and it's a bit missleading.
2. I did check the tutorial to confirm I have set API keys before in the correct way and they are valid, I did set them again in plugin and I did Sign in and confirmed the device. But there was only one Sign in request, so there is no request for 2nd login "After entering the code, i had to enter another code" (from tutorial Step 12).  I'm able to see my subscriptions and other videos, but when trying to play I get that "YouTubeException('Sign in to confirm you’re not a bot') "

**Comment by MoojMidge** [comment]
You are replying to an old and unrelated issue.

There have been numerous other issues opened about the problem you are having. Two of the pinned issues directly address the why/what/how:
https://github.com/anxdpanic/plugin.video.youtube/issues/1075
https://github.com/anxdpanic/plugin.video.youtube/issues/1095

You need to update to the latest beta version
https://github.com/anxdpanic/plugin.video.youtube/releases

After that follow the instructions in #1095 and your issue will be resolved.
