### ISSUE TITLE
7.1.1 - Endless loop "API key set changed: Resetting client and updating access token"

### ISSUE THREAD

**Issue by phpTrix** [anxdpanic/plugin.video.youtube#980]
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1
* Kodi Version: 21.1
* Kodi GUI Language: DE
* Operating System: LibreElec
* Operating System Language: EN

------

### Expected Behavior

One (1!) client reset after changing API keys, if that is required

------

### Current Behavior

Endless loop with "API key set changed: Resetting client and updating access token"

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Kodi YouTube addon
2. View log (.kodi/temp/kodi.log)

------

### Log    full log: https://paste.libreelec.tv/driving-reptile.log

2024-11-15 18:03:14.856 T:15995    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/sign/out/|
                                                        Params: |{'confirmed': True}|
2024-11-15 18:03:14.881 T:15995 warning <general>: [plugin.video.youtube] API key set changed: Resetting client and updating access token
2024-11-15 18:03:14.937 T:15996    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/kodion/route/sign/|
                                                        Params: |{'window_fallback': True, 'window_replace': True, 'window_return': False}|
2024-11-15 18:03:15.130 T:15998    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/|
                                                        Params: |{}|
2024-11-15 18:03:15.134 T:15568 warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-11-15 18:03:15.146 T:15998 warning <general>: [plugin.video.youtube] API key set changed: Resetting client and updating access token
2024-11-15 18:03:15.744 T:15999    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/sign/out/|
                                                        Params: |{'confirmed': True}|
2024-11-15 18:03:15.749 T:15999 warning <general>: [plugin.video.youtube] API key set changed: Resetting client and updating access token
2024-11-15 18:03:16.316 T:16000    info <general>: [plugin.video.youtube] Plugin: Running v7.1.1+unofficial.1
                                                        Kodi:   v21.1 (Kodi Omega)
                                                        Python: v3.11.9
                                                        Path:   |/sign/out/|
                                                        Params: |{'confirmed': True}|
2024-11-15 18:03:16.323 T:16000 warning <general>: [plugin.video.youtube] API key set changed: Resetting client and updating access token
2024-11-15 18:03:16.415 T:15568 warning <general>: CGUIMediaWindow::OnMessage - updating in progress
^C

------

### Additional Information

I uninstalled the addon and removed previous configuration (via the uninstall function), restarted kodi, reinstalled plugin 7.1.1 from zip file.
Now with and without entering the API key, client id and client key - still the endless loop "API key set changed: Resetting client and updating access token"

------

**Comment by dvdakker** [comment]
I can confirm this issue exists with both the official & unofficial version of the YT plugin.
Running on:
    Add-on Version: 7.1.1
    Kodi Version: 21.1
    Kodi GUI Language: EN
    Operating System: OSMC
    Operating System Language: EN
    Hardware: Raspberry PI 3B+

Attached files:
* [kodi_log_yt_official_no_debug.txt](https://github.com/user-attachments/files/17780685/kodi_log_yt_official_no_debug.txt): kodi.log captured with the official plugin, without debug-logging enabled
* [kodi_log_yt_unofficial_debug.txt](https://github.com/user-attachments/files/17780686/kodi_log_yt_unofficial_debug.txt): kodi.log captured with the unofficial plugin, with debug-logging enabled

**Comment by MoojMidge** [comment]
Thanks for the logs.

Can you test whether the issue is resolved after installing the following  version?
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

**Comment by phpTrix** [comment]
> Thanks for the logs.
> 
> Can you test whether the issue is resolved after installing the following version? https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/v7.1.1.zip

This version works instantly. Thanks a lot, I really missed youtube :-)

**Comment by MoojMidge** [comment]
Thanks for testing and confirming.

**Comment by MoojMidge** [comment]
Fix is now available in v7.1.1.1
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.1
