### ISSUE TITLE
Custom define "short" length to filter out more clips 

### ISSUE THREAD

**Issue by dtw2000** [anxdpanic/plugin.video.youtube#984]
### What Problem Does This Solve? 

This will give the user better filtering of unwanted videos.  Specifically, to filter those of duration less that x, where x is defined by user.  The code is pretty much already in place, just not customizable.

------

### Suggest a Solution (optional)

.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py >>> 
change short value from 60 to a GUI set value that is set by user with a default of 60.

------

**Comment by MoojMidge** [comment]
I believe shorts can be as long as 3 minutes now, but while the interface changes when playing them using an official YouTube client, the distinction is less important when using Kodi.

Anyway, a setting to change the duration from 30 seconds to 180 seconds will be available in the next beta release.

**Comment by dtw2000** [comment]
Sorry for the close / reopen.

Thank you for following up with the notion that a custom settings change will be in the next beta.  You mentioned that 30-180 seconds will be an option to adjust the "short" filtering.  I'll suggest that it would be more useful to be a bit more an open-ended integer input value.  For example, I've manually modified utils.py with a value of 900 (15 minutes) just for the ability to weed out what I consider "too short".  I recognize, this isn't optimal.  Ideally, I would prefer this option only for filtering files in the "My subscriptions" feed and not in any other feed, but for my use case, that's what i use kodi youtube for, listening to long form podcasts, and filtering out all the clips is what I'm after.

Thanks again

**Comment by MoojMidge** [comment]
> I'll suggest that it would be more useful to be a bit more an open-ended integer input value. For example, I've manually modified utils.py with a value of 900 (15 minutes) just for the ability to weed out what I consider "too short".

Won't be implementing this, but you are free to change the limits yourself. 

> Ideally, I would prefer this option only for filtering files in the "My subscriptions" feed and not in any other feed

When requesting something it is best to fully detail what you actually want. There is already a filter for My Subscriptions, it is simple enough to extend it with non-title matching filter criteria.

**Comment by dtw2000** [comment]
Thank you.  It took me a bit to digest what you've done.  That's great and better than what I was suggesting.

To accomplish my scenario, enable the "My Subscriptions (filtered)", flip it to blacklist to include all subscriptions, and in the filtered channel list set something like "{duration}>900"

**Comment by MoojMidge** [comment]
FYI you can use this as-is but it is still a work in progress - the format of the filter criteria will likely change to something like `{METADATA}{OP}{VALUE}` where `METADATA` can be a number of various video metadata attributes including `duration`.

**Comment by MoojMidge** [comment]
> To accomplish my scenario, enable the "My Subscriptions (filtered)", flip it to blacklist to include all subscriptions, and in the filtered channel list set something like "{duration}>900"

Have now updated the filtering. Available in https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

To achieve what you want you can use `{duration}{>}{900}`. Note that these custom filters apply on a per video basis, while the blacklist toggle only applies to the original channel name filters, so to filter out long video you would use `{duration}{<=}{60}`

Not properly tested, so let me know if you come across any issues.
