### ISSUE TITLE
LoginException ("Invalid client type")

### ISSUE THREAD

**Issue by malversoft** [anxdpanic/plugin.video.youtube#987]
I was doing checks to try to give additional information about issue #986, and now things are getting worse.

If you log out from your Youtube account in the Youtube plugin, you cannot log back in.
The login process fails due to "Invalid client type" (HTTP 401), before informing any validation URL.
So currently if you log out with the Youtube plugin, it is out of your account forever.

* Add-on Version: 7.1.1.1 (official)
* Kodi Version: 21.0.0
* Kodi GUI Language: es_ES
* Operating System: Windows 8.1
* Operating System Language: es_ES

------

To reproduce:

1. Log out Youtube user in the Youtube plugin.
2. Select the option to log in.

Expected beavior: Dialog with URL to validate code in the web.
Current behavior: Error message titled "LoginException", informing HTTP code 401 and "Invalid client type".

------

[Log of login attempt](https://paste.kodi.tv/zoxujigavo.kodi).

------

**Comment by MoojMidge** [comment]
When was the last time you logged in?

The error message is from Google, and has nothing to do with the plugin directly.

It means that when you created your OAuth credentials you did so incorrectly and now need to recreate them.

See the pinned issue for instructions and pay particular attention to Step 10:
https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1509319017

**Comment by malversoft** [comment]
> When was the last time you logged in?

5th of february of 2017, almost eight years ago, according to my saved notes and my API key creation date.
I followed the instructions posted [in this blog](https://www.howtogeek.com/273956/how-to-fix-kodis-youtube-quota-exceeded-problem/), six years before someone posted the necessary info [here in the repository](https://github.com/anxdpanic/plugin.video.youtube/issues/439#issuecomment-1509319017).

Then Google had no `"TV input devices and limited"` app scope for OAuth client, you just chose the option "Other" and the shown scope was `"Desktop"`.
Creating a new OAuth client id for the new `"TV input devices and limited"` scope and using its client id and secret in the plugin solved my problem.

Thanks for pointing me in the right direction. But please do not assume someone has done something "incorrectly", just because Google created new application scopes in the last eight years.   ;-)

Even the instructions you linked are pretty confusing. Steps 7-8 seem to be only triggered if you did not create any OAuth client id before in the project.  Those steps are not available in my case, that part of the process was done automatically when I created the OAuth client app id years ago.

Also to note, the Google Cloud console warns that OAuth management screen is to be renewed soon, so those instructions you linked could render almost useless for average users.

Thanks again for the directions. And thanks specially for the Kodi Youtube plugin, I think it is the one I use most.

**Comment by aizelauna** [comment]
I also have the PERMISSION_DENIED error. I noticed the issue right now.

**Comment by MoojMidge** [comment]
> Thanks for pointing me in the right direction. But please do not assume someone has done something "incorrectly", just because Google created new application scopes in the last eight years. ;-)

:-) Point taken.


> Even the instructions you linked are pretty confusing. Steps 7-8 seem to be only triggered if you did not create any OAuth client id before in the project. Those steps are not available in my case, that part of the process was done automatically when I created the OAuth client app id years ago.
> 
> Also to note, the Google Cloud console warns that OAuth management screen is to be renewed soon, so those instructions you linked could render almost useless for average users.

If they are willing and able to, anyone can contribute improved instructions. Unfortunately few have been able to spare the time.
