### ISSUE TITLE
Local History not working anymore

### ISSUE THREAD

**Issue by XXXBold** [anxdpanic/plugin.video.youtube#991]
### Context

First, thank you very much for this great Addon!

I mainly use this addon to play content that is sent over a phone (share->send to kodi) on the NewPipe-Android App.
At some point, the local playback history did stop working.
At first, no more entries were added when playing a new video, later after an update (?) all history disappeared and when playing any videos, the history is not populated anymore.

I don't have a Google/Youtube Account and therefore don't use an API Key, but I think for this it should't be required? At least it wasn't before.
(Playback itself works without issues when doing it like this)

* Add-on Version: Tested with latest from repo (7.0.9.2) and https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.1 which have the same behaviour
* Kodi Version: 20.2
* Kodi GUI Language: German
* Operating System: Armbian on Orangepi 5
* Operating System Language: English

------

### Expected Behavior

Local playback history should work as it did before, e.g. when Sharing a Youtube-Video from the Phone, it should be added to the history after it finishes.

------

### Current Behavior
Local playback history does not work at all (stays empty).

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. (Optional when already installed) Uninstall addon, say "yes" to delete all settings
2. (Re)install the addon, run the wizard.
3. Play any video using the "Send to Kodi" functionality on an Android Phone
4. Check the history in the Youtube Addon after the video has finished

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).
https://paste.kodi.tv/avamutenoc.kodi

------

### Additional Information

Let me know if you need more info.

------

**Comment by MoojMidge** [comment]
This was broken in v7.0.9.2 but should have been fixed in v7.1.0 and newer versions. It works fine for me and I largely use this addon in the same way you do.

Can you get a log showing sharing and playback of a YouTube video? It doesn't need to be a full Kodi debug log, you can instead only enable debug logging for this addon by selecting `YouTube > Settings > Advanced > Logging > Enable debug logging` when using v7.1.1.1

**Comment by XXXBold** [comment]
Hello @MoojMidge 

Thanks for your quick response!

Sure, here's the log (Hope it contains everything):
https://paste.kodi.tv/rugafoqeyu.kodi

**Comment by MoojMidge** [comment]
The good news is that the video is being saved to your local history,

The bad news is that because you don't have an API key, when you open your history list, the addon cannot populate the list with the actual details of the played video and so the resulting list is empty.

It would have worked previously because API keys used to be provided in the addon, but these have now been revoked, and you will need to get your own instead.

**Comment by XXXBold** [comment]
Damn, I feared so :/

Well okay, guess I just won't use the history anymore than.

Thanks anyway for the quick investigation!

**Comment by MoojMidge** [comment]
Re-opening. I think there is a way to save enough information to the local history to populate the history list with something useful even without providing API keys.

**Comment by XXXBold** [comment]
Oh, that would be great!
If I might suggest some infos, that would be interesting/important (to me at least) to save:

1. Link of the video (to be able to replay it)
2. Name/Title of the video (So you know what it is)
3. Thumbnail (So you know even better what it is ;))
4. Local play count (Knowing your addictions)

I think 1-3 are already available, because they're shown in Kodi/Yatse while playing.
In the List, 1,2 and 4 could be displayed.

**Comment by MoojMidge** [comment]
Can install this test version and see if it works:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by XXXBold** [comment]
Thanks for your effort!

I tested with this version, unfortunately, it's not possible now to play any videos.
Here's the debug log: https://paste.kodi.tv/otexaqawor.kodi

**Comment by MoojMidge** [comment]
Try it again (zip file is updated), issue may be fixed:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Comment by XXXBold** [comment]
Retested, now playing videos works again!
Also, the local history seems to work properly now, I can see it being populated both when a video ends or is stopped (then you have the option to continue or restart). Basically, it seems to work like it did in older versions of the Addon.

If you need a debug log of this working version or other info, let me know. Otherwise, from my side, this can be closed.

Thank you very much for supporting use cases without the requirement for API-Keys/google accounts!

**Comment by MoojMidge** [comment]
Thanks for confirming.

The issue will get closed when the changes are properly released.
