### ISSUE TITLE
Way to remove the "in progress" window when scanning the Subsription videos?

### ISSUE THREAD

**Issue by Tasosgemah** [anxdpanic/plugin.video.youtube#997]
I noticed in the latest version (7.1.1.1) there's an additional window that appears on the top right of the screen that says "in progress" as it loads the video list. This only seems to appear in the Subs videos. That's in addition to the standard loading window at the bottom right.

Is there a reason why this window appears? Doesn't seem to be helpful, it only appears for half a second anyway so it's not like you have any time to read the information it provides. It only makes the whole process look more janky, IMO.

This didn't exist in 7.0.9.2. And i couldn't find any option to disable it. Is there any other way?

**Comment by MoojMidge** [comment]
> Is there a reason why this window appears?

The background progress dialog will be used for all listings shortly, not just My Subscriptions.

There are a few issues with the way it cureently works, but it will be necessary for the additional filtering and pagination rework that will be implemented.


> i couldn't find any option to disable it. Is there any other way?

There is none and I don't intend to make one. Can you provide more details of why you don't want it?

**Comment by Tasosgemah** [comment]
> There is none and I don't intend to make one. Can you provide more details of why you don't want it?

Yes, i prefer the screen to be clean of pop-up windows like this... There's already the default kodi loading window at the bottom right. Having many windows pop up like this makes it feel janky IMO.

Just asking to have an option to hide it/make it invisible, like how most other information stuff has a way to be hidden. Not a big deal though.

**Comment by MoojMidge** [comment]
> There's already the default kodi loading window at the bottom right. Having many windows pop up like this makes it feel janky IMO.

Can you get a screenshot of this? By default Kodi only has a busy spinner in the middle of the screen with no information. It may be skin dependent.

**Comment by Tasosgemah** [comment]
![Untitled](https://github.com/user-attachments/assets/08a5c8fd-2929-464f-a348-d3c6d9ea4b86)

**Comment by DoctorVanGogh** [comment]
> Doesn't seem to be helpful, it only appears for half a second anyway so it's not like you have any time to read the information it provides.

That depends _entirely_ on your configuration.

If you have set things up to show a sufficiently large amount of elements per "page" and not just the bare minimum then the progress window will actually be on screen for several seconds and is quite helpful in determining if things are just slow or possibly stuck.

So:
👍 on getting rid of the *duplicate* wait indicators
👎 on removing the "in progress".

Remove the less informative "working" wait spinner instead ;)

**Comment by MoojMidge** [comment]
Agree the double notifications look a bit odd, but can't do anything about the "Working" spinner. That is part of the skin design. 

Don't intend to provide a way to disable the new progress notifications, too troublesome for little benefit, while showing the new progress notification has a purpose with the new functionality that is being implemented.
