### ISSUE TITLE
Notifications and security question in bookmarks

### ISSUE THREAD

**Issue by bierbaron2** [anxdpanic/plugin.video.youtube#998]
### What Problem Does This Solve? 

Thank you for the new version. I was wondering if it is possible that the notification for the bookmarks is optional? And also the security question whether something should be deleted from the bookmarks. It's nice that this is available. But for me an unnecessary step. Hence the question whether it can be selectable in the menu?

------

### Suggest a Solution (optional)

Optional security question when deleting something bookmarked and optional notification when the bookmark has been deleted

------

**Comment by MoojMidge** [comment]
Don't plan on adding this sorry. Trying to avoid having too many options if not necessary, as it becomes an ongoing maintenance issue to test and make sure that nothing breaks when other changes are made.
